### ISSUE TITLE
404 on landing page. Nginx, config with gophish 

### ISSUE THREAD

**Issue by koolkidjam23** [gophish/gophish#1001]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

Hello Jordan I just want to say thank you for your hard work and what you do for the community. I am a huge fan of the software.  I am running gophish v5 on Ubuntu Server. 

Im having a MAJOR headache,iv been stuck on this situation. 

I have Nginx configured on my VPS with gophish. Everything works perfect until I encrypt with certbot. It changes my configuration. and blocks landing pages. Saying theres a error in a tls Handshake. It also gives me the 404 error.

I cannot connect gophish through port 443 because nginx already uses port 443.

This is my **Nginx** server config
```
server {

	root /var/www/gethelp.work/html;

	index index.html index.htm index.nginx-debian.html;

	server_name domain.com www.domain.com;

	location /
	    proxy_pass https://x.x.x.13:8080;
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/gethelp.work/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/gethelp.work/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
 
        listen x.x.x.13:80 default_server;
	listen [::]:80 default_server;

	server_name domain.com www.domain.com;
    return 404; # managed by Certbot
}
```
And this is my **Gophish** Config 
```
{
	"admin_server" : {
		"listen_url" : "x.x.x.13:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "x.x.x.13:8080",
		"use_tls" : true,
		"cert_path" : "/etc/letsencrypt/live/gethelp.work/fullchain.pem",
		"key_path": "/etc/letsencrypt/live/gethelp.work/privkey.pem"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}
```
If you can please help me or just take a look at my config and see if I'm using the right ports I would appreciate so much.

**Comment by koolkidjam23** [comment]
did I ask wrong? I'm sorry I just really need help should I re write the ?

**Comment by jordan-wright** [comment]
Hi @koolkidjam23, thanks for reaching out. I've edited the comment to simply add better formatting for the code blocks- I hope you don't mind.

I'm afraid that auditing Nginx configs is outside the scope of the support we can offer, since we're not Nginx experts.

That said, from a cursory glance the configuration seems reasonable. Just proxying all requests to the internal Gophish listener. I could perhaps see Nginx complaining if it tries to proxy requests internally to the hostname x.x.x.13 and your certificate is for `gethelp.work`, this will be a mismatch and the cert wouldn't be trusted. [This answer](https://serverfault.com/questions/341023/nginx-as-reverse-proxy-with-upstream-ssl) might help.

Beyond that, I'm afraid there isn't much we can do to help here without going down the rabbit hole of supporting upstream proxy configs. Hopefully that answer helps, but I'm afraid that since this doesn't appear to be an issue with Gophish itself, I'm going to go ahead and close out this issue.

**Comment by ad0nis** [comment]
I'm not sure if this is the right place to ask this or if I should open a new issue, but if I'm following correctly, I believe this issue was likely opened so that campaign operators can control what happens when blue team folks or savvy users browse to the root of the gophish server instead of clicking on a link. I'm currently trying to figure out how to control this myself, and one of my first thoughts was an nginx config like this since gophish doesn't appear to support serving a page from / currently. Any chance that /static/index.html could be served from / in order to give some control over this?

**Comment by willem-tee** [comment]
Am in the same situation. Very puzzled about this and how to make it happen tbh

**Comment by mrpaddy35** [comment]
Any solutions to this so far, is anybody able to get both nginx and gophish work in the same machine ?
