### ISSUE TITLE
Error launching campaign emails and also unable to send test email. Error = max connection attempts reached

### ISSUE THREAD

**Issue by BatemanPaddy** [gophish/gophish#1013]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
gophish-v0.5.0-windows-64bit

Brief description of the issue: 
My attempts to send a test email failed, i was met with the error " max connection attempts reached" . I was only trying to send one email to a hotmail address.

I created a campaign and tried to launch it to a single email address for testing purposes. The status of the email is "error".

I am using the Google smtp server: smtp.gmail.com:587

What are you expecting to see happen? :
To be able to send a test email and launch a campaign

What are you seeing happen?
error messages

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  created template using gmail smtp server, try send test email to a hotmail account
 * Step 2 -  create campaign, try launch campaign, no emails will deliver . status = error 

This is my first time using GoPhish. I am running a 64-bit version of Windows 10. Please see screenshots of the errors below. Any help is much appreciated !!

![image](https://user-images.githubusercontent.com/19551660/37542495-4ab98922-2956-11e8-85dd-3bcbb2d35d24.png)

![image](https://user-images.githubusercontent.com/19551660/37542522-61f0c2a4-2956-11e8-984b-50d0c24b9ca4.png)

Thank you,

**Comment by jordan-wright** [comment]
Hi @BatemanPaddy, thanks for reaching out!

This is the generic error that indicates there's something wrong with your SMTP setup. You'll find in #963 that there's plans to make this better by showing the underlying error but I don't have a surefire timeline on that yet.

You can also find all sorts of [other issues](https://github.com/gophish/gophish/search?q=gmail&type=Issues&utf8=%E2%9C%93) which will help diagnose the issue you're having with sending email through Gmail.

Since we're tracking the "max connection attempts reached" solution in #963 and there have been all sorts of issues related to Gmail, I'm going to go ahead and close this one out as a duplicate for now. If there's any other information you can provide that you think will help us troubleshoot, let us know and we can always re-open.

Thanks again for getting in touch!
