### ISSUE TITLE
Trying to get emails opened and clicked link to work on the Dashboard

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#1017]
Emails are sending and the add tracking image is ticked. I am sending emails to gmail and https://temp-mail.org/en/ any reason its not working? Thanks

**Comment by jordan-wright** [comment]
Hi @Paddyk3ll3h3r, thanks for reaching out. In order to help you troubleshoot, we're going to need quite a bit more information. We ask for this information in the issue template, which is the text you saw when you first created the issue.

Since this doesn't follow the issue template, I'm going to go ahead and close it out. If you could, please recreate the issue and follow our template providing as much information as possible to help us troubleshoot. Once we have that information, we'll be able to help track down the problem.

Sorry for the inconvenience!
