### ISSUE TITLE
Not going to statistics in GoPhish

### ISSUE THREAD

**Issue by Sergey-01-08-90** [gophish/gophish#1019]
Hello!
I'm using version 0.5.0.
Picked up the hmail server.
Through the control panel, GoPnish create a "company" letters to the "victims" come, but the control panel does not record the opening of letters, go through the links and open the attached files.
Tell me please, what could be wrong?

**Comment by jordan-wright** [comment]
Hi @Sergey-01-08-90, thanks for reaching out. In order to help you troubleshoot, we're going to need quite a bit more information. We ask for this information in the issue template, which is the text you saw when you first created the issue.

Since this doesn't follow the issue template, I'm going to go ahead and close it out. If you could, please recreate the issue and follow our template providing as much information as possible to help us troubleshoot. Once we have that information, we'll be able to help track down the problem.

Sorry for the inconvenience!
