### ISSUE TITLE
Link in Gophish documentation not working?

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#1020]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 
When following the "Creating the landing page the" upon using http://192.168.56.101/mail/ as my import URL i get an error that states " Get http://192.168.56.101/mail/: dial tcp 192.168.56.101:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

What are you expecting to see happen? :
Link to be added and site to be imported

What are you seeing happen?
![gophish error](https://user-images.githubusercontent.com/32489324/37654683-e59a8874-2c3a-11e8-9348-16c3092d7a59.JPG)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Added the link "http://192.168.56.101/mail/"
 * Step 2 - Received an error

**Comment by S0larflare** [comment]
Looks like your gophish server can't connect to 192.168.56.101, is there a firewall blocking it?

**Comment by Paddyk3ll3h3r** [comment]
Thanks for the quick response! I was on college wifi, i swapped to my personal hotspot on my phone and am still getting the same issue. I use my personal hotspot to send phishing emails on gophish so there is no firewall there.

**Comment by jordan-wright** [comment]
Hi @Paddyk3ll3h3r, thanks for reaching out.

Please note that the IP address in the documentation is simply an example and almost certainly won't be correct for your environment 😄 In the docs, I had a virtual machine running the ["Morning Catch" VM](https://blog.cobaltstrike.com/2014/08/06/introducing-morning-catch-a-phishing-paradise/) as a demonstration, and `192.168.56.101` was the IP address of the virtual machine.

You'll need to change the IP/URL of that screen to point to the webpage you want to clone. This will need to be reachable even through a browser (as in, if you paste that URL into your URL bar, it gives the page you want).

Since this appears to be a misunderstanding of the docs, I'm going to go ahead and close this out. Hope this helps! Let us know if you run into any other issues.
