### ISSUE TITLE
Admin server won't connect

### ISSUE THREAD

**Issue by jonkaufmann** [gophish/gophish#1021]
What version of Gophish are you using?: 

Brief description of the issue: 
When I start the gophish server, the admin server refuses to connect
Netstat shows server listening on the port.
It is on AWS, but the security group allows connections on that port (I even tried allowing all traffic, no dice).

What are you expecting to see happen? :
Getting the admin page

What are you seeing happen?
Attempting to access the admin server at 3333 evokes this message on my web browser:
This site can't be reached
<host> refused to connect.

Please provide any terminal output that may be relevant below:

 2018/03/20 17:28:55 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20170827141312
 2018/03/20 17:28:55 gophish.go:104: Starting phishing server at http://0.0.0.0:80
 2018/03/20 17:28:55 gophish.go:87: Starting admin server at https://0.0.0.0:3333

Please provide as many steps as you can to reproduce the problem:
From a fresh aws server I ran the following:
 !#/bin/bash

#install prereqs
sudo su -
yum install gcc gcc-c++
yum install go
yum install git
exit
cd ~

#install gophish
go get github.com/gophish/gophish
cd ~/go/src/github.com/gophish/gophish/
go build
sudo ./gophish

**Comment by jordan-wright** [comment]
Hi @jonkaufmann, thanks for reaching out!

This is almost certainly a networking/firewall related issue. It appears that Gophish is starting up correctly and you mentioned that `netstat` is showing the service to be listening. If you're still seeing a connection refused error and you don't see any logs appear in the Gophish terminal, then it's likely the case that there is a firewall in the way.

The things you could try include:

* Make sure you're putting in the right IP/hostname
* Make sure the security group is set up correctly (I know you mentioned it's good, but never hurts to double check 😄 )
* Run tcpdump or similar to see if you can see traffic even hitting the box when you make the connection attempt

Beyond that, I'm afraid there's very little we can do on the Gophish side to help troubleshoot this. Sorry we can't be of more help! I'll keep this issue open for a couple of days until we get a chance to hear back. If you run into any other information that seems to indicate the problem lies with Gophish, please let us know!

**Comment by jonkaufmann** [comment]
Thanks @jordan-wright it does seem as though it is an aws issue. Managed to get it started on my own machine without problems. I'm not sure how to get around it, but I'll make sure to update if I do.

**Comment by jordan-wright** [comment]
Sounds good, thanks @jonkaufmann!

FWIW, an awesome community member wrote up a guide on how to get Gophish up and running with AWS that might help out https://gophish.gitbooks.io/user-guide/content/additional-references.html

Hope this helps, and please keep us updated if you find out anything!
