### ISSUE TITLE
URL Command but show text / hyperlink

### ISSUE THREAD

**Issue by JellyWelly** [gophish/gophish#1025]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0

Brief description of the issue: When doing a new email template we've put the command in for the URL and it works, but how can we turn it into a hyperlink so it shows for example 'Click Here' rather than the full URL ?

What are you expecting to see happen? : Shows the full URL

What are you seeing happen?
![gophish1](https://user-images.githubusercontent.com/37294856/37902153-6fbfa21e-30eb-11e8-913c-466f3d88de87.JPG)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by S0larflare** [comment]
<a href=“{{.URL}}”>Click here</a>

Sent from my iPhone

On 26 Mar 2018, at 11:47, JellyWelly <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0

Brief description of the issue: When doing a new email template we've put the command in for the URL and it works, but how can we turn it into a hyperlink so it shows for example 'Click Here' rather than the full URL ?

What are you expecting to see happen? : Shows the full URL

What are you seeing happen?
[gophish1]<https://user-images.githubusercontent.com/37294856/37902153-6fbfa21e-30eb-11e8-913c-466f3d88de87.JPG>

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Insert code here

Please provide any terminal output that may be relevant below:

Insert output here


Please provide as many steps as you can to reproduce the problem:

  *   Step 1 -
  *   Step 2 -

**Comment by JellyWelly** [comment]
Legend, Thanks!
