### ISSUE TITLE
Unauthenticated Server Side Request Forgery

### ISSUE THREAD

**Issue by muffinns** [gophish/gophish#1026]
What version of Gophish are you using?: 

https://github.com/gophish/gophish/releases/download/v0.5.0/gophish-v0.5.0-linux-64bit.zip

Brief description of the issue: 

It is possible to access the "Import Site" endpoint of the "Create Landing Page" area without cookie/API key, AKA without authentication. As such unauthenticated users who can access the admin portal can use it to perform server side request forgery attacks. Note: this is only really an issue if the admin interface is listening on anything other than 127.0.0.1, or if it is running on 127.0.0.1 on a multiuser machine accessed by non gophish admins.

Here is more information about the potential risks associated with this issue:
https://www.owasp.org/index.php/Server_Side_Request_Forgery
https://hackerone.com/reports/115748
https://blog.christophetd.fr/abusing-aws-metadata-service-using-ssrf-vulnerabilities/ <-- If someone is running this in AWS it could cause them to get totally pwned

What are you expecting to see happen? :

I'm expecting the POST request to the https://127.0.0.1:3333/api/import/site endpoint to fail when there is no cookie and/or API key as part of the request.

What are you seeing happen?

I am seeing that the gophish application fetches the resource specified in the "url" jason parameter of the https://127.0.0.1:3333/api/import/site even when the cookie and API key are missing from the request. 

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

N/A

Please provide any terminal output that may be relevant below:

N/A

Please provide as many steps as you can to reproduce the problem:

Here is the raw HTTP request that you can run against a local gophish server and see that it fetches google.com even though no authentication is provided:

```
POST /api/import/site HTTP/1.1
Host: 127.0.0.1:3333
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Content-Length: 54
DNT: 1
Connection: close

{"url":"https://google.com","include_resources":false}
```

Here is the corresponding curl command:

```
curl -vv -i -s -k  -X $'POST'     -H $'Host: 127.0.0.1:3333' -H $'User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0' -H $'Accept: application/json, text/javascript, */*; q=0.01' -H $'Accept-Language: en-US,en;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Content-Type: application/json' -H $'X-Requested-With: XMLHttpRequest' -H $'Content-Length: 54' -H $'DNT: 1' -H $'Connection: close'     --data-binary $'{\"url\":\"https://google.com\",\"include_resources\":false}'     $'https://127.0.0.1:3333/api/import/site'
```

**Comment by S0larflare** [comment]
Looks like /import/site , /import/email and /import/group all don't require auth.

https://github.com/gophish/gophish/blob/master/controllers/route.go#L62


I'm wondering if there is a specific reason for it? If not, it should be a simple fix.

**Comment by jordan-wright** [comment]
I don't know of a specific reason, but this definitely shouldn't be a thing.

Thanks for the heads up @muffinns, I'll get this fixed tonight and will tag a new release. It looks like impact is minimal since: 

* The admin server is localhost by default (but people definitely change that)
* I'm almost positive both of these just return stateless information (the html of the page, the processed csv) as opposed to actually saving any information in the database

But either way it's a bug and needs to be fixed pronto. Thanks again for the report!!

**Comment by jordan-wright** [comment]
@muffinns I believe I fixed this via https://github.com/gophish/gophish/commit/2131c17c33a0af757c80d94379baaca147de9931?w=1. You might see some whitespace changes since there were some files I hadn't touched since I added the auto-indentation plugin in my editor 😄 

If you could confirm this fixes the issue on your side, it'd be much appreciated! I'll tag a new release ASAP. The only other thing I want to get merged in first is #986, which shouldn't take much effort to get across the finish line. Since the actual impact of this seems to be pretty low, I'll wait the couple of days until I can finish up merging that PR.

Thanks again for the excellent report! I'm afraid Gophish doesn't have a bounty, but please know that you taking the time to report this is much appreciated. The very least I can do is add the "Contributor" badge to your name on the repo, so keep an eye out for that 😄 

Thanks again!

**Comment by muffinns** [comment]
@jordan-wright I appreciate what you guys are doing with this project and am happy that I could contribute in a small way. I'll let you know as soon as I verify the fix. Also, I plan to take a more in depth look at the security of the software in the future.

**Comment by muffinns** [comment]
@jordan-wright Sorry for being too dumb to know how to test the commits on a live installation. I looked at the diffs and as long as the API key is truly being required for those endpoints the issue should be mitigated. 

Unfortunately I have to mention this neckbeard-security-low-probability scenario just so you are 
You will still be subject to authenticated SSRF, but this is just the nature of providing this kind of functionality in an application.

Just so you know if y
