### ISSUE TITLE
Gophish No Result

### ISSUE THREAD

**Issue by Panda44981** [gophish/gophish#1027]
Hello everyone,

I followed the documentation to perform my first phishing campaign with this link : https://gophish.gitbooks.io/user-guide/content/campaign/introducing_the_morning_catch_corporation.html

Everything works until the end. My problem is that i can't see any result of my campaign.

I can receive an email, i can open the link and redirect to enter credentials of the vulnerable Morning Catch machine, but, the dashboard of gophish indicate me only that an email was sent.

I tried a lot of different things (by myself or some respond in this forum) but, nothing work.

Can you help me ?

Thank you.

PS : the version of gophish that i use is 0.5.0 and i only follow this documentation with Morning Catch machines.

**Comment by jordan-wright** [comment]
What are you using as the URL? It needs to point to your Gophish phishing server, not the morning catch VM. If you don't see the "clicked" event show up, that means the URL you're putting in your campaign is probably not correct.

**Comment by jordan-wright** [comment]
That depends, is the IP address pointing to your local machine running Gophish?

An easy way to tell if you're pointed at the right URL is to visit that URL in your browser. If you see a "404 Not Found" error, and you see the connection log in your terminal, then you're pointed to the right place. Otherwise, the URL isn't pointed to Gophish. Hope this helps!

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in over a week. @Panda44981 if you're still running into issues, please take a look at the comment above and we can continue working to troubleshoot this 😄 

Thanks again for reaching out!
