### ISSUE TITLE
 Gophish does not notify when an email is opened

### ISSUE THREAD

**Issue by lasilva19** [gophish/gophish#1036]
Hello all,

Sorry for my english,

I use Gophish version v0.5.0, and I have an issue with results of Campaigns. I installed Gophish in a AWS instance with Red Hat Linux, but  in my tests the Gophish notify when the emails is sent. But he does not notify when a email is opened. Does anyone know how to solve this problem?

**Comment by davidfornesm** [comment]
In my experience, this is the number one case for this happening: "In order to track opens, images must auto-load in a user’s email client. If the sender isn’t already in the recipient’s email contacts, their email client may be blocking images from rendering by default. Additionally, if a recipient views a tracked email as plain text, the tracking pixel never has a chance to fire. If you’re not seeing opens on your first email in your cadence, it could be due to images not auto-loading." (John-Henry Scherck)

I encourage you to visit this link https://www.docsend.com/blog/email-tracking-doesnt-work/ in which other causes are listed.

**Comment by lasilva19** [comment]
Thanks, davidfornesm. I solved my problem after changing the template. Previously the images were not being opened on the email client.
