### ISSUE TITLE
EMAIL: Not sent 

### ISSUE THREAD

**Issue by tuxlimr** [gophish/gophish#1042]
Today, I have just downloaded the package for ubuntu linux 16.04: 64bit

When trying to send mail as test message it is giving error. I am trying same with my personal gmail id.
SMTP server  : smtp.gmail.com:587

Server screen is showing : 
192.168.1.131 - - [14/Apr/2018:17:26:12 +0400] "POST /api/util/send_test_email?api_key=ce59da84dbbfd9c2bf44813418090bd17d77d500bf98a026446a55b555389eed HTTP/2.0" 500 86 "https://192.168.1.131:3333/sending_profiles" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

**Comment by jordan-wright** [comment]
Hi @tuxlimr, thanks for reaching out. We'll need much more information to help troubleshoot this. Specifically, we would need to know things like:

* What version of Gophish are you using?
* What error are you seeing?
* What does the email template look like?
* Are there any other terminal logs you can provide?
etc.

The issue template you saw when you first chose to open a new issue helps guide you through what information we need. Since this doesn't follow the issue template format, I'm going to go ahead and close this out. If you are still running into issues, please don't hesitate to open a new issue following the issue template and providing as much information as possible. This will help us effectively troubleshoot the issue.

Thanks for reaching out!
