### ISSUE TITLE
Updating Gophish version

### ISSUE THREAD

**Issue by Paddyk3ll3h3r** [gophish/gophish#1043]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.3

Brief description of the issue: 
I am in the process of updating my gophish to the latest version. I copied over my DB file everything worked as planned. I then changed db_name from sqlite3 to mysql (as im using mysql) when I click on the gophish application the command box pops up and then disappears right away. I was expecting it to work perfect when i took an exact copy of the json file from the working older version and pasted it into the new version. If i change just the "sqlite3" it doesnt work and if i change it back it works again. 

What are you expecting to see happen? :
The command box to stay and gophish to work

What are you seeing happen?
command box disappears
 
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 -  Copied config.json from older version into the newly downloaded folder
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out.

> I copied over my DB file everything worked as planned.

What do you mean by this? This seems to indicate that you're using SQLite, but then you mention later that you're using MySQL.

> I then changed db_name from sqlite3 to mysql (as im using mysql) when I click on the gophish application the command box pops up and then disappears right away.

It kind of sounds like your trying to migrate from SQLite to MySQL? If so, this won't work as you probably expect since:

* MySQL expects a connection string containing things like the credentials to connect. You can find more information in our documentation [here](https://gophish.gitbooks.io/user-guide/content/installation.html#using-mysql)

* We don't automatically migrate things from SQLite to MySQL, so if this is what you're trying to do, just know that things won't be migrated automatically.

I'm also guessing that you're starting Gophish by clicking on the exe from an explorer window. I recommend opening a command prompt and running the binary from that command prompt to see the error that is being thrown which might give more information as to why things aren't working.

**Comment by Paddyk3ll3h3r** [comment]
Thanks for your response, ok maybe my username and password were incorrect, are these the credentials of gophish or coming from the database?
