### ISSUE TITLE
[Feature Request] Multi-Stage Landing Pages

### ISSUE THREAD

**Issue by weasel0x00** [gophish/gophish#1049]
What version of Gophish are you using?: 
5.0

Brief description of the issue: 
Feature Request:  As many login processes are changing over to a multiple stage process -- Submit email address, then submit password, then possibly submit 2FA code, it would be great if we can setup one landing page to submit to another landing page, so we can capture submitted data that invovles a multiple submit process

**Comment by jordan-wright** [comment]
Hi @weasel0x00, thanks for reaching out!

I completely agree that multi-stage landing pages are really important. And the good news is that we have plans to make this happen. I don't have a timeline at the moment (probably within the next couple of months or so), but I'm planning on making a new campaign builder which not only allows multi-stage landing pages, but other really neat features as well. You can find all the details in #223.

Since we're tracking things through that issue, I'm going to go ahead and close this one out. Don't hesitate to drop a comment there or keep an eye on that issue to stay up-to-date on progress. 😄 

Thanks again for getting in touch. Have a great weekend!
