### ISSUE TITLE
New visual options - Better maps

### ISSUE THREAD

**Issue by acklenx** [gophish/gophish#1056]
What version of Gophish are you using?: 
5.0

Brief description of the issue: 
I check the only UI settings button, but all my users are from the US and rarely travel.

What are you expecting to see happen? :
Click on the check box for US Map instead of World Map and see a map of the US with higher resolution plot points.  Or perhaps even just a single state.

Likewise it would be nice to see who(AOL, TimeWarner, My Company, etc) owns (at least by percentage) those IP addresses for those that opened/clicked/submitted credentials.  I would gain insight into if they were they internal users or at home, not using VPN.  And most significantly I could see which ISPs were block my phish.  

What are you seeing happen?
Just a world map, that does appears to have the coordinate necessary.

#

**Comment by jordan-wright** [comment]
Hi @acklenx, thanks for reaching out!

This is a good suggestion, and I can see your point. I'm afraid that this might be trickier than we think, since we have many Gophish users who don't live in the US. This means that to provide the same experience to everyone, I'd need to build out configuration options for specifying arbitrary countries and loading their specific maps accordingly. This might get even tougher since I don't know that [datamaps](https://datamaps.github.io/) has maps other than the world map and the US-specific map. I'd also have to consider those cases where we use the US map, but there are results outside the US. 

This would be quite a bit of work for a feature that's disabled by default. I'm certainly open to pull requests if you're interested in taking this on, but I'm afraid I won't have time to commit to it anytime soon 🙁

**Comment by acklenx** [comment]
Fair enough.  I'm new to Go but I'll see if I think I can take a stab at it.  There are actually a quite a few features I would like to add, but instead of whining about all of them I'll see if I can't be useful first. ;)  Great product btw.

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this one out for now since, as mentioned above, the library we currently use for maps doesn't support this out of the box and maps are already disabled by default.

Thanks again for sending over the idea, @acklenx! Please keep them coming!
