### ISSUE TITLE
Question : How do I use external database to capture gophish data

### ISSUE THREAD

**Issue by amithbelur** [gophish/gophish#1059]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.3

Brief description of the issue:
1. I am using Gophish for a big client for their email campaigns. I want to use  external database(client database-oracle DB or MySQL DB) to save the gophish data.  Is that possible? Please let me know the steps .

2.Can i host gophish on Amazon cloud(AWS EC2) ? Any supporting documents ? 

What are you expecting to see happen? : Save all the gophish data to external database

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

I highly recommend reading through our [excellent documentation](https://gophish.gitbooks.io/user-guide/content/), since it covers how to get Gophish up and running as well as [how to use MySQL](https://gophish.gitbooks.io/user-guide/content/installation.html#using-mysql).

One of our awesome community members, @LarryGrim, wrote up a great comprehensive guide on running Gophish in an EC2 environment. You can find a link to it in our documentation [here](https://gophish.gitbooks.io/user-guide/content/additional-references.html).

Hope this helps! If you encounter any specific issues when getting Gophish up and running, please don't hesitate to file another issue.

**Comment by jordan-wright** [comment]
Also, as a quick note, I'd consider upgrading Gophish to the latest version. There are quite a few fixes and improvements that will make your experience much better 😄

**Comment by amithbelur** [comment]
Thanks a lot for the swift reply .... I got it from your documentation about MySQL and will go through AWS hosting document that you have provided. Cheers !!!
