### ISSUE TITLE
GoPhish Unresponsive during "Bulk Import Users" while uploading .csv

### ISSUE THREAD

**Issue by mirkatson** [gophish/gophish#1063]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
- v0.6 (build from source)

Brief description of the issue: 
 - GoPhish unresponsive during "Bulk Import Users" while uploading .csv
 - .csv is about 150000 entries. (26mb file) - they are properly formatted according to the First Name, Last Name, Email, Position columns
 - Running on MySQL instead of SQLite

What are you expecting to see happen? : 
- Users loaded into database successful.

What are you seeing happen?
 - Chrome remains unresponsive during uploading of csv
 - Also, I realised MySQL doesn't remove records from targets table even when you deleted the Group through GoPhish admin panel

**Comment by mirkatson** [comment]
I tried to split the records into small portions, GoPhish managed to take in around 10000 records without causing Chrome to hang.

Is there anyway I can upload as a single file instead of multiple files or is there any settings I can tweak (e.g timeout on SQL)?

**Comment by jordan-wright** [comment]
Hi @mirkatson, thanks for reaching out!

> .csv is about 150000 entries. (26mb file)

I'm afraid Gophish isn't currently built to handle this kind of scale. I have plans to improve this, but it will be an iterative process that will take some time. The only option in the meantime is to break up the groups into smaller batches. With this kind of scale, I recommend using our REST API as much as possible since it will be far more responsive than the web UI.

Sorry for the inconvenience! Since there are other issues for slow CSV uploads and large groups, I'm going to go ahead and close this one out.
