### ISSUE TITLE
Enhancement - Allow mix of HTTPS/HTTP for Landing/Tracking

### ISSUE THREAD

**Issue by alecisec** [gophish/gophish#1072]
Would be good to allow use of 'http' for tracking-pixel in the email template and then have 'https' for the landing page. Most Outlook versions will not automatically load images over a secure connection hence when sending a gophish campaign, the option is either to forgo the ability to track 'read emails' versus having users submit their credentials over an insecure connection. Neither is optimal, this would involve splitting the 'URL' field on the campaign screen into a 'tracking url' and a 'landing url'

**Comment by jordan-wright** [comment]
Hi @alecisec, thanks for reaching out!

I'm afraid I don't have a good way to make this happen. This is a very specific scenario and is one of those cases where the complexity it would introduce into the UX wouldn't justify the value that we would get from it.

I would recommend leaning towards the first option you mentioned and just recognizing that there may be difficulties getting reliable open statistics from Outlook. Granted, reliable email open statistics has always been tricky due to privacy concerns so I'd be much more focused on the click/submitted data events.

Thanks again for reaching out, and I'm sorry there isn't more we can do to help address this issue! Keep the feature ideas coming! 😄

**Comment by alecisec** [comment]
What about if the tracking pixel is (always) delivered in http (non-tls)? the issue is that tracking doesn't work on modern Outlook clients because they will not pre-load images on HTTPS

**Comment by jordan-wright** [comment]
This alone would be tricky to implement because I would have to make sure that we always have an instance of the phishing server (or, even more complicated, just the tracking pixel handler?) listening on HTTP regardless of configuration. I would then need to make sure I only ever sent the 

Then, this would likely break on Office 365 or Gmail, since it would cause a mixed-content issue trying to load an image over HTTP when you're on their HTTPS sites. 

This would also cause confusion if the user specifies they want their phishing server over HTTPS. I could foresee support issues asking why their configuration isn't being applied properly.

I try not to make decisions about Gophish based on the behavior of a single mail client, since this is an incredibly slippery slope to go down. For example, this alone would cause significant architectural changes.

I would recommend handling this either by customizing your own instance of Gophish to fit your needs. This could be as simple as manually entering the tracking url when building emails and standing up a separate Gophish server listening on port 80 pointed to the same database that will catch requests for the tracking pixel.
