### ISSUE TITLE
Need {{.salutation}} TAG for handle Male / Female salutations in mails

### ISSUE THREAD

**Issue by H4xl0r** [gophish/gophish#1086]
Would be nice to have a {{.salutation}} TAG 
Adding Male Female Mark to Mail menu / import
Adding salutation Menu in panel to set default salutations for male o fem.
Adding Default salutes for countries would also be an option
DE: Male : Sehr geehrter Herr..... , Herr ....
DE: Female: Sehr geehrte Frau.... , Frau ....
Etc.

**Comment by jordan-wright** [comment]
Hi there! Thanks for sending over this suggestion.

I'm afraid I don't see myself adding this tag into Gophish, only because of the complexity it introduces for minimal gain. I would have to introduce a field for "gender" in the CSV upload as well as creating the tag, providing reasonable defaults, etc. Doing it per country makes it much trickier.

It's quite possible that this is culture specific, but speaking only for myself I've found formal salutations to actually make the email seem even more suspicious. If the goal is to create a convincing pretext then I would recommend taking a casual approach (e.g. using the recipients first name) since that can seem more personable.

Thanks again for the suggestion, and I apologize for any inconvenience not adding this in causes. You are more than welcome to modify your instance of Gophish. Eventually the goal is to let users create their own custom template tags, but I don't have a timeline for when this will be possible.

**Comment by H4xl0r** [comment]
Ok i know would be a hard way till there , thanks for the replay !
Hope the .stag is possible....

**Comment by addagrm** [comment]
I agree that this might be tricky. However, I have currently campaigns were I'd need a salutation (Dear Mr. surName) but in other campaigns I would like to omit the salutation and use Hi firstName or Dear firstName surName. Thus it would be annoying to add the salutation to the firstname as it would require two recipient lists containing the same contacts.
For my purposes it would be sufficient to have a freetext field. This way we would circumvent the problems you described but we could still store the information in a structured way with a maximum of customizability. Im currently using the position field for this purpose but I might need this in future for the intended purpose.

**Comment by Al-TSN** [comment]
Couldn't this be accomplished with https://github.com/gophish/gophish/pull/1813

**Comment by addagrm** [comment]
> Couldn't this be accomplished with #1813

Yes, a flexible templating would be even better
