### ISSUE TITLE
User sub groups

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#1093]
This is a feature request...

What version of Gophish are you using?: 0.6.0

As of now, you create a group/list of users, and that is what you have to work with.  What I would like to see are sub groups.

Example:  I have a group named "IT".  There may be 50+ users in that group.  I would like to be able to create sub-groups such as "LAN/WAN", "Desktop", etc.  When creating/modifying a campaign, I could then either pick "IT" for the entire group or "IT/Desktop" for just a subset.

**Comment by jordan-wright** [comment]
Hi @krasian!

Due to the way we represent the group data in the database, this would be really, really tricky to make native support in Gophish. Instead, my recommendation would be to use the group naming to make this happen. For example, you could name groups "<group_prefix>/<subgroup>" (e.g "IT/Desktop"). Then, when selecting groups for a campaign, you could type "IT" and select all/some of the groups you want.

That should give _roughly_ the same functionality that it sounds like you're looking for, since adding full subgroup support in Gophish won't be possible any time soon.

Thank you so much for continuing to send in feature requests. Please keep them coming!
