### ISSUE TITLE
Ability to export/import configuration

### ISSUE THREAD

**Issue by krasian** [gophish/gophish#1095]
This is a feature request

What version of Gophish are you using?: 0.6.0

Currently, you can export campaign results.  I would like the ability to export/import campaign configurations, landing pages, user groups, templates, etc.

This would allow for users to archive individual components or entire campaign configurations.  It would also allow the ability to export one configuration, use your favorite text editor such as VI or Notepad++to make modifications, and then import it as a new configuration or overwriting an existing one.  For me, the area I would most use this is for landing pages and email templates.

**Comment by jordan-wright** [comment]
Hi @krasian!

To be honest, I think this is one of those things I'd defer to the API. This is a great example of the power that the API can the offer, letting you easily download the existing objects, edit them, and then reupload them back to Gophish. We have an awesome [Python API client](https://github.com/gophish/api-client-python) if Golang isn't your language of choice 😄

Alternatively, if you don't want to use the API, it should be trivial to use standard database utilities to dump/load the database contents into a new Gophish db.

Since we have those two options that would work really well and adding in an import/export to Gophish would add quite a bit of complexity, I can't see us adding this into Gophish anytime soon.

If you run into issues using the API or using the database to accomplish your goals, please don't hesitate to open an issue and we'll work together to track it down.

Thanks again for getting in touch!
