### ISSUE TITLE
Email retry does not work 

### ISSUE THREAD

**Issue by SimonFThomas** [gophish/gophish#1098]
Version 0.5.0 Windows 64 bit

Campaign does not always try to resend failed emails. I am sending via Office 365 and I hit the 30 messages per minute limit. The remaining messages show an error status. Sometimes they retry (if there is just one email left to send for example). But sometimes they fail (when I tried to send 160 messages).

Can you please advise how this can be fixed, or advise how I can slow down the message send rate so I don't hit the 30 per minute limit. At the moment I have to split the users into groups of 30

**Comment by jordan-wright** [comment]
Hi @SimonFThomas - thanks for reaching out!

I recommend giving v0.6.0 a shot since we refactored the way email retries work in that version to be far more reliable. This should fix the issue.

Since I'm pretty confident that the issue you're running into sounds exactly like the one we fixed in v0.6.0 I'll go ahead and close this out for now. However, if after upgrading you're still running into this problem, let us know and we can continue troubleshooting.

Thanks again for getting in touch!
