### ISSUE TITLE
Feature request- add email delay option

### ISSUE THREAD

**Issue by TAP-Tech** [gophish/gophish#1112]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Suggestion:  Add option to stage emails.  When testing a business, it is suspicious when everyone receives the same email at the same time.  Adding an option to delay emails by N seconds would be great!

**Comment by jordan-wright** [comment]
Hi @TAP-Tech - thanks for reaching out!

I'm happy to report that we have an open pull request at #1090 that aims to solve this problem. We're reviewing various approaches and I'm working with @c-f to figure out the best way to make this happen.

Since this is a duplicate, I'm going to close this out so that we can track the progress through that pull request. Thanks again for getting in touch!
