### ISSUE TITLE
Feature Request: Ability to resend Emails that Error out.

### ISSUE THREAD

**Issue by JRodriguez556** [gophish/gophish#1114]
What version of Gophish are you using?: v0.6.0

Brief description of the issue: 
I would like to Manually resend emails that error out. 
I.E. I have and email which error due to "*Max connection attempts exceeded - 454 4.7.0 Too many login attempts, please try again later.*"
I would like to resend this email manually rather than having to create a new campaign to resend it. 

What are you expecting to see happen? :
A "resend email" button or functionality via the API

**Comment by jordan-wright** [comment]
Hi @JRodriguez556,

Thanks for reaching out!

We have a similar feature request at #79 that appears to be the same thing you're referring to here. Since this appears to be a duplicate, I'm going to close this out so we can track everything through #79.

I don't have a timeline for implementation yet, but fortunately the email refactor we completed in #878 should make this much easier to implement.

Thanks again for sending this in!

**Comment by rodrigoguzman** [comment]
Hello everyone! someone found the solution via API as discussed here? I have the same problem as everyone, I only sent 130 emails out of 800.
