### ISSUE TITLE
Gomail does not return any error when email has been rejected

### ISSUE THREAD

**Issue by Storm75** [gophish/gophish#1116]
**What version of Gophish are you using?**
v0.6.0

**Brief description of the issue:** 
I am using a Postfix as SMTP relay on localhost. Mail are perfectly sent and I also managed to use DKIM.

Now, when I use any target email address, it is considered "Sent" when it is not (see the 2 last emails used) : 

time="2018-06-25T16:56:26+02:00" level=info msg="Mailer got 3 mail to send"
time="2018-06-25T16:56:26+02:00" level=info msg="Email sent" email=john@hello.com
time="2018-06-25T16:56:26+02:00" level=info msg="Email sent" email=notexistingemail@cyklyagzfrggjao.ch
time="2018-06-25T16:56:26+02:00" level=info msg="Email sent" email=zfpzekfpezkpfoez@tgghhostnngk.com

Postfix logs : 

Jun 25 16:47:32 chbppca001 postfix/smtp[27100]: EE63A80539: to=<zfpzekfpezkpfoez@tgghhostnngk.com>, relay=10.42.201.205[10.42.201.205]:25, delay=0.13, delays=0.08/0/0.04/0, dsn=4.1.2, status=deferred (host 10.42.201.205[10.42.201.205] said: 450 4.1.2 <zfpzekfpezkpfoez@tgghhostnngk.com>: Recipient address rejected: Domain not found (in reply to RCPT TO command))

**What are you expecting to see happen? :**

Gomail.Send() should return something different than < nil > in this case. Also the mention "the best way to send emails in Go." should be removed since this package is trash and does not even deserve to be included in Gophish.

**Comment by jordan-wright** [comment]
Hi @Storm75, thanks for reaching out.

I'll preface this by saying I could be wrong here since I haven't personally used Postfix, but it seems that in this case the mail is received successfully by Postfix, in that Postfix is telling Gophish it's properly queued up the message for delivery. However, when Postfix then tries to send the email upstream, it fails.

I don't know of a surefire way to catch this since to Gomail the message seems to have been sent successfully in that it got a successful response from Postfix. I'm open to ideas, but we'll need to make sure they're not Postfix specific. I've considered the possibility of building a built-in SMTP relay but that's a long way off and wouldn't be nearly as powerful as postfix.

> Also the mention "the best way to send emails in Go." should be removed since this package is trash and does not even deserve to be included in Gophish.

Let's keep it civil, please. Gomail was chosen because it made it easier to do bulk sending. I forked the library since the original has since been abandoned by the maintainer. It does the job of letting us send emails upstream and works a vast majority of the time, so we'll keep it around for now 😉

**Comment by Storm75** [comment]
Thanks for the explanation. It makes sense now.
