### ISSUE TITLE
Allowing users to see each others campaigns

### ISSUE THREAD

**Issue by DustinEJD** [gophish/gophish#1117]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**0.6.0**
Brief description of the issue: 
**I would like to allow for users to be able to see each other's phishing campaigns. On a local instance of GoPhish, when I create a new user, it does not have access to the other user's campaigns**
What are you expecting to see happen? :
**Support for multi-user sharing of campaigns, so one user might be able to control and begin a campaign, where the other(s) might be only able to see the results, or possibly edit the campaign**
What are you seeing happen?
**The second user cannot see the main user's campaigns, therefore the list of campaigns for the second user is blank**
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - **Create a second or more users**
 * Step 2 - **View the second or the next user's list of campaigns, and the main user's campaign(s) is not there**

**Comment by jordan-wright** [comment]
Hi @DustinEJD,

Thanks for reaching out! We have a feature request open at #1034 that looks to cover what you're looking for. Basically, this would create the idea of "teams" in Gophish with various (albeit simple) roles.

There's no timeline on this yet, but we've had members of the community reach out interested in making this happen.

Since this appears to be a duplicate, I'm going to go ahead and close it out. We'll track progress through either #1034 or a formal RFC when we draft one.

Thanks again for sending this in!

**Comment by inlguy** [comment]
Based on the way we are using gophish the current model works really well.   I'm requesting that you maintain backwards compatibility in this regard. Please ensure different users cannot see each others campaigns without being granted permissions to do so. .  Thank you.
