### ISSUE TITLE
Doesn't show Submitted Data

### ISSUE THREAD

**Issue by GETBus** [gophish/gophish#1118]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Brief description of the issue: I sent out a test campaign to myself. I opened the landing page, entered a username and password, and submitted. It appeared from the client side to have worked. But when I go back to my Dashboard, all it shows is "Link Clicked", and thats it. It doesn't show "Data Submitted" at all. I went back and tried again, same thing, it only shows "Link Clicked" and it doesn't show that it submitted any data.

What are you expecting to see happen? : I am expecting for it to show that not only I opened the email and clicked the link but that I submitted data and to show what that data was (I selected in the campaign to store passwords and data unencrypted).

What are you seeing happen? It's only going as far as saying "Link Clicked" and thats it.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Simply submitting data through the Landing Page (in this case, a Facebook Import)
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @GETBus,

Thanks for reaching out!

Typically, this indicates there is something wrong with the HTML form on the landing page. Could you post the landing page you're using? That will help us quickly track down the issue.

**Comment by GETBus** [comment]
Jordan-wright:

Sure! It's a clone of Facebook. I had to attach it here as a .TXT file because it was too long to paste. Let me know how I can get this fixed. Thanks!

[Landing-Page_Facebook.txt](https://github.com/gophish/gophish/files/2141779/Landing-Page_Facebook.txt)

**Comment by jordan-wright** [comment]
Hi @GETBus,

Sorry for the delay. With any landing page, the high level recommendations to ensure Gophish is working correctly are to:

* Remove any Javascript that isn't needed for the page to function
* Remove any `onsubmit` listeners that might be causing the form submission to be processed by Javascript
* Make sure all `<input>` elements have a `name` attribute so they are sent appropriately.

I recommend making sure that the page you're using complies with those suggestions and that will likely help fix the issue.

On a side note, I strongly recommend against using a direct, as-is clone of any website. Instead, consider removing or changing all official branding to avoid confusing users. You will have the same results using a generic page and it helps prevent both brand infringement and unnecessarily hurting the user's trust in a brand. Remember, we're on the good side here. You can find more information about this in https://github.com/gophish/gophish/issues/1057.

For now, since this was a direct clone of Facebook's page, I've gone ahead and removed the attachment from the previous issue. Totally understood that you posted it for troubleshooting at my request, but I try to avoid permanently hosting that kind of content where possible.

Hope this helps!
