### ISSUE TITLE
Automation of creation/updating/removal of users and groups

### ISSUE THREAD

**Issue by DustinEJD** [gophish/gophish#1120]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**0.6.0**
Brief description of the issue: 
**We are in a corporate setting and would like to automate the creation/updating/removal of users and groups. We use ADUC, and could potentially export the users with their emails and positions. However, is there a way to automate this process, this way if someone leaves or joins the company we do not have to re-import a new list of users.**
What are you expecting to see happen? :
**Some type of automation for the users and groups pages**
What are you seeing happen?
**We currently have to manually import the list of users every time it gets updated**
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @DustinEJD,

Thanks for reaching out! I'm afraid there isn't currently a way to sync and refresh user groups from external identity providers. Since there are so many different external providers to consider, I can't see us adding specific ones in the future.

Instead, we have a comprehensive REST API that is perfect for situations like this. Using our [Python client](https://github.com/gophish/api-client-python), you could write a script that manages your groups for you, syncing up with your identity provider on a periodic basis. While the specifics of syncing to identity providers is out of the scope of our support, we're always happy to help if you encounter any issues using the client or our API.

I hope this helps! Thanks again for getting in touch.
