### ISSUE TITLE
Query in GoPhish Reports

### ISSUE THREAD

**Issue by amithbelur** [gophish/gophish#1127]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.3

Brief description of the issue: One of our user has raised a query on GoPhish. PFB the query.
1. **Can the goPhish report also capture, e.g. if the user click on the link only, click the link and submit data, time clicked and browser type (browser or mobile)?**

2. **Can the GoPhish reports be customizable according to our requirements so that a good/professional looking report can be sent to client ?** 

Please answer.

Thanks in advance --Amith

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @amithbelur,

Thanks for reaching out!

All of the information in your first question is captured in our raw event log, which can be exported from the campaign results page as a CSV.

Then, when it comes to organizing and visualizing that information, like your second suggestion, I'm afraid that's not something we do in Gophish beyond the traditional dashboard. Any other visualization would be both development heavy and likely unique to each person's suggestions so we just stick to one dashboard layout. I recommend using the CSV or our API to build a visualization that works for you.

If in the process of using Gophish for client engagements you build out a new way to visualize reports, I highly recommend considering open-sourcing what you build! Gophish itself is free software and I encourage community members to give back so that other community members can benefit.

Thanks for reaching out, and I hope this helps!
