### ISSUE TITLE
HTML Class is Removed Completely

### ISSUE THREAD

**Issue by vonswoopington** [gophish/gophish#1128]
**What version of Gophish are you using?:**  v0.6.0 

**Brief description of the issue:** HTML class gets removed if you import the page, add it manually, or  toggle the HTML source, or try to save the template.

**What are you expecting to see happen? :**  HTML class should not be removed since it is required for the page to display correctly.  It should import the html class when "Import Site" is used.

**What are you seeing happen?**

The class disappears if you toggle HTML Source, Import Site, save the template, or toggle html source.  That portion of HTML is replaced with `<p>&nbsp;</p>`

**If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:**

```
<html class="login-page ol-modernize-js ol-modernize-flexbox ol-modernize-canvas ol-modernize-canvastext ol-modernize-webgl ol-modernize-no-touch ol-modernize-geolocation ol-modernize-postmessage ol-modernize-websqldatabase ol-modernize-indexeddb ol-modernize-hashchange ol-modernize-history ol-modernize-draganddrop ol-modernize-websockets ol-modernize-rgba ol-modernize-hsla ol-modernize-multiplebgs ol-modernize-backgroundsize ol-modernize-borderimage ol-modernize-borderradius ol-modernize-boxshadow ol-modernize-textshadow ol-modernize-opacity ol-modernize-cssanimations ol-modernize-csscolumns ol-modernize-cssgradients ol-modernize-cssreflections ol-modernize-csstransforms ol-modernize-csstransforms3d ol-modernize-csstransitions ol-modernize-fontface ol-modernize-generatedcontent ol-modernize-video ol-modernize-audio ol-modernize-localstorage ol-modernize-sessionstorage ol-modernize-webworkers ol-modernize-applicationcache ol-modernize-svg ol-modernize-inlinesvg ol-modernize-smil ol-modernize-svgclippaths" lang="en" style="">
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create new template
 * Step 2 - Paste the above HTML Class
 * Step 3 - Toggle Source
 * Step 4 - The code becomes replaced with `<p>&nbsp;</p>`

 Any thoughts on what could be causing this?

Thanks

**Comment by jordan-wright** [comment]
Hi @vonswoopington 

Thanks for reaching out!

I'm afraid that importing landing pages is always a "best-effort" approach, where I can't guarantee the editor we use, CKEditor, will do exactly what we want.

In this case, it appears that CKEditor doesn't like classes at the root of the HTML node. If instead you were to structure the HTML so that the class list occurs on the nested `<body>` element, CKEditor shouldn't remove these according to my testing. In this case, the stylings will still be applied.

I don't think there's much we can do in this case to change the behavior of CKEditor, so adjusting the HTML will be our best bet. Sorry for the inconvenience!

Thanks again for getting in touch!
