### ISSUE TITLE
Gophish and VPS for beginners

### ISSUE THREAD

**Issue by habsfan50** [gophish/gophish#1130]
@jordan-wright @stracire Hi, I am very new to all of this and trying to understand how to run Gophish on a VPS. Please let me know if I am understanding this correctly.
 I rent a VPS from DigitalOcean for example, log into my VPS using something like SSH, and install gophish. Then I purchase a domain and inside the dns management page of my domain, point the domain to the IP address of the server. Does this mean that when I connect to my domain address I will be directed to the server? 

Can the VPS have a domain so I can skip buying a domain because I'm only using a landing page that I created in gophish and I don't require any other pages because I'm using this a test? 

Thanks in advance.

**Comment by stracire** [comment]
An IP-adres is just like a phone number. Nowadays you just enter a name and press call. A domain does nearly the same trick for an IP-adres. So a domain is a 'nice to have', but not a must have. You can still visit the landing page by just entering the IP. People often do not trust an IP. Domains are trusted more often. But in my experience people often do not check what they are clicking. Sending e-mails with just an IP-address as a link will still give interesting results. 

If you are new to the world of e-mail, then I recommend to read some articles about spoofing, SMTP and configuring a mailserver. Since configuring Gophish is only a first step.

**Comment by jordan-wright** [comment]
Hi @habsfan50, as @stracire mentioned, domains aren't strictly _required_ but a nice-to-have when building campaigns.

> Can the VPS have a domain so I can skip buying a domain because I'm only using a landing page that I created in gophish and I don't require any other pages because I'm using this a test?

I don't know of any free domains that come with a VPS, besides possible dynamic DNS offerings which will likely be pretty heavily blacklisted.

That said, I'd like to take a step back and reconsider if Gophish is the correct framework for your use case. Gophish has a great featureset, but it does require some networking/system administration to operate that unfortunately can't be avoided. @stracire is absolutely correct that configuring Gophish is likely going to be the "easy part" throughout this whole process. There's an entire other process around setting up and maintaining a mail server, configuring proper email authentication, managing the domains and networking, and more that is out of the scope for the support we can provide. Usually, Gophish can get by using the mail server already set up by organizations to send emails but it sounds like that may not be the case here.

Instead, if you're just wanting to run good phishing campaigns and get the results, there are hosted solutions that are completely free which may be a better option. One in particular I can recommend is [Duo Insight](https://insight.duo.com/) (disclaimer: I work at Duo).

Gophish is great for people who need that level of flexibility but sometimes the technical barriers can get in the way. These hosted solutions offer a really great alternative that still gives high-quality (but less configurable) phishing campaigns for free.

I hope this helps! Since your original question has been answered, I'm going to go ahead and close this one out. Thanks again for getting in touch!
