### ISSUE TITLE
Email Delivery by Time Zone

### ISSUE THREAD

**Issue by definity** [gophish/gophish#1131]
This is an enhancement request.

There should be support for email delivery by time zone.  For people using GoPhish to run campaigns that span the globe, the recipient time zone is often an important attribute from a scheduling perspective.  This is especially important when there are large groups of recipients and admins want to ensure emails are delivered at, for example, 9:00 AM on Tuesday.  Without delivery by time zone, one would need to create a separate campaign for each group of users.  If the UTC offset were included as an optional field in the user list (or CSV for bulk import), GoPhish could use this to deliver the email to the user at the correct date/time specified in the campaign.

While this might be solved by creating campaigns programmatically with the GoPhish API, I found the [API documentation](https://gophish.gitbook.io/api-documentation/campaigns) a little "rough" but it looks doable with a little bit of coding.

Nevertheless, I maintain that email delivery by time zone is an enhancement that would be welcomed by anyone who is using GoPhish with a user base spanning multiple time zones.

Thanks for all your hard work and for considering this request!

**Comment by jordan-wright** [comment]
Hi @definity,

Thanks for reaching out!

I can totally understand the desire to send emails based on the time zone of the recipient. However, I'm afraid this would be pretty tricky to implement. We'd have to figure out a non-confusing UI, make sure we're calculating offsets correctly when building the campaign, adjust reporting to reflect the different time zones, and more.

I won't say a hard "no" to this since it's possible we'll get to this in the future, but given the development time I can't see it realistically happening any time soon. 🙁 With this being the case, I'm going to go ahead and close this out _for now_ as "wontfix", but it's possible I will re-open this again in the future.

That said, I agree with you that creating campaigns programmatically might be the way to go in the meantime. You could consider creating user groups that contain users in the same time zone. Then, you could build campaigns around those groups.

I apologize for any inconvenience this causes in the meantime. I appreciate you reaching out, and please keep the ideas coming!
