### ISSUE TITLE
Multiple landing pages with different domain names and SSL

### ISSUE THREAD

**Issue by Clunkline** [gophish/gophish#1136]
**What version of Gophish are you using?:** 
0.6.0
**Brief description of the issue:** 
I want to use multiple domains which will be using SSL
**What are you expecting to see happen? :**
Multiple landing pages which show the domain instead of an IP and have the green ssl lock sign.
**What are you seeing happen?**
I can only use one landingpage that will actually "listen"

Many thanks for already answering all my questions so fast! For now: I have multiple domains pointed with the A record to my phishing server, because I regularly will use different scenarios. When I set the listener info in the config.json to any of the domains it works fine and i can use that scenario. However when I use a scenario with another domain on the same IP, I would need to change the info in the config and restart the server. How can I set this up and use a different ssl certficate for every domain? I already searched through the issues and I could only find something abt a reverse proxy server in between and i don'y have that.

**Comment by jordan-wright** [comment]
Hi @Clunkline!

I'm afraid this isn't possible with the current version of Gophish. This would be pretty tricky to implement, since we'd have to handle proper SNI support to know which certificate to return.

The best way to handle this at the moment would be to use certificates with subject alternate names for your domains. That way, you can have multiple domains share a certificate.

I hope this helps! Sorry there isn't more we can do in the meantime.

**Comment by Clunkline** [comment]
Hi Jordan,

Thanks for your quick replies. Using 1 certificate with alternate domain names configured in it is acceptable for me I guess. However, I do have a follow-up question:

Lets say I start a phishing campain on friday for domain1.com. I would have "listen_url" : "domain1.com:443" In the config file. What if I want to start another campain for domain2 on monday? Is it possible to listen at 2 domains at the same time?(Since campain 1 is still running on monday and I want to keep "listening" there, but also I want to listen for the second campain now). Or should I really wait until campain 1 is done and then manually edit the config file and change the listener to domain2 before I start a new campain? (This would be dissapointing). If so, do you have any other suggestions on how I could achieve my target situation(a situation in which I could start multiple phishing campains for different groups on different domains). Many thanks in advance!

**Comment by S0larflare** [comment]
If you set the listen url to 0.0.0.0:443, then you should be able to run multiple campaigns with different urls.

Sent from my iPhone

On 22 Jul 2018, at 00:08, Clunkline <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jordan,

Thanks for your quick replies. Using 1 certificate with alternate domain names configured in it is acceptable for me I guess. However, I do have a follow-up question:

Lets say I start a phishing campain on friday for domain1.com<http://domain1.com>. I would have "listen_url" : "domain1.com:443<http://domain1.com:443>" In the config file. What if I want to start another campain for domain2 on monday? Is it possible to listen at 2 domains at the same time?(Since campain 1 is still running on monday and I want to keep "listening" there, but also I want to listen for the second campain now). Or should I really wait until campain 1 is done and then manually edit the config file and change the listener to domain2 before I start a new campain? (This would be dissapointing). If so, do you have any other suggestions on how I could achieve my target situation(a situation in which I could start multiple phishing campains for different groups on different domains). Many thanks in advance!

**Comment by KiransHub** [comment]
@S0larflare I think the OP is asking more about SSL signing though this is quite a useful point for listening in general. I will try it myself. 

I don't think it answers the OPs question about SSL though
