### ISSUE TITLE
List RIDs / remove the requirement for a RID

### ISSUE THREAD

**Issue by RizzyRong** [gophish/gophish#1145]
What version of Gophish are you using?: v0.6.0

Brief description of the issue: 
Is there away to list the RIDs out of the database?
Or is there away to remove the need for a RID?

What are you seeing happen?
I want to use gophish as just a landing page to track users I talk into browsing to my page and login in during a vishing engagement.

**Comment by jordan-wright** [comment]
Hi @RizzyRong,

It looks like you just want a standard web server. In this case, any web server such as Apache or nginx would work just fine - you could just watch the access logs as calls are being made.

I'm afraid that there is no way to remove the need for the `rid` parameter, since it's a unique ID generated for every recipient of a phishing simulation that tells Gophish what landing page to load, who is clicking the link, etc.

Hope this helps!
