### ISSUE TITLE
Logged Keystrokes or Captured Post 

### ISSUE THREAD

**Issue by bandrel** [gophish/gophish#115]
Would be nice to have the ability to log keystrokes or capture POST on landing page.

**Comment by bandrel** [comment]
I see that there is currently a branch.  Assuming this a feature you are already working on

**Comment by jordan-wright** [comment]
Yep! Coding this as we speak :smile:

**Comment by rfdevere** [comment]
Aim for the live capture as seen in simple fishing framework, failing that just the post like in SET.

**Comment by jordan-wright** [comment]
Interesting! Can you expand on what you mean by "live capture?" I might need to spin up an instance of SPT.

What I'm doing now is capturing any POST request and serializing those into json to store in the database. So it can at least capture creds! I'm going to work to making things like automatically cleaning up form "actions" so the users don't have to manually change that.

**Comment by rfdevere** [comment]
https://github.com/tatanus/SPF This hillbilly god! SPF is a brilliant little CLI tool. When you input credentials on the cloned phishing site the keystrokes are sent one key at a time with some java magic. Great for live phishing 2-factor portals. Might be overkill but look into it for mere amusement.

**Comment by tatanus** [comment]
so, what is meant by "live capture" is that with SPF I log in real time to both a log file and to the console all of the key strokes (including TABs and BACKSPACEs and DELETEs) so that even if the victim does not hit the form submit, you still have a log of what they did enter.  It is also useful because sometimes people enter other passwords without thinking and then go back and change them, thus you can collect them as well.  This is possible because I host the phishing website via a built in web server (python twisted-web to be precise) and thus can inject a javascript keylogger into the web pages and capture the keystrokes in real time.

if you have any questions or would like to know more/need addition info/etc, please feel free to contact me.

P.S.   I definitely like this tool.   Good work   :)

**Comment by tatanus** [comment]
to help limit the confusion, let me further clarify, while I do the "live capture" as stated previous, I also capture and log all POST variables (such as usernames/passwords/tokens/etc...) when submitted.

**Comment by jordan-wright** [comment]
Ah, ok, gotcha. First off, that's way cool that you implemented this in SPT. Great work!

I'm going to be thinking about ways I could integrate this into gophish. It might be tricky since I'd have to:

* Probably do this via a websocket connection (or long polling)
* Save each keystroke to the database somehow. Those updates might get expensive after a while.

If I can come up with an elegant solution, I'm definitely game to add this.

**Comment by tatanus** [comment]
sounds good and good luck adding it.

I added it to my tool as it was something I always wanted in a phishing tool and since I was writing it, I added it.

And it is SPF (speed phishing framework) not SPT which is a different project by someone else.   ;)

**Comment by rfdevere** [comment]
@tatanus Thanks for this, you're all gentleman.
