### ISSUE TITLE
Querying API for campaign info based on rID parameter

### ISSUE THREAD

**Issue by fridgehead** [gophish/gophish#1151]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.4

Brief description of the issue: Is it possible to query the API for campaign information using the rID parameter from a phished user?

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hey @fridgehead, thanks for reaching out!

I'm afraid this currently isn't possible. You could iterate over campaigns looking for that `rid` but totally understand that an o(n^2) search like that wouldn't be ideal. Since this isn't a common use case I hear about, I don't think I'll be adding an endpoint for this soon, but I'll keep it in mind. If I can find a good way to make this work, I'll make it happen.

Instead, for now, if you have access to the database, each entry in the `results` table has a campaign ID field you could use to query for the campaign. Still not ideal, but probably the quickest way to get the data you're after. You could also write a script for this, using some of the functions in the Gophish code, but that'd add another layer of complexity for sure.

I hope this helps! Thanks again for reaching out. I'll keep that API endpoint in mind to see if I can get something implemented.
