### ISSUE TITLE
Issue Setting Up Gophish with Proxy Server

### ISSUE THREAD

**Issue by shahriarshayan** [gophish/gophish#1155]
Hello, Thanks for your prompt reply. We are also not understanding the issue. We have doing internal social email awareness campaign from GoPhish. For example, our GoPhish config.json is have following configuration  GoPhish Dashboard IP: 192.168.x.x:3333 GoPhish listener url: 192.168.x.x:84  However, our internal network also having a proxy server which is y.y.y.y:3128  Scenario 1: After launching the campaign from GoPhish, it has been observed that, if receiver browser doesn't have the mentioned proxy server in the browser proxy settings then our GoPhish listener and the redirect page is working smoothly. there is no issue happened.  Scenario 2: After launching the campaign from GoPhish, it has been observed that if receiver browser have enabled the proxy (y.y.y.y:3128) setting in his/her IE, Firefox or Chorme, then my redirecting page is not working.  We are facing this problem specially in scenario 2. Need your kind suggestion.

**Comment by jordan-wright** [comment]
Hi there,

Thanks for reaching out!

As mentioned in #1146, it's very important that you please follow the issue template we created. It guides you through what information we need in order to help troubleshoot.

> if receiver browser doesn't have the mentioned proxy server in the browser proxy settings then our GoPhish listener and the redirect page is working smoothly

At this point, it seems that everything in Gophish is working as intended. I'm afraid that any scenarios beyond this are out of the scope of what I can control and support. I'm afraid I don't know the specifics of how your proxy servers are set up and what might be causing the redirect to fail. For Gophish, we require that the recipient of the emails is able to reach your Gophish server. How that happens is a networking exercise, not something we can control in Gophish.

Sorry I couldn't be of more assistance!
