### ISSUE TITLE
Feature Request: User-Agent from all campaign events

### ISSUE THREAD

**Issue by ad0nis** [gophish/gophish#1166]
What version of Gophish are you using?: 
built from git today

Brief description of the issue: 
Similar to https://github.com/gophish/gophish/issues/908 - User-Agent strings not being harvested on email open.

What are you expecting to see happen? :

I would like to see the User-Agent harvested for each email open.

What are you seeing happen?

I'm seeing users open emails multiple times, and I'd like to know what devices they're opening them from. Is the user looking at it over and over on their phone, or starting on the phone and moving to their laptop, or what? Does it reveal an Outlook User-agent, perhaps? Who knows!

To add to this feature request, it would be nice to be able to view the raw user agent strings as well as the parsed ones that the latest UI currently shows.

**Comment by jordan-wright** [comment]
Hi @ad0nis,

Thanks for reaching out. The user-agent for these events should be in the raw logs. We don't show the raw UA's in the UI since they would take up quite a bit of real-estate in the results view.

It's difficult for us to parse these particular user-agents in the same way, since many of them will likely be for things like Exchange instead of the traditional device/browser format. I'll do some experimenting, but at this time I don't plan on adding that.

Hope this helps! For getting these logs, I definitely recommend looking at the raw logs export, since it should have all the info you're looking for.
