### ISSUE TITLE
Sending emails partially

### ISSUE THREAD

**Issue by brekler88** [gophish/gophish#1177]
Hello, right now im using the latest version of gophish and already launched a teste.

This tool is awesome, but i need to know if there is any way to configure gophish to send the emails partially... like 33% every 1 hour.

The first email i sent was great, but a lot of people said "omg, so weird, everyone received the same time".

Im trying another tool that i can configure the sending time, and i tought gophish should do that aswell.

Any way i can configure that ?

**Comment by jordan-wright** [comment]
Hi @brekler88,

Thanks for reaching out! You're not alone! 😄 Staggering emails has been requested before in #110 #611 and #501. There's also a first take on this in #1090.

There's still some changes in that pull request to get the format how I'd like it to be, but the hard work has been done. If I have some time this weekend, I'll see if I can merge in that pull request and finish it up.

For now, since this is being tracked in other issues, I'm going to go ahead and close this one out so that we don't have too many duplicates open.

Thanks for getting in touch!
