### ISSUE TITLE
Recover deleted campaign

### ISSUE THREAD

**Issue by brekler88** [gophish/gophish#1181]
Hello guys, by mistake i deleted a campaing and i was supposed to click on "complete".

Is there any way i can recover that campaign ?

**Comment by jordan-wright** [comment]
I'm afraid not 😞 Right now, we fully delete the campaign and associated result entries. In the future, we may just consider soft-deleting, which would just add a "DeletedAt" column instead of removing the records. The ORM we use supports this, but there would be some migration work involved.

We'd also have to consider the space considerations, since campaigns _could_ wind up taking quite a bit of space over time.

For now, I'm sorry to say that there isn't more we can do to help recover the campaign. 😞

**Comment by brekler88** [comment]
Ohh well....
Lucky i printed the results yesterday =D
but i wanted to leave a record on my server

thanks anyway!
