### ISSUE TITLE
How to send an email from Gophish as an Alias email domain?

### ISSUE THREAD

**Issue by geead** [gophish/gophish#1183]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  0.6.0

Brief description of the issue: Trying to send an email via my dedicated smtp server (Gmail) as an alias (not sure if it is possible)

What are you expecting to see happen? : Hoping to have my email sent to the receiver as the Alias email domain and not the one which is originally set in the "Sending Profile" (have made the Alias my default sending email address in Gmail)

What are you seeing happen? The address of the email being sent is still the one I use "From" in the "Sending

**Comment by jordan-wright** [comment]
Hi @geead,

Thanks for reaching out!

Gmail is a unique example, since it will always show the sender as the authenticated user. Instead, if you're looking to do a phishing simulation for your organization that uses Gmail, you will need to set up an external VPS with Gophish that has a mail relay like Postfix. Then, Postfix will send emails to the servers listed in your domain's MX records, spoofing the sender.

But, it's important to note that you'll want to consider setting up email authentication for the custom domain. You can find more information about that [here](https://www.trustedsec.com/2018/03/take-employees-phishing/).

I hope this helps!

**Comment by geead** [comment]
Hi @jordan-wright,

Thanks for the quick response!

The phishing simulation in my situation is actually going to be on office365 (have been using Gmail to test and see if it would work as an Alias) - would it be the same process if the initial Sender email is within outlook365?

The end goal is that lets say an email being sent as John Smith <john.smith@companyname.com> will be Aliased to the received to come up as e.g. IT Support <john.smith@ITSupport.net> (or even changing the john smith name) - not sure if this is possible, just reaching out to see as it is my first time learning the Gophish platform.

Cheers,
Geaad

**Comment by jordan-wright** [comment]
It's _possible_ that office365 does the same thing, but I've never used it so I'm afraid I can't say for sure. The safest bet would be to send the emails from a VPS with email authentication configured correctly. This would essentially be setting up a proper domain and mail relay to send email from, and then sending the emails 😄 

Anytime you authenticate as a user and try to spoof the domain, it's up to the mail relay to determine if/how that will be allowed.

**Comment by geead** [comment]
Thanks for the help! - sounds like VPS is the way to go :)
