### ISSUE TITLE
Automatic reply statistics

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#1190]
Hi,

When I launch phishing campaigns I create a rule so *@phishingdomain.com goes to a personal email account.
That email account has a rule to put everything form phishingdomain.com into a folder.

It would be good if there was a way to forward these emails back to gophish to include in the statistics.
(usually automated things like: out of office, mailbox no longer in use etc.)

**Comment by jordan-wright** [comment]
Hi @nanoymaster,

Thanks for getting in touch, and I apologize for the delay in getting back to you. I can completely understand the desire to ingest email bounces into Gophish, and there have been [other issues](https://github.com/gophish/gophish/search?q=imap&type=Issues) asking for the same, but it would take a _significant_ amount of work to make that happen.

We'd have to start by having a full IMAP implementation to pull the emails from a stored mailbox. This would then require us to build out the UX for managing IMAP which likely would only cause more confusion than it'd be worth. Finally, we'd have to figure out how to map those bounces to campaigns and figure out the UI for showing those results- not to mention if we needed to parse the bounced messages to figure out what kind of message it is.

All this to say I don't have plans to make this happen any time soon, since I can't justify the amount of development it would require. I apologize for any inconvenience this causes!

Thanks again for getting in touch!
