### ISSUE TITLE
HTML Export

### ISSUE THREAD

**Issue by netektives** [gophish/gophish#120]
Can an HTML export be on the radar for future release?

**Comment by jordan-wright** [comment]
Which HTML would you like to export? The HTML is already returned via the API for templates and landing pages.

**Comment by netektives** [comment]
Thanks for the quick response, this tool is awesome.

What I was referring to was the Campaign results screen.  I see that I can export to a csv and the events, which could be used to create something like a Crystal Report, but being able to save the results as html would be helpful as well.

**Comment by jordan-wright** [comment]
@netektives - Good idea! I've been thinking about other export options, such as HTML, PDF, etc.

Eventually, we're planning on having an enterprise offering. I don't know what that looks like yet, but there may be some export options that we support on the enterprise version. I'll keep this open for now, since I'd like to offer at least one "pretty" export option for the free version so people having things to go with besides CSV.

I think HTML is a great choice!

**Comment by jordan-wright** [comment]
I'm going to go ahead and close this out for now. It's possible that I'll look into providing HTML reporting in the future, but for now we'll rely on people being able to parse CSV however they prefer.

Thanks for the suggestion!
