### ISSUE TITLE
gophish.db delete enteies

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1201]
Was looking through the database, and saw that old users were still in the database even if i deleted them on from the admin panel. is that a mistake that it dosen't delete the entries. Don't know if it is only users, dont want to delete landingpages, email templates and campaigns...
Hope you will look throug this "issue".
im using sqlite3, just standart gophish install.

**Comment by jordan-wright** [comment]
Hi @dsmurf,

You're correct that we don't delete the actual user entries themselves. This is because user IDs are mapped in a many-to-many relationship with groups. If we wanted to also delete users when a group is deleted, we'd have to introduce other checks, such as if the user belongs to any other group, how do we handle bringing a user back onboard if they've been deleted and recreated, etc.

For now, I don't plan on changing this, but I'm open to suggestions! Thanks again for getting in touch!
