### ISSUE TITLE
Feature request: Attachement tracking

### ISSUE THREAD

**Issue by CyberM070** [gophish/gophish#1214]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Feature request

What are you expecting to see happen? : Is is possible to track if someone openend an attachment and display it on the dashboard? See for example https://bananatag.com/attachment-tracking/. This would be a great opportunity to see if employees would fall for 'malicious' attachments and be able to track it.  

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @CyberM070,

Thanks for reaching out! Attachment tracking is something that's been requested [many times](https://github.com/gophish/gophish/search?q=attachment+tracking&unscoped_q=attachment+tracking&type=Issues) in the past. Right now, I don't have an ETA when it will be available, since there are different ways to perform attachment tracking, yet with Gophish I want it to "just work" with as little work required by the user as possible.

For some ideas and possible options in the meantime, I recommend checking out the linked issues.

Thanks again for getting in touch!
