### ISSUE TITLE
Namecheap & CPanel installation

### ISSUE THREAD

**Issue by samiej927** [gophish/gophish#1217]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Gophish v0.7.1

Brief description of the issue: I'm new to this and having a little problem understanding on how to properly setup and install GoPhish on Windows 10 with Namecheap & CPanel

What are you expecting to see happen? I would like to see it work

What are you seeing happen? Nothing at all cause i don't understand what needs to be done. A little bit more detail on the installation process would help me out greatly

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @samiej927,

I'm afraid I haven't used cPanel before, so I can't provide in-depth installation instructions. From what I recall about cPanel though, it isn't a complete VPS in that it restricts what you can do so it likely won't work. For Gophish to be installed, you access to a full server so that you can run the Gophish binary.

Once you have access to a full VPS, you can follow the instructions in our documentation to install and run Gophish.

I hope this helps!
