### ISSUE TITLE
Duplicate Emails Sent in Campaign?

### ISSUE THREAD

**Issue by geead** [gophish/gophish#1223]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.6.0

Brief description of the issue: Duplicate emails sent out when conducting a Phishing Simulation Test

What are you expecting to see happen? Send one email per the people in my "Users & Groups" list.

What are you seeing happen? I conducted a Phishing Simulation to a large number of email accounts within my organisation (Phishing Security Test done within IT), and it started sending emails twice to people during the stage of sending the emails - just want to find out if this has ever happened before?

**Comment by jordan-wright** [comment]
Hi @geead,

Thanks for reaching out! Without more information about the workflow, it would be hard to pin down what might be causing this. For example, did the Gophish server crash during sending emails? Barring an unknown bug, Gophish _shouldn't_ send duplicate emails. If it detects duplicate recipients it should ignore them.

There have been similar reports such as #1073, however this was resolved by upgrading to 0.6.0 which refactored the way our mailer works. If you're still seeing this, I recommend first checking out the events for a given recipient to see what the duplicates "look like". As in, does Gophish show only one "Email sent" event, or two? Were there any error events listed that may have indicated a retry that would suggest duplicate emails being sent?

You might also try upgrading Gophish to the latest version and see if that helps, since it's possible some bug was fixed that would help resolve this issue.

**Comment by jordan-wright** [comment]
Hey @geead,

Just checking in, if you could review my comment above and let me know what you think I'd be happy to continue troubleshooting this.

**Comment by jordan-wright** [comment]
Going ahead and closing this particular issue since there hasn't been any updates in a couple of weeks. Another issue, #1073 appears to be the same bug so we'll close this in favor of tracking things through that issue.
