### ISSUE TITLE
Problems "not" with gophish.

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1224]
Im having problems and dont know its with gophish or not.
When i send out a campaign, to a domain that whitelisted the mailserver.
I have installed postfix on the gophish server.

**Comment by dsmurf** [comment]
The whitelisting is done, and emails dont end up in spam.
But it has taken more then 16 hours to send 136 mails.

**Comment by jordan-wright** [comment]
That could be normal depending on the receiving server. It's a common technique to send a "backoff" response code when you receive email from new servers. I'm not sure if whitelisting would prevent this- it would probably depend on the mail server and the settings.

Unfortunately, there isn't anything we can do on the Gophish end to fix this. If Gophish sees the temporary error response code, it will apply an [exponential backoff](https://github.com/gophish/gophish/blob/c315867ceac3c962e381f5d2f72ecd47163e8ecd/mailer/mailer.go#L164) and you will see this reflected in the UI. Otherwise, if Postfix sees the response code (I'm not sure if it propagates this back up to Gophish), you may need to check the Postfix logs to see what's going on.

Sorry I can't be of more help! Since this isn't something we can directly change in Gophish, I'm going to go ahead and close this one out for now. I recommend continuing to work with the receiving mail server to see if there's any information on why the emails are being delayed.

If you come across any more information, don't hesitate to add it to this issue and we can continue troubleshooting.

Thanks again for reaching out!

**Comment by akash-bit** [comment]
> The whitelisting is done, and emails dont end up in spam.
> But it has taken more then 16 hours to send 136 mails.

HOW TO WHITELIST THE SERVER...
