### ISSUE TITLE
sending profile localhost port no. change

### ISSUE THREAD

**Issue by dsmurf** [gophish/gophish#1228]
**What version of Gophish are you using?:** 
0.71

**Brief description of the issue:** 
if i write localhost in sending profile is sends out on port 25
where can i change localhost to send out on a different port, so i dont have to write localhost:portno in sending profile.

**Comment by jordan-wright** [comment]
Hey @dsmurf, thanks for reaching out.

I take it you’re asking how to tell Gophish that emails should be sent to a port different than 25? If that’s the case, the only way to do that is to specify the host:port syntax in a sending profile like you mentioned.

**Comment by dsmurf** [comment]
I want it to send from another port just by typing localhost

**Comment by jordan-wright** [comment]
Hey @dsmurf,

I'm afraid this isn't possible in Gophish. The default SMTP port is 25, so that's what we use if you don't specify a port. If you wish to use a non-standard port, you'll need to specify that in the sending profile.

Sorry I couldn't be of more help! If you _really_ need to just put `localhost` and wish it to go to a separate port, you'd have to do something on the host to pass the traffic from port 25 to whichever port you want.
