### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by mcvaa** [gophish/gophish#1229]
What version of Gophish are you using?:  Gophish ver 0.7.1

Brief description of the issue: 
Created a Self Signed Cert but need a Requested SSL Cert

What are you expecting to see happen? :
The connection is not secure trying to create a secure connection internal and external.

What are you seeing happen?
![sslconnection](https://user-images.githubusercontent.com/14318521/46678181-16af3b00-cbb2-11e8-887a-f1a223162d76.PNG)

What type of CSR SSL cert should I create? 

Please provide any terminal output that may be relevant below:
{
	"admin_server": {
		"listen_url": "0.0.0.0:3333",
		"use_tls": true,
		"cert_path": "gophish.crt",
		"key_path": "gophish.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:443",
		"use_tls": true,
		"cert_path": "aquarest.esi.net.crt",
		"key_path": "aquarest.esi.net.key"
	},

	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "0.0.0.0:443"
}
```
The aquarest.esi.net.crt and aquarest.esi.net.key were both created using openssl

**Comment by dsmurf** [comment]
I used letsencrypt and that worked for me. i have a ssl connection.

**Comment by loco1101** [comment]
Same here.
Generated letsencrypt cert, converted PEM to key and crt, inserted values into config, but i have only http working.

**Comment by jordan-wright** [comment]
Hi @mcvaa,

You will need to create a valid, CA signed certificate for the SSL cert to be trusted by the browsers.

As @dsmurf and @loco1101 mentioned, Let's Encrypt is a free way to get this set up. You can find information about it [here](https://letsencrypt.org/getting-started/). Otherwise, the provider you used to register the domain name will also offer the ability to create an SSL certificate through them.

I'm afraid the actual creation of the certificate is outside the scope of the support we can provide. However, it's worth noting that _eventually_ I'm hoping to add Let's Encrypt support directly into Gophish so that certificate generation is automatic like magic 😄 Not ETA on that yet, and will likely be a little bit later down the road.

I hope this helps!

**Comment by mcvaa** [comment]
Perfect wasn't sure if you used another type of certificate creation but I am now just waiting on our provider. After I saw the response for letsencrypt cert I figured it was a normal process. Thank you for all of your help with this. 

Colleen

**Comment by mcvaa** [comment]
Oh and you can close this ticket 💯
