### ISSUE TITLE
Malicious links in message source

### ISSUE THREAD

**Issue by rleekc** [gophish/gophish#1231]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: v0.5.0

Brief description of the issue: why is there so much malicious links in the message source of my phishing email?

What are you expecting to see happen? : I expect malicious activity with the links on the message source

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @rleekc,

It's unclear what you're asking here. Can you provide the issue you're encountering in more detail? I don't know what you mean by "why is there so much malicious links in the message source of my phishing email?".

**Comment by robichau** [comment]
@rleekc can walk you through the process of recreating the issue, but in the mean time, here are some screenshots (3) of the header content, and (1) the actual message body.

PR


![body](https://user-images.githubusercontent.com/44037410/46759946-7591b480-cc85-11e8-9949-e5f97c498478.JPG)
![header1](https://user-images.githubusercontent.com/44037410/46759947-7591b480-cc85-11e8-95c2-76380e3134a6.JPG)
![header2](https://user-images.githubusercontent.com/44037410/46759948-7591b480-cc85-11e8-82e2-8def6f566374.JPG)
![header3](https://user-images.githubusercontent.com/44037410/46759949-7591b480-cc85-11e8-973f-6a31d7344823.JPG)

**Comment by jordan-wright** [comment]
Huh. That's definitely a lot of sketchy links.

The short answer is that there shouldn't be anything in Gophish causing this. If you're importing an email, then Gophish gives you the option to convert any found links to the `{{.URL}}` tag, though that won't be caught here since those are CSS rules, not actual links. So if those links are in the email being imported, then they'll be in the resulting email, too.

The best way to confirm is to check the email you're importing to see if the links are in there (they should be). If they are, then you'll need to manually remove them if you don't want them to appear.

I hope this helps!

**Comment by rleekc** [comment]
Basically, anytime I go to email template -> HTML -> source, after copying and pasted my HTML text in, the junk links pop up in my HTML text after I refresh the source by clicking it twice.

If I were to only use text instead of HTML, I wouldn't be able to enter change the link in {{.URL}}, but thankfully there wouldn't be any junk css in the message source. 

Not sure if it has anything to do with CKEditor as the culprit of the issue.

**Comment by rleekc** [comment]
I didn't use import email, I wrote my own email in HTML section of email template

**Comment by jordan-wright** [comment]
That’s definitely peculiar! Would you be willing to share the HTML you’re using so that I can try to reproduce the issue on my end?

And to verify, do you have any browser extensions that maybe have some kind of ad protection in place? I could see the recognizing the HTML and trying to adjust them. If you think this might be the case, then perhaps trying it in an incognito window would be a good test case.

**Comment by rleekc** [comment]
<body>

<p>Security Alert:</p>

<p>As many of you have probably seen in the media, there  has been a marked increase in hacking incidents on the web.  Organizations such as PayPal, Experian, Anthem and others have been forced to disclose incidents involving huge stores of User IDs and Passwords. While we have not been hacked, we have seen an increase in the number of security incidents in the organization related to compromised user IDs and passwords.</p>

<p>Please take time to reset your work password in order to keep our operations safe. You have 3 days to complete this task.</p>
<p><a href="{{.URL}}">Click here to change your password.</a></b></p>

<p>
Thanks!<br />
IT Management</p>



</body>

**Comment by rleekc** [comment]
Hmm, I posted my HTML text and it was formatted. I'll try it out on an incognito window.

Also, even if I don't put any HTML in and just refresh the source button by click it twice, the junk css still pops up.

**Comment by rleekc** [comment]
I just disabled my adblocker on my firefox and the malicious links did not show up! Thanks for your help, really great software!

**Comment by jordan-wright** [comment]
Awesome! I’m glad we were able to get the issue fixed.
