### ISSUE TITLE
Python API doesn't work properly

### ISSUE THREAD

**Issue by ninostephen** [gophish/gophish#1243]
**The gophsih python API seems to be broken**

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
I was trying to add a new campaign using existing pages, users etc via the python api. When i run the code the campaign doesn't get added to it. so i tried retrieving an existing campaign. That too didn't work. 

What are you expecting to see happen? :
Have a new campaign added and displayed in the list
What are you seeing happen?
```requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\x16',))```

```Python
from gophish import Gophish
from gophish.models import *
apiKey = '' 
api = Gophish(apiKey, host = 'http://127.0.0.1:3333', verify = False)
        
Groups = [Group(name=groups)]
Pages = Page(name=pageId)
Templates = Template(name=template)
Profile = SMTP(name=SMTPProfile)

campaignId = Campaign(name=campaignName, groups=Groups, page=Pages, template=template, profile=Profile)
campaignId = api.campaigns.post(campaignId)
print(campaignId)
for campaign in api.campaigns.get():
            print(campaign.name)
```

**Please make the API documentation more understandable. I had hard time understanding what each function does.**

**Comment by jordan-wright** [comment]
Hi @ninostephen,

Thanks for reaching out! I'm sorry to hear you're having trouble with the Python API client.

Just to make sure I understand what's going on, I'm assuming that your variables such as `groups`, `pageId`, `template`, etc. have been defined earlier in your code.

The `ConnectionError` occurs because your telling the Gophish client to connect via `http`, while I'm assuming Gophish is listening on HTTPS. Just change the `host` argument to `https://127.0.0.1:3333` and that should fix that.

Next, assuming those variables are defined to string values that are valid names for existing groups, landing pages, etc. then what you're doing looks like it should work ok. But you will need to ensure that those objects actually do already exist in Gophish before trying to use them in a campaign.

I hope this helps!

**Comment by jordan-wright** [comment]
And if you have any specific areas of the documentation you would like clarified, please let me know or consider [sending a pull request](https://github.com/gophish/api-client-python/). I'm afraid that a blanket "please make the API document more understandable" request isn't clear enough for me to take action to fix it.

**Comment by ninostephen** [comment]
Well that solved the bad status line error. Now I've a new one.

```
<gophish.models.Error object at 0x7fea4391ce80>
```

**Comment by jordan-wright** [comment]
I just noticed that errors aren't detailed in the documentation (at least, not at first glance). That's an area where I'll improve it.

For now, you can see the error using `print(your_error.message)`.

**Comment by jordan-wright** [comment]
Hi @ninostephen,

Just checking in - are you still encountering the issue?

**Comment by ninostephen** [comment]
I'll confirm it by today eve (9PM IST). My duty was given to one of my
teammates.

**Comment by jordan-wright** [comment]
Hi @ninostephen,

Just checking in on this one. Have you been able to confirm if this issue is still being encountered?

**Comment by ninostephen** [comment]
Thanks for your help. Everything seems to be working well now💪🙌

**Comment by jordan-wright** [comment]
Great to hear! I appreciate the quick follow-up.

Have a great day!
