### ISSUE TITLE
Domain Issue with gophish(urgent and important)

### ISSUE THREAD

**Issue by TheManiac3** [gophish/gophish#1251]
What version of Gophish are you using?: 
0.6

Brief description of the issue: 
I have two websites running on 1 domain server, when they both were Non-ssl(unsecured connection) they were working correctly. i have running them on my server. I have redirected gophish from the other website with the same domain name but different port number. It was still working. The issue i face now is i have applied ssl on the other website and it is working correctly but gophish is now not working(admin server is running but can't access it globally.. My question is that how can i redirect gophish on the same ssl or without ssl from a secured website.. 
Website 1 running on www.domainname.com
gophish running on www.domainname.com:3333 

config.json:
{
	"admin_server": {
		"listen_url": "domainname.com:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"

	},
	
	"phish_server": {
		"listen_url": "0.0.0.0:8081",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
}

**Comment by jordan-wright** [comment]
We’ll need more information to understand what’s going on. What do you mean you can’t access the admin server? What error do you get?

And I’m afraid I don’t follow your setup. What do you mean you redirected Gophish from the other website? Do you have something like nginx in front or is this just a domain pointed to an IP address that happens to have both Gophish and something else exposed.

And what specific steps did you take that caused this issue? It’s difficult to see how changing a service to use HTTPS would inadvertently break Gophish.

**Comment by TheManiac3** [comment]
Hi ,

Thank you for your response. 

Yes, domain is point to the IP address. On that IP/server, I have moodle running on Apache, while on same physical server/IP, gopshish is running too.
Moodle is my point of entry.
There is a button in moodle menu, on clicking it, user is redirected to gophish login page.

This was working when SSL wasnt applied. Today I applied SSL on my domain, for apache. This means that moodle is running on SSL now. Now when I click on the link for gophish in moodle menu, it doesnt open anything. It says site cannot be reached.

All steps taken to apply SSL were Apache related. Nothing in configuration for gophish.

My configuration for gophish is in the question.

**Comment by jordan-wright** [comment]
> There is a button in moodle menu, on clicking it, user is redirected to gophish login page.

So let's start by taking Moodle out of the picture. I'm guessing that the architecture looks like this:

```
User ---> Server ---> Apache (port 443) ---> Moodle
                 `--> Gophish (port 80/3333) ---> Gophish
```

As in, Gophish is not behind Apache, but rather exposed directly. I'm also assuming that the link to Moodle points directly to Gophish, and not to some kind of Moodle-specific redirect.

If this is the case, let's start by trying to reach Gophish directly in the browser via https://your_domain:3333. If that doesn't work, then I recommend hopping into the server and starting to troubleshoot, working your way through the process:

* Is Gophish running? Does restarting it help?
* Are there any messages in the Gophish terminal that indicate an error?
* If you don't see any logs in the Gophish terminal when you request the admin page, what other services are listening on port 3333? You can probably use something like `lsof -i tcp:3333` to figure this out.
* Try changing the `config.json` to use `0.0.0.0:3333` instead of `domain:3333` and see if that helps

**Comment by jordan-wright** [comment]
Glad that fixed the issue!

**Comment by TheManiac3** [comment]
Hi,
Thank you for the response.

Last time we were having issues with admin server and it helped with 0.0.0.0:3333 by your assistance. Now we are having issues with the phishing server. 

When user is clicking on {{URL}}, there is no response on the page, and no response on dashboard. URL being served is domain.com:8081/?rid=

In our config file, right now it's "0.0.0.0:8081" that was working internally fine before we chose the domain.

Kindly help us with the phishing server @jordan-wright. Which configuration should we go for. Our domain is SSL certified.
