### ISSUE TITLE
Using API for Attachment Tracking

### ISSUE THREAD

**Issue by loza0269** [gophish/gophish#1258]
What version of Gophish are you using?: 
0.7.1
Brief description of the issue: 

Attempting to use the API to pull the RId variable for redirection or have the attachment have visibility into the universal variables so I could reference the {{.RId} for redirection.

What are you expecting to see happen? :

Attachment can pull the {{.RId}} variable

What are you seeing happen?

The attachment has no visibility into the variable.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - create html document that uses the {{.RId}} variable to redirect users to the landing page once they open the attachment
 * Step 2 - Launch campaign
* Step 3 - Open Attachment

Summary:

I would like to track when users open attachments and I understand this is not a native functionality, so my workaround is that I would like to use an HTML doc as the attachment and inside that HTML doc is either an API call for the RId or reference the {{.RId}} variable. If I have the RId variable in the HTML doc then I can use that to redirect to the landing page and the stats in gophish under clicked link would actually be the people that opened the attachment.

I don't know if this is possible, but I'd like to hear everyone's thoughts.

Thank you all!

**Comment by jordan-wright** [comment]
Hi @loza0269,

I'm afraid this isn't possible. We currently don't parse attachments for template variables, since this might run the risk of breaking certain attachment types.

We're considering ways that we might be able to support certain types of attachments in the future, but I don't have a timeline on when this will be possible.

Sorry we couldn't be of more help!
