### ISSUE TITLE
email open tracking not working

### ISSUE THREAD

**Issue by juniorzee** [gophish/gophish#1281]
my campaign status says "email sent" but my dashboard status says "in progress". meanwhile the email sent has been opened 3 hours ago and the logins has been inserted long ago, but tracking isnt working and my gophish.exe say " http: TLS handshake error from 127.0.0.1:50711:" . what seems to be to the problem?

**Comment by orangemacaroon** [comment]
where do you install your gophish?

**Comment by juniorzee** [comment]
please can you help me with my current issue?

**Comment by orangemacaroon** [comment]
can you give more details on your settings?

**Comment by jordan-wright** [comment]
Hi @juniorzee,

Please follow the troubleshooting steps in our documentation [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) and let me know if you continue to run into issues.

Thanks!

**Comment by juniorzee** [comment]
I've done everything but the exact place i'm finding it difficult is the
"campaign URL". I don't understand that part well, should i purchase a
domain and insert it there so i receive the data? or is there a different
way to solve this?




[image: screencapture-localhost-3333-users-2018-11-16-17_01_50.png]
[image: screencapture-localhost-3333-campaigns-2018-11-16-17_11_00.png]
[image: screencapture-localhost-3333-templates-2018-11-16-17_00_17.png]
[image:
screencapture-localhost-3333-sending_profiles-2018-11-16-16_56_58.png]

**Comment by juniorzee** [comment]
[image: screencapture-localhost-3333-landing_pages-2018-11-16-16_58_15.png]

**Comment by jordan-wright** [comment]
It looks like your screenshots aren’t showing up.

You can do one of two things for the campaign URL:
* Use the external IP address of the Gophish server
* Buy a domain, setup DNS so that the domain resolves to the external IP address of the Gophish server, and then use that domain.

Gathering this information or setting up the domain is beyond the scope of the support we provide, but can usually be found through a few Google searches.

I hope this helps!

**Comment by juniorzee** [comment]
how do i set my campaign URL on the external IP address of Gophish server?

**Comment by S0larflare** [comment]
![image](https://user-images.githubusercontent.com/8939757/48625920-70243a00-e9a8-11e8-83d2-306fde95194a.png)
That bit, what are you putting in there?

**Comment by jordan-wright** [comment]
Yes, as @S0larflare mentioned, that's where you put the external IP address of your server.

I highly encourage you to give the documentation a read, since it's designed to give real examples on how these fields should be filled in. You can find the individual field information [here](https://docs.getgophish.com/user-guide/documentation/campaigns) with a full example [here](https://docs.getgophish.com/user-guide/building-your-first-campaign/launching-the-campaign).

**Comment by juniorzee** [comment]
my last question....  where do i locate the "external IP address of the
Gophish server".

**Comment by jordan-wright** [comment]
This is beyond the scope of the support we can provide. In my previous comment, you'll see:

> Gathering this information or setting up the domain is beyond the scope of the support we provide, but can usually be found through a few Google searches.

I recommend working with your network administrator to determine the correct external IP address.

**Comment by securitygeneration** [comment]
@juniorzee When SSH'd in to your GoPhish server, running `curl ifconfig.co` on the command line should return the public IP address of your server/network. Now whether that server is accessible from the internet or hidden behind NAT is another question. As Jordan said, if this part confuses you, you probably need to go away and Google it a bit or ask a network admin.

**Comment by orangemacaroon** [comment]
@juniorzee , where do you install your goPhish server?

**Comment by jordan-wright** [comment]
Going ahead and closing this one since the original questions have been answered.
