### ISSUE TITLE
I HAVE INSTALLED AND CONFIGURE HMAILSERVER RELAY STILL ERROR

### ISSUE THREAD

**Issue by playjett** [gophish/gophish#1293]
please this is what am still getting after setting up my hmailserver to create relay.
what should i do for it to work now??????
 
 
![capture4](https://user-images.githubusercontent.com/37704143/48881128-7eb78a80-edc8-11e8-841c-b30729cbd253.PNG)

**Comment by jordan-wright** [comment]
Hi @playjett,

I’m afraid there isn’t enough information here to troubleshoot. In the future, please follow our issue template, since it asks the required questions needed to effectively help.

For now, this issue appears to be related to your hmailserver configuration. I encourage you to refer to their documentation to determine how authorization should be set up. I also encourage you to review any logs for hmailserver to see if they give more information about why this error is received.

To confirm that Gophish is the one having some kind of issue here, please verify with some other tool, be it telnet, Python, etc. that you can establish an authenticated SMTP session through the server. Gophish should support this type of authentication, which is why it leads me to believe the problem is with how hmailserver is set up.
