### ISSUE TITLE
Mail settings

### ISSUE THREAD

**Issue by dyneko** [gophish/gophish#1298]
Hi,

That's a good work, I have several questions :

1/ How can we update the CKEditor (3 years outdate) to the latest version ? In linux version ?
2/ I want to use :  Content-Type: multipart/alternative   instead of   Content-Type: text/html;
3/ How we can disable :   Content-Transfer-Encoding: quoted-printable
4/ How we can disable : the using of  ESMTPS 
5/ When the new Windows version will be released ?

Is it possible to have an answer asap, please.

Thanks :)

**Comment by jordan-wright** [comment]
Hi @dyneko, thanks for reaching out.

> 1/ How can we update the CKEditor (3 years outdate) to the latest version ? In linux version ?

We won't be able to update to CKEditor 5, since it drops support for full page editing. Our best bet will be to use the latest version of CKEditor 4. I'll see if I can get it updated, but I don't have an ETA on that.

> 2/ I want to use : Content-Type: multipart/alternative instead of Content-Type: text/html;

You can fork the [mail library](https://github.com/gophish/gomail) and adjust Gophish accordingly. This is something custom, so not something I'll be able to really help with.

> 3/ How we can disable : Content-Transfer-Encoding: quoted-printable

You can fork the [mail library](https://github.com/gophish/gomail) and adjust Gophish accordingly. This is something custom, so not something I'll be able to really help with.

> 4/ How we can disable : the using of ESMTPS

You can fork the [mail library](https://github.com/gophish/gomail) and adjust Gophish accordingly. This is something custom, so not something I'll be able to really help with.

> 5/ When the new Windows version will be released ?

No ETA at the moment. I'm working on a few more features before releasing a new version.

I know this isn't a ton of help, but I'm afraid there aren't easy answers to the questions beyond "you _can_ do that, but you'll have to do it for yourself since that's not something we support." Either way, I hope this helps!

**Comment by dyneko** [comment]
Thank you.  I have found for the 2/ and 3/ in the file : writeto.go  . What about using ESMTPS ?
