### ISSUE TITLE
ERROR IN SENDING TEST MAIL

### ISSUE THREAD

**Issue by playjett** [gophish/gophish#1301]
I have the 7.1 version of gophish, anytime i try to send test mails and when i launching a campaign this is what i see on 5 time over and over.
![capture12](https://user-images.githubusercontent.com/37704143/49198006-14fa2c00-f346-11e8-8c78-0df3cd0d8505.PNG)
please someone should help with a solution.thanks in advance.

**Comment by playjett** [comment]
the last time i tried again it says EOF.
how can i get gophish to work?

**Comment by jordan-wright** [comment]
Hi @playjett,

It looks like you may have accidentally opened a duplicate issue at #1300, so I closed it out.

This error is received by your SMTP server. It has nothing to do with Gophish. If you google that error message with details about whatever SMTP server you're using, it should give more information. There's nothing Gophish can do to help solve that problem.

As mentioned in #1293, if you refuse to follow our issue template which asks for the information we need to help troubleshoot, we simply are unable to help. Since this doesn't follow the issue template and is an error being received by the SMTP server, I'm going to go ahead and close this one out.

**Comment by playjett** [comment]
Sorry about that,but thank you very much for being there.
i use my 7.1 version gophish,and on the sending profile the error still persist, i want to detail my configurations to you for a better understanding and help.
I am using hmailserver to configure my relay, this is how i filled in credentials,
i created a domain e.g belinda.com, and created two users call(user1@belinda.com).
under SMTP CONFIGURATION it went like this,  i created a route under the PROTOCOL, SMTP like this belinda.com and in the target smtp host as SMTP.GMAIL.COM port 465. Please i need help, if there is any further configuration let know and how to, and please help me reflect these information to gophish to work properly. thanks am grateful  so far.

**Comment by playjett** [comment]
Sorry about that,but thank you very much for being there.
i use my 7.1 version gophish,and on the sending profile the error still persist, i want to detail my configurations to you for a better understanding and help.
I am using hmailserver to configure my relay, this is how i filled in credentials,
i created a domain e.g belinda.com, and created two users call(user1@belinda.com)(user2@belinda.com).
under SMTP CONFIGURATION it went like this, i created a route under the PROTOCOL, SMTP like this belinda.com and in the target smtp host as (SMTP.GMAIL.COM) port 465. Please i need help, if there is any further configurations let me know them and how to run them, and please help me transfer these informations to gophish (sending profile interface) for it to work properly. thanks am grateful so far.

**Comment by trogdor0** [comment]
We're you ever able to resolve this? I'm getting an eof error.

**Comment by sr-Meliodas** [comment]
Somebody can helpme?

I have install hmailserver and I tried to setup gophish sender to this?
Only still recive -max connection attempts exceeded - unencrypted connection error.
My configuration on hmailserver was never modified it set by default parameters, how can I fixed?
