### ISSUE TITLE
GoPhish sends emails sequentially?

### ISSUE THREAD

**Issue by securitygeneration** [gophish/gophish#1305]
I bulk-imported a list of alphabetically-sorted email addresses to create a group, and when launching the campaign (using the 'send by' field), I noticed that it queues each of the email it's going to send alphabetically, instead of randomising the list? Although I can see a potential desire for a phishing campaign to be delivered in a particular order, generally it would probably be good to have the option to send them in random order instead of all the As, then all the Bs, etc.

**Comment by ragnarkarlsson** [comment]
Agreed, I like the latest feature in 0.7 to trickle the emails out, randomising the order would make that even better.

**Comment by jordan-wright** [comment]
HI everyone!

I totally agree that this should be possible.

@ragnarkarlsson is correct that this appears to largely be covered by #501, since it will allow for emails to be sent at random intervals between the launch date and the "send emails by" date. This will naturally change the order of how emails are sent.

With this already being covered in #501, I'm going to go ahead and close this one out so we can track the status through the original issue.

Thanks again for getting in touch!
