### ISSUE TITLE
Large numbers of emails slow to send

### ISSUE THREAD

**Issue by FasterThanGoogle** [gophish/gophish#1313]
What version of Gophish are you using?: Latest build

Brief description of the issue: I have uploaded 100,000 users to my GoPhish server but it seems to be very slow when using the application. In addition, when sending out the emails, it's averaging about 500 emails every 10 minutes. I know it's not the mail server that is the bottleneck, but when opening campaigns and importing the users, my Chrome browser would not respond and I had to wait a few minutes for it to unfreeze. I also know that the server hosting GoPhish is not the issue, as when sending a campaign with 10k users at a time, the CPU usage is only on 20% with extremely low bandwidth and low disk usage.

As a little side note, I used the same amount of users a while ago using GoPhish version 0.4, that sent emails out with a much faster rate. Are there any settings I can enable (or has something changed speed wise between current and 0.4 causing the slowness or GoPhish and the sending of emails) to increase the speed that emails are being sent?

What are you expecting to see happen? : GoPhish to not freeze when using normal functionality (opening campaigns and importing users) and to send emails out at a much faster rate than 500 every 10 minutes.

What are you seeing happen? GoPhish freezing during normal functionality, and emails being sent very slow in comparison to an older campaign using the same amount of users, on an older version of GoPhish (0.4).

Kind regards,

**Comment by jordan-wright** [comment]
Hi @FasterThanGoogle,

I'm afraid this falls into generic performance improvements. Some other examples of this can be found [here](https://github.com/gophish/gophish/search?q=slow&state=closed&type=Issues).

I have plans to improve the performance of Gophish, but I'm afraid it will take some time. For larger campaigns, I recommend forgoing the UI for now, and instead leverage our Python API client for managing campaigns.

In terms of sending emails quickly, the previous versions Gophish didn't do any type of retries or resilient handling when it came to sending emails. It just sent them and would hope for the best, and would fail everything any time an error was encountered. Now we have a more resilient sending strategy, but it's possible this came with a performance tradeoff. Without more diagnostic information I can't do anything to really track it down.

Since there isn't really anything actionable here except to continue with performance improvements where possible, I'm going to go ahead and close this one out. Thanks for reaching out with your feedback!
