### ISSUE TITLE
Problem with latest source

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#1324]
What version of Gophish are you using?: Latest source

Brief description of the issue: When I 'go get' I get an error:

> gophish/gophish/controllers/route.go:111:5: api.Use undefined (type *mux.Router has no field or method Use)

Looks like this might be due to the refactoring work from #1321 as that is when api.Use appeared.

**Comment by jordan-wright** [comment]
Hey @S0larflare!

Sorry about that. I cleaned up and refactored a bunch of the way our servers ran. You should be able to fix this by updating the gorilla/mux dependency:

`go get -u github.com/gorilla/mux`

Then the build should work :)

**Comment by S0larflare** [comment]
Yep that has sorted it. I had to do that on a fresh build on a machine that has never had Go installed let alone Gophish though, which is odd.

**Comment by jordan-wright** [comment]
Interesting! I'm sure you're aware of this, but anytime you're on a fresh box, it's a good idea to run `go get -u ./...` from the Gophish directory to grab an updated copy of all the dependencies. Eventually, I'll integrate Go's new modules feature so that things are versioned a bit better, making it safer to upgrade dependencies.

Glad you were able to get this one sorted!
