### ISSUE TITLE
Email Template Auto Switch to "Other"

### ISSUE THREAD

**Issue by WaplWearnes** [gophish/gophish#1327]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Verion 7.1

Brief description of the issue: Email Template Protocol for link auto Switch to "Other"

What are you expecting to see happen? : Select "Http" Protocol instead of "Others" 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
<html>
<head>
	<title></title>
</head>
<body>
<p>Dear colleagues,</p>

<p>It&#39;s been another great year for our company, so we&#39;d like to celebrate in style this holiday season!</p>

<p>&nbsp;</p>

<p>Here are the details:</p>

<p>2019 Holiday Party</p>

<p>When: Friday, December 28, 6 PM</p>

<p>Where: TBC</p>

<p>&nbsp;</p>

<p>Our annual holiday party will be catered, so we will need an accurate headcount. Due to the limited time left, please RSVP by clicking the following link and registering no later than Wednesday, 26 December</p>

<p>&nbsp;</p>

<p><a href="{{.URL}}">RSVP</a> Here!</p>

<p>&nbsp;</p>

<p>Happy Holidays!!!</p>

<p>{{.Tracker}}</p>
</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @WaplWearnes,

Thanks for reaching out! I think this is a good case where simpler is better.

For background, this editor isn't built by me, but rather it's CKEditor 4, so any changes I make are going to be through that code. Fortunately, there have been a [few](https://stackoverflow.com/questions/13335287/how-to-remove-protocols-from-link-dialog-ckeditor) [cases](https://stackoverflow.com/questions/46345415/customize-ckeditor-link-dialog) of people doing some customizations so it should be possible.

I might just strip out most of the options here to make it as simple as possible. I'll remove the protocol dropdown entirely since we don't really use it anyway. I'll also probably consider removing the other tabs at the top since they likely cause more confusion than they are helpful.

**Comment by jordan-wright** [comment]
Hey @WaplWearnes,

I took a first stab at making the dialog simpler. It currently looks like this:

<img width="685" alt="screen shot 2018-12-27 at 2 44 35 pm" src="https://user-images.githubusercontent.com/1317288/50494195-63ebbd80-09e7-11e9-9597-2c2312062a9b.png">

You'll notice that this still doesn't address your concern, since the "Other" field will still show up as the default for `{{.URL}}` URLs. Unfortunately, I couldn't get to work properly. The issue is that CKEditor is a bit picky with how it does things. If I removed the protocol field completely then it wouldn't be able to make the links at all. If I hid the field with CSS, there wouldn't be a way to set the URL's to be HTTPS via the UI.

The long term solution would be to write my own CKEditor link plugin by refactoring the built-in one. That is a ways away, but I should be able to get to it at some point.

In the meantime, fwiw, seeing "Other", "HTTP", or "HTTPS" really doesn't matter, since we strip that out already. You can see that [here](https://github.com/gophish/gophish/blob/master/static/js/src/app/templates.js#L25). We make the protocol for the `{{.URL}}` tag when the landing page is generated based on your phishing server config (whether or not you have `use_tls` set).

I hope this helps a little bit!

**Comment by WaplWearnes** [comment]
Hi Jordan,

Thanks for the update

Just to confirm that in the protocol for Http,Https,Others all will be redirect to the landing page as long it  include {{.URL}} in the link right?

**Comment by jordan-wright** [comment]
Hi @WaplWearnes,

Sorry for the super late response. You are correct- as long as `{{.URL}}` is in the link field, it will work since we strip out any http:// or https:// schemes. You can see the code responsible for that [here](https://github.com/gophish/gophish/blob/a73ac4ab7c181afae8ee49fd3d4c08cb2fed1211/static/js/src/app/templates.js#L25).
