### ISSUE TITLE
Phish_Server not working, no sign that it is Actively listening 

### ISSUE THREAD

**Issue by hamsik7** [gophish/gophish#1347]
What version of Gophish are you using?: 
I am Using the latest version of goPhish
Brief description of the issue: 
**I can't seem to see Gophish server Listening which consequently User activities are not tracking at all.** 

![image](https://user-images.githubusercontent.com/34604835/51473912-98982e00-1d75-11e9-8636-7c77486c5fbe.png)

**This is how i configured My landing page:** 

![image](https://user-images.githubusercontent.com/34604835/51474124-3db30680-1d76-11e9-8afc-8d95d227c0a0.png)

**I tried:**

-  http://myexterna-server-ip/testingweb.html - it takes me to the landing page when i click on the link on the email but nothing is reported to go phish when i refresh the dashboard.

- http://myexterna-server-ip:8080/testingweb.html (this didn't work, page didn't load).

Can anyone help me with this because it is so frustrating !!

 This is the **Config file:**

![image](https://user-images.githubusercontent.com/34604835/51474385-fe38ea00-1d76-11e9-835b-b16e9c6a4692.png)

**Comment by S0larflare** [comment]
It looks like you have apache running on port 80, have you changed the port for GoPhish in config.json? If not, stop your apache server and restart GoPhish, it should all work then

Sent from my iPhone

On 21 Jan 2019, at 12:18, hamsik7 <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Gophish are you using?:
I am Using the latest version of goPhish
Brief description of the issue:
I can't seem to see Gophish server Listening which consequently User activities are not tracking at all.
[image]<https://user-images.githubusercontent.com/34604835/51473912-98982e00-1d75-11e9-8636-7c77486c5fbe.png>

This is how i configured My landing page:
[image]<https://user-images.githubusercontent.com/34604835/51474124-3db30680-1d76-11e9-8afc-8d95d227c0a0.png>

I tried:

  *   http://myexterna-server-ip/testingweb.html - it takes me to the landing page when i click on the link on the email but nothing is reported to go phish when i refresh the dashboard.

  *   http://myexterna-server-ip:8080/testingweb.html (this didn't work, page didn't load).

Can anyone help me with this because it is so frustrating !!

**Comment by hamsik7** [comment]
@S0larflare yes i configured goPhish to run on port 8080 have a look at the config screenshot i provided.

**Comment by hamsik7** [comment]
after i run gophish, run the netstat command and found that it is actually listening on the port that i specified.
