### ISSUE TITLE
Anonymous Campaign 

### ISSUE THREAD

**Issue by greenmouse147** [gophish/gophish#1353]
Hello,
First of all, thank you for this incredible work.

I am working on an awareness campaign in my company.

I want to do an "Anonymous Campaign", which means that it is enough to have statistics on the number of open emails, clicks etc. without personal information.

I thought of a solution to develop this,

if we look at the sql structure based on the result of the campaign it is like that:

>  integer primary key autoincrement,"campaign_id" bigint,"user_id" bigint,"r_id" varchar(255),"email" varchar(255),"first_name" varchar(255),"last_name" varchar(255),"status" varchar(255) NOT NULL ,"ip" varchar(255),"latitude" real,"longitude" real , position VARCHAR(255), send_date DATETIME, reported boolean default 0, modified_date DATETIME)`

I think we can just replace the email, first name etc... with Anonymous?

maybe you can add the anonymous campaign option via a checkbox, 
What do you think? 

kind regards

Axel

**Comment by jordan-wright** [comment]
Hi @greenmouse147, thanks for reaching out!

I'm afraid it wouldn't be as simple as replacing the fields in the database. The reasoning is similar to https://github.com/gophish/gophish/issues/1139#issuecomment-427202892, but essentially boils down to the fact that if a user clicks a link which loads a template containing something like `{{.FirstName}}`, we'd need to know what that is in order to present the appropriate page.

Right now, it seems our best bets would be to allow anonymous reporting on the frontend by "hiding" the data, as well as potentially encrypting the data at rest.

Since this is so similar to #1139, I'm going to go ahead and close this one out so that we can track progress through that issue.

Thanks again for getting in touch!
