### ISSUE TITLE
Gophish is available from one IP only. How to make it publicly available?

### ISSUE THREAD

**Issue by bkozlovsky** [gophish/gophish#1358]
**Version of Gophish**: 0.7.1

**Brief description of the issue**: 

I've installed Gophish on Centos VPS and I assume that after running the binary it somehow configured a firewall rule that restricts connections to an IP address the binary was started from. So now I have both domain:3333 and domain:8080 available from a single IP address. Trying to connect from my home the browser shows "This site can’t be reached"

**What are you expecting to see happen?** : I expect both domain:3333 and domain:8080 to be available from all IP addresses

I'm running Gophish on Centos 7 server which uses cPanel. Please help me investigate this. Thank you.

**Comment by jordan-wright** [comment]
Hi @bkozlovsky,

@S0larflare is correct - Gophish doesn't modify any firewall rules. If you're having issues reaching the Gophish listener, then the issue is almost certainly firewall/networking related outside of Gophish (assuming your `config.json` lists both servers to listen on `0.0.0.0:port`.

Without more information, I'm afraid there isn't anything we can do to help troubleshoot this. I'm going to go ahead and close out this issue for now, but if you continue to have difficulty reaching the Gophish server and have information that suggests this is being caused by Gophish, let us know and I'll be happy to re-open this so we can continue troubleshooting.

Thanks again for getting in touch!
