### ISSUE TITLE
 dial tcp 74.125.133.109:587: i/o timeout

### ISSUE THREAD

**Issue by adrigondite7** [gophish/gophish#1360]
Hello,

I get the following error with the smtp server.

 "dial tcp 74.125.133.108:587: i/o timeout"

The url of the error belongs to the google servers.

I hope you can help me.

a greeting

**Comment by adrigondite7** [comment]
I missed this error in the section "sending profiles", in "send test email"

**Comment by jordan-wright** [comment]
Hi there!

So just checking - it sounds like you were able to find documentation that helped you resolve the issue?

**Comment by adrigondite7** [comment]
no, I have not solved it

I have two gophish ceuntas, in two different machines, with a similar configuration, but in one of them that error comes out

**Comment by jordan-wright** [comment]
This sounds like a firewall or networking issue. This error is Gophish saying that it's unable to reach that IP address on port 587. If these machines are hosted with a cloud provider, it's possible the provider limited outbound SMTP connections to prevent spam.

I'm afraid there isn't anything we can do within Gophish to help solve this issue. Since there isn't we can really do to fix this one, I'm going to go ahead and close this out. I recommend reviewing your firewall settings or reaching out to your cloud provider to determine if this is a block on their side.

If you come across any evidence that this is a bug in Gophish, please let me know and I would be happy to re-open this issue to continue troubleshooting.

Thanks again for reaching out!
