### ISSUE TITLE
Accesst to landing pages

### ISSUE THREAD

**Issue by RoniWar** [gophish/gophish#1363]
What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 

Hey Guys, Im having trouble with the actual campaign flow process.
I set up the gophish server on an amazon ec2 ubuntu server, I have access to the admin interface via port 3333 and can send the actual emails via an external SMTP that I configured.
But I want to actually track the opening, clicking, etc.
I still have an older amazon ubuntu server that used to host the html content on previos campaings, I first tested gophish and just used it to create the email, the actual html pages were hosted on the older amazon server so I obviosuly couldn't track the openings, or can I? the html pages must be hosted on the phish server? 

I don't understand how to enable the html page to communicate with the listening server?
When I import the site in the new landing page tab, does it create a local copy? Do I need to change anything in it?and how and where do I point out to it in the email link? does the link in the email continues to point out to the external location where the html pages are located(In my case the older ubuntu server) .

Thanks in advance

**Comment by jordan-wright** [comment]
Hi there!

Hosting HTML pages on a different server and still tracking things in Gophish isn't supported at this time. Gophish is expected to host the landing pages so that it can track campaign events.

> When I import the site in the new landing page tab, does it create a local copy?

Yes, Gophish stores a copy of the HTML in it's database so that it can load the page when users click the links in phishing emails.

> and how and where do I point out to it in the email link?

In the email, you need to use the `{{.URL}}` template tag in your links, which will automatically be filled in when emails are sent with whatever URL you use when setting up the campaign.

I recommend checking out the ["Building Your First Campaign"](https://docs.getgophish.com/user-guide/building-your-first-campaign) section of our docs, along with the [FAQ](https://docs.getgophish.com/user-guide/faq).

I hope this helps! Let me know if you continue to run into issues.

**Comment by RoniWar** [comment]
Thank you very much Jordan,

It does seem to work now, now just need to find the submitted user info.
Where is it stored exactly?

Regards,
Ron
