### ISSUE TITLE
Separating landing page from rest of the framework 

### ISSUE THREAD

**Issue by jamz212** [gophish/gophish#1371]
How would one go about separating the landing page into its own hos/container for purposes of improving the security of gophish? I ask this as the landing page is the only component of the gophish that needs to reside on the public internet, everything else could be behind firewall or NAT.  I ask this as I am concern that a vulnerability in the landing page could allow an nefarious actor to gain access to the email listing stored in the campaigns or worse.

**Comment by jordan-wright** [comment]
Hi @jamz212,

It seems that this is similar to a question I got in #1373. Take a look at the comment at https://github.com/gophish/gophish/issues/1373#issuecomment-466728351 where I talk about how this might be possible.

Let me know if this doesn't answer your question and I'd be happy to re-open this issue to continue chatting through it.

**Comment by jamz212** [comment]
Jordan, thank you for your response. I think I get it, this workaround creates a front end that responds to the user queries and replays those queries back to the gophish server, thus introduces intermediary that would have to be compromised first, before the attacker can move laterally to compromise gophish, assuming gophish has been configured only to respond to the front end. Not ideal, but could work. That said if I am understanding correctly this would track clicks but not necessarily be able to capture user input and how would one go about synchronising cloned sites between gophish and the front end web server?

Best regards,
________________________________

**Comment by jordan-wright** [comment]
Another option would be to create a separate instance of Gophish that is responsible for just the front-end connections.

This would look like this:

* The admin instance:
    * The admin server available, but firewalled responsibly
    * The phish server set to 127.0.0.1, effectively shutting it off
    * Responsible for sending emails
* The containerized frontend instance
     * The admin server set to 127.0.0.1, effectively shutting it off
     * The phish server available
     * The `disable-mailer` flag set to disable sending emails
* Both share a single MySQL instance

This solves the goal of having a separate, containerized frontend instance but I'm not quite sure how many new threat models it solves. Since it has to share a database instance with the other Gophish server (so that it can track events and data submissions), anyone who gets access to that will have access to the database.

> That said if I am understanding correctly this would track clicks but not necessarily be able to capture user input

You could capture user input here, too. You'd have to write Javascript to catch the form submission and send an ajax back to Gophish, similar to how the original ajax request is being sent.

> how would one go about synchronising cloned sites between gophish and the front end web server?

You probably wouldn't. In this case, you could make a blank landing page in Gophish, since it won't be rendering the page anyway. You could focus your efforts on maintaining the landing pages on your external server.

**Comment by jamz212** [comment]
I agree that sharing one database would not necessary resolve the issue as the same database contains all data including the email addressees I am trying to protect? If there was a way where there are two databases, one "internal" responsible  for maintaining sensitive data and running the , and the front end database  responsible for data collection with a process (lambda script perhaps) responsible for necessary data synchronization between the two databases?
________________________________

**Comment by jordan-wright** [comment]
Something like that might be possible depending on how granular MySQL replication is or your willingness to script out a syncing utility, but it’d be pretty far out of the scope for support we can provide here.

If you do wind up doing this, I’d be interested to hear your approach and results!

**Comment by jamz212** [comment]
OK, let me ask you this bit differently; how would one go about security gophish server other than the obvious things like exposing management interface and smtp forwarder to the internet?
________________________________

**Comment by jordan-wright** [comment]
Restricting access to the management interface (and smtp forwarder, though I consider that separate to Gophish) is the single biggest thing you can do to secure a Gophish installation.

Otherwise, the attack surface of the phishing server is quite small.

If you expect all of your recipients to come from the same IP address space, you can limit that as well with firewall rules but beyond that I’m afraid there’s not much separation you can do at this time without building custom tooling.

**Comment by jamz212** [comment]
I though of limiting landing page by IP, but with high number of mobile users that is not practical or successful anymore...
________________________________
