### ISSUE TITLE
Expose tracking API

### ISSUE THREAD

**Issue by pielgrzym** [gophish/gophish#1373]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 

Campaign tracking is hardcoded to landing pages, which in turn are hardcoded to gophish. There are other, more specialized tools for building landing pages (like Evilginx2) which could be easily integrated into gophish if proper APIs were exposed.

What are you expecting to see happen? :

- Have an API for managing tracking urls per campain per user
- more flexible landing pages mechanism allowing to build link templates to external landing page service
EDIT:
To clarify - I only use gophish for sending and tracking clicks. What I'd like to have is the ability to embed js to callback do gophish from the landing page so I could use gophish for analytics. Modular design allows more flexibility when it comes to costs, evasion etc.

**Comment by jordan-wright** [comment]
Hi there!

This should be possible, you just have to be a bit creative with it.

> Note: I haven't tested any of this, so please double-check my work.

What you can do is first create a blank landing page. Then when building a campaign, set the URL to `http://whatever_real_url/?rid={{.RId}}`. Gophish will put the recipient's ID as a parameter in the URL that points to whatever real landing page or phishing server you want.

Since it doesn't point to Gophish, you'll need to, like you mentioned, add a Javascript snippet that makes a request back to Gophish. This would look something like this (again - I haven't tested this so it'll need cleanup or modification):

```javascript
let url = new URL(window.location)
let rid = url.searchParams.get('rid')
fetch(`http://gophish_url/?rid=${rid}`)
```

This essentially grabs the `rid` out of the URL and sends an AJAX request to Gophish emulating the same request that Gophish would see if the email link were clicked and it pointed directly to Gophish.

I hope this helps!
