### ISSUE TITLE
Issue Connecting to Gophish Server

### ISSUE THREAD

**Issue by emilio406** [gophish/gophish#1374]
Hello, i am having issues with gophish.  i installed mine on a vps this way . i downloaded the binary not source. first i go to the config.js and change  "listen url" to my vps ip address before my gophish could work. As the 0.0.01 and 0.0.0.0 didnt work.  then i run the setup as administrator. the cmd popped up and stays on. i go to my browser and input my ipaddress with port 3333, and gophis worked.  the issue i am having is my landing page is not exposed to the internet.  when i type my vps ip on any browser. i see nothing.  i had to change the phish listening url to my ip address and stil not working

**Comment by emilio406** [comment]
step 1 - I use gophish-v0.7.1-windows-64bit

step 2 - i edited config.js listening url to my vps ip address before Gophish can work.  But my landing page doesnt work.  i have tried editing phishing url to my vps ip address but my landing page cannot be found on browser

step 3- i am expecting the landing page to show

step - 4 - this is my landing page https://dominguezcorp.com/

step 5 - is there a more detailed way to run setup  on vps?

**Comment by jordan-wright** [comment]
We'll need to see the contents of `config.json` in order to be able to effectively troubleshoot. If you're setting the server address to `0.0.0.0` and you're having trouble connecting, it's almost certainly going to be a networking/firewall issue.

**Comment by emilio406** [comment]
it is working now.  error i made was inputting https:// to landing page ip address instead of http.  I have two questions.  First,  if i was using a domain with valid SSL certificate,  do i edit the phishing url port in config.json from 80 to 443 ?
Secondly, my rdp got suspended after my successful test.  where can i buy an rdp that wont get blocked?

**Comment by jordan-wright** [comment]
If you're wanting to setup TLS for the phishing server then yes, it's recommended to change the port to 443.

> Secondly, my rdp got suspended after my successful test. where can i buy an rdp that wont get blocked?

Where you host Gophish is up to you. The important thing is to be transparent to the service provider that you're using Gophish, inform them of tests your running, etc. If the service provider suspends you for running phishing simulations, you'll need to reach out to them with more information about what you're doing and work directly with them.

Since the original issue has been resolved, I'm going to go ahead and close this one out.
