### ISSUE TITLE
hello, i installed Gophish on a rdp, my first test was detected by the cloned company and had my rdp taken down.  how do i make the gophish page undetectable???

### ISSUE THREAD

**Issue by emilio406** [gophish/gophish#1376]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @emilio406,

In the future, please put your issue in the body of the Github issue as opposed to the subject, since it keeps things cleaner.

We don't provide support for making Gophish "undetectable"- quite the opposite! We encourage running [transparent phishing simulations](https://github.com/gophish/gophish/issues/1057), that make it clear to any service providers and companies you engage with:

* That you're running a phishing simulation
* Who to contact for more information

If your Gophish installation was detected by the company who's website you cloned, then that's a good thing! It means that company's brand infringement process is working as-intended.

I encourage you to overcommunicate to any service provider you work with what your intentions are, what approvals you have, and work directly with them to ensure your phishing simulations run smoothly.
