### ISSUE TITLE
Default HTML Page for Server Domain

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1378]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
Suggestion (if not already an option): default landing page for phishing server

What are you expecting to see happen? :
When going to the phishing server in a web browser via a plain IP or domain name (i.e. "http://www.domain_name.com"), go to a default landing page

What are you seeing happen?
Currently results in a "404 page not found" error

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 - 
 
----------------------

Hi.

Not sure if this is already an option that I missed somewhere, but can I set a default web page for the phishing server if someone visits the IP or domain via a browser without any other parameters in the URL?

For example, if we set up the phishing server with the domain "www.domain_name.com", that domain can be used with the campaign landing pages, and if an html file is put into the static/endpoint directory, a web browser can visit it via "www.domain_name.com/static/page.html". However, if the web browser is pointed to just "www.domain_name.com", it results in a " 404 page not found" error. Putting an index.html file into the root gophish or gophish/static directories do not do anything for this error.

So is there a way to set a default html page for just the domain/IP address of the phishing server?

By the way, this question looks to be the same as the below issue/question from last year, but figure it wouldn't hurt to ask again.
https://github.com/gophish/gophish/issues/978

Thanks.

**Comment by jordan-wright** [comment]
Hi @riab-tam,

I'm afraid this isn't possible without modifying Gophish. You can find the code responsible for rendering this response [here](https://github.com/gophish/gophish/blob/11493024a07d13c2213913b0ef2e37b2aff7e409/controllers/phish.go#L195).

Essentially, you'll want to replace the calls to `http.NotFound(w, r)` with a call to write out your page content, since that response it what's returned if an `rid` parameter isn't provided. It's possible that you might have luck using [`http.ServeFile`](https://golang.org/pkg/net/http/#ServeFile) for this, though I haven't tried it personally.

Another option would be to put something like nginx in front of Gophish, [check if the `rid` is provided](https://stackoverflow.com/questions/23988344/making-nginx-check-parameter-in-url) and, if it isn't, serve a static HTML file.

I'll keep this in mind as a potential future feature, though I'm afraid I don't have plans to implement this anytime soon.

I hope this helps point you in the right direction!

**Comment by riab-tam** [comment]
Hello, Jordan.

OK, thanks for the info. We'll look into potentially updating the http.NotFound(w, r) function to server a web page if there are no valid GoPhish parameters in the URL.

Another related question: has there been any update to this previous issue (https://github.com/gophish/gophish/issues/489)? Specifically this part: "Instead, what do you think about adding a simple HTTP redirect listener automatically if we see that the user configured TLS? This would be for the phishing server only, and would automatically redirect to the correct HTTPS listener."?

We added an SSL certificate for the domain of both the admin and the phishing servers, and updated the config.json file accordingly, and in case anyone tries accessing just the non-secured domain, would like it to automatically redirect to the https enabled phishing listener.

Thanks much.
