### ISSUE TITLE
not capturing submitted data

### ISSUE THREAD

**Issue by jepunband** [gophish/gophish#1381]
What version of Gophish are you using?: 
0.7.1

Brief description of the issue:
i did a test on the login page, email is clicked and opened, i input the username and password but on gophish submitted data after refresh it is not capturing any data. 

What are you expecting to see happen? :
input data is captured.

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

[fb.txt](https://github.com/gophish/gophish/files/2924423/fb.txt)

**Comment by jordan-wright** [comment]
Hi @jepunband,

Generally this is the result of missing some data in the `<form>` element. You can find [a bunch](https://github.com/gophish/gophish/search?q=capturing+submitted+data&unscoped_q=capturing+submitted+data&type=Issues) of other issues which may help.

Other than that, it's not really clear what's happening here, and we weren't given a bunch of information to go off of. I'm going to go ahead and close this one out since it's very likely that looking through the other issues will help you solve the issue you're encountering.

Also note: I've removed the attached landing page, since it appeared to be a clone of a well-known brand. In the future, you can just post the `<form>` element for troubleshooting.
