### ISSUE TITLE
Hard-Code Listener URL into Config files?

### ISSUE THREAD

**Issue by NicolasCarson** [gophish/gophish#1391]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: It seems that having spaces before or after the Listener URL causes gophish to crash. 

What are you expecting to see happen? : Having one space before or after the listener URL when setting up a campaign to launch causes the GoPhish program to crash when the campaign is kicked off. 

What are you seeing happen? Immediately after clicking launch campaign gophish seems to crash as it immediately asks for you to sign into the web portal again when I was already just signed in prior to hitting the launch campaign button. 

My Main question is: Would it be possible to hard code the listener URL into the gophish config files somehow so that there would be no risk of entering the listener URL with spaces? This issue is also remediated by making sure to enter the Listener URL without spaces around it in the campaign configuration window of the GoPhish web portal. Just trying to see if there is another hard-coding method to avoid even the risk of human error. 

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Enter Listener URL with multiple or single spaces before or after the URL
 * Step 2 - Fill out the rest of the campaign details
* Step 3 - Click Launch Campaign Button

**Comment by jordan-wright** [comment]
Hi @NicolasCarson,

Since the campaign URL can change with every campaign, I don't plan to add a hardcoded URL in the `config.json`.

Instead, I think we can do a better job of validating URLs that are entered for a campaign. The rule should be that if Gophish doesn't throw an error when the campaign is launched, it's expected that the provided information is valid.

Could you please paste in a copy of the output you see in the terminal when Gophish crashes? That would help me track down the source of the problem.

**Comment by jordan-wright** [comment]
Closing this issue since there hasn't been any updates in quite a while.
