### ISSUE TITLE
Newly created accounts have a '0' in the role_id column

### ISSUE THREAD

**Issue by alecisec** [gophish/gophish#1426]
What version of Gophish are you using?: af4c8f6  

Brief description of the issue: If admin user(s) create a new account the role_id field isn't populated / remains as a '0' causing a login to crash the program

What are you expecting to see happen? : default of '2' or optionally '1' for admin

What are you seeing happen? value set to '0' by account creation process

**Comment by jordan-wright** [comment]
Hi @alecisec,

I apologize that you ran into this! This stemmed from the recent addition of RBAC support. I'm working right now to move registration to a full user-management API which should be done soon. This should resolve the issue.

I'm tracking this issue through #1375. Since this appears to be a duplicate, I'm going to close this one out in favor of working through that one.

Thanks again for the heads up!
