### ISSUE TITLE
Scheduled emails continue being delivered after stopping a Campaign

### ISSUE THREAD

**Issue by dunderhay** [gophish/gophish#1447]
What version of Gophish are you using?: 
Gophish v0.7.1

Brief description of the issue: 
Scheduled emails keep being sent after marking the campaign as Complete. When creating a new campaign and using the "Send Emails By (Optional)" feature to specify an end time for the last scheduled emails to be delivered by, if you try to stop the campaign before the specified end time - by marking the campaign as Complete, the scheduled emails continue being sent.  

What are you expecting to see happen? :
When marking a campaign as Complete, all remaining scheduled emails that have not yet been sent should no longer be delivered. The campaign can be ended without having further emails sent, and statistics can be gathered on emails that have already been delivered. 

What are you seeing happen?
After stopping the campaign (mark as complete), the scheduled emails in the queue that have not yet been sent, keep being delivered.

**Comment by dunderhay** [comment]
Quick work around - just delete the sending profile.

**Comment by jordan-wright** [comment]
Hi @dunderhay,

This was fixed back in https://github.com/gophish/gophish/commit/53b3a98521f98e06cddc9b2f203d08427dd1e088 but hasn't made it into a release yet. I'm afraid I don't have an ETA on when a new release will be built, since I'm still finishing up a few features.

Thanks for getting in touch!
