### ISSUE TITLE
Email Target Map has no Data

### ISSUE THREAD

**Issue by dhruvin917** [gophish/gophish#145]
So I've been messing around with this tool for a bit and I'm absolutely loving its capability so far. The thing I'm stuck on is that when I look at the results of the campaigns, there isn't data about the location being displayed. Is there something I need to include in the template itself or is it something else on my end?

**Comment by jordan-wright** [comment]
The map will only work if the IP's of your clients are external ips and not internal (RFC 1918) ip addresses.

Are your targets external or internal on your network?

**Comment by dhruvin917** [comment]
They are internal but located globally. Some are located in China, India, Russia, and other parts of North America.

**Comment by jordan-wright** [comment]
If they have internal addresses, then there is no way for gophish (or any app) to know where they are located accurately.

This falls back on how IP geolocation works. Since internal addresses are used by everyone, they simply can't be pinned to one location.

We use the popular MaxMind databases if you want to check out their docs to see how it works.

**Comment by dhruvin917** [comment]
Hmm. Okay, thanks for all the help. I'll look deeper into MaxMind.
