### ISSUE TITLE
API Key Reset Via /api/reset not returning any data

### ISSUE THREAD

**Issue by 62150** [gophish/gophish#1468]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
**0.71**
Brief description of the issue: 
I'm using POSTMAN and testing API's, everything works except the "/api/reset" endpoint and I'm following your docs > https://docs.getgophish.com/api-documentation/settings

I get a 200 response, but in the body response I have no data.

What are you expecting to see happen? :
I should be able to see data in the body response like below 
{
    "success": true,
    "message": "API Key successfully reset!",
    "data": "0123456789abcdef"
}
What are you seeing happen?
I'm seeing an empty body response (blank)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hey @62150,

Thanks for getting in touch! Make sure you're sending a POST request, not a GET request.

**Comment by 62150** [comment]
@jordan-wright 

I tried all methods...jk. Of course I did a POST request

I used burpsuite to capture the reset request via GUI, which does the following /api/reset?api_key=[string]

previously I did notice I had an extra "/" after "reset", but without it I get no response...which is now a different behavior and when I remove a character from the api key in the request I actually get a response saying the api key is invalid.

Let me know

**Comment by jordan-wright** [comment]
I only mention to ensure it's a POST request since during testing I would see the same behavior you describe (200 status with empty body) when making a GET request instead.

I use Insomnia instead of Postman, but everything seems to work for me with `POST /api/reset?api_key=your_api_key`:

<img width="1191" alt="Screen Shot 2019-05-29 at 1 37 47 PM" src="https://user-images.githubusercontent.com/1317288/58582284-01f1e700-8217-11e9-8c54-52569079a0bc.png">

**Comment by 62150** [comment]
I installed Insomnia and still getting the same behavior. I have now tried 3 different systems (windows10's and ubuntu), what else can I troubleshoot?

![resetapi](https://user-images.githubusercontent.com/51170081/58585210-f26da080-820c-11e9-9fa6-dd6c6c037f55.JPG)
![resetapibad](https://user-images.githubusercontent.com/51170081/58585211-f3063700-820c-11e9-885f-990cb3488c36.JPG)

**Comment by jordan-wright** [comment]
What logs do you see in the Gophish terminal?

**Comment by 62150** [comment]
When I first make the POST request I get this:

2019/05/29 13:29:37 http: panic serving 127.0.0.1:54698: interface conversion: interface {} is nil, not models.User
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc042146000)
        /usr/local/go/src/net/http/server.go:1726 +0xd7
panic(0x9ad660, 0xc0422807c0)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/gophish/gophish/controllers.API_Reset(0x1589990, 0xc0421304b0, 0xc0421f2a00)
        /go/src/github.com/gophish/gophish/controllers/api.go:53 +0x2b5
net/http.HandlerFunc.ServeHTTP(0xa76e88, 0x1589990, 0xc0421304b0, 0xc0421f2a00)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/gophish/gophish/middleware.RequireAPIKey.func1(0x1589990, 0xc0421304b0, 0xc0421f2900)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:94 +0x319
net/http.HandlerFunc.ServeHTTP(0xc0420d5240, 0x1589990, 0xc0421304b0, 0xc0421f2800)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0420ee000, 0x1589990, 0xc0421304b0, 0xc0421f2800)
        /go/src/github.com/gorilla/mux/mux.go:162 +0xf4
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc0421575e0, 0x1589990, 0xc0421304b0, 0xc0421f2400)
        /go/src/github.com/gorilla/csrf/csrf.go:184 +0x7d1
net/http.(Handler).ServeHTTP-fm(0x1589990, 0xc0421304b0, 0xc0421f2400)
        /usr/local/go/src/net/http/h2_bundle.go:5475 +0x54
net/http.HandlerFunc.ServeHTTP(0xc042126560, 0x1589990, 0xc0421304b0, 0xc0421f2400)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0x1589990, 0xc0421304b0, 0xc0421f2300)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc0421265a0, 0x1589990, 0xc0421304b0, 0xc0421f2300)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/gophish/gophish/middleware.GetContext.func1(0x1589990, 0xc0421304b0, 0xc0421f2300)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x259
net/http.HandlerFunc.ServeHTTP(0xc0421265c0, 0x1589990, 0xc0421304b0, 0xc0421f2200)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1589990, 0xc0421304b0, 0xc0421f2200)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:342 +0x26a
net/http.HandlerFunc.ServeHTTP(0xc0421de2a0, 0x1589990, 0xc0421304b0, 0xc0421f2200)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xac21e0, 0xc0421dc1e8, 0xac3000, 0xc0421de2a0, 0xa76fa0, 0xac6d20, 0xc0420fc000, 0xc0421f2200)
        /go/src/github.com/gorilla/handlers/logging.go:45 +0x13a
net/http.serverHandler.ServeHTTP(0xc0421ee000, 0xac6d20, 0xc0420fc000, 0xc0421f2200)
        /usr/local/go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc042146000, 0xac7320, 0xc042280340)
        /usr/local/go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x282

**Comment by 62150** [comment]
And I get this when adding an incorrect api key, which is expected 

time="2019-05-29T13:31:50-07:00" level=info msg="127.0.0.1 - - [29/May/2019:13:31:50 -0700] \"POST /api/reset?api_key=953c6c80ba00b8aa36b38a63f213a8646d402a7922d7714845f3cd01ca979b0 HTTP/1.1\" 400 70 \"\" \"insomnia/6.5.3\""

**Comment by jordan-wright** [comment]
Ah, ok, I see the issue. I'm pretty sure this is a bug.

The first crash is the important one since it is a crash, making this a good time to breakdown how Golang crash dumps operate. Here's how we can dissect this one:

```
interface conversion: interface {} is nil, not models.User
```

So at some point, we're trying to convert _something_ into a `models.User` object. Unfortunately, that something is `nil` so it breaks. Let's see why that's happening.

```
github.com/gophish/gophish/controllers.API_Reset(0x1589990, 0xc0421304b0, 0xc0421f2a00)
/go/src/github.com/gophish/gophish/controllers/api.go:53 +0x2b5
```

So the panic happened in `api.go` on line 53. That's [here](https://github.com/gophish/gophish/blob/15e57b6cd081139e34af236e0eda56f209d287f7/controllers/api.go#L53). This makes sense - we're trying to load our user object from the request context. Basically, I have middleware that says "check the API key provided. If it matches a user, load it into the request. Otherwise, the request isn't authenticated".

The weird part is that this shouldn't be nil, right?

```
github.com/gophish/gophish/middleware.RequireAPIKey.func1(0x1589990, 0xc0421304b0, 0xc0421f2900)
/go/src/github.com/gophish/gophish/middleware/middleware.go:94 +0x319
```

Moving up the chain, we see that this is where the middleware says "we had a valid API key, now call the right handler". You can see the code [here.](https://github.com/gophish/gophish/blob/15e57b6cd081139e34af236e0eda56f209d287f7/middleware/middleware.go#L94).

Looking here shows us where the bug is. You'll notice that in `api.go`, we're looking for an object in the request called `user`. But, in `middleware.go`, we're only setting `user_id` and `api_key`. This means that it loads `nil` instead of a user, causing a panic.

The good news is that this is already fixed in the source. You can see us setting the `user` object [here](https://github.com/gophish/gophish/blob/27553ccc1fd271bad71bef8dd08795daf9dfec8a/middleware/middleware.go#L97). The bad news is that this hasn't made it into a release yet. I'm finishing up a few tiny features then I'll tag a new release. Unfortunately, I don't have an ETA at the moment.

Thanks for reporting this and providing the logs! Since this is already fixed in the source branch, I'm going to go ahead and close this one out.
