### ISSUE TITLE
Add sender signature to email template

### ISSUE THREAD

**Issue by topyson** [gophish/gophish#1476]
Version 0.7.1

Wondering about a new feature. Would it be possible to set the email signature within the sender profile, which then will be automatically added to the email when sending?
This way the email template can be static. In my campaigns, the email template remains the same, however the sender changes every single time.

What are you expecting to see happen? :
No need to change the email template, if just the sending profile variies.

**Comment by S0larflare** [comment]
Is it not just as easy to copy the template, alter the signature and use that?

Sent from my iPhone

On 1 Jun 2019, at 06:50, topyson <notifications@github.com<mailto:notifications@github.com>> wrote:


Version 0.7.1

Wondering about a new feature. Would it be possible to set the email signature within the sender profile, which then will be automatically added to the email when sending?
This way the email template can be static. In my campaigns, the email template remains the same, however the sender changes every single time.

What are you expecting to see happen? :
No need to change the email template, if just the sending profile variies.

**Comment by topyson** [comment]
Yes that's possible, but not user friendly. I would like to keep the email template list small and don't want to have same templates with just one signature alteration.

**Comment by jordan-wright** [comment]
Hi @topyson,

Thanks for reaching out! I completely understand wanting the ability to customize a sender's signature. However, I'm hesitant to add this directly in Gophish since it's one of those things that's pretty optional. Many people may choose not to have a signature in the email, and when things are heavily optional I tend to avoid putting them in Gophish. This is to avoid falling down the slope of having too many options.

Since we have the ability to have signatures in the email content in templates (manually, but it's there), I'm not going to add first-class support for signatures at this time, though it's possible I'll revisit this in the future.

Sorry I couldn't be of more help! Please keep the ideas coming!
