### ISSUE TITLE
GoPhish Reporting Discrepancy 

### ISSUE THREAD

**Issue by jdeberry** [gophish/gophish#1501]
![image](https://user-images.githubusercontent.com/7111755/61081791-1ae4df00-a3f6-11e9-90f4-bd70959c7c0a.png)

**Comment by jordan-wright** [comment]
Hi @jdeberry,

Thanks for reaching out! Gophish will only report the IP addresses it sees, so this is an indication that an IP address that, according to the database you're using for GeoIP lookups (which could be inaccurate, but that's another issue) resolves to a different country, had access to the email sent to the recipient.

I say this because if you see a Clicked Link event (or "Opened Email" event), that means the host at the IP address had access to the `rid` parameter required to generate those events. It's possible that what you're seeing is some kind of spam appliance.

There is no functionality in Gophish to generate these events from the IP addresses you're seeing. Sorry there isn't more I could do to help!
