### ISSUE TITLE
Feature Request: Running "default" phishing site not requiring ?rid= under subpath

### ISSUE THREAD

**Issue by edermi** [gophish/gophish#1513]
**Version:** gophish-v0.7.1-linux-64bit

**Brief description of the issue:**

I completely understand the rationale behind using an unique ID for each phishing mail sent (user tracking, not getting caught by bots visiting only "/" etc.), nevertheless sometimes it is useful to have static phishing pages that just grab credentials. For example, phishing links printed out and dropped across physical locations or told via phone. In such scenarios it is required to have a simple URL without the RID. 

Currently such scenarios require "workarounds", e.g. creating a dummy campaign with a dummy user, send a mail, get the respective link for that user and configure the reverse proxy to forward requests for the webroot to this specific URL.

Ideally, landing pages may provide an optional field for "static hosting" where a path may be provided (e.g. "/owa", "/login") etc. where these pages are hosted afterwards.

There are several ways on how to represent the collected data. Maybe each time "static hosting" is enabled, a campaign is automatically created with a dummy entry showing data entered on that site, but there are certainly other good approaches, too.

**Comment by jordan-wright** [comment]
Hi there,

Thanks for taking the time to send this in! I understand the desire to create a phishing page without having to tie it to a specific campaign. However, I don't believe Gophish is the right tool for this.

> There are several ways on how to represent the collected data. Maybe each time "static hosting" is enabled, a campaign is automatically created with a dummy entry showing data entered on that site, but there are certainly other good approaches, too.

As you can see, since this isn't the normal flow Gophish supports, we'd have to go out of our way to try and bend the functionality of Gophish to support this use case, which would result in a very non-ideal UX.

I do have plans to support non-email campaigns (such as USB drop campaigns) by allowing campaigns to be created without an email configuration attached. In this case, individual links would still be created, but no emails would be sent which is _sort of_ related to your use case, though not exactly.

All this said, I don't anticipate adding this functionality at this time. My best recommendation would be to simply leverage a web server with appropriate logging to accomplish this task.

Thanks again for taking the time to provide your feedback!
