### ISSUE TITLE
How to host GoPhish (Locally / remote server)? 

### ISSUE THREAD

**Issue by Allen-Paul** [gophish/gophish#1541]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: 
This is the first time that I am using Gophish. I don't have much idea on hosting part.
I hear about hosting gophish but I am not sure what is this hosting. How to host Gophish (Locally / remote server)?
-> If I run the gophish in my local system, which server it is using? Will that be accessible outside?(I tried with testing mail but I also have doubts on "URL" in  campaign section)
-> If I host it on remote server, Will I need to make change in the config.json file?

Thanks in advance.

What are you expecting to see happen? :
Idea on how to host gophish

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @Allen-Paul,

Gophish is essentially a web server. It hosts the pages recipients see when they click on a link in the generated emails.

This means that people need to be able to reach the Gophish server in order to see the landing page. This is a networking issue, requiring the server that's running Gophish to be reachable. This may be done by using a server hosted in the cloud, one hosted in your own DMZ, or elsewhere. As long as the people opening the email can reach your Gophish server, then you'll be set.

**Comment by Allen-Paul** [comment]
Thanks for the information. This tool is really awesome.
