### ISSUE TITLE
masking submitted credentials

### ISSUE THREAD

**Issue by RoniWar** [gophish/gophish#1544]
Hey guys,

I know that this issue might have been addressed before but I'm still wondering whether it's possible to somehow encrypt the captured user credentials, as for our campaigns/clients
this is considered a strong security issue.
Also, how do you remove the credentials? does deleting the campaign also deletes the 
the data from the DB?

Thank you in advance,
Ron

**Comment by jordan-wright** [comment]
Hi there!

There is a PR open for this at #1314, I just haven't had the time to do a follow-up review and merge since I was trying to get v0.8.0 out the door.

As such, there is currently no way to encrypt stored credentials. We do delete events when a campaign is deleted, but there is an open issue at #1452 that suggests this may not quite work as intended with SQLite. I haven't had a chance to merge in a fix for that.

I hope this helps! Since we have multiple issues and PR's open for this, I'm going to close this one out as a duplicate.
