### ISSUE TITLE
Version in settings does not match current version

### ISSUE THREAD

**Issue by RicardoPires19** [gophish/gophish#1551]
This may be a small bug, but in the settings page it is indicated that version 0.7.1 is what I'm using, instead of version 0.8.0, even though I performed a clean installation with the latest release. 
Can you please confirm if it's only a minor bug or if the version wasn't updated correctly? I used the linux 64 bit release btw.

**Comment by Dextroz** [comment]
Hey there!

I’m having the same issue to. I think it has updated successfully but someone has forgotten to update a possibly hardcoded version number 😁

**Comment by jordan-wright** [comment]
Hey there!

Yeah, whoever forgot to update that version number is an absolute goober. In my opinion, probably the worst developer there is.

...also it was me. I forgot to bump that. 😳 the good news is that your upgrade likely completed without any issues. Since cutting a new 0.8.0 release would be tricky, I don’t know that I’ll fix the current release. Rather, I’ll include a note that mentions this so people are aware.

Thanks for the heads up on this! So sorry for the confusion.
