### ISSUE TITLE
A Weird Timeline

### ISSUE THREAD

**Issue by fungfung0727** [gophish/gophish#1559]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?:  Gophish v0.8.0

Brief description of the issue: The timeline of my campaign got weird. It shows a user clicked the link for hundreds of times with different devices in 3 days. I don't think the user actually click this much amount of time. It is just a one-time problem but i would like to know the reason of it and prevent it from happening again.

What are you expecting to see happen? : A more reasonable timeline.

What are you seeing happen? A timeline of one user clicking the link for hundreds of times with different devices in 3 days.

![image](https://user-images.githubusercontent.com/53885385/63824204-ea96d700-c988-11e9-85e0-016d8fa2b651.png)

![image](https://user-images.githubusercontent.com/53885385/63824212-f1bde500-c988-11e9-83ae-81c41aeb564d.png)

**Comment by glennzw** [comment]
I'd guess the URL link is being hit by an AV vendor, cache service, or some other automated piece of software. Maybe check the HTTP logs on the server to see the source IP and User Agent? You can grep for the campaign RID:

![rid](https://user-images.githubusercontent.com/3966613/63836162-f1195480-c970-11e9-9a1b-4250ced10328.png)

I've encountered this before, too. We could solve this (or reduce its likelihood) by including some JavaScript in every landing page to call back to the GoPhish server, rather than just a naked GET request (as most automated services won't execute JS). Food for thought for @jordan-wright

**Comment by jordan-wright** [comment]
I agree that this definitely appears related to #1555. Unfortunately, there isn't anything we can do to fully solve this issue, since it's true that the page _is_ being requested.

@glennzw I appreciate the thought around adding JS to the landing page! I'm awfully hesitant to do this though, since it would add significant complexity to landing pages as they are manipulated. It also has the downside of not reporting any actual clicks if JS is disabled for the user. Finally, it wouldn't surprise me at all if AV vendors are loading these pages in some form of sandboxed browser with limited JS capability, which would negate all the complexity we put it to try and make this more resilient to false positives.

All that said, I'd prefer to keep the logic as is for now. In cases like this, it should be reasonable for admins to recognize that these were some form of automated clicks from a service and compensate for them in the statistics they pull for their campaigns. This to me also has the side benefit that admins can see how their spam appliances are engaging incoming emails. 🤷‍♂

**Comment by glennzw** [comment]
So I've been thinking about how we could solve this without making any changes to GoPhish and I have a working solution (well, a hack).

Host this webpage somewhere (e.g. on your GoPhish server but on a different port):

```
<html>
    <head>
      <style>
        body {
            margin: 0;
        }
      </style>
    </head>
        <body>
          <iframe name="frame" style="border: 0; width: 100%; height: 100%">Please enable JavaScript to view this page.</iframe>

          <script>
            GoPhishServer = "http://gophish.local/"
            rid = window.location.search.substr(1)
            var site = GoPhishServer + "?" + rid  
            document.getElementsByName('frame')[0].src = site;
        </script>
        </body>
    </html>
```

Edit `GoPhishServer` to be your GoPhish server. Now create a new campaign and in the `URL` parameter enter the the address where the above page is hosted. Done.

How it works is that we host a blank iframe page, and load the iframe contents via JavaScript of the actual GoPhish server + rid for the user.

Now if a dumb crawler grabs the page the JavaScript won't execute, so no hit on the GoPhish server. If a human user clicks it the JavaScript executes and loads the GoPhish page, good hit.

The caveat of course is that the user's browser supports frames and has JavaScript enabled. I figure that's pretty likely.

<hr>
e.g:
Open link from email, see this in GoPhish logs:  

```
time="2019-08-30T14:18:30+01:00" level=info msg="127.0.0.1 - - [30/Aug/2019:14:18:30 +0100] \"GET /?rid=OJgAnMI HTTP/1.1\" 200 84 \"http://localhost:8000/?rid=OJgAnMI\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36\""
```

Using wget:
`wget "http://localhost:8000/?rid=OJgAnMI"`

Nothing in GoPhish logs.
