### ISSUE TITLE
package bitbucket.org/liamstask/goose/lib/goose: https://api.bitbucket.org/1.0/repositories/liamstask/goose: 410 Gone

### ISSUE THREAD

**Issue by orishai** [gophish/gophish#1560]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.8.0
Brief description of the issue: 
when trying to use go get github.com/gophish/gophish i get the following error:
package bitbucket.org/liamstask/goose/lib/goose: https://api.bitbucket.org/1.0/repositories/liamstask/goose: 410 Gone
What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @orishai,

After giving it a shot in a fresh Docker instance, I didn't encounter any issues:

```
docker run -ti golang /bin/sh
# go version
go version go1.11.2 linux/amd64
# go get github.com/gophish/gophish
```

It's possible this was a blip with Bitbuckets service, but if you still encounter the issue you may consider upgrading your version of Go. If that doesn't work, I'd appreciate if you could send me details about your setup (OS, Go version, etc.) so I can try to repro on my end.

Since things appear to be ok for now, I'm going to go ahead and close this out.

**Comment by samotelf** [comment]
Just my two cents.
This happened to me yesterday when using go1.8.1, I updated today to go1.12.9 and well went smooth.
Now trying to smooth things out.
