### ISSUE TITLE
Email bouncing back

### ISSUE THREAD

**Issue by flacko12** [gophish/gophish#1571]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: Latest

Brief description of the issue: Emails sent are bouncing back

What are you expecting to see happen? : to go through

What are you seeing happen?
It just sends the email back to my dummy account because of {{.URL}} and {{.tracker}} if i take those 2 out it will work fine but i need to track the results 

HTML CODE:
<html>
<head>
	<title></title>
</head>
<body>
<p>Please support our IT department by answering this <a href="{{.URL}}">survey</a>.<br />
<br />
<br />
Thanks,<br />
IT Department.</p>

<p>{{.Tracker}}</p>
</body>
</html>

Please provide any terminal output that may be relevant below:

```
Insert output here
```
![asdafas](https://user-images.githubusercontent.com/54702859/64221716-584e8000-cf00-11e9-9820-3b836c76ac91.PNG)

**Comment by rfdevere** [comment]
This is actually a good sign too! I always like it because it means emails are at least being received. 

When you are phishing an organisation to educate the staff and using GoPhish it is worthwhile to whitelist the GoPhish server, emails and domains that are used. This will stop the issue with the bounce back. GoPhish is designed to be an educational platform so isn't exactly discreet or hard to detect as a phishing server.

Whats happened with the above is the recipient has identified it as a phishing server or the quality of the email was poor so it was blocked. 

If you have full permission it might just be easier to create an email address right up in your exchange or Office365 whatever and use the SMTP creds in GoPhish! Far less mail filters and gateways to worry about. Remember to firewall/restrict tcp 22 & 3333 at a minimum the second data (like company email creds) are on the server.

**Comment by jordan-wright** [comment]
@rfdevere is correct. There isn't anything we can do within Gophish to get around every spam filter, which is both a good thing and expected. All the advice given above is applicable here.

Sorry there isn't more we can do to help!
