### ISSUE TITLE
FROM address not showing as required in sending profile

### ISSUE THREAD

**Issue by faheemadam** [gophish/gophish#1572]
What version of Gophish are you using?:  0.7.1

Brief description of the issue:  setup sending profile , used specific FROM address but test email shows the username EMAIL instead.

What are you expecting to see happen? : the FROM address in sending profile to be the FROM address on the email arriving

What are you seeing happen? : the FROM address is showing on the received test email as the USERNAME in sending profile not the FROM address from FROM :)

i am using using GMAIL to relay the emails

**Comment by jordan-wright** [comment]
This is a known issue. Sending emails from Gmail will automatically have your authenticated username displayed instead of whatever "From" name you configure in Gophish. You can almost certainly find more related information in [these issues](https://github.com/gophish/gophish/search?q=gmail&unscoped_q=gmail&type=Issues)

I'm afraid there is nothing we can do in Gophish to change this functionality.
