### ISSUE TITLE
Randomize order of users in a group

### ISSUE THREAD

**Issue by jonas2k** [gophish/gophish#1576]
Thanks for creating Gophish. It's awesome!

One thing I would love to see is the possiblity to randomize the order of users in a group. If you schedule a campaign, emails get sent in the defined interval in alphabetical order. It would be useful if one would be able to define to send emails in random order (or randomize targets in a group).

In #746, something similar got requested, but apparently never got merged.

Thanks for all your efforts.

Regards,

Jonas

**Comment by jordan-wright** [comment]
Hi @jonas2k!

Thanks for reaching out. I do recall the issue at #746. Eventually I’d be interested in seeing what I can potentially do to make this happen with a clean UX. Since we already have an issue for tracking that feature, I’m going to close this one out in favor of that one.

Thanks again for reaching out, and keep the ideas coming!
