### ISSUE TITLE
Outlook 365 strips link

### ISSUE THREAD

**Issue by cplatt1989** [gophish/gophish#1582]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.7.1

Brief description of the issue: 
Outlook 365 is displaying URL instead of link text

What are you expecting to see happen? :
I'm trying out a simple test template, that just says click here - "here" should be a link.

What are you seeing happen?
In the desktop version of Outlook, it works fine, but in Outlook 365, it displays like this - Click [10.10.1.200?rid=MwkRNBR]here

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```
<html>
<head>
	<title></title>
</head>
<body>
<p>Click <a href="{{.URL}}">here</a></p>
{{.Tracker}}</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - This happens in any browser
 * Step 2 - I tried creating a Transport Rule for 365 to bypass spam/clutter filtering, but I don't think that's the issue - it does go straight to my inbox.

I'm running GoPhish in an on-prem Windows VM, using a Linux relay box to send through 365. I'm just wondering if anyone has run into this issue before? It looks like 365 is (correctly) trying to secure the email by revealing the URL, but I need a way to stop it from doing that.

Thanks,
Corey

**Comment by jordan-wright** [comment]
Hi there!

Your template looks fine to me. This appears to be some kind of security setting within Outlook 365. I'm afraid there isn't anything we can do within Gophish to get around this.

Since you're asking if anyone else has run into this issue before, I'll leave this open for comments for a couple days before closing.

**Comment by glennzw** [comment]
I'm running Outlook too in a test lab and don't see this problem, so I'd hope there's a setting to enable links. It seems like a good safety measure though, ideally you could only enable links for GoPhish emails rather than across the board. This might help:

https://github.com/gophish/gophish/issues/223
