### ISSUE TITLE
How to modify X-Mailer to make "gophish" disappear"?

### ISSUE THREAD

**Issue by anonuser78** [gophish/gophish#1596]
What version of Gophish are you using?: Gophish v0.8.0

Brief description of the issue: I can't modify the X-Mailer header and remove "gophish" 

What are you expecting to see happen? : I expect to see something, that might not that obvious for the users to check the headers and see "gophish" in it

What are you seeing happen? I have tried to test it out and added a custom header in the Sending profile, but the X-Mailer: gophish still didn't disappear. 

Headers: 
X-Mailer: gophish
X-Gophish-Contact: *****@gmail.com
testme: notagophishatall   #custom header#
![image](https://user-images.githubusercontent.com/47336246/65077862-d29feb00-d969-11e9-9302-6ae9cfca0828.png)

**Comment by glennzw** [comment]
As per https://github.com/gophish/gophish/issues/1553#issuecomment-523969887 you'd need to comment out a line in the source and recompile.

**Comment by jordan-wright** [comment]
@glennzw is correct, if you want to remove it completely then you will need to modify Gophish. Otherwise, you can add a custom header with a blank value, like a single space, and that will replace the header sent out.

That said, I would recommend keeping the header in the email. If a recipient is going so far as to inspect and alert on the email based on the headers, that's a great outcome!

**Comment by s3m73x** [comment]
Actually having this header is pretty bad because it allows services like mimecast to easily filter and detect mails sent by gophish. Please give in the Option to overwrite it.
