### ISSUE TITLE
Feature Request: Webhook implementation

### ISSUE THREAD

**Issue by Al-TSN** [gophish/gophish#1602]
New here, if I'm not putting this in the right place please let me know.  Additionally, I didn't some searching and did not find any related features.

We basically use GoPhish entirely through the API and it has been working well for us.  However, we are required to run a job every night to retrieve any transactions that may have occurred for any/all of our campaigns that have closed to analyze the transaction data, e.g. opens/clicks etc.

We are looking at the ability to enable, could be configured through the API or a configuration file that would send a JSON package to a defined endpoint whenever a send/open/click transaction is written to the database.  This would give the ability to accomplish real-time reporting within our custom portal.

Some general practices that we have seen with other systems are, expecting a 200 response within a few seconds, if the connection to the endpoint fails x number of times consecutively the webhook is disabled. 

I would like to hear if others are interested in this capability.

Thanks,
Al

**Comment by quelsan** [comment]
Was just about to post a RFC about this - I've started to work on this this type of feature

**Comment by Al-TSN** [comment]
Fantastic, I look forward to contributing

**Comment by quelsan** [comment]
One option, while somewhat hacky, is to just marshal and POST all created events to a specified URL. I've added some debug logging and the POSTed events would in that case look something like this, but as JSON:

```
time="2019-10-04T10:28:08Z" level=warning msg="Event: &{Id:0 CampaignId:49 Email:user@example.com Time:2019-10-04 10:28:08.214555596 +0000 UTC Message:Email Sent Details:}"

time="2019-10-04T10:29:18Z" level=warning msg="Event: &{Id:0 CampaignId:49 Email:user@example.com Time:2019-10-04 10:29:18.56053065 +0000 UTC Message:Clicked Link Details:{\"payload\":{\"rid\":[\"L5U9rMR\"]},\"browser\":{\"address\":\"172.17.0.1\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0\"}}}"

time="2019-10-04T10:31:49Z" level=warning msg="Event: &{Id:0 CampaignId:49 Email:user@example.com Time:2019-10-04 10:31:49.445241146 +0000 UTC Message:Submitted Data Details:{\"payload\":{\"password\":[\"god\"],\"rid\":[\"L5U9rMR\"]},\"browser\":{\"address\":\"172.17.0.1\",\"user-agent\":\"curl/7.64.0\"}}}"
```

Would basically have the same structure as the event API endpoint.
If the asynchronous POST fails, the data could be written to a database table and handled by worker for retries.

**Comment by Al-TSN** [comment]
Not that hacky. Would just need a way to configure/enable the endpoint. Probably want the worker to have a max number of retries before disabling. Also have some notification on errors. 

I was thinking the easiest way to configure would be by adding and endpoint to the api, this way no UI changes would be required. 
POST to create the webhook
PUT to change it
GET to list the webhook info
DELETE to remove it

I think this works, posting all events. Let the receiver handle each specific event.

**Comment by ahmedkhalid1710** [comment]
yeah that feature would be so helpful. 
higher level webhook config rules ( like requests time out - temp blocking send - .. etc  ) would prevent wasting server resources. 
since gophish is typically used through the API it would be perfect if those webhooks are also configured through the API 

Thanks. 
Ahmed.

**Comment by quelsan** [comment]
> Not that hacky. Would just need a way to configure/enable the endpoint. Probably want the worker to have a max number of retries before disabling. Also have some notification on errors.

Yeah, this one approach - somewhat like sending profiles work.
Another option is to specify a webhook URL during campaign creation (which could also be done via the API).

**Comment by Al-TSN** [comment]
I'm a big fan of single purpose endpoints.  Since code has to be written either way, by separating webhooks code from campaigns changing one endpoint doesn't impact the other.  Also you would probably just be sending the same webhook information on every campaign. IMHO.

**Comment by quelsan** [comment]
I guess the only counter argument is that it could be nice to create single purpose taco belled receivers, for application specific TOTP tokens and similar.

**Comment by jordan-wright** [comment]
Hey everyone! I’d be happy to discuss a detailed RFC when I get more time to type, but for now here are a few thoughts.

* For the infrastructure side, there’s definitely prior art we can consider, such as looking at the way GitHub sends webhook events. This includes signing mechanisms, retry policies, etc.
* Personally, I’d like for the webhook URL to be configurable only by an admin user with system level permissions. Though, if there’s a use case otherwise I’d be open to discuss it.
* To start, I think it makes sense to have a single webhook url that is global for Gophish. The trick is that we can make it a templated URL, so you could use things like {{.CampaignURL}} in the path to make it easier to support separating multiple campaigns upstream (though, this information will also be in the JSON sent over).

More than anything, know that this is something I’m interested in, and I’m excited about the great ideas! Happy to help however I can to see this development happen.

**Comment by Al-TSN** [comment]
That's awesome Jordan.  Totally agree on the prior art, there is Github, Jira, mandrill, SendGrid, etc. 

I also agree on the admin user, definitely don't want someone to figure out how to backdoor getting information out of Gophish.  this can be controlled via API key, if we use the API to configure, or permissions through the UI.

The single webhook for global Gophish works, this make the responsibility of the downstream worker to understand and handle and discard what ever is needed or not.  We have implemented a practice of just ingesting the JSON, sending back a quick 200 and then processing it as needed.

This will be a great help for our organization and we are willing to help/contribute any way we can.  Only downside is no GO experience, so other then helping with the specifications, not sure we can contribute on the coding.

**Comment by jordan-wright** [comment]
Let's start with something like this - if anyone wants to take the reigns developing this, I'll be happy to help any way I can:

We'll create a new `webhook` package in `github.com/gophish/webhook` that implements a `Webhook` struct which looks something like this:

```go
type Webhook struct {
    client *http.Client
}
```

Creating a new instance of this will instantiate an `http.Client` with reasonable timeout policies like this:

```go
const DefaultTimeoutSeconds = 10
...
client := &http.Client{
    Timeout: DefaultTimeoutSeconds * time.Second,
}
```

The `webhook.Webhook` object will have a function, `Send` which looks like this:

```
func (hook *Webhook) Send(server string, secret []byte, data interface{}) error {}
```

The `data` will be marshaled as JSON and send to the `server`. For now, we will not do any form of retries and errors will be logged. This is in line with how Github does things, and makes things much easier.

The `secret` will be used to sign the outgoing request in an `X-Gophish-Signature` header. Similar to Github, we could sign the payload with HMAC+SHA256 (note: GH uses SHA1 but I think it's reasonable for us to use SHA256).

We will have the standard API operations for this:

* GET /webhook - Get webhook details (though, I'm not quite sure if we should include the `secret` in the resulting output JSON - probably not).
* POST /webhook - Overwrite the webhook details
* DELETE /webhook - Delete the webhook
* POST /webhook/ping - Validates the webhook by sending a `{"ping": "ok"}` test event to the configured webhook server to help with troubleshooting.

All of these API's should only be valid for users with the `models.PermissionModifySystem` permission. You can find an example [here.](https://github.com/gophish/gophish/blob/c3e90183c8ad0add0ed2ae43a34b8a2c1cacd998/controllers/api/server.go#L68)

The UX for managing the webhook should include a button for sending the validation event.

We'll then need to figure out what events we want to send. As in, just campaign events or any Gophish event? Doing just campaign events might be a good way to start.

I think that should just about cover it. This is a great way to get involved with the Gophish codebase since it's a separate, yet self-contained project that includes backend work, frontend work, database schemas, etc. 😄

**Comment by quelsan** [comment]
A good start may be to add this to the "createEvent" function - my gut feeling says that these are the most relevant to Webhook

**Comment by jordan-wright** [comment]
Hey everyone,

I've made the 1602-webhook branch to handle this functionality. If anyone wants to start working towards this, let me know and I can help get the ball rolling.

**Comment by GildedHonour** [comment]
@Al-TSN I can provide help on this. Let's discuss it by skype or email first. My email is in my profile.

**Comment by GildedHonour** [comment]
I'm going to work on this.

**Comment by GildedHonour** [comment]
I've create a PR, wip.

The fields a webhook will have are: 
  * title - used internally to distinguish webhooks between each other
  * url - where to webhook to be sent

Anything else?

**Comment by GildedHonour** [comment]
The events for which a webhook will be sent:

  * link clicked
  * data/form submitted
  * email opened

**Comment by GildedHonour** [comment]
<img width="1238" alt="Captura de pantalla 2019-11-01 a la(s) 10 42 13" src="https://user-images.githubusercontent.com/2032888/68000870-b3c79080-fc59-11e9-856c-52c0d9e7243b.png">

**Comment by codeafterdark** [comment]
Amazing progress. Are there any events that are missing. I’m thinking message sent, campaign ended.

**Comment by Al-TSN** [comment]
Sorry that was my alter ego above.  Same question about the events.

**Comment by ahmedkhalid1710** [comment]
those are all the events we're interested in. 

Campaign Created 
Email Sent
Email Opened 
Clicked Link 
Error Sending Email

**Comment by jordan-wright** [comment]
The easiest answer would be "any event that occurs in a campaign" should be sent. This currently includes:

* Campaign Created
* Email Sent
* Error Sending Email (both permanent and temporary)
* Email Opened
* Clicked Link
* Submitted Data
* Email Reported
* Campaign Completed

**Comment by GildedHonour** [comment]
Noted.

Will the webhooks be global for all the admins or will every admin have its own list?

**Comment by Al-TSN** [comment]
IMHO the webhooks should be global for all admins

**Comment by jordan-wright** [comment]
I think for now we can consider making webhooks global. In the future, we can consider user-specific webhooks.

And to that end, I’m not entirely convinced we need more than one right now? It seems like the simplest use case is setting up a single webhook that sends events upstream. Do y’all have a use case that requires multiple to be configured?

Just trying to start simple and we can iterate from there.

**Comment by Al-TSN** [comment]
The case I can make for multiple webhooks is supporting dev, QA and Prod environments. These would be three different endpoints.  

I have seen where webhooks can be configured by event and call different endpoint based on the event, but I don’t think that is needed for this

**Comment by jordan-wright** [comment]
Wow! Thanks for the quick response @Al-TSN.

I could see the usefulness there. In that case, we can move forward as we are now where it looks like @GildedHonour is supporting multiple webhooks.

**Comment by Al-TSN** [comment]
You’re welcome @jordan-wright  I’ve been watching this closely and love the progress being made by @GildedHonour  I appreciate your input along the way!

**Comment by GildedHonour** [comment]
CRUD has been implemented.

I'm working on ping.

**Comment by GildedHonour** [comment]
Ping - implemented

**Comment by GildedHonour** [comment]
<img width="1429" alt="Captura de pantalla 2019-11-08 a la(s) 02 09 57" src="https://user-images.githubusercontent.com/2032888/68415269-dd1c7b00-0189-11ea-9327-03a7165f9d7c.png">

**Comment by Al-TSN** [comment]
Does it make sense to have 1 ping as a requirement for the webhook to be live?

**Comment by GildedHonour** [comment]
I think yes: when changing its url and when adding a new webhook, a ping will be sent automatically to validate it for it to be changed or created. I'll add it.

**Comment by GildedHonour** [comment]
I've added "is_active" flag.

**Comment by GildedHonour** [comment]
I'm working on sending a webhook when an event occurs.

**Comment by S0larflare** [comment]
Is there a visual indicator for the 'status'? I'm thinking along the lines of a traffic light or a red/green circle to the left of the 'Ping' button.

**Comment by GildedHonour** [comment]
We can add it, or a green and red labels.

**Comment by GildedHonour** [comment]
I've added 'send webhook' to Campaign - created and completed.
Moving on to the other events.

**Comment by GildedHonour** [comment]
Done with sending webhooks at the rest of the events.

**Comment by Al-TSN** [comment]
This is fantastic.. Looks like we are getting close!

**Comment by GildedHonour** [comment]
Yeah. In terms of functionality, it basicaly works. There're some improvements to be made UI- and code quality-wise. And also the tests.

**Comment by vanditamathur** [comment]
Hi,
Can I configure Webhooks programatically using APIs? I believe APIs are not available yet to configure Webhooks. Is this something that is planned? If yes, can you please point me to the issue for that? Thanks.
