### ISSUE TITLE
What registers a link click? 

### ISSUE THREAD

**Issue by pwnywhisperer** [gophish/gophish#1605]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Unclear on when in the process the link click registers - if a recipient has a security feature in place that doesn't allow the landing page to render, will the "link click" statistic still be recorded? In this scenario, the recipient did click the link, but an error was generated on the displayed link from the phishing email sent.

What are you expecting to see happen? : I'm not sure what I am expecting - I've played with this using Burp to see if I could see when the "link click" registered and am hoping you can confirm in this process when that registers. 

PS - I swear I looked for this answer in the forums, and I really hope it's not redundant.

**Comment by jordan-wright** [comment]
Hi there,

Gophish registers a link click when an HTTP request is made to the phishing server URL (the URL you used when building a campaign) with the recipient's `rid` as a parameter.

It's not the landing page loading that matters, it's whether or not the Gophish server receives the HTTP request, since that triggers the event in the database.

You can find the code responsible for this here: https://github.com/gophish/gophish/blob/6222c5e180a97d0aa3ec345d0c7af06c380f3db5/controllers/phish.go#L244

Hope this helps!
