### ISSUE TITLE
Gophish Mailer

### ISSUE THREAD

**Issue by HarisBinZahid** [gophish/gophish#1620]
I want to add approval workflow in gophish as a person launch a campaign it add in campaigns list but emails will not be send until approval by manager.
I want to stop email sending on campaign launch, how can i do that?
Which function runs to send emails when campaign launched?

**Comment by jordan-wright** [comment]
I'm afraid this currently isn't possible in Gophish. It might be worth considering an API endpoint that allows you to modify a campaign while it is in a scheduled state, though I won't have time to implement that anytime soon.

If you're looking to build custom functionality into Gophish, then you can see where a campaign is launched [here](https://github.com/gophish/gophish/blob/master/controllers/api/campaign.go#L42) which calls [this function](https://github.com/gophish/gophish/blob/master/worker/worker.go#L100). I hope this helps point you in the right direction!

Since this isn't currently possible in Gophish, I'm going to go ahead and close this one out. Thanks for getting in touch!
