### ISSUE TITLE
http: Accept error: accept tcp [::]:80: accept4: too many open files

### ISSUE THREAD

**Issue by HacKeD0x90** [gophish/gophish#1633]
gophish version

**./gophish  --version
0.5.0**

Brief description of the issue: 
Everything is working fine and i'm able to use landing pages and email templates however after sometime 10 maybe 15 min the gophish service just crashes and alert that too many files are open

```
2019/10/26 00:56:56 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:56:57 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:56:58 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:56:59 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:57:00 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:57:01 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:57:02 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2019/10/26 00:57:03 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

```

**Comment by jordan-wright** [comment]
I'd start by upgrading Gophish to make sure there isn't some weird bug that's since been fixed. 0.5.0 is a pretty old version.

Beyond that, there's likely a problem happening outside of Gophish, such as a low user limit on the number of open sockets. I recommend just googling that error message you see along with what OS you're running to find instructions on how to update that limit - if you have permissions to do so.

I hope this helps!
