### ISSUE TITLE
Using shared mysql server

### ISSUE THREAD

**Issue by bhagoria** [gophish/gophish#1638]
Hi Sir,

I am planning to user a shared mysql server hosted remotely. Per documentation, the only change required is config.json as other changes like Updating the mysql config won't be applicable here.

Phishing:xxxxx@(10.10.x.x:3306)/phishing?charset=utf8&parseTime=True&loc=UTC

If I don't make any change in the mysql.config in shared mysql server remotely hosted because of the dependencies of other dbs, would it create a problem in the date line format with Gophish?

Thanks

**Comment by jordan-wright** [comment]
I don't use MySQL often, so I can't speak to how confident I am you'd have issues without changing the config. More broadly though, I would say that any attempt to use Gophish outside of the instructions we provide should be considered untested, unsupported, and potentially cause for issues.

**Comment by vertoforce** [comment]
Dropping a note here that I too would really appreciate not having to change the settings on the mysql server.

**Comment by vertoforce** [comment]
If anyone is interested, this is because gophish uses [gorm](https://github.com/jinzhu/gorm).  Gorm talks about this issue [here](https://github.com/jinzhu/gorm/issues/595)

Turns out instead of making that change to the database, you can instead change the struct to use a time pointer `*time.Time` instead of `time.Time` to have it insert `NULL` instead of the `0000-00-00` thing.  I was going to make a PR, but there are a lot of `time.Time` objects and I'd rather just not touch them

You can instead do [this](https://github.com/jinzhu/gorm/issues/595#issuecomment-618783102) to the database instead of setting it in the config, which is a passable workaround for me.
