### ISSUE TITLE
Results and Raw Details have conflicting data - Dashboard Incorrectly Displaying Data

### ISSUE THREAD

**Issue by nicpenning** [gophish/gophish#1643]
**What version of Gophish are you using?:** v0.8.0

**Brief description of the issue:** Results and raw events show conflicting data. In the raw events, the "details" field is Email Sent whereas in the results it shows the "status" field as Scheduled.

**What are you expecting to see happen? :** We are expecting that the data for Results.csv and Events.csv to match up. The Dashboard incorrectly displays the Results.csv.

**What are you seeing happen?**
This is the Events.csv for one record:
user@ourdomain.com,2019-09-20T15:46:23.835504Z,Email Sent,

This is the Results.csv for the same record to show the discrepancy:
4SE2bDq,Scheduled,,0,0,2019-09-20T15:46:00Z,false,2019-09-20T15:44:53.5372001Z,user@ourdomain.com,Firstname1,Lastname1,Position1

This is the dashboard view, note that it doesn't add up with even the API results.
![image](https://user-images.githubusercontent.com/5582679/67978000-1f244a80-fbe7-11e9-85ed-d96dbb0099b9.png)

This is using the API to get a count of emails sent.
![image](https://user-images.githubusercontent.com/5582679/67978363-f6508500-fbe7-11e9-8dfe-10e359a48b0f.png)

It is also interesting that the API doesn't validate the Dashboard results. The PowerShell script above gets the count of Email's sent and shows the discrepancy.

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - Schedule a large campaign (>7000 emails) only a few minutes ahead of when it needs to be launched.
 * Step 2 - Export results and events after the campaign is finished.
 * Step 3 - Compare results. You will also notice the dashboard will align with the Results.csv and not the Events.csv

 Note: The API also exhibits the same behaviors.

You can use this PowerShell script to check the results.

```powershell
$apiKey = [Enter API Key here]

add-type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
    public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
    }
}
"@
$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

$campaigns = Invoke-RestMethod https://127.0.0.1:3333/api/campaigns?api_key=$apiKey
#$results = $campaigns[11].results
#$results.Count

$x = 0
$campaigns | ForEach-Object{
$campaigns.Name[$x] + " [$x]"
$x++
}


$campaignNumber = Read-Host "Select the campaign number to return results."
$campaigns[$campaignNumber].results | Out-GridView

$($campaigns[$campaignNumber].timeline.message -eq "Email Sent").count
$($campaigns[$campaignNumber].results.status -eq "Email Sent").count

```

**Comment by jordan-wright** [comment]
Hey @nicpenning!

I’m sorry to hear you’re seeing unexpected results with the data being stored in Gophish.

I’ll start with the assumption that _if_ something weird is happening, it might be tied to the size of the campaign. This shouldn’t happen, so let’s work our way backwards.

First, it would help to understand what’s in the database, since this is the authoritative source of information. Could you take a look and see what counts you measure in the database itself, and how they compare to what the API returns? My hope is that at the very, very least the API and the database would show the same values.

Once we confirm that’s the case, we can think about why there might be a discrepancy around the status of results and the events in the DB.

Sorry again for the trouble. We can work together to try and figure out what’s going on.

**Comment by nicpenning** [comment]
@jordan-wright, Thanks for the quick response! 

What would be the best way to measure the counts in the Database?

Should we export the results and the raw events or should we query the .db file directly? We are using the default sqlite3 database for the campaigns. Every campaign is 7500+ email account and they do tend to slow down in the GUI. We are also running in a Windows environment.

We noticed that if we don't schedule it out quite a ways (hours or a day) ahead of time the campaigns seem to get corrupt.

Is there a tool you have to sanitize the database then we could share that if it will help?

Let us now how to proceed, also, thank you and those involved for such a great tool!

**Comment by nicpenning** [comment]
Hey @jordan-wright , we took a look at the database and the data there matches up with what gets exported as I noted before. So it seems that your assumption is correct. The results that are exported as a csv or using the API are confirmed to be the same as what is found in the database.

How shall we proceed?

Thanks again!

**Comment by jordan-wright** [comment]
Hi @nicpenning!

My apologies for not getting back to your earlier comment. Thanks for the update!

So it seems that the events are getting added, but the actual result object isn't getting updated. I suppose it's also possible that's it's getting overwritten, but that's probably less likely.

There is definitely something _weird_ happening that looks to only affect larger campaigns. This seems potentially semi-related to #1677, #1080, #1552, and #1065. 

I have plans to spend some time over the weekend to run some large local campaigns myself and see if I can reproduce the issue. My very best guess at this point is that there is some kind of database race-condition causing these inconsistencies which, as you can imagine, is a tricky thing to debug 😄 

If you would be willing to send me an anonymized copy of your `results.csv` and `events.csv`, it'd really help me out.

I'll keep you updated! Sorry again for all the hassle- this is definitely unexpected behavior.

**Comment by jordan-wright** [comment]
I forgot to mention the email address you can use to reach me - it's hi@getgophish.com.

If you also have any terminal logs to go along with the data, that'd help a _ton_ since it'll help me see what Gophish was doing through all this.

**Comment by jordan-wright** [comment]
Ok, after doing some digging, here's what I think is happening.

Right now, when we create a campaign we perform every database command individually. This includes:

* Making the initial campaign data
* Adding each result
    * Which also includes a `SELECT` to make sure the candidate ID isn't taken
* Adding each maillog
* Finally, doing another save on the campaign

Doing some testing, it appears that launching a large campaign can take a while as I'm sure you've seen. This is largely due to running each SQL command by itself.

But the bigger problem is that I think this is causing the results you're seeing. Here's what I think is happening:

* We create the initial campaign data
* We start the process of creating results and maillogs, but it takes a while
* While this is happening, our worker polls for new maillogs, picking up the ones that have been created and sends the emails
* All the results finish getting created, our final save occurs which overwrites the status of all results to "Scheduled".

With this in mind, there are a couple of fixes I'll implement:

* I'll see about using a single database transaction for the campaign creation. Initial tests seem to suggest this will also increase performance (which would be expected), but I'll want to do some testing to make sure this doesn't inadvertently break anything
* I'll remove that last campaign save. For a few reasons, it's really not needed

I think this will resolve the behavior you're seeing. I'll let you know when the changes are made.

**Comment by nicpenning** [comment]
Thanks for digging deeper into this! We can still send you the database on Monday the 2nd if you are interested. We will be on the watch for those changes.

**Comment by jordan-wright** [comment]
That would be wonderful! It’ll help confirm my hunch, so I’d appreciate it a ton!

**Comment by jordan-wright** [comment]
Hey there!

I've merged 44f8840, which I anticipate fixes this issue.

Please don't hesitate to send the db my way and I'll still take a look. Otherwise, there are a couple of other PR's I hope to get merged in, then I'll cut a new release and you can take it for a spin 😄 

Sorry again for all the hassle! Hopefully this makes things work like a charm.

**Comment by nicpenning** [comment]
Hey @jordan-wright, we are working on getting you the DB. How would you recommend we go about sanitizing the database?

**Comment by nicpenning** [comment]
Hey @jordan-wright , did you get our database that we sent awhile back? If so, did it confirm your findings?
