### ISSUE TITLE
Customize/Obfuscate Tracking Image URL

### ISSUE THREAD

**Issue by syserr0r** [gophish/gophish#1648]
It would be great to be able to customize the tracking image url inserted into the e-mail.

Most of our users use webmail and we have (uBlock Origin) ad-blocking set-up, so anything matching `spamsite.com/track` in the url gets blocked -- if we could change the tracking image to have another name, such as `spamsite.com/foo` then it would work even better.

Overall love Gophish, keep up the good work!

**Comment by jordan-wright** [comment]
I appreciate the feedback! I can understand the use case, but at this time, I don't have plans to support custom paths for the tracking URL. It'd be a big change from what we're doing now in the hopes of trying to get slightly more reliable metrics for certain users.

Instead, I'd recommend treating "Email Opened" events as best-effort, since there are many reasons why those events wouldn't be received, such as the email client refusing to load any 1x1 pixel images.

Sorry I couldn't be of more help! Please keep the ideas coming!
