### ISSUE TITLE
Unable to reach url site on public ip address 

### ISSUE THREAD

**Issue by Phoenix2875** [gophish/gophish#1650]
Hi, using version 0.7.1 on windows server 2012.
Working perfectly. Configured all fields, template, landing page etch. Campaign starts sending email correctly.
The gophish is on a VPS in cloud with no public ip restrictions. Firewall is actually down.
I putted in campaign url the http://xxx.xxx.xxx.xxx (public ip address) with no port specified so it's using http.
Started campaing but url not reachable. Effectively if you try the url, nothing works.
Maybe i left something back? I'm thinking about how can redirect to that server without a web platform like iis or apache or something different. 
Can someone give me some help? Thank you

**Comment by jordan-wright** [comment]
You don't need IIS or Apache for Gophish to work, since it starts its own webserver. You'll want to start by making sure you are running Gophish as an administrator so that it can properly bind to TCP port 80.

Beyond that, I'd recommend taking a look at our [FAQ](https://docs.getgophish.com/user-guide/faq) which gives some advice on how to troubleshoot issues like this. It's almost certainly going to be that:
* Gophish can't bind to the port (a privileges issue)
* A firewall is blocking the connection
* There is some other network condition outside of Gophish preventing the connection

I hope this helps!

**Comment by Phoenix2875** [comment]
Today I'll try than you for now Jordan

**Comment by Phoenix2875** [comment]
Maybe found the problem. It tells starting phishing server at http://0.0.0.0:80 this is not right i thing. Is that something to change with 127.0.0.1 at least. Where is the config file to modify?
