### ISSUE TITLE
Is Authentication really required?

### ISSUE THREAD

**Issue by DKhalaf** [gophish/gophish#1655]
Hello
Is it really required to authenticate the users we're sending mails out from? And if so, is there a way to bypass this authentication? 
Also, is it anywhere possible to create an already existing domain such as "One.com" and send emails out from it? I was thinking of setting up a mailserver where I could pretty much take any domain without purchasing, create a few users like Mike@one.com and use it for Gophish.. Would this work? :-)
It is primarily for educational purposes. Thanks in advance.

**Comment by jordan-wright** [comment]
SMTP authentication is used when trying to send email out from a particular mail server (say, your organization's mail server so it can ensure you're authorized to send email as user@example.com). If you use an open-relay, authentication won't be needed, but it's not a guarantee that the receiving mail server will allow emails sent from that organization's domain.

In general, I'd encourage you to read more broadly about how SMTP and SMTP authentication works, since this isn't the forum for answering those questions. Instead, these issues are for supporting the features that Gophish offers.
