### ISSUE TITLE
Email Tracking?

### ISSUE THREAD

**Issue by eliddell1** [gophish/gophish#1656]
What version of Gophish are you using?: 0.7.1

Brief description of the issue: I started a test campaign, to play around.  I was under the impression that enabling email tracking would give me a notification each time the email was open and that it would include the ip address of where our victim opened it.  I can not find any of ip address info and it seems that no matter how many times it is opened each new open just folds under 1 open.

What are you expecting to see happen? : I was expecting to get a count of each time it was opened along with the ip address of where it was opened.

What are you seeing happen?  I see no ip address

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hey there!

At a high-level, email open tracking should be thought of as a "best effort" kind of thing, since many email clients either cache the tracking pixel (Gmail does this), or refuse to render it by default for privacy reasons. This is likely why you see the behavior you're seeing.

Regarding the IP address, we do record it but don't currently render it in the dashboard. If you download the "Raw Events", you'll find events that look like this, providing the IP address:

```
Matthew.Maldonado@example.com,2019-11-11T16:26:08.964718029Z,Email Opened,"{""payload"":{""rid"":[""A8xCL8k""]},""browser"":{""address"":""127.0.0.1"",""user-agent"":""Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/3.0)""}}"

I hope this helps!
```

**Comment by eliddell1** [comment]
Thanks..  figured it out..  its in the event data if you export.. just not in the gui itself.

**Comment by p-yu** [comment]
@jordan-wright Hey I was looking for email open tracking info and stumbled on this piece. Thanks for the explanation regarding email open tracking! 

Just would like to have a bit more clarification on this topic: I had a campaign on client and found that the majority of data submitted record (25) doesn't have email opened record (only 9 have), which of course makes no sense. 

Is there any recommendation on increasing the accuracy of email opened count? Since its a really important metric (Email opened to email click ratio) especially if we want to compare several campaigns to see the improvement. 

Thanks a lot in advance :)
