### ISSUE TITLE
Email landing page dont work

### ISSUE THREAD

**Issue by Sleimboyy** [gophish/gophish#1666]
When i do a link in the email then click on the link it dont get to my landing page how do i do that

**Comment by jordan-wright** [comment]
I’m afraid there isn’t anything we can do to help without having more information. As it is, all this tells me is “it’s not working as expected”. I don’t have any information on what you’re trying, how you have Gophish configured, etc.

We have the issue template for a reason, since it asks the questions to try and get the information we need to troubleshoot.

Please follow the issue template if you are still running into issues.
