### ISSUE TITLE
Feature Request: Add Extra Tracking

### ISSUE THREAD

**Issue by bhaizlett123** [gophish/gophish#1669]
Hello,

Is there a way to be able to add like an extra tracking mechanism, like have a custom link after the login and if they click that link, track it?

**Comment by jordan-wright** [comment]
Hi there!

Currently, we only support tracking the first link that's clicked. It's possible that in the future we'll support different kinds of tracking (see #223 for ideas - no ETA on when this work would be completed though). Since this would be part of a bigger rearchitecture of how we think of campaigns, I'm going to close this out in favor of bigger initiatives like #223 

Thanks for getting in touch!
