### ISSUE TITLE
Turn off Support for TLSv1.0

### ISSUE THREAD

**Issue by plaverty9-r7** [gophish/gophish#1689]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.5.0

Brief description of the issue: 
How do we turn off support for TLSv1.0 and below? I create a cert using Let's Encrypt and that part works great. The only issue is that my gophish server is supporting TLSv1.0, TLSv1.1 and TLSv1.2 as well as ECDHE-RSA-DES-CBC3-SHA and DES-CBC3-SHA ciphers. My landing page can't be reached as there is a firewall blocking all TLSv1.0 connections. I want to turn off support for TLSv1.0 and leave support for 1.1 and 1.2 on. I've tried editing my nginx.conf file and restarting gophish, but that doesn't seem to resolve it. Where can I fix this? 

Thank you!

**Comment by jordan-wright** [comment]
> I've tried editing my nginx.conf file 

Is nginx in front of Gophish? If it is, then this sounds like an Nginx issue, not a Gophish issue. And in case it _is_ Gophish handling the TLS v1.0 connection then no, there's no way to disable that from within Gophish. The answer would be to _add_ Nginx to handle that config for you 😄 

Since there isn't anything we can do on our end to resolve this, I'm going to go ahead and close this out. Thanks for getting in touch!

**Comment by oliver-yu** [comment]
![image](https://user-images.githubusercontent.com/18164716/231697446-34e796fc-2c33-46aa-867b-7c23686aef02.png)

**Comment by oliver-yu** [comment]
![image](https://user-images.githubusercontent.com/18164716/231697896-984e3215-76f2-4fc5-8798-0fe85c27fe58.png)
