### ISSUE TITLE
Harden Cipher list

### ISSUE THREAD

**Issue by S0larflare** [gophish/gophish#1698]
Off the back of #1689 and #1691 can we also harden the allowed cipher list? Something along the lines of:

```
        ps.server.TLSConfig = &tls.Config{
  MinVersion: tls.VersionTLS12,
        CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
                PreferServerCipherSuites: true,
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
                        tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
},
}

        as.server.TLSConfig = &tls.Config{
  MinVersion: tls.VersionTLS12,
        CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
                PreferServerCipherSuites: true,
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
                        tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
},
}
```
I appreciate it's a little restrictive (so perhaps only do it for the admin server?) but it is something that is popping up on vulnerability scans for weak/deprecated cipher suites.

**Comment by jordan-wright** [comment]
Hmm, yeah, this is quite a bit more restrictive. There are a few different cipher suite recommendation lists to consider, and I'd like to get your take.

First, there's the [Mozilla intermediate compatibility](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29) list, which supports what I would consider to be reasonable clients.

Then, there's the recommended cipher suites from [this Cloudflare post.](https://blog.cloudflare.com/exposing-go-on-the-internet/).

Finally, there's the [default cipher suites](https://github.com/caddyserver/caddy/blob/008415f206dec7c72c3b0abe36d5a40213abb7a2/caddytls/config.go#L492) in webservers like Caddy.

My goal is to encourage compatibility while removing the "obviously" bad cipher suites to try and make vuln scans a bit cleaner. I don't know that we should shoot for the most modern configuration since it's quite possible many larger users will have older systems.

When it comes to curve preferences, both Caddy and the Cloudflare post just recommend X25519 and CurveP256. Cloudflare calls out that these are chosen since they're optimized:

> However, you should still set PreferServerCipherSuites to ensure safer and faster cipher suites are preferred, and CurvePreferences to avoid unoptimized curves: *a client using CurveP384 would cause up to a second of CPU to be consumed on our machines.*

I don't think this performance hit would be significant for Gophish, but at the same time it seems that if those two curves are good enough for CF and Caddy, then they're probably good enough for us.

What do you think?

**Comment by S0larflare** [comment]
Sorry Jordan, should have come back earlier. The Caddy default list looks good to me (the one's I have up there are simply the strongest from an older list I had, I mostly just got rid of any CBC related ciphers). I don't think performance is a big concern, especially if we only do this for the admin console as typically you would have one or two users on it at a time. It might make a bit of a difference if we did it to the phishing server if that is set to serve TLS, at least during very large campaigns, but part of me thinks that should just be a note we make in the docs somewhere for the 0.01% of people who may be interested in it?
