### ISSUE TITLE
Possible query performance improvement

### ISSUE THREAD

**Issue by aczietlow** [gophish/gophish#1702]
https://github.com/gophish/gophish/blob/f570a611db089cb72e6a5259df08726b20c1671b/models/group.go#L330

Version
0.8

I'm encountering bottlenecks from mysql on production use. We're currently running with ~150k targets across 6000 groups. When using the api to create groups with upwards of 15k targets, especially on a populated database, we've seen slower than expected response times (Upwards of over 60 seconds). This makes sense when we think about the number of rows that need to be scanned per group target.

(I'm not DBA, so I'm trying to work through this) **Is there a good reason to include the select statement in the db transaction?** `err = tx.Where("group_id=? and target_id=?", gid, t.Id).Find(&GroupTarget{}).Error`

Seems related to #1686

**Comment by jordan-wright** [comment]
Hey @aczietlow,

Thanks for reaching out! I'm always open to ways we can improve backend performance.

Just to make sure I understand correctly, are you suggesting that this is a new bottleneck that you didn't have before #1686? That would be surprising, since my early tests (using SQLite, IIRC) suggested that creating groups of 10k members was improved from roughly 17 seconds to just over 6 seconds.

At the very least, the good news is that we have benchmarks we can use to evaluate any improvements we make, which brings me to that specific query.

This is a great question! At first, I was going to mention that this deals with the way we update groups, since we do the select all + delete old + insert new approach, rather than a delete all + insert from scratch approach (though, personally I'd be interested in benchmarks to see which is faster). But looking more into this, it appears anywhere we call this we know that there is no current many-to-many record for the group_target, so it'd probably be safe to remove.

Doing a quick check by commenting out that particular query, I see that all tests pass, and we see an immediate performance improvement:

Before:

```
BenchmarkPostGroup100-4     	      97	  12669438 ns/op	 2989519 B/op	   52917 allocs/op
BenchmarkPostGroup1000-4    	       6	 199644153 ns/op	29897194 B/op	  528142 allocs/op
BenchmarkPostGroup10000-4   	       1	6554607059 ns/op	299220704 B/op	 5282490 allocs/op
BenchmarkPutGroup100-4      	     100	  10119219 ns/op	 2589318 B/op	   46079 allocs/op
BenchmarkPutGroup1000-4     	       7	 168557835 ns/op	25813116 B/op	  458433 allocs/op
BenchmarkPutGroup10000-4    	       1	7956365402 ns/op	260380848 B/op	 4581523 allocs/op
```

After:

```
BenchmarkPostGroup100-4     	     134	   8945467 ns/op	 2355247 B/op	   42328 allocs/op
BenchmarkPostGroup1000-4    	       9	 114773957 ns/op	23551154 B/op	  422217 allocs/op
BenchmarkPostGroup10000-4   	       1	3451863992 ns/op	235606416 B/op	 4221775 allocs/op
BenchmarkPutGroup100-4      	     142	   8514006 ns/op	 2270849 B/op	   40773 allocs/op
BenchmarkPutGroup1000-4     	       8	 137215092 ns/op	22629723 B/op	  405363 allocs/op
BenchmarkPutGroup10000-4    	       1	6853912391 ns/op	228576368 B/op	 4051160 allocs/op
```

This shows pretty nice performance improvements across the board! For example, creating a new group of 10k members (`BenchmarkPostGroup10000`) goes from 6.5 seconds to 3.4 seconds. 🎊 

If you'd like to draft a PR with that query removed, I'd be happy to do some more comprehensive digging to make sure things won't break, then merge it in.

Great catch!

**Comment by jordan-wright** [comment]
> I'm not DBA, so I'm trying to work through this

This has been my motto since I started working on Gophish. 😄  For example, I think that with some clever indexes created, we can do even better. But I don't know much about how to identify which indexes make the most sense.

Here's an example of the benchmarks both with the change mentioned above, and creating an index on the target email:

```
BenchmarkPostGroup100-4     	     133	   9272950 ns/op	 2353291 B/op	   42308 allocs/op
BenchmarkPostGroup1000-4    	      12	  90023962 ns/op	23526834 B/op	  421966 allocs/op
BenchmarkPostGroup10000-4   	       1	1044137796 ns/op	235104352 B/op	 4216646 allocs/op
BenchmarkPutGroup100-4      	     146	   8248483 ns/op	 2270487 B/op	   40768 allocs/op
BenchmarkPutGroup1000-4     	      12	  93634844 ns/op	22617658 B/op	  405241 allocs/op
BenchmarkPutGroup10000-4    	       1	2533942403 ns/op	228466528 B/op	 4050053 allocs/op
```

So this drops the time needed to create a group with 10k members to... 1 second. 👀 

This seems super promising, but it's pretty unfamiliar territory for me. If you know of any DBA's who could give guidance, any suggestions are always appreciated!

**Comment by aczietlow** [comment]
From some initial testing I think there is some performance drop off when using mysql once there are ~100k targets. I think part of the bottleneck if during the lookup of checking for any many-many relationships on the grouip_targets table. I'm going to continue to work on some improvements to query performance at higher capacity. I've seen some minor improvements from adding an index to some tables. I'll try to put up a PR with some of the performance improvements we've come across. 

`ALTER TABLE `group_targets` ADD INDEX `idx_target_group` (`target_id`,`group_id`) USING BTREE`

Ultimately my goal is to have existing database with 100,000s of group targets, and 10,000s campaigns, AND to be able to create groups and campaigns with of 10,000 targets in sub 60 seconds.

**Comment by jordan-wright** [comment]
I think that's a super reasonable goal! I'd be open to any performance improvements y'all come across.

In the meantime, I've gone ahead and merged in the change that removes that unnecessary query. That should help a bit 😄

Since the original issue is resolved, I'm going to go ahead and close this issue out, but please don't hesitate to reference it in any future PR's that you submit related to performance.

Thanks again, and great catch!
