### ISSUE TITLE
How to collect the data

### ISSUE THREAD

**Issue by seventeenli17** [gophish/gophish#1706]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 
I'm a dummy to setup the page to test on my Windows 10 desktop
What are you expecting to see happen? :
The testing mail is OK which delivered to my mail box. I can open the mail and see the content but no figure updated on the portal. If I use my desktop as gophish server and landing page portal. 
How shall I configure on the JSON file ?
Dear Jeff,

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
config.json:- and 10.10.8.88 is my desktop IP
{
	"admin_server": {
		"listen_url": "10.10.8.88:3333",
		"use_tls": true,
		"cert_path": "gophish_admin.crt",
		"key_path": "gophish_admin.key"
	},
	"phish_server": {
		"listen_url": "10.10.8.88:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": ""
	}
}
```html
mail template :-
html>
<head>
	<title></title>
</head>
<body>
<p>Hi {{.FirstName}},</P>
<P> The password for {{.Email}} has expired. Please reset your password <a href="{{.URL}}">here</a>. </P>
<P>Thanks, SAE IT Team</p>
</body>
</html>

```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
If I understand correctly you're reading the email, but it's not being marked as 'Email Opened' in the Gophish UI. This is usually because your email client is blocking loading of remote images / content. 

Watch your Gophish logs, you should see a request for the tracking pixel, e.g:

```time="2020-01-07T17:39:59Z" level=info msg="::1 - - [07/Jan/2020:17:39:59 +0000] \"GET /track?rid=GNlIrOx HTTP/1.1\" 200 95 "```

Also make sure you ticked the "Add Tracking Image" option in your email template, or manually add it to the end of your email, just before the `</body>`. So, for your email:

```
html>
<head>
	<title></title>
</head>
<body>
<p>Hi {{.FirstName}},</P>
<P> The password for {{.Email}} has expired. Please reset your password <a href="{{.URL}}">here</a>. </P>
<P>Thanks, SAE IT Team</p>
{{.Tracker}}
</body>
</html>
```

**Comment by seventeenli17** [comment]
No "Email Opened" recorded in the portal even add the track here as well as no "track" when I do the search in the gophish server log 
<html>
<head>
	<title></title>
</head>
<body>
<p>Hi {{.FirstName}},</P>
<P> The password for {{.Email}} has expired. Please reset your password <a href="{{.URL}}">here</a>. </P>
<P>Thanks, SAE IT Team</p>
{{.Tracker}}
</body>
</html>
And "checked" Add Tracking Image
I'd like to double confirm I shall input 10.10.8.88 in the launching compaign page URL field which is the IP in the config.json I specified ? 
config.json:- and 10.10.8.88 is my desktop IP
{
"admin_server": {
"listen_url": "10.10.8.88:3333",
"use_tls": true,
"cert_path": "gophish_admin.crt",
"key_path": "gophish_admin.key"
},
"phish_server": {
"listen_url": "10.10.8.88:80",
"use_tls": false,
"cert_path": "example.crt",
"key_path": "example.key"
},
"db_name": "sqlite3",
"db_path": "gophish.db",
"migrations_prefix": "db/db_",
"contact_address": "",
"logging": {
"filename": ""
}
}

**Comment by jordan-wright** [comment]
> I'd like to double confirm I shall input 10.10.8.88 in the launching compaign page URL field which is the IP in the config.json I specified

You should likely use `0.0.0.0:80` in the config.json since this tells Gophish to bind on all interfaces. You would then put the IP address that recipients can reach, presumably `10.10.8.88` in this case, in the Campaign URL field.

@glennzw is correct- tracking email opens is a best effort approach, since many email clients block the loading of remote images. It's better for troubleshooting purposes to try and make sure that "Clicked Link" events are being registered.

To that end, you should review the email that you receive- does it have the URL you expect? It should look something like `http://10.10.8.88/?rid=XXXXXX` where `XXXXXX` is a unique ID. If it doesn't, then it sounds like either the template is wrong or you're using the correct value for the campaign URL field.

If it looks right but you don't see your landing page, then it's likely a networking issue.

I hope that helps get you pointed in the right direction!

**Comment by seventeenli17** [comment]
I tried to put 0.0.0.0:80 into config.json and put 10.10.8.88 into Campaign URL field but not work.
I can see the link show http://10.10.238.88/?rid=sWSR5nw
Since I'm using my desktop as gophish server and IIS server for testing
I found that the link in mail cannot link to my IIS default.htm

**Comment by seventeenli17** [comment]
sorry, let me correct. This linked to my desktop IIS default html page instead of landing page as well as no open / link clicked record on Gophish portal.

**Comment by jordan-wright** [comment]
The problem sounds like you almost certainly have IIS running on port 80, which will prevent Gophish from being able to bind to that port.

When using Gophish, you don't need to run IIS. Shutting down IIS and restarting Gophish should resolve the issue.
