### ISSUE TITLE
After campaign launch user positions not showing

### ISSUE THREAD

**Issue by CaptainBobby** [gophish/gophish#172]
I successfully imported users with the following information populated
FirstName, LastName, Email, Position

After launching a campaign and viewing the results the Position field is empty, it is also empty when exporting the results. I was hoping to use this data for statistics based on office location, which is how I populated the position field. I realize the images below are from different target groups but the issue is the same regardless of the group of targets I select.

Any idea why this might not be showing?

![users_position](https://cloud.githubusercontent.com/assets/17417959/13236446/a05eb2ca-d981-11e5-96cf-66b3fae7f7f7.png)
![campaign_no_position](https://cloud.githubusercontent.com/assets/17417959/13236455/a9e01474-d981-11e5-9233-ceea3160e16e.png)

**Comment by jordan-wright** [comment]
Hi @CaptainBobby - thanks for the report!

Are you using the pre-built binary? If so, you might try building from source until the next release is published (should be the end of this week or the next - just finishing some things up). This looks like it's related to #163, which has been fixed in the master branch.

**Comment by CaptainBobby** [comment]
Thanks @jordan-wright - I am using the pre-built binary for Linux. I will try from source and see if that fixes the issue.
