### ISSUE TITLE
Using Gophish to do Internal Campaigns

### ISSUE THREAD

**Issue by empty0n3** [gophish/gophish#1724]
Hey ya'll! I'm having a little bit of trouble to set up Gophish in my company.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: I'm running Gophish in a Kali Linux VM. I'm also using smpt.gmail.com:587 and a gmail account to config the sender profile. 

What are you expecting to see happen? : At this point, I just want to see the dashboard working and updating when I open the emails and open the link in the email template.

What are you seeing happen? The emails are sent but the dashboard does not work when I click the links and even when I open the emails.

My landing page was made just by importing a simple google account log in using the gophish orange button there
The email template is just simple text and the tag {{.URL}}.

I really think that my problem is with the URL when I'm launching the campaign. I don't know what to put there.

Help me please! :(

**Comment by glennzw** [comment]
So the landing page loads, but this isn't reflected in the dashboard? I'd suggest two things:

First, try a very simple landing page. Here's one:

```
<html><head>
	<title></title>
</head>
<body>
<form action="" method="post" name="form"><label>Username:</label> <input name="username" type="text"/><br/>
<label>Password:</label> <input name="password" type="password"/><br/>
<input id="login" name="login" type="submit" value="Login"/> </form>


</body></html>
```

Secondly, watch your Gophish log output when you click the link - you should see hits coming through.

Oh, also I'd recommend using the latest version of Gophish, you're a couple behind.

**Comment by empty0n3** [comment]
The landing page doesn't work either.
I dont have a domain configured yet and I'm just testing it in my local environment.
About the version, I've downloaded the 0.8.0 but the text file name "VERSION" that comes with it says it is version 0.7.1.

I'll try that landing page! :)
BUT, since I'm not using a specific domain, what should I put in the URL when launching the campaign?

**Comment by jordan-wright** [comment]
It sounds like the issue is what you're putting as the URL when creating a campaign. This value should be the domain/ip address that points to your Gophish server. It needs to be reachable by all recipients, so typically you'd see folks run Gophish on a server - either an internal server if all their users are internal, something in a DMZ if they self-host, or on a cloud VPS.

A good way to check if the URL you're using is reaching your Gophish instance is to browse to it yourself. You should see a very generic "404 not found" error if things are working. You can find more information in our [FAQ](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

Let us know if this doesn't help!

**Comment by empty0n3** [comment]
hmm I see! So there's no way I can run a campaign with Gophish installed only on my local Kali VM?

**Comment by empty0n3** [comment]
and what about the version? I think I have the most recent one but the text file named "VERSION" that comes with it says it is version 0.7.1.
