### ISSUE TITLE
User opening the email results in status change from 'Success' back to 'Email Opened'

### ISSUE THREAD

**Issue by Jake151** [gophish/gophish#175]
As the image shows is a user opens the email multiple times it adds it into the time line but will change the status to the lesser state 'email opened', expected outcome would be to still show 'success' but to also show the 'email opened' statuses in the time line. 

![gophish](https://cloud.githubusercontent.com/assets/6080638/13325599/648ecc20-dbda-11e5-80d6-d61e5c0888e3.png)

**Comment by jordan-wright** [comment]
Thanks for the report! It looks like you're probably using the prebuilt binary. I'm happy to report that this has already been fixed in master and is slated for the next release (coming early next week at the latest!).

For now, if you build from source you'll have this fix as well as some crazy cool new features we've added.

Let me know if that works for you!

**Comment by Jake151** [comment]
Brilliant! I will build from source, thank you for such a great bit of kit

**Comment by jordan-wright** [comment]
You bet. Let me know if that doesn't fix the issue, and I'll re-open.
