### ISSUE TITLE
How are Groups and Targets Associated with Campaigns in the Database?

### ISSUE THREAD

**Issue by riab-tam** [gophish/gophish#1754]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.7.1

Brief description of the issue: Hi. We're creating and launching numerous campaigns for various target groups. As the numbers increase, we're adding indices as necessary to the gophish database tables to improve query performance for specific results. In the campaigns table, there are ID columns for the various parts of the campaign (template_id, page_id, smtp_id), which all make sense and which we have added a non-unique index to. One campaign part is the group, or group of targets, that the campaign will be run on. We would expect there to be a group_id column in the campaign table as well, but do not see such a column, nor anything obvious in the gophish database tables of how the groups are mapped to each campaign.

What are you expecting to see happen? : campaigns.group_id column in the database

What are you seeing happen? No campaigns.group_id column

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
The recipients of a campaign are in the `results` table. When a campaign is launched, we create an entry in this table for every unique member in the specified groups.

We don't do a direct mapping to the `targets` table since you can imagine the case where a campaign is launched and then sometime later the group information is updated somehow. In this case, this could cause very unexpected behavior. That's why we make copies.

You can find the code responsible for this [here](https://github.com/gophish/gophish/blob/6e20f64322480d5dd311e1186122358db4585796/models/campaign.go#L511).

I hope this helps!

**Comment by riab-tam** [comment]
Hi, Jordan. Yes, that makes sense. Thanks!
