### ISSUE TITLE
I can't start gophish

### ISSUE THREAD

**Issue by JunPham** [gophish/gophish#1760]
I use Ubuntu 19.10
I have opened the NAT port on the modem as 443
My IP is 192.168.1.7 
I signed up for SSL
But i can't start gophish. I don't have VPS.
![image](https://user-images.githubusercontent.com/42670522/75524185-fb133180-5a3f-11ea-9748-07db9300130b.png)

**Comment by jordan-wright** [comment]
There isn’t enough information in here to begin troubleshooting. Please provide the logs you see in your terminal when you try to start Gophish.

**Comment by jordan-wright** [comment]
@Cyb3r-BoT that sounds like a different issue. Please open a new issue for that, providing the data requested in the template as well as your config.json, and the directly listing (e.g. `ls -alh`) in your Gophish directly.

For now, since there haven't been any updates in a few days, I'm going to go ahead and close this one out.
