### ISSUE TITLE
Connection refused while loading the the landing page from the url

### ISSUE THREAD

**Issue by chris134pravin** [gophish/gophish#1762]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.9.0

Brief description of the issue: When I am trying to load my site I am unable to load it as I am being shown the following error "Get http://XXXXXXXXX.tech: dial tcp xxx.xxx.xxx.88:80: connect: connection refused"

What are you expecting to see happen? : I am trying to import my site as the landing page which will be co related to the 

What are you seeing happen?

![gophish error](https://user-images.githubusercontent.com/12962838/75662459-280c5200-5c95-11ea-9305-40f2abfed232.png)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Just to make sure I’m clear on what you’re trying to do- you’re saying there’s a URL that you want to import as a landing page. Otherwise, it looks like the issue is cut off after “related to the”.

In any case, the error you’re seeing suggests that Gophish is unable to reach the URL you’re providing. This particular error seems to suggest that the server at that domain name isn’t listening on port 80. I’m afraid there isn’t anything we can do in Gophish to fix this, since it’s a networking issue.

Sorry we couldn’t be of more help!

**Comment by chris134pravin** [comment]
Yes, There is a URL where I have developed a website with the login credentials for the end users. And that the server at that domain name is listening on port 80 as you can see in the below screenshot where I am able to generate the rid as per the guide

**Comment by jordan-wright** [comment]
I’m afraid I’m not quite following. In the first screenshot, you showed that you were trying to import a landing page, but in this screenshot you’re suggesting that the domain points to Gophish.

Im not sure where the miscommunication is happening, but here’s some info that might help:

In order to capture events, the URL you use in a campaign must point to your Gophish instance. So, if you want a landing page, then Gophish has to host it.

This is where “Landing Pages” come in. Ideally, you would take whatever HTML you want to display to the user and add it as a landing page. Some folks have websites they want to copy into Gophish which is where the import function comes in. All this does (in a nutshell) is make a request to the given URL and copy the HTML into the modal window so it can be saved.

In your case, you also mention that you’re generating an rid. To be clear, you should never need to generate an rid yourself. Gophish does this automatically when it sends out campaign emails.

Let me know if you have any other questions based on this! It seems there’s a possible miscommunication, I just can’t tell where.

**Comment by chris134pravin** [comment]
Okay, let me explain it clearly 
1. Gophish is installed on docker on a cloud server. 
2. Gophish and the website that was created by me with the login portal are both hosted in the same server with different port numbers. 
3. When I run a Campaign by following the step given in the user guide everything works fine but on the landing page section, I am unable to load my webpage as per the guide this is where I get my first error.

Issue 1
 
![gophish error](https://user-images.githubusercontent.com/12962838/75743841-6b6bcc80-5d38-11ea-9c6b-ecfd52c0d6d8.png)

But as per your previous reply "the error you’re seeing suggests that Gophish is unable to reach the URL you’re providing. This particular error seems to suggest that the server at that domain name isn’t listening on port 80. I’m afraid there isn’t anything we can do in Gophish to fix this since it’s a networking issue."  I checked on this as well and the server at that domain name is listening on port 80, This is the part where I really cannot understand why gophish is unable to copy the site into gophish.

4. When I run a campaign as per the steps given by the guide and ensure that all the steps are followed i am still unable to receive any details on the statics.

Issue 2

I did go through the FAQ and the Guide and followed the step as procedures but yet I don't receive any static of the campaign that Iran. Further, I have attached the screenshots. This is where I don't understand why I am not receiving any statics because everything I step that I have done is as per the guide and also " It should be the URL you used when creating the campaign with a unique rid parameter. So, it should look like this: http://your_url/?rid=XXXXX. " I am able to see the unique rid generated by gophish as per the screenshot

![Capture](https://user-images.githubusercontent.com/12962838/75745345-0e264a00-5d3d-11ea-89f2-f3fa58afc32b.JPG)
But yet I am unable to receive any kind of statistics even after following the guide I even tried rebuilding the gophish container yet it's the same.

**Comment by jordan-wright** [comment]
I'm afraid it's still not clear what's going on here. It seems like there are two issues: not being able to import the landing page, and not seeing any statistics. In the future, please keep issues on GitHub limited to a single issue you're having so that we can track it better.

> When I run a Campaign by following the step given in the user guide everything works fine but on the landing page section, I am unable to load my webpage as per the guide this is where I get my first error.

This error means that Gophish (wherever it's hosted) isn't able to reach the URL you're providing (wherever it's hosted). This is 100% a networking problem and not something I can help with. You need to make sure that the Gophish container is able to reach whatever domain is redacted in that error message.

> I checked on this as well and the server at that domain name is listening on port 80

Maybe you can reach it, but you need to ensure that the Gophish container can reach it.

> Further, I have attached the screenshots

I only see a screenshot of your URL bar, which doesn't give me enough information to troubleshoot. Is that `rid` generated by Gophish, or by you? What do you see on that page? Do you see your landing page, as expected? What URL did you use when building the campaign? Have you confirmed it's reachable?

I need a lot more information before I can effectively troubleshoot. Please walk through your process step-by-step so that I can try to reproduce the issue.

**Comment by chris134pravin** [comment]
>In the future, please keep issues on GitHub limited to a single issue you're having so that we can track it better.
I completely understand therefore let's just stick to the 2nd issue in regards to the Statistics not being displayed on the dashboard.

> Is that rid generated by Gophish, or by you?
The rid i is generated by gophish
>What do you see on that page?
I am able to see the website login page developed by me (ScreenShot Below)
![gophish error](https://user-images.githubusercontent.com/12962838/75850080-68daa700-5e0c-11ea-9567-47982e011fe7.png)
>What URL did you use when building the campaign?
The URL used during the campaign is a purchased domain. where gophish is using the purchased URL to be accessed through port 3333 and the login page is using the same Domain on port 80. 
(Screenshot Below)
![gophish error 1](https://user-images.githubusercontent.com/12962838/75851201-0cc55200-5e0f-11ea-882d-48a920e18f50.png)
![gophish error 2](https://user-images.githubusercontent.com/12962838/75851200-0cc55200-5e0f-11ea-959a-843ad18b7215.png)
>Have you confirmed it's reachable?
Yes, I confirmed that it is reachable.

**Comment by TheGroundZero** [comment]
I've noticed I can't import certain sites in GoPhish (e.g. MS login page of my organisation).  
I believe the server is preventing you from visiting the site, it's probably blocking the "client" of gophish, which I assume is cURL?  

One of the hobby sites I'm hosting on a simple webhost will allow me to visit a custom page with my browser, but blocks any automated attempt (wget, cURL).
