### ISSUE TITLE
Super admin managment suggestion

### ISSUE THREAD

**Issue by edrojas69** [gophish/gophish#1801]
What version of Gophish are you using?: 
v0.9.0

Issue:

I have two admin users and one user with basic privileges, who are sending different phishing campaigns.

Is there a way to see all the campaigns that are sending  with a single administrator user?
...

An alternative would be to create a portal attached to gophish that consults the database to be able to view the other campaigns, this is totally impractical.

**Comment by jordan-wright** [comment]
Hi there!

Currently this is not possible. I would like to expand on our RBAC controls to support more advanced use cases in the future, but I admittedly don’t see myself having time to do this anytime soon.

Since there isn’t any immediate action I can take on this, I’m going to go ahead and close this one out.

Thanks for getting in touch!
