### ISSUE TITLE
Feature Request: Prefix URL for backend behind reverse-proxy

### ISSUE THREAD

**Issue by blacksph3re** [gophish/gophish#1804]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.9.0

Brief description of the issue: 
I want to access the backend through a reverse proxy at example.com/phishing. This would help me reusing the machine I run gophish on, and adding a couple of other services to it. Also I can use the more sophisticated IP filtering/routing/authentication options of the reverse proxy.

What are you expecting to see happen? :
Two options: Gophish either

* offers a configuration option to set a prefix path to all links, assets and api requests
* only uses relative links, i.e. src="images instead of src="/images

What are you seeing happen?
When visiting the backend, it does a redirect to example.com/login, that request does not reach gophish and is routed somewhere else by the reverse proxy. When I manually type example.com/login (or rewrite that redirect in the reverse proxy), it fails loading all assets, because they are not prefixed.  When I set the reverse proxy to not strip the /phishing part, it will create a 404.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Set up a reverse proxy of your choice, e.g. nginx:
```
location /phishing/ {
    proxy_pass http://some-ip:3333/;
}
```
 * Step 2 - Visit the site - example.com/phishing, redirect to example.com/login
 * Step 3 - Visit the site example.com/phishing/login - broken assets

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out! I’m always hesitant to add any new configuration unless it pertains to the core value of Gophish. Since this would only help a very small subset of users, I don’t anticipate adding this configuration at this time.

And using absolute paths for assets makes development much easier, so I don’t plan on changing that up to support this custom use case.

Perhaps there are path rewriting directives you can use on your proxy to help get this working as expected.

Thanks again for getting in touch!
