### ISSUE TITLE
Question - Creating Campaign

### ISSUE THREAD

**Issue by Hemza** [gophish/gophish#181]
Hi gophish community , i've install go phish on windows , i've insert all the needed parameters, but it doesnt work error in sending emails, is there specifique config or ports to be opened...?? please provid us with the best preconfig  for windows

**Comment by Hemza** [comment]
is there an option for tranking credentials insert

**Comment by jordan-wright** [comment]
Hi @Hemza, it looks like you have two questions here. First, I'm afraid there is no default or "best preconfig" for Windows - it all depends on your setup. You'll need to know what MTA to use for relaying your emails before you can use gophish.

Are you receiving errors? If so, what do they say? What configuration options can you share with us so that we can better troubleshoot?

Also, what do you mean "tranking credentials insert"? If you mean tracking credentials that are inserted into the landing page form then yes, this is possible in the next release (or now if you build from source).

Hope this helps!

**Comment by jordan-wright** [comment]
Hi @Hemza - just checking in.. did the comment above answer your questions?

**Comment by Hemza** [comment]
hi jordan , i want to say tracking credentials that are inserted into the
landing page form ( only 3  caracters)

2016-03-02 15:45 GMT+01:00 Jordan Wright <notifications@github.com>:

**Comment by jordan-wright** [comment]
So you're asking if there's a way to capture credentials submitted by people who clicked the phishing link. Yes, you can, but it's coming in the next release which will be released here in a day or so after we finish everything up.

**Comment by jordan-wright** [comment]
Hi @Hemza, I'm going to close this for now since it looks like we've answered your questions. Please don't hesitate to open another issue if you have other questions come up.

Thanks!
