### ISSUE TITLE
Not able to get listener working on VPS

### ISSUE THREAD

**Issue by nickdtong** [gophish/gophish#1821]
Building off of ticket #1814

In the config, I notice that the admin panel is located at 127.0.0.1:3333
That doesn't have any effect on the listener, correct? 

Because while I'm not able to access the listening page, I'm able to access the admin console.

**Comment by jordan-wright** [comment]
The value in the config determines which interfaces Gophish binds to. For example, specifying `127.0.0.1:3333` says to only listen on localhost on TCP port 3333. Setting this to 0.0.0.0:3333, for example, says to bind on all interfaces (making it externally reachable) on port 3333.

My guess is that your phish_server is set to 0.0.0.0:80 (or :443) and Gophish isn't able to bind to those ports since they're privileged. This is the reasoning behind #1814.

**Comment by f3rrgalex** [comment]
Just add https:// before your url

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn’t been any updates in 10 days.
