### ISSUE TITLE
Import Site With Static Asset 404 Page Not Found

### ISSUE THREAD

**Issue by zoben10** [gophish/gophish#1825]
Version:  **2020-01-16-000000**

Issue: **Hello, I'm having a issue to import a site with the static assets. I did everything on the documentation, but it doesn't seems to work.**

Expectation:  **I'm expecting to see my site imported correctly.**

Results: **404 page not found**

_______________________________________________________________________________________________________

**Here is my file named (MySite_files) located in directory static**

![image](https://user-images.githubusercontent.com/61861342/80531004-e1bb3280-8967-11ea-9eb3-2f8320323a27.png)

_______________________________________________________________________________________________________

**Here is the URL of my phishing server. P.S: I also tried putting my VPS IP, it still doesn't work.**

![image](https://user-images.githubusercontent.com/61861342/80531017-e7b11380-8967-11ea-8abd-4eb54b4a2ff1.png)

_______________________________________________________________________________________________________

**Here is the output I get.**

![image](https://user-images.githubusercontent.com/61861342/80531028-eed82180-8967-11ea-9845-2d5ec80c9b15.png)

**Comment by jordan-wright** [comment]
Ok, so there's a quite a bit here.

1) Gophish doesn't automatically import static files. It just imports the HTML and add a `<base>` tag to have relative assets loaded from the original page. If you want to import static assets into Gophish, you need to download them manually and update links. You can find more information in our documentation [here](https://docs.getgophish.com/user-guide/documentation/landing-pages#static-assets).

2) Let's say that you have your static assets hosted somewhere else. In this case, you're importing the site using the IP address `0.0.0.0`. This would load for _you_ but not for anyone else, since 0.0.0.0 would have the recipient try to load assets from their local machine and that won't work. The site import feature of Gophish is typically expected to be used to import a site that anyone can reach.

I hope this helps! Thanks for getting in touch!
