### ISSUE TITLE
Sending mails has been delaying for one day and also  Application is Automatically closing

### ISSUE THREAD

**Issue by sreekanth99850** [gophish/gophish#1827]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
9.0
Brief description of the issue: 

1. Sending mails has been delaying for one day and also  Application is Automatically closing.
2.Sometimes i Can't able to create groups 
3.My application is taking is so much time for loading the page

Daily I'm sending mails to 2k users and I have around 50+ templates.

I want to know is there any limit for sending the mails and also for creating the email templates.

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi there!

For future reference, if possible let's keep issues to a single problem with Gophish so that we can track things accordingly. For now:

1. I'm not sure what you mean by "Sending mails has been delaying for one day". Did you schedule a campaign to be launched in the future, or did you have it launch immediately? If you're in general seeing campaigns be slow to send, then some of the improvements we recently made should resolve this.

Also, when you say that Gophish is closing, is this happening because of an error that you can see in the logs?

2. Without more information about what you're seeing when you try to create a group, there isn't anything I can do to help out.

3. This is a known issue. When you have large campaigns, it can be a bit slow to load the dashboard. For large campaigns, I generally encourage folks to work with the API or the database directly.

**Comment by sreekanth99850** [comment]
Hi jordan,

Thanks for your reply.

1. I'm  scheduling Campaigns immediately but it was taking more time for sending the mails.
2. I tried to create groups by using CSV file.After selecting the CSV file data is not loaded.

Daily I'm sending mails to 2k users and I have around 50+ templates.
Can you please tell me is there any limit for sending the mails daily.So that I can proceed.

**Comment by jordan-wright** [comment]
There is no limit in Gophish for sending emails though there are performance issues in the release version (fixed in the master branch) that make sending large amounts of emails slow.

Without a sample CSV file, Python code, and the associated errors, I’m afraid I can’t do anything to help here.

**Comment by sreekanth99850** [comment]
Thanks for your reply

I got a solution . My Application is overloaded . So that's why many things are not working properly
I deleted old campaigns Now It's working fine.

**Comment by aukhan288** [comment]
I want delay for 30s after each email.
Anyone can tell Wich file is sending emails as a crone jobe. What I should do for it.
Thanks
