### ISSUE TITLE
GoPhish, Windows 2012(Cloud) and DNS Settings

### ISSUE THREAD

**Issue by Daphnedescends** [gophish/gophish#1833]
What version of Gophish are you using?: 9.0

(just before you read, i'm still fairly new with server config, but i'm able to do most things with decent guides..).

I want to use GoPhish for enterprise phishing campaigns on staff (legitimate and requested by the companies, I will add).

**Does anyone have a step-by-step guide to configuring  Virtual Windows 2012 for GoPhish  via Vultr/cloud based server, and making sure the DNS settings point to the correct place.**

I've been at this for 2 days and no guide ever produces what you need from start to finish.

- GoPhish itself is working on localhost:3333..bla bla and log in and template config is possible.
- 1. SMTP is setup on my server, already. This I know. But can't find a decent guide to check what should be there.
- 2. I can't get GoPhish to send emails (haha not port 25 before you start, i know vultr block this) via port 587.
- 3. My MX records are correct as far as I can see. (via GoDaddy..yeah, I know)

When I used a **gmail** account, obviously it works perfectly. But I don't have an 'E-Mail client' set up on win 2012, do I need it? I thought GoPhish would be the 'email client'? What's recommended? 

Even when Gmail worked, I still couldn't get any responses on the campaign after I opened multiple emails.

I'm sure i'm missing something simple, but i'm losing my mind here...TBH any assistance is welcome, even if it's "no, do it this way - linux/AWS instead" Anything!

**Comment by jordan-wright** [comment]
Hi there!

You can find community blog posts in our documentation [here](https://docs.getgophish.com/user-guide/additional-references). I don't know that any of them are Windows-based.

I don't have any specific windows server experience with Gophish so I'm afraid I can't be of more help. Since this has been open for more than a week, I'm going to go ahead and close it out. You might give a Linux distribution a shot since it seems there are more folks in the community taking that approach and documenting their process.
