### ISSUE TITLE
Error Max connection attempts exceeded - 454 4.7.0 Too many login attempts, please try again later. o6sm14466556pfp.172 - gsmtp

### ISSUE THREAD

**Issue by security-prince** [gophish/gophish#1836]
**What version of Gophish are you using?:** 
gophish v0.9.0 with Gmail SMTP

**Brief description of the issue:** 
I am having a similar error to #963 on my end, in my case, I am using gophish v0.9.0 and  Gmail SMTP to send out emails, for me, I tried sending out the emails to over 600 users at once but after 78 success I started getting this error `Error Max connection attempts exceeded - 454 4.7.0 Too many login attempts, please try again later. o6sm14466556pfp.172 - gsmtp`, what I am wondering is does gophish tries and logs in to Gmail SMTP for sending each email? if yes maybe this is what is causing this error. As for logs, I checked the error log for gophish I am seeing this error in it `2020/05/13 12:22:36 http: TLS handshake error from <IP>: remote error: tls: unknown certificate`

**Comment by jordan-wright** [comment]
Gophish doesn't authenticate on every SMTP connection (at least, it shouldn't 😉) We [establish a connection](https://github.com/gophish/gophish/blob/master/mailer/mailer.go#L141) and authenticate, then we [send the emails](https://github.com/gophish/gophish/blob/master/mailer/mailer.go#L163) using that connection.

I'm afraid without more information (that may be hard to get, since it would include dropping some debug logs into Gophish and building from source) it'll be really hard for us to track down what's causing this.

**Comment by jordan-wright** [comment]
Closing this as there have been no updates in over 2 weeks.
