### ISSUE TITLE
QR Codes

### ISSUE THREAD

**Issue by dryahweh** [gophish/gophish#1843]
Hi Jordan!

Thanks for all the effort you put into GoPhish! I have a question related to using QR Codes with GoPhish.

Some of my clients are asking if we can use QR Codes instead of URLs. We have tried using Dynamic QR Codes to register victims scanning the code, yet the result does not provide me the email that scans nor the IP (although the IP is not as important as the email). Normally GoPhish autogenerates a link with an RID to track the target who clicked the link.

Is there a way of using a QR to replace the URL in this scenario? This would result in the event being picked up by the GoPhish listener without the user clicking, but scanning.

Thanks in advance for the help!

**Comment by S0larflare** [comment]
I can’t see any particular issue. On the face of it I think it would be pretty simple, just use something like this:

https://github.com/skip2/go-qrcode/blob/master/README.md

And instead of including the URL include the generated qrcode. I’m not sure how widely used it would be, but I think it would be a reasonably simple addition to GoPhish

Sent from my iPhone

On 21 May 2020, at 16:16, dryahweh <notifications@github.com> wrote:

﻿

Hi Jordan!

Thanks for all the effort you put into GoPhish! I have a question related to using QR Codes with GoPhish.

Some of my clients are asking if we can use QR Codes instead of URLs. We have tried using Dynamic QR Codes to register victims scanning the code, yet the result does not provide me the email that scans nor the IP (although the IP is not as important as the email). Normally GoPhish autogenerates a link with an RID to track the target who clicked the link.

Is there a way of using a QR to replace the URL in this scenario? This would result in the event being picked up by the GoPhish listener without the user clicking, but scanning.

Thanks in advance for the help!

**Comment by glennzw** [comment]
Agreed with S0larflare. You could:

 * Create a campaign, in your emails insert an image with src `http://<youserver>/qr/{{.rid}}.jpg`
 * API into the campaign grabbing all the URLs
 * Foreach email use the QR library above to create `{{.rid}}.jpg`
 * Copy all the generated QR images into your server's webroot

Only small snag is some email clients may not display remote images. Alternative plan is to use the API to insert campaign emails with base64 embedded QR images.

**Comment by jordan-wright** [comment]
Thanks for reaching out! There's no way to generate QR codes in Gophish emails right now. More manual approaches like the one @glennzw suggested work. If you were wanting to generate the QR code in a landing page, it'd be different since you could use a Javascript library [this one.](https://davidshimjs.github.io/qrcodejs/)

> I’m not sure how widely used it would be, but I think it would be a reasonably simple addition to GoPhish

I agree that it would (hopefully!) not be a huge amount of work, but I also agree that it wouldn't be used very widely. With that in mind, I'm not in a place where I'd be willing to add this to Gophish at this time.

Thanks again for getting in touch!

**Comment by dryahweh** [comment]
Hi @glennzw @jordan-wright @S0larflare, thanks for the tips!

I tried following your tips but unfortunately I'm stuck. I understand GoPhish creates the RID once the campaign is launched and not before. This means I need to use the result from the generateID function right after the campaign is blasted so the RID encoded in the QR and the RID for the specific email match.

Do the steps above mean that I would be able to get the RId result from the generateID function for each email, and generate the QR containing the phishing URL + RID?

**Comment by glennzw** [comment]
I've been giving this some thought, and there's actually a much easier solution that doesn't require us to touch Gophish, and requires no pre-campaign work from us. We just need an endpoint that dynamically creates a QR code from a supplied URL, and we load an image in our Gophish email template with this.

To that end I went ahead and built a solution:

`https://kyouar.herokuapp.com/`

e.g. you can supply a URL and a QR image is returned. Here's one for Google:

`https://kyouar.herokuapp.com/u/www.google.com`

So, in our Gophish email templates all we need to do is:

```
Please scan the QR code below to win a brand new piece of string:

<img src="https://kyouar.herokuapp.com/u/{{.URL}}">
```

I tested this with a Dropbox campaign, works beautifully:

![QR2](https://user-images.githubusercontent.com/3966613/83038443-dde90180-a034-11ea-9f1e-18c07fc98656.png)

**Comment by dryahweh** [comment]
Hi @glennzw! Thanks for the help!

Our team also came up with a php script hosted in our webserver that uses [https://sourceforge.net/projects/phpqrcode/](phpqrcode library) and modified it to create the QR as base64. We still have the issue of the email client blocking our images though.

**Comment by glennzw** [comment]
Yeah inserting the images is going to be harder - I'd need to spend a bunch more time to figure that out, but seems you're on the right path. Let us know how you get on. 

If I get some free cycles I'll have another crack at it.

**Comment by edermi** [comment]
@glennzw Is the source code of your QR code generator publicly available?

**Comment by glennzw** [comment]
@edermi Ah whoops forgot to link to it. Here you go:

Source: https://github.com/glennzw/kyouar
Deployed: https://kyouar.herokuapp.com/

I also just added the option to return a base64 encoded version of the QR, suitable for use in an img tag. e.g:

```
curl https://kyouar.herokuapp.com/b/www.google.com/ 

data:image/png;base64, iVBORw0KGgoAAAANSUhEU...
```

**Comment by aZaz31** [comment]
Just enter this code in the email and Voila: <img src=https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl={{.URL}}>

**Comment by vanosg** [comment]
Just a general comment, I've seen a few issues mentioning QR codes since 2020 and generally were dismissed due to uncertainty of their use or implementation (here as well as #2897  #2377 #2809 etc). I think that in 2020 the use case was less prevalent, but I also think the phishing landscape has changed since then and maybe it's time to look at integrating the use of QR codes in GoPhish again?  @jordan-wright  @glennzw  while I can't provide much in the way of code, I'd love to help figure out how to properly document the demand signal for something and push for this to be added as a new feature. Much appreciated for any second-look you can offer at this topic!

**Comment by fin3ss3g0d** [comment]
This is a feature built into a modified version of gophish, [evilgophish](https://github.com/fin3ss3g0d/evilgophish) 

[Quishing blog](https://fin3ss3g0d.net/index.php/2024/02/24/qr-code-phishing-with-evilgophish/)

**Comment by Janberkb** [comment]
Leaving a pointer here since this thread has historical context:

I’ve opened PR #9411 for native `{{.QR}}` template support, and I added the fuller implementation/context note in #3346 so the discussion can stay in one place.

Happy to adjust the approach based on maintainer feedback.
