### ISSUE TITLE
Can't reach listener URL from phishing email

### ISSUE THREAD

**Issue by guillelle** [gophish/gophish#1847]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.9.0

Brief description of the issue: 
I can't reach the landing page from the received phising email. I've tried localhost, https://localhost:3333, http://192.168.1.1, also a public cloud server. I Always get conn_refused or conn_timeout or 404. 
The landing path is created correctly as localhost/?rid=xxxxxxx or 192.168.1.1/?rid=xxxxxx or whataver/?rid=xxxxxxxx

What are you expecting to see happen? :
I expect to see the landing page 

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - create template with {{.URL}} tags
 * Step 2 - create landing with google account
 * Step 3 - launch campaign with localhost as url listener

**Comment by jordan-wright** [comment]
The phishing server is likely not running on port 3333. Rather, it's likely running on port 80 (the default) or 443 if you enabled TLS.

When setting up a campaign, it's important to set the URL to point to the phishing server. So if you're putting localhost:3333, that won't work since it's the admin server. Instead, you should use the publicly available IP address of your server with the port (probably 80 or 443) specified in your config.json.

You can find more information in our user guide [here](https://docs.getgophish.com/user-guide/building-your-first-campaign/launching-the-campaign) and [here](https://docs.getgophish.com/user-guide/documentation/campaigns).

We even have a section in our FAQ dedicated to this problem which you can find [here](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard).

I hope this helps!
