### ISSUE TITLE
recent docker commit changed default password? 

### ISSUE THREAD

**Issue by littlejob** [gophish/gophish#1876]
**What version of Gophish are you using?:** latest

**Brief description of the issue:** newest docker image will not accept default username and password 

**What are you expecting to see happen? :** admin:gophish should work (tested prior gophish:gophish as well)

**What are you seeing happen?:** invalid credentials error on fresh build. using native DB 

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - im fronting this instance behind a reverse proxy (nginx) - auth page is accessible
 * Step 2 - docker run -dit --ip 172.17.0.2 -p 3333:3333 --name gophish_prod gophish/gophish
 * Step 3 - browse to admin page - try logging in with default credentials admin:gophish

**Comment by glennzw** [comment]
If you're using the latest build the default credentials have been randomised: https://github.com/gophish/gophish/pull/1867

`Removes the default password (gophish) for admin users to instead have the password randomly generated when Gophish first starts up`

**Comment by littlejob** [comment]
> If you're using the latest build the default credentials have been randomised: #1867
> 
> `Removes the default password (gophish) for admin users to instead have the password randomly generated when Gophish first starts up`

Am I missing the documentation on where this password is displayed/found? I appreciate your prior quick response.

**Comment by littlejob** [comment]
> > If you're using the latest build the default credentials have been randomised: #1867
> > `Removes the default password (gophish) for admin users to instead have the password randomly generated when Gophish first starts up`
> 
> Am I missing the documentation on where this password is displayed/found? I appreciate your prior quick response.

found it...
`docker logs gophish_prod`
`Please login with the username admin and the password ####`

**Comment by jordan-wright** [comment]
You didn't miss any documentation. This is a brand new change and I haven't had time to write the docs for it. I typically try to have documentation (fairly) up-to-date at time of release.

In the meantime, I can see the value of being able to set the initial admin password during automated deployment scenarios. To solve that problem, in bf76f86 I've added the ability to set a `GOPHISH_INITIAL_PASSWORD` environment variable which will set the password rather than having it be randomly generated. It's worth noting this is only for setting the *initial* admin password.

Thanks for getting in touch!
