### ISSUE TITLE
Discussion regarding campaign automatic refresh rates and possible timestamp entry

### ISSUE THREAD

**Issue by kpomeroy1979** [gophish/gophish#1878]
Hi guys,

When we perform phishing tests for clients and the goal is to bypass MFA and gain access externally we are often looking at the campaign results in real time, waiting for the status to change to red / Submitted Data. We sort the status of a running campaign by Status so that the red Submitted Data entries appear at the top. Is there a way to modify the refresh rate so that we don't' have to manually refresh? 

Also, when we sort by Submitted Data, is there a way for GoPhish to show a time stamp on when the user submitted the data. I'm not 100% correct on this, but during a recent campaign we had so many users Submit data that we lost track of the most recent person because the sorting did not APPEAR to have the most recent user who submitted data at the top of the list. 

Hope that makes sense.

![image](https://user-images.githubusercontent.com/33209502/85767480-492a0000-b6d5-11ea-9009-fbca3e285a8b.png)

**Comment by S0larflare** [comment]
If I’m getting your use case right, the easiest way to get this would be from the console/log. If you tail the output and grep for ‘Submitted’ you’ll get the details along with a time stamp

Sent from my iPhone

On 25 Jun 2020, at 18:17, K. Pomeroy <notifications@github.com> wrote:

﻿

Hi guys,

When we perform phishing tests for clients and the goal is to bypass MFA and gain access externally we are often looking at the campaign results in real time, waiting for the status to change to red / Submitted Data. We sort the status of a running campaign by Status so that the red Submitted Data entries appear at the top. Is there a way to modify the refresh rate so that we don't' have to manually refresh?

Also, when we sort by Submitted Data, is there a way for GoPhish to show a time stamp on when the user submitted the data. I'm not 100% correct on this, but during a recent campaign we had so many users Submit data that we lost track of the most recent person because the sorting did not APPEAR to have the most recent user who submitted data at the top of the list.

Hope that makes sense.

[image]<https://user-images.githubusercontent.com/33209502/85767480-492a0000-b6d5-11ea-9009-fbca3e285a8b.png>

**Comment by kpomeroy1979** [comment]
Good idea. I checked the log file but I don't see much to grep on to filter
out on Submitted data. Is there a way to change the log file level to
something more verbose? Right now it's level=info.
I think you're on the right track though. When the user submits data, there
is a POST entry in the log file along with the identifying RID=XXXXXX so I
can grep for Post but in testing it seems like GoPhish refreshed the page
pretty quickly.

In a perfect world I'd like to see a timestamp alongside the Submitted Data
field so we know we are sorting by the most recent submitted data but I may
be able to work with this.

**Comment by kpomeroy1979** [comment]
I think I found it.

https://github.com/gophish/gophish/issues/1631

    "logging": {
                "filename": "",
                "level": "debug"
        }

**Comment by kpomeroy1979** [comment]
False alarm. That does not work. GoPhish does not start when I add the
"level" entry to the config file.

**Comment by glennzw** [comment]
@kpomeroy1979 I wrote up a quick solution for you. You can paste the following code into your console and it'll query for submitted data for the campaign, and sort by most recent event first. e.g output:

<img width="650" alt="Screenshot 2020-11-03 at 19 17 17" src="https://user-images.githubusercontent.com/3966613/98024887-42d92c80-1e09-11eb-8223-52f8efb7e6db.png">


```
function checkSubmitted(id) {
    resultsL = []
    api.campaignId.results(id)
        .success(function (campaign) {
            $.each(campaign.results, function (j, result) {
                if (result.status == "Submitted Data"){
                    resultsL.push(result)
                }
            })
        }).then(function(){
            resultsL.sort((a, b) => (a.modified_date < b.modified_date) ? 1 : -1) // Sort by 
            $.each(resultsL, function(index, r) {
                console.log(r.email + " submitted data at " + moment(r.modified_date).format('MMMM Do YYYY, h:mm:ss a'))
            });
        }) 
}

(function(){
    console.clear()
    checkSubmitted(campaign.id) // Or set whatever campaign id you want
    setTimeout(arguments.callee, 5000);
})();
```

**Comment by glennzw** [comment]
Also, this feels like a good use case for the new webhooks feature. You could even send an alert to an SMS provider or something so you can be on your toes to grab that MFA token.

**Comment by kpomeroy1979** [comment]
Hey man,

I am sorry I forgot to reply and thank you for this. This is exactly what I
was looking for. MUCH APPRECIATED!. Very cool of you to do that.

**Comment by glennzw** [comment]
No worries, glad it worked for you and thanks for the reply!
