### ISSUE TITLE
Feature Discussion - Naming of "Email Opened"

### ISSUE THREAD

**Issue by scottg88** [gophish/gophish#188]
Most browsers (definitely Outlook) block images by default from non-"trusted" emails.
The tracking image is therefore blocked by default. It's a great feature to track whether the image is accessed or not, however I think the naming in the campaign results of "Email Opened" conveys a misleading idea.

For example a couple of scenarios:

1:
User opens email, does not click the phishing URL and either ignores or deletes the email. (user is not phished)

2:
User opens email, does not recognise the email as dodgy looking, clicks Download Pictures or equivalent. (user is "phished" successfully regardless of whether they click the URL or not, as there could potentially be attack vectors via images, or at the very least verifies for the sender that the email address is legit)

In these cases it would be clearer to say something other than "Email Opened" for scenario 2, as technically the user opens the email in scenario 1 but has been trained successfully to identify and ignore a phishing email.

"Images Downloaded" or something similar could work. What are others opinions?

**Comment by jordan-wright** [comment]
Hey @scottg88 - thanks for this!

I'm always happy to discuss ways that gophish can be more clear in its reporting. I'm definitely open to other suggestions on the status naming, and I hope we get some good ones. For now, let me at least mention why I picked "Email Opened" in the first place. :smile: 

There is only so much gophish is technically able to see in terms of if an email is opened. Tracking images are the most common (and probably one of the only) ways to tell if an email is opened - you'll find this a lot in the marketing business where they use it a ton. This is also where the initial status of "Email Opened" came from, since it's what they use.

Unfortunately (or fortunately, depending on your use case), mail clients caught on that it's a privacy concern, which is why they have a tendency to block these by default.

The reason I picked "Email Opened" in this case is two-fold:

* It's true - While it won't catch *everyone* opening the email (as you mentioned for those who don't download pictures), it's not incorrect to say that everyone who downloaded the tracking image did indeed open the email.

* It's easy to understand - I'm trying to design gophish in such a way that it's the easiest to understand for the majority of people using it. I originally determined that "Email Opened" would likely be an easier metric to understand than "Tracking Image Downloaded", which might only introduce other questions.

Now, let's talk about the other case - where the user *doesn't* download the tracking image. In this scenario, if the user doesn't click the link (deletes it or doesn't touch it), there is no way for gophish to know what happened. We can't definitively say the user deleted the email, since it could have simply been caught by a spam filter. This is why I leave the status "Email Sent".

I hope this gives a bit of insight to where these terms came from! Again, gophish is meant to be the best tool possible, which means it needs to be useful. I'm always open to suggestions like these, and I'm looking forward to seeing what people come up with!

Thanks again for the report!

**Comment by scottg88** [comment]
Thanks @jordan-wright for the response.

I can see the reasoning behind it and already plan to include clarification in reports I generate from the data results export.

I wonder if there is instead an opportunity for an on-hover tool tip in the "Details" section of the campaign results (where a recipient's results is expanded out to show events), e.g.:

"Email Sent": Email delivered, email either unopened or recipient blocking images
"Email Opened": Recipient loaded tracking email, email confirmed opened

Thanks for developing the tool!

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. We'll stick with "Email Opened" unless we see something else come up later.

Thanks for bringing this up for discussion!
