### ISSUE TITLE
Issue : Missing logo, background and images custom Landing Pages

### ISSUE THREAD

**Issue by zoben10** [gophish/gophish#1880]
Using the Latest version!
 
  Issue to upload landing page. I copied my Phish-Site_files and Phish-Site.html into /static folder.  When I try to clone the page on GoPhish, the data on Phish-Site_files are not appearing on my landing page, see Image 2 below.

  I'm expecting to see my landing page fully clone like the original site.

![2020-06-27 17_40_15-VirtualBoxVM](https://user-images.githubusercontent.com/61861342/85955772-112df180-b94f-11ea-834a-8b83c8e7ca56.png)

![2020-06-27 17_41_46-VirtualBoxVM](https://user-images.githubusercontent.com/61861342/85955774-14c17880-b94f-11ea-90c8-07566191fdde.png)

 * Step 1 - Visit the login form of targeted website
 * Step 2 - Right-click and press Save As ---> Save File as Phish-Site and File type as "Web Page, complete"
 * Step 2.1 - Saving the file above creates two files : Phish-Site_file and Phish-Site.html
 * Step 3 - Move the file Phish-Site_file to /gophish/static/
 * Step 4 - Copy HTML code of Phish-Site.html
 * Step 5 - Paste HTML code of Phish-Site.html on Go Phish -> Landing Page -> Paste HTML

**Comment by glennzw** [comment]
I'm guessing you want to rename `Phish-Site.html ` to `index.html`

**Comment by zoben10** [comment]
@glennzw thanks for your help

I am using GoPhish, it's not necessary doing that...? Why am I getting this error ? 



![GoP](https://user-images.githubusercontent.com/61861342/86049703-9d5c1980-ba20-11ea-9d8c-5d9350db5a0c.png)

**Comment by glennzw** [comment]
To be honest I've never used the website cloner. But the site you're cloning needs to be browsable - if the file isn't called index.html it won't default to load the page, but give the directory listing like in your screenshot.

The error you're getting looks like a unicode issue - that's the code point for a [double quote](https://www.fileformat.info/info/unicode/char/0022/index.htm). I'm not sure why you'd be getting that, I'd have thought Gophish handles unicode in templates, but maybe not.

**Comment by jordan-wright** [comment]
Hi there!

So Gophish doesn't really work the way you're describing. If you have a full mirror of a website that you want to add to Gophish, you would need to:

* Move the static assets (JS, CSS, images) into `/static/endpoint`
* Paste in the index.html into the landing page editor (note: you'll probably want to paste as unformatted text, and you might try to remove any kind of smart-quotes, etc.)
* Modify all the links to static assets to be off `/static/<your path>` so that they hit the Gophish server.

The easier way to do this is to just use the "Import Site" button and paste in the URL of your site.

I hope this helps!
