### ISSUE TITLE
I can't use the submit button feature

### ISSUE THREAD

**Issue by dfmcaldeira** [gophish/gophish#1905]
What version of Gophish are you using?: gophish-v0.10.1-windows-64bit\db\db_sqlite3

Brief description of the issue: I created a button to submit the data and continue to another page but it's not working

`<div class="kGBvlU"><button class="hlZUfM ctnSzd" id="login-submit" spacing="default" type="submit"><span style="align-self: center; display: inline-flex; flex-wrap: nowrap; max-width: 100%; position: relative; width: 100%; justify-content: center;"><span style="align-items: center; align-self: center; flex: 1 1 auto; margin: 0px 4px; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; transition: opacity 0.3s ease 0s; opacity: 1;"><span>Continue</span> </span> </span></button></div>`

 When I try to submit the data nothing happens

Can someone help me?

**Comment by addagrm** [comment]
You need to put your form inside <form> tags

**Comment by jordan-wright** [comment]
Yep! @addagrm is correct.

At a high-level, Gophish expects a POST request made in order to collect data. How to create an HTML form that sends a POST request is outside the scope of our support since there are ample HTML tutorials and references in other places that are better suited than what we can offer 😄
