### ISSUE TITLE
hosting landing page in seprated web server 

### ISSUE THREAD

**Issue by omarix** [gophish/gophish#1913]
Hi, 

Please I would to know if there's a possibility to host a landing page in a separated web server in order to hide link with a domain name that can trick the user, and when the user click on the link a page querying  the listener for accounting and reporting purpose ? in case this feature is not available, I strongly hope to be registered in your roadmap 

Thanks advance for your support 

Regards.

**Comment by jordan-wright** [comment]
You'd have to parse the `rid` parameter and then send the appropriate AJAX requests upstream to Gophish to mimic the user hitting the Gophish page. How specifically to do this is beyond the scope of our support, but you should find some other examples by searching through the issues.

The tricky bit will be registering email opens, since JS won't be available there. You'd have to send a server-side request upstream to Gophish.
