### ISSUE TITLE
Cannot send test email/any email from GoPhish with domain

### ISSUE THREAD

**Issue by feedpeepxans** [gophish/gophish#1935]
**GoPhish Version: 0.10.1 

Hello I'm trying to send emails from my domain, which is from GoDaddy, and my SMTP server, which is hosted on a digitalocean server via Postal. The server is live, however I have trouble sending from it from CERTAIN places. For example, MXToolbox shows the SMTP server is valid, and I'm able to send a test email from GMass. However, on SMTPer and GoPhish, I am unable to connect to my SMTP server/send any emails. On SMTPer I get an operation timeout, and on GoPhish I get Max connection attempts exceeded - dial tcp *myserverip*:25: i/o timeout.

If anyone has any suggestions with what I could do to fix this PLEASE let me know.

Thank you

**Comment by unicorn-art** [comment]
Apa itu gophish tidak sesuai ekspektasi!
Lagg!

**Comment by glennzw** [comment]
> Apa itu gophish tidak sesuai ekspektasi!
> Lagg!

We're a team of volunteers who freely give up our time to maintain this project. There's no need to be rude.

Your original question is outside the scope of gophish support; the problem is with your mail server setup. The timeout message implies your mail server is not reachable and the connection fails.
