### ISSUE TITLE
Multiple IP/domains for landing pages to get around safe browsing warnings

### ISSUE THREAD

**Issue by lerra** [gophish/gophish#1942]
Hi,

I would like to see the feature of having the possibility to add multiple IP/domains for landing pages to load balance between when sending out the mails. 

The idea here is to lower the possibility to get hit by safe browsing warnings by creating multiple temporary load balancers or ip's.

The interface should also support to show what URL the user(s) got assigned in the case of one get blacklisted and the ability to "re-send with a new url".  
 
Is there any plans for such already?

**Comment by nahojderp** [comment]
I would also like to see this feature! When dealing with larger campaigns 1k+ emails the safe browsing warnings are constant even if scheduling the campaign to send for a month. This would be a great way to lower the risk being blacklisted by safe browsing.

**Comment by jordan-wright** [comment]
There are plans in the future to add support for managing domains with Gophish. That said, these plans do not include load balancing between domains when sending out emails. Rather, it's just do things like make Let's Encrypt support work out of the box.

I'm hesitant to add this since it would add quite a bit of complexity to the UX to target a pretty narrow use case. So I'm going to close this out as "wontfix" for now, but I'll reconsider in the future.

Thanks for sending this idea in!
