### ISSUE TITLE
About landing pages

### ISSUE THREAD

**Issue by naddika** [gophish/gophish#1956]
Hey

1) Does gophish host the landing page? If yes, then that requires that gophish and landing page run on the same server, right?

2) In "new campaign" what's URL for? Is it the same URL/IP where the landing page runs? 

3) And if I specify not a local URL where gophish is running,  but some external IP or domain/URL to which I and user-target have access to, will it still work? But how will gophish be able to "Capture Submitted Data" there then?

**Comment by glennzw** [comment]
Hi @naddika, you can find most answers here: https://docs.getgophish.com/user-guide/

1. Yes (by default landing pages on 80, admin on 3333, configure this in your config.json)
2. Yes
3. The user would click the link, and be taken to whatever page you specify here. If it's not gophish, there won't be a way to register the link being clicked or data submitted.

**Comment by naddika** [comment]
Thanks. I've seen the documentation, not everything in there has been described in the detail.

When I specify "Launch Date" and "Send Emails By (Optional)" in a new campaign, what frequency of emails will it run with? How many of them will be sent at all? One email to each user, once? And one per user once a day, every day if the end date has been specified?

**Comment by glennzw** [comment]
It will run as fast as possible unless you specify a Send By, then it will (approximately) dispatch at regular intervals over that period (actually it will be a burst every minute or so).

There's a pull request for specifying sending frequency here: https://github.com/gophish/gophish/pull/1557

**Comment by think-how** [comment]
@glennzw hi - sorry to intrude - can I ask - if the user would be taken to the website specified by the URL, then what is the purpose of the Landing Pages? 
in my setup, the user indeed was directed to the website hosted in the server together with gophish - the Landing Pages was not visited at all, and I have a problem - the statistics were not collected - in the dashboard - only email sent was recorded - the rest remained zero - is this problem related to Landing Pages? - how can I resolve this issue?
thank you very much

**Comment by glennzw** [comment]
@think-how You create the landing page, and then specify its location with the URL parameter. There's no real use to use a non-landing page URL in this parameter.

So, create a landing page, host it on your server at foobar.com, then specify foobar.com in the URL when launching a campaign.

**Comment by jordan-wright** [comment]
Hi everyone!

In the future, let's please try to keep issues focused on a single question or bug. Otherwise, they turn into long back-and-forths with no clear definition of done.

To that end, @glennzw has answered the questions given in this issue. To recap:

* Landing pages are hosted by Gophish. This is important for tracking purposes. It's not **required**, but if you don't point the URL to Gophish then you're largely on your own when it comes to tracking clicks
* When creating a campaign, in the URL field it is expected that you put the IP/domain name/port corresponding to the Gophish phishing server.
* Gophish will see this inbound request and return the correct landing page

If you are not seeing the events you expect in the Gophish interface, then I would encourage you to refer to [our documentation](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard) where we walk through some common troubleshooting steps.

Thanks for getting in touch!
