### ISSUE TITLE
Url issue

### ISSUE THREAD

**Issue by felix-fsd** [gophish/gophish#1995]
Hey, what do I have to insert under the point URL to create a new campaign. The IP address of a server? 
In some youtube tutorials they inserted http://0.0.0.0:80 (the phishing server shown in the application but when the tartget opens the landing page the link doesn´t work
thanks for your help
Felix

**Comment by glennzw** [comment]
Yes you need to enter an IP that the target user can reach. So if your server is running on public IP 1.2.3.4, then you'd enter http://1.2.3.4.

There was a fairly long back and forth on this recently, perhaps this post helps too: https://github.com/gophish/gophish/issues/1979#issuecomment-699286676

Hope that helps.

**Comment by namanagrawal94** [comment]
If you are running the gophish server on the localhost server, you will have to write "http://localhost" in URL section of the campaign.

Hope this helps.

**Comment by jordan-wright** [comment]
As mentioned by others, you need to use the IP address or domain name of the Gophish server that is reachable by the recipients receiving the emails. Note that using "localhost" is almost certainly not want you want since that's only reachable from people on the Gophish server itself, and 0.0.0.0 is also not what you want since recipients can't put that in their browser and reach your Gophish server.
