### ISSUE TITLE
Phishing server is listening in ipv6

### ISSUE THREAD

**Issue by HugoLS** [gophish/gophish#2016]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: 
After a fresh install
When i'm using 0.0.0.0:80 as phishing server address, gophish listen in tcp6. If i'm using a specific address, like 127.0.0.1 or 182.168.1.2 for example, it is working well (using tcp, and accessible)

What are you expecting to see happen? : I'm expecting to see gophish listening in ipv4 for 0.0.0.0 address

Please provide any terminal output that may be relevant below:

```
[root@localhost gophish] more config.json
{
	"admin_server": {
		"listen_url": "192.168.$$.$$:3333",
		"use_tls": true,
		"cert_path": "gophish.crt",
		"key_path": "gophish.key"
	},
	"phish_server": {
		"listen_url": "0.0.0.0:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
[root@localhost gophish] netstat -anp | grep gophish
tcp    0    0    192.168.$$.$$:3333    0.0.0.0:*    LISTEN    2138/./gophish
tcp6  0    0     ::80                             0.0.0.0:*    LISTEN    2138/./gophish
```

If i modify the ip address:

```
[root@localhost gophish] more config.json
{
	"admin_server": {
		"listen_url": "192.168.$$.$$:3333",
		"use_tls": true,
		"cert_path": "gophish.crt",
		"key_path": "gophish.key"
	},
	"phish_server": {
		"listen_url": "192.168.$$.$$:80",
		"use_tls": false,
		"cert_path": "example.crt",
		"key_path": "example.key"
	},
	"db_name": "sqlite3",
	"db_path": "gophish.db",
	"migrations_prefix": "db/db_",
	"contact_address": "",
	"logging": {
		"filename": "",
		"level": ""
	}
}
[root@localhost gophish] netstat -anp | grep gophish
tcp    0    0    192.168.$$.$$:3333    0.0.0.0:*    LISTEN    2138/./gophish
tcp    0    0    192.168.$$.$$:80        0.0.0.0:*    LISTEN    2138/./gophish
```

I don't understand why it is using ipv6 instead ipv4 when i'm using a mask address like 0.0.0.0

Thank you for your help

**Comment by fenggy09** [comment]
same issue here

**Comment by glennzw** [comment]
Could you give more info on what OS/distribution/etc you're using so we can try reproduce this.

**Comment by txr13** [comment]
I suspect that this is actually completely expected behavior.

By default, IPv6 sockets _also_ listen in IPv4, and will handle inbound connections from IPv4 addresses. When an explicit IPv4 address like 192.168.x.x is specified, that calls for an IPv4-only socket. But the all-zeros address is probably defaulting to the standard meaning of "all IPs on this machine", which includes any IPv6 addresses. Hence the socket spawns in an IPv6-capable state and will show up as a v6 socket, even though it's still 100% capable of handling IPv4 traffic.

Ref: https://unix.stackexchange.com/questions/237731/why-are-ipv4-tcp-connections-showing-as-tcp6

**Comment by glennzw** [comment]
Thanks @txr13 that's useful to know.
