### ISSUE TITLE
Tracking link should return an image

### ISSUE THREAD

**Issue by nmalcolm** [gophish/gophish#202]
The tracking link used in email templates returns an empty "plain" response. As the tracking element is an image, the response should ideally be a 1x1 transparent gif. The main reason for this change is some (most?) email clients will show a "broken image" icon at the bottom of the email if there is no image to load. This is a problem when creating pixel-perfect emails.

**Comment by jordan-wright** [comment]
Great suggestion! I didn't know that email clients would show a broken image. I wonder if this would still be the case if we returned a 204 No Content? Might save us from having to store an image, but that wouldn't be the worst thing in the world :smile:

**Comment by rfdevere** [comment]
To add images like this and to completely avoid the broken image the idea is to get Google to host that image… as per http://arstechnica.com/information-technology/2013/12/gmail-blows-up-e-mail-marketing-by-caching-all-images-on-google-servers/

Whilst in this section can we have the IP gathered at this point, using the image?

**Comment by jordan-wright** [comment]
The hard part with having Google host the image is that we lose the ability to capture the IP address at that stage.

I might just have to add a static 1x1 PNG to gophish and have it dumped by the phish tracker. If Google caches it after that, we might lose some email opened events, but at least we'll have the first one.

**Comment by grutz** [comment]
What about generating a transparent 1x1 image with a color that is unique to the user's gophish ID? This way the image itself would be different, thus hopefully cached by anyone except the first time.

A roadblock here for accuracy is that we have no direct way to identify if the user opened/viewed the image or if the MTA or MUA did it on-behalf of the user.

**Comment by jordan-wright** [comment]
> What about generating a transparent 1x1 image with a color that is unique to the user's gophish ID? This way the image itself would be different, thus hopefully cached by anyone except the first time.

This is an interesting idea. It all depends on how Google has it implemented. Looking [here](https://sendgrid.com/blog/googles-new-image-caching-5-things-need-know/), it would appear that Google will fetch the image once and cache it from then on. Since we append a unique ```rid``` to each url, Google would *have* to fetch it at least once to know if it's cached or not.

By that time, we already have Google's IP and the fact that the email was received and opened. That's probably good enough for our use case.

> A roadblock here for accuracy is that we have no direct way to identify if the user opened/viewed the image or if the MTA or MUA did it on-behalf of the user.

Bingo. This is tricky and, in the case of gmail, it appears to be the former. It's to my (limited) understanding that Google will only fetch the image once the email is opened by the user, but I could be wrong.

Regardless, I agree that we need to return a blank png instead of no content. I'll make that happen.

**Comment by jordan-wright** [comment]
Ok, a valid image is now being returned. Give it a shot and let me know if you run into issues!

**Comment by congriholdplantains** [comment]
I have the broken image issue as well and I am running that latest release. It seems this was fixed in version 0.2 that is not out yet. When is it being released?
