### ISSUE TITLE
Not recording email opened stats 

### ISSUE THREAD

**Issue by JodieandSophie** [gophish/gophish#2050]
What version of Gophish are you using?: 0.11.0 

Brief description of the issue: When we performed a campaign this month we have noticed that when a user opens the email it is not recorded at all. 

What are you expecting to see happen? : When a user opens the email I expect to see it counted in the Email Opened stats. 

What are you seeing happen? The only time it is recorded is when the user clicks on the link. So both email opened & link clicked are recorded from users clicking the link. This did not happen in the previous campaign, we have ran comparisons between all campaign components from October vs November and there are no differences. We have noticed that there is an IMAP settings issue. Could this be causing the problem with the email opened stats?

**Comment by glennzw** [comment]
Hi there,

This often happens if the email client is blocking remote images loading. Gophish uses a 1x1 tracking pixel in the email, and if this image is loaded, gophish knows the email has been read. You could watch the gophish console when you open a test email, you should see an entry like:

```
time="2020-11-26T13:21:08+01:00" level=info msg="::1 - - [26/Nov/2020:13:21:08 +0100] \"GET /track?rid=Fw8Pyja HTTP/1.1\" 304 0 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36\""
```

NB the `track?rid=Fw8Pyja` is the email loading the tracking pixel. If you're not seeing this, then it's most likely your email client blocking remote images.

Next, check the source of the email, and make sure the tracking pixel URL is in there, something like `http://yourserver/track?rid=Fw8Pyja` . If it's not, there's a chance you didn't add the tracking pixel to the email.

Hope that helps!

**Comment by jordan-wright** [comment]
Closing this since @glennzw is correct- it's likely an issue with either a misconfiguration in the campaign URL/template, or the email client is not loading remote images. You can find more information [in our FAQ.](https://docs.getgophish.com/user-guide/faq#events-arent-showing-up-on-the-dashboard)
