### ISSUE TITLE
Support for postgres database

### ISSUE THREAD

**Issue by PrakharSrivastav** [gophish/gophish#2053]
What version of Gophish are you using?: 0.11.0

Brief description of the issue: Support for postgres

What are you expecting to see happen? : Postgres database supported as a backend

What are you seeing happen? No options available now

**Comment by PrakharSrivastav** [comment]
I have a fix ready as a PR for this change. However I do not have access to send a PR or push a new branch. Could someone provide me an access?

**Comment by glennzw** [comment]
Hi @PrakharSrivastav - nice work! You can open a pull request from your fork of gophish to get your changes submitted.

**Comment by jordan-wright** [comment]
Hi there!

I appreciate you reaching out, but I'm afraid I'm not interested in supporting Postgres at this time. It's already difficult enough ensuring compatibility with SQLite and MySQL, and bugs have slipped in in the past due to the lack of testing for MySQL, so I'm not in a position to support yet another database.

You are, of course, free (and encouraged!) to maintain a fork of Gophish with Postgres support.

Thanks again for getting in touch.

**Comment by steffen-karlsson** [comment]
We have added full support for Postgres in GoPhish in this fork: https://github.com/corticph/gophish-postgres
