### ISSUE TITLE
Can't run the program on MACOSX

### ISSUE THREAD

**Issue by bouffetout** [gophish/gophish#2066]
Hello I'm on mac osx I downloaded the Zip but don't know which file to launch i tried them all it does work.
Is there a specific software required to launch GoPhish ? Which file is the launcher ? Thanks

**Comment by glennzw** [comment]
Open a [terminal](https://macpaw.com/how-to/use-terminal-on-mac), and run the gophish binary:

```
cd gophish
./gophish
```

**Comment by jordan-wright** [comment]
As always @glennzw is spot on. If that doesn't work for you, please provide all the output in the terminal here so we can help troubleshoot.

In the meantime I'm going to go ahead close this out.

**Comment by bouffetout** [comment]
> Open a [terminal](https://macpaw.com/how-to/use-terminal-on-mac), and run the gophish binary:
> 
> ```
> cd gophish
> chmod +x gophish
> ./gophish
> ```

Doesnt work. " No such file or directory"

**Comment by jordan-wright** [comment]
We really need more information to help you out.

At this point all we know is that you tried downloading the file and it doesn’t seem to run because you’re getting a “No such file or directory error”. That’s just not much for us to go on.

If you want us to help troubleshoot, please provide the exact steps you’re taking. Consider making a recorded gif, or including every action you’re taking and the exact output or thing that happened along the way. We should be able to follow your steps exactly and arrive at the same error message.

Otherwise, I’m afraid we just won’t be able to help out.

**Comment by bouffetout** [comment]
Hello thanks for the answer, 
I downloaded the MAC version gophish-v0.11.0-osx-64bit.zip

Then i unzip in the standard folder called Downloads : none of the unzipped files are launchable : https://imgur.com/x3JXXKX so I open the Terminal and type Glen's commands, get the error No such file or directory

so I rename the folder gophish-v0.11.0-osx-64bit into gophish and try "cd Downloads" "cd gophish", still impossible to launch the program

**Comment by glennzw** [comment]
You'll need to give us a screenshot of the terminal command failing. 

You're likely not inside the gophish directory when you run the command.

**Comment by bouffetout** [comment]
https://imgur.com/a/en6be1S

is there some kind of detailed tutorial somewhere thanks

**Comment by glennzw** [comment]
It's running. Open your browser and navigate to https://127.0.0.1

There's lots of documentation here:


https://getgophish.com/documentation/

**Comment by bouffetout** [comment]
indeed i can now see the login panel I tried 
username = admin
password = gophish 
without success
