### ISSUE TITLE
How Do I Solve The "Deceptive Site Ahead" Issues????

### ISSUE THREAD

**Issue by testinglab66** [gophish/gophish#2071]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current version

Brief description of the issue:  I have my site with lock key on it but it's not displaying on the address bar when I run gophish.

What are you expecting to see happen? : I'm expecting to have the greenlock shown and appear on the registered domain I'm using with gophish.

What are you seeing happen? Unsecure with no greenlock on the site, when clicked on the phishing link it pops with "Deceptive Site Ahead" and I don't know how to fix this...

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by horllste** [comment]
You can't

**Comment by jordan-wright** [comment]
There isn't anything we can do in Gophish to prevent Google from flagging sites as deceptive.

**Comment by linehammer** [comment]
Google Safe Browsing services has created this warning message in order to protect its users from browsing unsafe online content. This message usually means that your website is hacked and Google has marked it insecure. These sites are often called phishing or malware sites.

You can visit a page or access a downloaded file that shows a warning. This isn't recommended.

- Visit an unsafe page
- On your computer, open Chrome.
- On the page where you see a warning, click Details.
- Click Visit this unsafe site.
- The page will load.

When you visit an unsafe site, Chrome will try to remove the unsafe content from the page.

The adware behind the fake [Deceptive Site Ahead](http://net-informations.com/q/mis/deceptive.html) alerts is not an ingenious virus. It cannot install itself. No, it needs your approval to enter. So, it uses a lot of trickery to gain your permission. It usually hitches a ride with other software. So, pay close attention when browsing the Internet, and when downloading/installing software.

**Comment by Shivamupadhayay07** [comment]
How I can remove that Deceptive warning from my GitHub.io while seeing the README.md file ?

**Comment by Aseem2004** [comment]
Maybe try changing the name of your branch

**Comment by imvickykumar999** [comment]
I created a phishing website as a part of my project but now every 
    GitHub page is blacklisted, how do I solve this issue from GitHub?

![image](https://github.com/gophish/gophish/assets/50515418/6468c170-499a-4330-aaa6-aa1345d40c21)

**Comment by Aseem2004** [comment]
Not getting any info on how to remove this. Affecting the deployments of all my projects.

**Comment by imvickykumar999** [comment]
> ```
> I created a phishing website as a part of my project but now every 
> GitHub page is blacklisted, how do I solve this issue from GitHub?
> ```
> 
> ![image](https://user-images.githubusercontent.com/50515418/275461243-6468c170-499a-4330-aaa6-aa1345d40c21.png)

I would like to share how my GitHub Page became whitelisted after I transferred ownership to my Organization GitHub Account, then after 1 day, that deceptive message was removed from my main account.

I mean, due to that one repository, my all GitHub pages went blacklisted and that's not good for my other GitHub pages na, but transferring ownership to another account really removes that deceptive message.

Also I mentioned my GitHub Page URL to https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by DeveloperMubby** [comment]
I created a phishing website as a part of my project but now every 
GitHub page is blacklisted, how do I solve this issue from GitHub?
