### ISSUE TITLE
unable to unzip and install on VPS

### ISSUE THREAD

**Issue by bouffetout** [gophish/gophish#2074]
Hi 

after connecting to my VPS and downloading the zip into my VPS i'm unable to unzip and install it : 

http://pastie.org/p/3OLEdpSNYFKWCSdKxnnhd5

i tried "sudo apt update" without success

**Comment by jordan-wright** [comment]
You need to run “apt install unzip” as its own command to install unzip, then you can run the unzip command on the ZIP folder.

**Comment by bouffetout** [comment]
thanks for your precious help I did unzip it i think.
Now i find myself unable to run the binary file it cant locate it
 
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# chmod a+x ./gophish

root@ubuntu-s-1vcpu-1gb-sgp1-01:~# ./gophish

-bash: ./gophish: No such file or directory

root@ubuntu-s-1vcpu-1gb-sgp1-01:~# ls

LICENSE    VERSION      db       gophish-v0.11.0-linux-32bit.zip  static
README.md  config.json  gophish  snap                             templates

root@ubuntu-s-1vcpu-1gb-sgp1-01:~# ./gophish

-bash: ./gophish: No such file or directory

**Comment by jordan-wright** [comment]
It looks like everything started successfully. You should be able to login. That warning is exactly what it suggests- a warning that you don't have a contact address configured in config.json.

I'd gently encourage you to read our [documentation.](https://docs.getgophish.com/user-guide) We work hard trying to give good documentation on how to get Gophish running so that we don't need to spend the **incredibly** limited amount of volunteer time we have giving personalized step-by-step instructions.

Since your original question is answered and it seems you have Gophish running, I'm going to close this issue.

**Comment by bouffetout** [comment]
your help is highly appreciated thank you very much for your time
