### ISSUE TITLE
GoPhish links clicked almost immediately upon receival (by Microsoft?)

### ISSUE THREAD

**Issue by 0x412e4e** [gophish/gophish#2115]
**What version of Gophish are you using?:** 0.11.0 

**Brief description of the issue:** 
GoPhish email links are being clicked almost immediately upon receival. For example, the campaign page shows that supposedly our users click the email's link always a few seconds after receiving it, even if it's four o'clock in the morning.

We are using M365 and we have TrendMicro's Cloud App Security. We've whitelisted the sender in both of these systems, without doing so, the emails would be quarantined and marked as spam immediately. 

However, I still suspect that it's Microsoft's Outlook still somehow checking if the link in the email is legit.

**What are you expecting to see happen?:** 
I noticed no such behaviour when I was testing GoPhish with only a few users. At the moment I'm targeting about a hundred users.

**What are you seeing happen?**
Here for example is my entry in this campaign I've created (I'm Antti!). It shows that I received the phishing email today at 4:19 AM and immediately clicked the link using Windows 10 and Chrome (I don't even use it on my laptop):

[screenshot](https://i.imgur.com/7Zra5pT.png)

This same behaviour is happening to all of the entries in the campaign, and it's really skewing the results.

**Please provide any terminal output that may be relevant below:**
From `journalctl -eu gophish` we can see a Microsoft IP (13.80.183.173) clicking the link immediately after being sent:
```
Feb 11 04:19:12 gophish.domain.corp gophish[1166]: time="2021-02-11T04:19:12+02:00" level=info msg="Sending emails to mailer for processing" num_emails=1
Feb 11 04:19:12 gophish.domain.corp gophish[1166]: time="2021-02-11T04:19:12+02:00" level=info msg="Email sent" email="\"Antti Lastname\" <antti.lastname@domain.corp>"
Feb 11 04:19:18 gophish.domain.corp gophish[1166]: time="2021-02-11T04:19:18+02:00" level=info msg="13.80.183.173 - - [11/Feb/2021:04:19:18 +0200] \"GET /?rid=EvCbLo2 HTTP/1.1\" 200 6179 \"\" \"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36\""
```

Edit: If there is no way around this issue, could I somehow modify `gophish.db` using a script to remove all the link clicking entries by Microsoft?

**Comment by glennzw** [comment]
Tricky one. I assume you've added a Advanced Threat Protection (ATP) Bypass Rule on your O365? That's usually the culprit. Steps to do that are:

1. Create a new mail flow rule in your Exchange/Office Admin center.
2. Give the rule a name such as "Bypass ATP Links".
3. Click More options....
4. From the Apply this rule if…. drop-down menu, select The senders then select IP address is in any of these ranges or exactly matches.
5. Enter gophish SMTP server IP
6. From the Do the following… drop-down menu, select Modify the message properties... and then set a message header.
    * Click the first *Enter text... link and set the message header to: X-MS-Exchange-Organization-SkipSafeLinksProcessing
    * Click the second *Enter text... link and set the value to: 1
9. Click Save.

Otherwise, I can think of two possible workarounds, but they'll need some work:

1. Block IP
Check the IP that's "clicking the link". If this is some server side device, you could firewall it off from the gophish server, so only target users real clicks can reach the gophish server.

2. Javascript middleware
I've proposed this solution in another issue when someone had a similar problem, but I can't find it now. Basically, you can run a small intermediate webserver to 'pass on' the request to the real gophish server, but it does it via Javascript. So if the thing examining the link isn't handling javascript you might be able to sneak through.

It's odd though, in your screenshot, that the user agent is Windows + Chrome, which, and as you say that's not your machine setup. Maybe TrendMicro is examining the link in a VM.

**Comment by 0x412e4e** [comment]
Thanks for the reply!

I had forgotten to make the M365 bypass rule, and I've configured it now.

Now I'll just wait for GoPhish to send the next email in the campaign... will be a few hours from now. After that, I'll see if I need to make the IP block using FirewallD or something similar (running on CentOS 7).

Thanks again for the detailed reply! I'll let you know what happens...

**Comment by 0x412e4e** [comment]
Making that mail flow rule had no effect... I think I've figured out a way to deal with this:

When the campaign is over I will export the results to a CSV file, then in Excel I'll remove all the false positive click entries which have the Microsoft IP as the source.  After that I'll use [GoReport, a Gophish Reporting Tool](https://github.com/chrismaddalena/Goreport) to create a report which doesn't have the false positives included.

I can't use GoPhish's campaign page's reporting tool because it already has a ton of false positive clicks, so it is not trustyworthy to indicate actual user behaviour.

**Comment by glennzw** [comment]
Odd the O365 option didn't work. Did you trace the culprit IP back to Microsoft? Other option is always to block the offending IP, unless it's dynamic.

Do let us know if you find another workaround, I'll go ahead and close this out for now.
