### ISSUE TITLE
what is my external ip gophish server address?

### ISSUE THREAD

**Issue by UCSG123** [gophish/gophish#2125]
I have a domain and I would like to point to that external gophish server ip address

**Comment by jordan-wright** [comment]
It's your server, so it's whatever IP address you've assigned to it.

Im afraid that isn't something we can help with since it's outside the scope of Gophish.

**Comment by UCSG123** [comment]
My ip is 127.0.0.1 is that the ip?

**Comment by UCSG123** [comment]
Because when I put in the domain that ip, it only works for my computer but not for other computers when the link is open

**Comment by jordan-wright** [comment]
That's the loopback IP address. You need the external IP address.

At this point, the best thing I can do is recommend googling how to find the external IP address on the operating system or cloud provider you're using. I'm afraid this kind of networking/sysadmin knowledge is one of the prerequisites to using Gophish, since it isn't something we can help with here.

**Comment by UCSG123** [comment]
So.. It´s my ip address of my computer? I have to use it when I'm creating the campaign?

**Comment by jordan-wright** [comment]
I cannot tell you the IP address of your computer - that's something you'll need to determine yourself. You need the IP address of the server running Gophish that is accessible to all recipients of the emails being sent.

This kind of networking/sysadmin knowledge is a prerequisite to using Gophish, and not something we can help with here. I would gently suggest that there are other phishing simulation providers that host all of this for you that you may find more usable- many of these have a competitive free offering that might fit your use case.

Sorry we can't be of more help!
