### ISSUE TITLE
Is it possible point the tag {{.Tracker}} to an image in other website ?

### ISSUE THREAD

**Issue by walrus-cyber** [gophish/gophish#2158]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.11.00

Brief description of the issue: 

What are you expecting to see happen? : 
I think is not a issue, its a question. We should use the tag {{.Tracker}} to check if an e-mail is opened or not, but in gmail this doesnt work. I know its a e-mail client protection.
Is it possible point the tag {{.Tracker}} to an image in other website ? I mean if the image is loaded the Gophish could report the e-mail is opened. Is it possible ?

What are you seeing happen?
{{.Tracker}} to check if an e-mail is opened or not, but in gmail this doesnt work. I know its a e-mail client protection.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by glennzw** [comment]
When you insert {{.Tracker}} in an email it's replaced by whatever you specified as your landing page and a trailing unique identifier. e.g:

`https://my-phishing-server.com/track?rid=yNx1u53`

So, you can have the tracker reside on any webpage, but it must be redirected to your gophish server (e.g. you could buy a new domain that points back to your gophish server).

I don't think this is useful though. The real problem is that GMail is blocking remote images - and I don't know if there's an easy way around this.

**Comment by glennzw** [comment]
Closing as haven't heard back. Feel free to reopen.
