### ISSUE TITLE
Max connection

### ISSUE THREAD

**Issue by palashmandokhot** [gophish/gophish#2159]
hi,
i am just testing a gophish on yandex mail when i used send test mail so it shows something like this Max connection attempts-dial tcp: lookup smtp.yandex.ru on my 127.*.*.*>127.*.*.* i/o timeout and when i start campaign so the campaign is failed means after launch campaign it shows error failed 505 5.5.4 Error: send AUTH command first now what i do how i tested it and how to to send mail on yandex mail the yandex server is smtp.yandex.ru and port is 456.

**Comment by glennzw** [comment]
Hi there,

This looks to be a problem with your email provider rather than gophish. A quick Google of the error seems to suggest that perhaps you're not enabling SSL, and yandex only accepts SSL connections: https://stackoverflow.com/questions/42391432/c-sharp-yandex-mail-send-error-5-5-4-error-send-auth-command-first

**Comment by glennzw** [comment]
Closing out as haven't heard back.
