### ISSUE TITLE
Admin account has been lost

### ISSUE THREAD

**Issue by LizaChernysh** [gophish/gophish#2236]
What version of Gophish are you using?: 
The last avaliable version of Gophish -11.0

Brief description of the issue: 
After updating the Gophish from version 7.0 to 11.0 admin access was lost. Could you please advise how to recover admin user?
Thank you!!

**Comment by glennzw** [comment]
Is the user not present in the database, or the password you're trying is rejected? Double check the console to make sure a new password isn't being printed out.

Otherwise, you can edit the gophish.db file using a SQLite client and change the admin hash. e.g:

```
sqlite3 gophish.db 'update users set hash="$2a$10$IYkPp0.QsM81lYYPrQx6W.U6oQGw7wMpozrKhKAHUBVL4mkm/EvAS" where username="admin";'
```

...will set the admin password to 'gophish'.

**Comment by LizaChernysh** [comment]
I moved the old DB and the admin user was there. Now the password which I'm trying is incorrect.

**Comment by LizaChernysh** [comment]
The access is restored. Thank you very much!

**Comment by glennzw** [comment]
No worries!

**Comment by cardosoJV** [comment]
Thank you!
