### ISSUE TITLE
WildCard Implementation on GoPhish

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2237]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Team, we are planning to use Wild Card so that every time we are to send out email it has a different host name so resources involved should not get a feel that these are phishing email. Kindly assist so it can be implemented. 

Thanks again for continuous support

**Comment by glennzw** [comment]
Great question, I've had the same thought before. The way I solved this problem was by including the random `{{.RId}}` parameter in the email sender address. You can do this by adding a `From` Email Header in the Sender Profile, e.g:

<img width="699" alt="Screenshot 2021-06-20 at 15 32 36" src="https://user-images.githubusercontent.com/3966613/122678139-5d67e680-d1dd-11eb-8e6f-9fac0e760810.png">

Every email will now come from

`<randomRID>@foo.com` (e.g gXur34e@foo.com)

You could add this to the domain side too, along with any other text.
