### ISSUE TITLE
Console Avalibility on Other Machine

### ISSUE THREAD

**Issue by hammi198** [gophish/gophish#2246]
Hey team,Wanted to ask if we have an option of accessing Go Phish admin page from other server / over the internet. So for example i have a Go Phish running on A machine and have added Users which dont have access to A but wanted to open this on B machine which is available on internet / intranet. How would i be able to do this?

thanks in advance

**Comment by glennzw** [comment]
You can access the admin server from anywhere, but you'll need to route the traffic so that it hits your gophish admin server. 

e.g. you could host gophish on your server, listening on localhost:3333, and setup appropriate redirection with socat or Caddy or nginx such that some other machine on some other port gets routed to the gophish admin port.

**Comment by atheriqbal** [comment]
As glennzw suggested you need to redirect external URL to server A. 
For example, in a linux/windows server, add a line 
serverA externalURL 

Let us know if this helps.

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to re-open if you're still having trouble.
