### ISSUE TITLE
Question - Cannot send emails to other domains ?

### ISSUE THREAD

**Issue by ms08067** [gophish/gophish#2313]
What version of Gophish are you using?: 

0.10.1

Brief description of the issue: 

I have recently been exploring different open source frameworks for phishing, tried out gophish today. I am using a gmail business account to do sending with 'less secure' apps enabled. Emails that are sent to gmail work fine. Emails that go to other domains fail.

What are you expecting to see happen? :

I expected the emails to send to the other domains.

What are you seeing happen?

Gmail gives me a response that the account does not exist. Please see below. (Am I only able to send to the same exact domain that my mail comes from ??) 

Please provide any terminal output that may be relevant below:

time="2021-09-24T17:27:57Z" level=warning msg="550 5.1.1 The email account that you tried to reach does not exist. Please try\n5.1.1 double-checking the recipient's email address for typos or\n5.1.1 unnecessary spaces. Learn more at\n5.1.1  https://support.google.com/mail/?p=NoSuchUser 17si5697335qks.415 - gsmtp" code=550 email="\"xxxx xxxx\" <xxxxx@xxxxx>"

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Configure Sending Profile
 * Step 2 - Send Test Email

**Comment by atheriqbal** [comment]
Hi, 

Code 550 means : 
 The requested command failed because the user’s mailbox was unavailable for example because it was not found, or because the command was rejected for policy reasons.In addition, SMTP response code 550 is also commonly used to indicate additional instances of permanent failures. For example, “550 The mail server detected your message as spam and has prevented delivery.”

**Comment by glennzw** [comment]
@atheriqbal is spot on as usual; this is a mail server problem.
