### ISSUE TITLE
My Gophish is not monitoring actions (When the E-mail was open, Clicked, and other inforrmation)

### ISSUE THREAD

**Issue by ViegasCuamba** [gophish/gophish#2456]
Hello,

![Capture](https://user-images.githubusercontent.com/34270662/167133066-25f9d364-118d-4144-b85e-b12f0b0e28bc.PNG)
![Capture](https://user-images.githubusercontent.com/34270662/167133360-cb822e60-2d8f-4dcd-8192-4bd9618275f2.PNG)
I'm having problems with gophish, gophish has already been installed but when I send a phishing campaign it just shows me that the email was sent but it doesn't show when it is opened. Can you help me?

**Comment by zer01sec** [comment]
Hi,

It looks like your email client does not show images by default, thus the tracker is not loaded. You should either click on the first link inside the yellow rectangle and select 'Download images' ('Apresentar imagens'), or add this particular user to the safe list (the option bellow).

**Comment by ViegasCuamba** [comment]
> Hi,
> 
> It looks like your email client does not show images by default, thus the tracker is not loaded. You should either click on the first link inside the yellow rectangle and select 'Download images' ('Apresentar imagens'), or add this particular user to the safe list (the option bellow).

I tried but doesn't work.

**Comment by ViegasCuamba** [comment]
> Can you confirm if the option 'Add Tracking Image' inside 'Email Templates' is checked: ![image](https://user-images.githubusercontent.com/97805141/167141099-8e4983fe-bbcb-461e-8464-38e0c7cf55ee.png)

![Capture](https://user-images.githubusercontent.com/34270662/167141558-164ddedd-3cad-4475-b415-40d672632a67.PNG)

Yes, is checked.

**Comment by zer01sec** [comment]
Even though I think the issue is with the mail client not downloading images, can you tell me if you can reach the landing page behind the link ('Clique aqui') in the phishing mail?

![image](https://user-images.githubusercontent.com/97805141/167145298-be6b8b10-5d46-4cb9-9b6c-7575a89e05ef.png)

In addition, what is the domain/IP address you are using for the URL field when creating new 'Campaign'? Is it the one you set for the phish_server listen_url inside config.json file?

**Comment by glennzw** [comment]
Closing out as haven't heard back, feel free to re-open. Thanks @zer01sec for fielding this one.
