### ISSUE TITLE
[suggestions] Multiple Websites / External hosting with internal tracking 

### ISSUE THREAD

**Issue by vysec** [gophish/gophish#248]
Hi,  I wanted to suggestion some possible improvements after playing around with GoPhish for a while. 

**Multiple Landing Pages**
I am sure that GoPhish is already working on the ability to clone websites such as Google accounts that have multiple stage authentication. 

**External Hosted Sites**
It would be good if you could define the {{.URL}} for each campaign and have the cloned files in a zip to be uploaded to an external Web server.  Then you could have many phishing sites at once with one centralised area of data collection. 

Currently to overcome this requirement,  a PHP redirector needs to be built on the external host but is not ideal and does not mask all the information. 

Furthermore,  if the source of the cloned site was available it would make modification of the whole page more flexible. For example we may want to POST the users credentials to the actual website to log them in. 

**Internal logging**
On the external websites and trackers,  we don't want any leakage on the location of the GoPhish centralised system. So the trackers should point to the external website which then works with a redirector in PHP that makes the external server log a track event in the centralised server. This prevents the end user finding out about the phishing server all together. 

**Support scheduled campaign launching**
You can make campaigns and press the run key at a later time or schedule them to run at a certain time. 

Also should be able to stop a campaign midway. 

I hope these suggestions bring some ideas from a practical and scalable point of view.  I will edit more ideas as they come along.

**Comment by vysec** [comment]
Also good job at making it super easy to install.

**Comment by jordan-wright** [comment]
Hi @vysec - thanks for the report!

I would recommend taking a look at the existing issues we have open, as they address a bunch of what you're already suggesting:

* Multiple Landing Pages - #127 and #219 
* External Hosted Sites - Something like #164 
* Support scheduled campaign launching - #21 

The last one, "Internal logging" is easiest done by throwing up a simple reverse proxy on a VPS. That has the same effect you're talking about without us having to somehow integrate with external systems.

For now, since these are all ideas that have been proposed, I'm going to go ahead and close this out. Thanks again for the reports!
