### ISSUE TITLE
Simple email tracking just wont work. 

### ISSUE THREAD

**Issue by cyberhax1** [gophish/gophish#2554]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
11.0
Brief description of the issue: 
The emails just arent tracking. I tried every option, i tried add listener URL, i tried {{tracking}}, nothing happens. Maybe there is some doccumentation or anything what should i do to get listener work? I were thinking should i do something also in config.json file?
![tracking not working](https://user-images.githubusercontent.com/111095604/184258246-24e35104-9746-48c8-8654-f9f5b47c4f04.png)
Here are all the campaigns i tested on my gmail account, also i opened all of them, i tried different options of listener.
![tracking not working2](https://user-images.githubusercontent.com/111095604/184258404-89ca5707-5589-4f7e-aa9e-e08a2ca2160d.png)
Here is my config.json file (i deleted ip ending) but it still dont track opened emails....

What are you expecting to see happen? :

What are you seeing happen?
Tracking opened emails
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by quentingosset** [comment]
Your address is local (0.0.0.0) so the mail sent has a tracking link that points to an "image" of 1px/1px to the address 0.0.0.0 which does not load because it tries to contact the address 0.0.0.0 which is local so does not exist on the internet. I had the same case ;)

**Comment by cyberhax1** [comment]
> Your address is local (0.0.0.0) so the mail sent has a tracking link that points to an "image" of 1px/1px to the address 0.0.0.0 which does not load because it tries to contact the address 0.0.0.0 which is local so does not exist on the internet. I had the same case ;)

Got it. But what did you do to resolve this issue? For example, i use digitalocean server, i should change the admin & phish server listener URL in config.json to my Digital ocean ip without changing :ports?

**Comment by quentingosset** [comment]
You have to make your gophis server available on the internet. 
Actually what happens is that you are local so : 
1) When you send the mail to test@test.com, you receive the mail correctly in your mailbox.
2) You click on the mail, it redirects you to your LOCAL phishing server -> Since it's your own machine, your server is running so YES, the page works for YOU. 
EXCEPT... the mail you received on your gmail mailbox will try to access the image 0.0.0.0:3333/trackingimg.png but gmail can't access this image.
3) Try to send the email to a friend, and ask him to open the phishing site, you will see, he will not have access because you redirect him to a local server that he does not have.

So yes, you have to make your server accessible to the outside world so that gmail will be able to load the tracking image and your "external friends from your network" will be able to access the phishing domain

**Comment by glennzw** [comment]
If you view the email source you'll see the tracking pixel at the bottom. Manually click that and see if it loads. e.g:

<img width="931" alt="Screenshot 2022-08-12 at 19 47 07" src="https://user-images.githubusercontent.com/3966613/184414811-b1f18817-d2ce-4edc-806f-800720d4857f.png">




Here's the template HTML from the above email:

```html
<html>
<head></head>
<body>
<p>Hello {{.FirstName}}, please click <a href="{{.URL}}">here</a></p>
{{.Tracker}}</body>
</html>

```

**Comment by cyberhax1** [comment]
Hello! Thanks for replies! I solved the issue simple by editing config.json IP to 0.0.0.0:443 and also adding SSL. and in listener i also put domain https://mydomain.com
