### ISSUE TITLE
Help with Continuous Integration failing

### ISSUE THREAD

**Issue by glennzw** [gophish/gophish#2567]
The Continuous Integration workflow ([here](https://github.com/gophish/gophish/blob/master/.github/workflows/ci.yml)) is failing on the 'Get Depdendecy' step for go1.11 and go1.12, and I can't work out why:

<img width="437" alt="Screenshot 2022-08-26 at 12 53 44" src="https://user-images.githubusercontent.com/3966613/186888762-927d1677-bc5c-484a-aa46-75151fd12667.png">

https://github.com/gophish/gophish/runs/8017009399?check_suite_focus=true

It succeeded two weeks ago, and I can't see any major changes that would have caused this:

https://github.com/gophish/gophish/runs/7812586053?check_suite_focus=true

Running the 'Get Depedency' command locally doesn't throw any errors, just the same warning as seen in the github ouput:

```bash
➜  gophish-master $ go1.11 get -v -t -d ./...
go get: -t flag is a no-op when using modules
➜  gophish-master $
```

It seems to have started failing after I [bumped the version to 12](https://github.com/gophish/gophish/commit/6b61426aabc237398ae465ca6921c6d3d653e3c2) (which involved just changing the contents of the VERSION file from 0.11.0 to 0.12.0):

<img width="350" alt="Screenshot 2022-08-26 at 13 00 25" src="https://user-images.githubusercontent.com/3966613/186889918-ff26d7bc-c4a2-4139-9ebf-412141f2863e.png">

Any insights would be appreciated.

**Comment by glennzw** [comment]
It looks like it might be due to this:

https://github.com/mattn/go-sqlite3/commit/595e13285d510654c5a85402f5084f9d429f380c

(and just coincidental timing with my version bump)

**Comment by edermi** [comment]
Go 1.12 is also quite dated. Maybe it is a good idea to jump to a even more recent version? Modernizing some of GoPhish's structures is something that will become necessary at some point, especially as we cannot expect dependencies to support old Go versions for so long.

**Comment by glennzw** [comment]
Thanks @edermi - I'd agree it does seem reasonable to jump to a much more recent version of Go. I'm trying to find a way to test this CI without doing a push every time (perhaps I can create a private fork to test this).

Do you have anything in mind in terms of modernising gophish's structures? If you have specifics in mind perhaps we could start a discussion thread, or open an RFC issue.

**Comment by edermi** [comment]
Allegedly it is possible to create a manual trigger in the CI config which can be started from the web interface: https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960

Regarding modernising gophish, I have some things in mind:

- Switch to a recent Go version
- As discussed in https://github.com/gophish/gophish/pull/2528, Gorm matured a lot since it was introduced to GoPhish and the Goose version used is unmaintained. If the database migration feature of Gorm is sufficient to our use cases, Goose may be removed completely. 
- Once a recent version of Gorm is in use, it is possible to switch to the native Go sqlite implementation (https://github.com/glebarez/go-sqlite) - it is slower, but we don't require any C code anymore which improves portability, removes the requirement for gcc, and probably there are less dependencies to carry around
- Update and revisit all dependencies. Maybe other dependencies matured, too, bringing nice additional capabilities or allow us to remove other dependencies / workarounds.

Maybe we should take this into a separate issue and discuss potential fields of improvements there.

**Comment by glennzw** [comment]
We're green again:

<img width="221" alt="Screenshot 2022-09-12 at 22 08 51" src="https://user-images.githubusercontent.com/3966613/189759384-4ec1bddf-159a-4107-a76d-e926ddf2d75e.png">

🎉
