### ISSUE TITLE
Training-Option when user clicks on link / entered credentials

### ISSUE THREAD

**Issue by hheile** [gophish/gophish#257]
Hello there,

thank you for your project. It really helps me for the awareness-training of my users. 
I have some requests about new ideas, which i've seen somewhere before.

this should have two options:
1) training-landing-page comes up when target clicks on the link
and/or
2) training-landing-page comes up when target enters credentials somewhere

(can be choosen).

landing page could be something like this:
Your company set up a security awareness programm. this programm simulates a phishing-attack to you. When you see this page it means, you fell in. 

....

something like that. 

best regards
hheile

**Comment by jordan-wright** [comment]
Hi @hheile, implementing training pages is absolutely on our roadmap. We're working out the best way to handle this, but big strides towards this will happen when #223 and #127 are knocked out.

Since this is a bit of a duplicate from both of those, I'm going to go ahead and close this out. Keep an eye on those issues, since that's what we're actively working on :smile:
