### ISSUE TITLE
 501 Error: Bad sender address syntax

### ISSUE THREAD

**Issue by syh4ck** [gophish/gophish#2624]
Hey Guys Im facing an issue with the latest version of gophish, 

The sending profile MAIL from Input : `First Name <test@example.com>`, 

Even after entering in above format I'm getting 
 501 Error: Bad sender address syntax

Need help ?

**Comment by glennzw** [comment]
I've seen this a few times recently; I'm guessing you're using Outlook / O365? Can you try with just `test@example.com` and let me know if that works?

Do older versions (e.g 0.11) work?

**Comment by syh4ck** [comment]
Hi Glennzw,

Both approaches I tried didn't work. I finally got the previous version and am now using it.

**Comment by glennzw** [comment]
Would you be able to help me get to the bottom of this issue in the newer versions?

If you could share which email provider you're using and I'll try replicate it on my side. I think it's probably got to do with this PR: https://github.com/gophish/gophish/pull/2334

Further discussion [here](https://github.com/gophish/gophish/pull/2334), where Mailgun seems to be the culprit.

**Comment by righter83** [comment]
I've got the same on my own postfix mailserver:

`warning: Illegal address syntax from mail[2a03:4000:3e:XXX in MAIL command: <XXX XXX <XXXX@XXXX>>`

**Comment by drego85** [comment]
Same problem here with last version 0.12.1:

```
level=warning msg="501 <Support Test <support@EXAMPLE-DOMAIN.com>>: \"@\" or \".\" expected after \"Support\"" code=501 email="\"Andrea D\" <andrea.d@xxxx.net>"
level=error msg="501 <Support Test <support@EXAMPLE-DOMAIN.com>>: \"@\" or \".\" expected after \"Support\""
```

Therefore it is not possible to specify the textual name sender of the email.

**Comment by troplolBE** [comment]
I got the same issue on my side and did some research. The issue was introduced in the #2334 PR. I was able to work around it by just changing the code and use the old `send` function instead of the new `SendCustomFrom` function.

I did some debug and I saw that the smtp_from variable in the picture here under does not contain the surrounding `<>` characters. It must been added afterwards but I haven't found where.

https://github.com/gophish/gophish/blob/cec2da512890e4e5fe893aaf2a223a501408370d/mailer/mailer.go#L171

Hope this helps.

**Comment by troplolBE** [comment]
Hi @glennzw @syh4ck 

I did some digging about this issue and got to the bottom of it. The problem comes from the default smtp implementation of go. The gomail package uses the Mail function in its Send function in the smtp.go file as shown below.

![image](https://user-images.githubusercontent.com/12971225/203517164-24cc493a-d414-4979-b65e-5125a2b41091.png)
https://github.com/gophish/gomail/blob/1f6d0dfd512ee80d9926a04a5e53986d4ae07d82/smtp.go#L169

The `Mail` function is part of the default smtp implementation of the Go SDK. The function validates the content of the from parameter and uses the `cmd` to put it in the right format and send the command to the smtp server. The function formats strings as sprintf and we can see that the format string is like this

![image](https://user-images.githubusercontent.com/12971225/203518068-47e057f4-6b54-41db-8b58-65c775041dd0.png)
And is formatted like this

![image](https://user-images.githubusercontent.com/12971225/203518178-bb019993-86b1-4bcf-9df5-4f2525790ff5.png)

The error will prevail as long as we make use of the native `Mail` function from the native smtp implementation.

Maybe using a different package than gomail could do the trick ? A custom implementation of smtp could maybe also do the trick.

**Comment by glennzw** [comment]
Hi @troplolBE - thanks so much for digging into this. It's been on the top of my stack to figure this out but things have been a bit busy. I concur with your latest point - I too read the RFC and agree - https://twitter.com/glennzw/status/1532737173497192449

Running some MiTM tests we can see the difference between the successful v11 and failing v12:

v11:
```
220 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa Python SMTP proxy version 0.2
EHLO localhost
502 Error: command "EHLO" not implemented
HELO localhost
250 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
MAIL FROM:<first@last.com>
250 Ok
RCPT TO:<glenn@foo.com>
250 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Mime-Version: 1.0
Date: Wed, 23 Nov 2022 17:25:21 +0000
X-Mailer: gophish
Subject: Default Email from Gophish
To: "Glenn Wilkinson" <glenn@foo.com>
From: "First Last" <first@last.com>
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
It works!
This is an email letting you know that your gophish
configuration was successful.
Here are the details:
Who you sent from: First Last
Who you sent to:=20
Now go send some phish!
250 Ok
QUIT
221 Bye
```

v12:
```
220 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa Python SMTP proxy version 0.2
EHLO localhost
502 Error: command "EHLO" not implemented
HELO localhost
250 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
MAIL FROM:<First Last <first@last.com>>
250 Ok
RCPT TO:<glenn@foo.com>
250 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Mime-Version: 1.0
Date: Wed, 23 Nov 2022 17:20:48 +0000
To: "Glenn Wilkinson" <glenn@foo.com>
From: "First Last" <first@last.com>
X-Mailer: gophish
Subject: Default Email from Gophish
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
It works!
This is an email letting you know that your gophish
configuration was successful.
Here are the details:
Who you sent from: First Last
Who you sent to:=20
Now go send some phish!
250 Ok
QUIT
221 Bye
```

So the updates to v12 changed the `MAIL FROM` from:

`MAIL FROM:<first@last.com>`

to

`MAIL FROM:<First Last <first@last.com>>`

So I think your PR is spot on - thank you! I'll give it a proper test later.

**Comment by glennzw** [comment]
The difference is that in v11 we set the Mail Envelope (in the email headers) to the name in angle brackets- whereas in the newer v12 we have the option to set Sender Envelope manually in the Email Template.

So this means that in the Sending Profile we can only set `MAIL FROM` which means when we send a test mail it can fail here. We could add the Sender Envelope option in the dialog for the Test Mail popup, but that seems a bit clumsy.

**Comment by glennzw** [comment]
This should be fixed now with the latest code release. See https://github.com/gophish/gophish/pull/2669
