### ISSUE TITLE
Looking for some (paid) help to set up GoPhish on a Mac

### ISSUE THREAD

**Issue by matoboltd** [gophish/gophish#2626]
Hi Glenn.

Just following up from our Twitter convo.

Context - I'm a more basic Mac user, I'm used to having a .DMG file and installing an app, and I'm getting lost in the language of "binaries" etc. 

I'm looking for somebody to help (happy to pay for your time, of course) to set up a GoPhish instance on one of our office Macs and to help with fine-tuning the set up.

Cheers,

Ben.

**Comment by glennzw** [comment]
Hi Ben,

You can download the Mac binaries here: 

https://github.com/gophish/gophish/releases

(or direct download link for Mac: https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-osx-64bit.zip)

To set it up you'll need to unzip that folder, open your `Terminal`, navigate to the folder and run the `gophish` binary. e.g:

```sh
cd Downloads
cd gophish-v0.12.1-osx-64bit
chmod +x gophish
./gophish
```
 
The bigger question is why you want to run it locally on your laptop, rather than a server on the internet. If you send out a phishing campaign people clicking the links won't be able to hit your phishing server if it's on your local network (unless the targets are on the same local network in a classroom environment or something).

**Comment by matoboltd** [comment]
Hi Glenn.

Can I have a private conversation with you, please?

This is not something I’d like to discuss in an open forum.

Thanks.

**Comment by glennzw** [comment]
Sure! Drop me an email or head back over to Twitter

**Comment by glennzw** [comment]
Sure! Drop me an email or head back over to Twitter
