### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by bossmunya** [gophish/gophish#2650]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
gophish v0.11.0.
Brief description of the issue: 
ssl certificate not showing as secured 
NET::ERR_CERT_AUTHORITY_INVALID
What are you expecting to see happen? :a
A green lock showing its https secured
What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
certificates
Please provide any terminal output that may be relevant below:
NET::ERR_CERT_AUTHORITY_INVALID
Insert output here
```NET::ERR_CERT_AUTHORITY_INVALID

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - installed an ssl certificate with certbot
 * Step 2 -tried to open the site

**Comment by glennzw** [comment]
Did you copy over the certificate generated and/or update your `config.json`?

See: https://www.n00py.io/2017/09/phishing-with-gophish-and-letsencrypt/

**Comment by jordan-wright** [comment]
As @glennzw called out, we do have some community guides on integrating with LetsEncrypt that you might find helpful.

That said, without more information we won't be able to troubleshoot this. Please let us know the exact steps you took configuring certbot, provide any logs you can find, etc.

Any information helps!

For now since this has been open for quite a while I'll close this out. We can always re-open if you're still encountering the issue and can provide troubleshooting logs.
