### ISSUE TITLE
E-mail immediately showing up as opened, while not opened

### ISSUE THREAD

**Issue by natanvdmeulen** [gophish/gophish#2679]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
Latest
Brief description of the issue: 
I've send a test email to 4 of my coworkers to check if the tracker and trackerURL are working. None of my coworkers opened the mail nor clicked the URL in it, but it shows up as opened immediately.

What are you expecting to see happen? :
I expected the Emails opened counter to be 0 until one of them opened it.

What are you seeing happen?
The number goes up immediately.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Template:
Beste {{.FirstName}},<br><br>
<b>Graag nodig ik je uit voor een exit-gesprek.</b><br>
Zou je <a href="{{.URL}}">dit</a> formulier van tevoren willen invullen?<br><br>

Met vriendelijke groet,<br>
Jochem Meijer

{{.Tracker}}

**Comment by jordan-wright** [comment]
It’s likely the case that there’s some anti-spam appliance that’s intercepting the email and loading the URLs it sees to try and determine if the pages are safe.Since this involves visiting the tracking URL, the email shows up as “opened”.There’s no good way around this on the Gophish side since we only look for whether or not the tracking URL was visited.On Nov 30, 2022, at 8:56 AM, natanvdmeulen ***@***.***> wrote:﻿
Thanks for reaching out! We're happy to help resolve issues as quickly as possible.
Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation, which covers how to use Gophish.
What version of Gophish are you using?:
Latest
Brief description of the issue:
I've send a test email to 4 of my coworkers to check if the tracker and trackerURL are working. None of my coworkers opened the mail nor clicked the URL in it, but it shows up as opened immediately.
What are you expecting to see happen? :
I expected the Emails opened counter to be 0 until one of them opened it.
What are you seeing happen?
The number goes up immediately.
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:
Template:
Beste {{.FirstName}},
Graag nodig ik je uit voor een exit-gesprek.
Zou je dit formulier van tevoren willen invullen?
Met vriendelijke groet,
Jochem Meijer
{{.Tracker}}

**Comment by dehinde007** [comment]
I'm using gophish 0.12.1 which is hosted locally on my kali machine. I have launched a campaign and messages are delivering but the tracker doesnt work and thus not providing any metric. I'm thinking if I need to host his on a Public VPS for the tracker to work?

**Comment by natanvdmeulen** [comment]
Thanks for the reply! It always happens with the same companydomain, so I guess you are right. :)

**Comment by dehinde007** [comment]
@natanvdmeulen for email tracking to start working, do I have to host gophish on a public VPS/server?

**Comment by natanvdmeulen** [comment]
> 

@dehinde007 If you want email tracking to work outside of your own host, you'll need some kind of VPS/Server indeed. The 'image' that will be sent with our email will have a Listener URL, to know if the mail has been opened. If you run gophish locally, the URL will be http://localhost?rid=something, so you wont be able to check it.

**Comment by natanvdmeulen** [comment]
@dehinde007 depends how you set it up. Did you add a {{.Tracker}} to your email? did you specify your domain/IP when hosting a domain?

**Comment by dehinde007** [comment]
There is a {{.Tracker}} in my email that's why i'm able to track opened emails. I don't understand what you mean by when hosting a domain. I didn't host anyother thing apart from gophish on a VPS.

**Comment by dehinde007** [comment]
@natanvdmeulen There is a {{.Tracker}} in my email that's why i'm able to track opened emails. I don't understand what you mean by when hosting a domain. I didn't host anyother thing apart from gophish on a VPS.

**Comment by natanvdmeulen** [comment]
@dehinde007 what's the ip of your VPS?

**Comment by dehinde007** [comment]
@natanvdmeulen 206.189.112.164

**Comment by natanvdmeulen** [comment]
@dehinde007 did you change your config.json? To be able to reach your admin panel and your listeners URL from anywhere, you should change both IPs to 0.0.0.0

**Comment by dehinde007** [comment]
@natanvdmeulen I have already taken this step. And to just confirtm, any link I create on the email template is automatically supposed to get tracked right. Or is there a special way to create links that you want to track?

**Comment by natanvdmeulen** [comment]
@dehinde007 
There are a few types of Trackers. {{.Tracker}} will add an image to your email. When the image 'loads' the email has been opened. {{.URL}} will add the URL landing page into your email. When this one has been clicked the 'Clicked Link' counter will add up

**Comment by dehinde007** [comment]
@natanvdmeulen so where exactly does the link to the landing page go? in an <a> tag?

**Comment by natanvdmeulen** [comment]
<a href="{{.URL}}">I'm a link</a>

**Comment by dehinde007** [comment]
@natanvdmeulen This is what appears in my mail. < a href="http://x.x.x.x?rid=OsVLfCh"> Click me</a> My VPS Ip appear in the link and isn't masking.

**Comment by dehinde007** [comment]
@natanvdmeulen Ok great it works. Thank you very much for the support.

**Comment by natanvdmeulen** [comment]
@dehinde007 I just figured it out myself 3 days ago haha. Glad I could help.

**Comment by dehinde007** [comment]
@natanvdmeulen Lol. Nice. Are you a security researcher? and about attachments, have you tried tracking those as well?

**Comment by natanvdmeulen** [comment]
@dehinde007 I'm doing research about security within an organisation. I've tried the attachments, but it looks like microsoft doesn't allow image objects anymore. So I haven't figured out a different way. Also, gophish documentation says you can only track one thing at a time. So it would either be a clicked link or an opened attachment.

**Comment by glennzw** [comment]
Closing this one out, seems everything was answered.
