### ISSUE TITLE
XSS, Replay requests without CSRF, cookies

### ISSUE THREAD

**Issue by alou1** [gophish/gophish#273]
Hi!
First, thanks a lot for this nice tool.

I confirm. Stored   XSS  (#272 issue)  vulnerabilities are present in almost all forms.

And I found that almost all requests are not restricted by the csrf_token or the cookies. I tried to replay many requests like adding/deleting templates, groups, ... and registering new gophish users with empty cookie and/or without csrf-token and the requests are accepted and work without restriction. I don't think that's normal.

Also, I'm trying to add somethings like getting targets through theHarvester, delaying email manually. But it's not easy for me because I'm not golang friendly :)

**Comment by jordan-wright** [comment]
Hi there,

Thanks for the report! What version of gophish are you using? The xss is something we're working to fix. Fortunately, the attack exposure is relatively small - someone has to already be logged in as the admin to save the payload.

Re: CSRF - everything on the UI uses your API key to query the API. I'm open to correction, but I don't see a use case here, as someone would need your API key to be able to replay requests. By the time they have that, it's game over anyway.

Thanks again for this report!

**Comment by alou1** [comment]
You're right! 
It's not really an attack exposure. :)
It's just that I don't think cookies and csrf token are  checked when a (post) request is sent. 
But it is not a real attack exposure.
Thanks for your  availability!

**Comment by jordan-wright** [comment]
It depends on what you're referring to. Cookies/CSRF are not employed on backend ajax calls since everything is done via the API key unique to your account. If an attacker gets this api key, it's game over anyway... Unfortunately, this is one of the risks of having an api-based platform as opposed to a straight-ui form based platform.

For now, I'm going to go ahead and close this out, since it's a confirmation of #272 which will stay open until the issue is fixed.

Thanks for the report!
