### ISSUE TITLE
Issue with on behalf of 

### ISSUE THREAD

**Issue by eberg2** [gophish/gophish#2753]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
0.12.1

Brief description of the issue: 

Trying to send emails but they always appear as Spotify <no-reply@spotiify.com> on behalf of domain@phishing.com

I have seen that there are lots of information out there in regards to this and it seems to point to Return-path Address 
 

I have tried to set that in headers but it seems to not get set

Looking at the email i can see it is set too 
Its: Return-Path: <bounce+cd5234.c3e85-***=gmail.com@domain-phishing.com>

And below i can see that my custom headers gets set
Return-Path: ":" <no-reply@spotiify.com>
Sender: ":" <no-reply@spotiify.com>

Is this expected or a bug or is it a bad config at any part?

**Comment by glennzw** [comment]
There are two values to set:

1. SMTP From
This is set in your Sending Profile. It's part of the SMTP protocol. This should be an email address only.

2. Sender Envelope
This should match the SMTP From, but some providers will allow it to be different. It's a header set in the email header, rather than part of the SMTP protocol. You can set a name too, e.g `Bob Smith <bob@foo.com>`

**Comment by glennzw** [comment]
Closing out as haven't heard back. Feel free to reopen.
