### ISSUE TITLE
SMTP From

### ISSUE THREAD

**Issue by snackshih** [gophish/gophish#2766]
Hi All,

When I created "Sending Profile", the SMTP From input is: "Company Test <Support@Supportgmail.com>".
But when I test sending and receiving letters, the name of the sender is different from the SMTP From I set. How can I troubleshoot this problem?

![sending-profile](https://user-images.githubusercontent.com/52151061/219302117-7a04e9c6-f125-41f6-9746-5058166416a4.jpg)

![gophish-issue](https://user-images.githubusercontent.com/52151061/219302106-7d2418bd-d8fd-422c-addb-e4caf19d9b73.jpg)

**Comment by glennzw** [comment]
There are two values to set:

1. SMTP From
This is set in your Sending Profile. It's part of the SMTP protocol. This should be an email address only.

2. Sender Envelope
This should match the SMTP From, but some providers will allow it to be different. It's a header set in the email header, rather than part of the SMTP protocol. You can set a name too, e.g `Bob Smith <bob@foo.com>`

**Comment by snackshih** [comment]
Hi glennzw, thank you for your reply.
I'm currently testing my settings in the sending profile:

SMTP From: 123@456.com "<abc@xxx.com>"
Username:: abc@xxx.com
But I received a letter and saw that it still shows **abc@xxx.com**, which is not the same as what I set in SMTP From.

How can I set the Sending Profile so that the sender's name is different from my email address?

**Comment by glennzw** [comment]
Please share a screenshot of:

1. Your Sending Profile
2. Your Email Template

**Comment by snackshih** [comment]
I think I know what the problem is, thank you glennzw.

**Comment by samsmg** [comment]
I want to send an email using example@outlook.com and I want it to appear as envelop sender example2@gmail.com, how do I do it?
