### ISSUE TITLE
error

### ISSUE THREAD

**Issue by miexuwang** [gophish/gophish#2925]
[root@sc gophish]# go build
# bitbucket.org/liamstask/goose/lib/goose
../go/pkg/mod/bitbucket.org/liamstask/goose@v0.0.0-20150115234039-8488cc47d90c/lib/goose/dialect.go:119:15: undefined: sqlite3.Error

**Comment by migguel0** [comment]
This is a problem between CGO and Cross Compiling. Because SQLite is developed using C language. When cross-compiling is used maybe, some of the features don't work as expected.

You could try to build the project through this command:
`env CGO_CFLAGS="-g -O2 -Wno-return-local-addr" GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build`

Also you need to install `gcc` in your host.

This worked for me... I hope it will be helpful
