### ISSUE TITLE
Campaign copy doesn't include groups

### ISSUE THREAD

**Issue by rcutmore** [gophish/gophish#295]
When copying a campaign the groups aren't included. An error is encountered [here](https://github.com/gophish/gophish/blob/master/static/js/app/campaigns.js#L205) when attempting to add groups to the new copy. From what I can see this is because campaign groups aren't currently being tracked in the database. It seems like a *campaign_groups* table would need to be added to the database to track this.

**Comment by jordan-wright** [comment]
Yeah, this was kind of an early on design decision to store the actual users for every campaign instead of the groups so that, if the groups change, we can still know who was originally targeted.

I'm not sure there is a clean way to keep track of both the groups used as well as keeping the original targets without storing duplicate information. If you have any thoughts - I'm definitely open to options!

**Comment by rcutmore** [comment]
That's a good point. Off the top of my head I can think of a few options, none of which are ideal.

1. Create a *campaign_groups* table to track the groups. This stores duplicate information and the group members might change between campaigns.

2. Add a *group_id* field to the *results* table for looking up the original groups. This muddies up the database schema and the group members might change between campaigns.

3. Don't try to copy groups to a new campaign and remove the JS code trying to do so. Assume the user will manually add the desired groups to the new campaign.

**Comment by jordan-wright** [comment]
Lets do option 3 for now. It's cleaner and matches what currently happens.

Thank for putting this together!
