### ISSUE TITLE
Cannot attach zip or rar files

### ISSUE THREAD

**Issue by do-nan-fer** [gophish/gophish#2954]
What version of Gophish are you using?: 
0.11.0

Brief description of the issue: 
Email are not sent when .zip, .rar or .exe files are attached.

What are you expecting to see happen? :
I'd like to send a phishing campaign with .zip or .rar files attached.

What are you seeing happen?
no email sent.

does GoPhish support .zip or .rar files. if not, is there anything I can do to make it work.

**Comment by jordan-wright** [comment]
I'm afraid there isn't enough information here for us to troubleshoot. My assumption is that the email provider you're using to send from, or the recipients email provider is dropping any email containing attachments with those file types (for good reason!)

Since I assume you're using this for an authorized test, you can look at logs from the recipients email server to determine if it's the case. If it is, you may need to adjust the server settings to allowlist your gophish server's IP address in order for emails to not be dropped.

There isn't any logic I'm aware of in Gophish to drop these types of attachments, so I'm going to preemptively close this one out. If you have logs or other information to suggest this is a bug in Gophish, please provide all the information you have and we can always re-open this!

**Comment by do-nan-fer** [comment]
yes. do you know if it's supported. has anyone tried to send a zip file.

**Comment by jordan-wright** [comment]
It should be supported just fine. Attachments to Gophish are nothing more than a set of bytes.

**Comment by do-nan-fer** [comment]
do you know something about this functionality. has anyone tried it?

https://github.com/gophish/gophish/pull/2759
