### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by prashanth9911** [gophish/gophish#2987]
Hi team,

my Gophish environment is ready, when I try to send a test mail on the sending page I get an error like

 Max connection attempts exceeded - 535 5.7.8 Error: authentication failed:

I have entered the correct password for the user account. Could you help me how to fix this issue?

Kind Regards.
prashanth N

**Comment by jordan-wright** [comment]
I'm afraid there is not enough information here to help troubleshoot this issue.

In this case, the error you are receiving is from the email provider, not Gophish. I would encourage you to search through other issues, and review the logs from your mail server to determine what the underlying issue is with the credentials being used.

Sorry we can't be of more help!
