### ISSUE TITLE
Disable realtime view

### ISSUE THREAD

**Issue by AStrunk** [gophish/gophish#309]
Hi,

When running large campaigns (+300 emails) the .js just locks the browser (any browser). The only way to see results is to go through the API and sort results there manually.
It could be nice if there was a way to stop the real-time refresh of the map and results, so that large datasets wouldn't stop the browser from responding.

Br,
A

**Comment by jordan-wright** [comment]
Hey @AStrunk - I bet I can make this happen. Let me see what I can do.

**Comment by AStrunk** [comment]
Hi @jordan-wright 
Perfect! Thanks for the response.

Br,
A

**Comment by andyg1** [comment]
This is killing me too. It's more or less impossible to view any stats using the webpage. My feeling is that the rendering of the map is killing the browser - I'm seeing 99%+ CPU on the active tab in Chrome. The map hasn't been useful for any of the campaigns we've run, so it would be nice if there was a dumb-downed results page to view. At the moment, the only use we make of the results page is to click the "download csv" button, which is impossible because the page is already locked out by that point.

**Comment by Backhouse90** [comment]
Does anyone know the upper limits of a campaign without the browser crashing . We're hoping to start a campaign in my organisation soon and were originally thinking around 300 - 500 users at a time. For example, has anyone found that the browser can cope with say 200 emails?

**Comment by andyg1** [comment]
I was working on a mid-2009 Macbook Pro with 4GB of RAM (I think) and a campaign with 1000+ mails was impossibly slow on the reporting page. In the 100s it doesn't seem too bad, but escalates quickly. It's a combination of the system you are using and the number of emails. With more horsepower, you may have happier times.

**Comment by jordan-wright** [comment]
This has been fixed in recent versions of Gophish. The polling is optional and the new poll interval is one minute instead of 10 seconds.

If you're still running into issues using the latest source, let me know and we can troubleshoot.
