### ISSUE TITLE
Template variables in Landing Pages

### ISSUE THREAD

**Issue by javiorcoyen** [gophish/gophish#327]
Hi,

I've created a campaign with the following email:

```
Dear {{.FirstName}},

Please access the following link:
{{.URL}}

```

And the following landing page:

```
<html><head>
	<title></title>
</head>
<body>
<p>Hi {{.FirstName}}, this was a phishing simulation </p>
</body></html>
```

When I receive the email the user's name appears correctly, although when I click on the link, the landing page doesn't show the name of the user, it just shows: 

> "Hi {{.FirstName}}, this was a phishing simulation"

Is there a way to show on the landing page the name of the user who clicked on the link? 

Thanks,

**Comment by jordan-wright** [comment]
Your closing brackets after FirstName need to curly brackets, not square brackets.

**Comment by javiorcoyen** [comment]
Sorry, it is closed with curly brackets, but still not working.

**Comment by msobell** [comment]
Agree -- this would be a very useful feature.

**Comment by jordan-wright** [comment]
Oh snap - my bad. This isn't implemented when I thought it was.

I'll get this knocked out this weekend if not earlier. Sorry for the inconvenience. Good catch!

**Comment by msobell** [comment]
Awesome!

**Comment by jordan-wright** [comment]
Ok, should be fixed. Let me know if you run into any issues!

**Comment by jordan-wright** [comment]
It should be noted that it's only setup to work for things that are part of the target (first name, last name, email, etc.). The {{.URL}} will not work right now - I'll have to make some more changes for that.

**Comment by javiorcoyen** [comment]
It works perfect now, thanks!!

**Comment by KampaiDiscount** [comment]
Gophish rulez ! , is there any place to share landing pages and email templates like this one ?
<html><head>
	<title></title>
 <center> <img src="http://personalsystems.co.za/wp-content/uploads/2017/08/Office365-Page.jpg" width="830" height="400"></center>
</head>
<body>
  <p style="text-align:center;"
<p>
  <b> Please log in to your Microsoft<sup><sup><sup>TM</sup></sup></sup> account to continue.</b><br>
  </p>
<p style="text-align:center;"
<form action="" method="POST">Username:<br/>
<input name="fname" type="text"/><br/>
Password:<br/>
<input name="password" type="password"/><br/>
<input type="submit" value="Submit"/> </form>
</p>
<img src="https://assets.onestore.ms/cdnfiles/external/uhf/long/9a49a7e9d8e881327e81b9eb43dabc01de70a9bb/images/microsoft-gray.png" alt="Girl in a jacket" width="120" height="25">
</body></html>

**Comment by KampaiDiscount** [comment]
GOPHISH RULEZ !!! Is there any place to share email templates and Landing pages like this one ?
[office365.txt](https://github.com/gophish/gophish/files/1464280/office365.txt)

**Comment by mehervez** [comment]
Hi Jordan

I am using the windows 64 bit version of gophish and really find it to be quite different from the 32 version. This particular feature mentioned by javiorcoyen  here doesn't seem to be working for me as well. To summarize the template variables work fine for the email template but not for the landing page. I am trying to use the {{.Email}} - The target's email address so that the user does not have to key in the email address but it simply displays "{{.Email}}" instead of the users email address on the login page.

Landing page uses the email template as follows:

<div id="userNameArea"><input autocomplete="off" class="text fullWidth" id="userNameInput" name="UserName" placeholder="someone@example.com" spellcheck="false" tabindex="1" type="email" value="{{.Email}}" /></div>
