### ISSUE TITLE
Constant crashing on multiple servers

### ISSUE THREAD

**Issue by rserowik** [gophish/gophish#332]
I have been trying to use GoPhish (version 0.1.2) for the past week and have encountered consistant crashing/hanging.

My first attempt was on an Amazon AWS Red Hat micro instance, and my second was on an AWS Windows Server Base micro instance.

In both cases, I am able to run the application and create records of every kind without an issue. After a period of an hour or so, I run into multiple Issues. The most common problem, or symptom, is when I try to load a page, any page with the exception of Settings, the page will display the spinning/loading image and not load any existing records. Sometimes, I receive an error about a failure reading from the database, which clears up after several page refreshes. Sometimes restarting the application helps, and sometimes it does not. 

At this time, I am running GoPhish on an AWS Windows Server Base micro instance and am experiencing the problem where I constantly see the loading icon on every page, except for Settings. I have restarted the application - closed gophish.exe and restarted - and the problem is still occurring. 

Is this a known issue, or is it possible I'm doing something wrong? The gophish.exe console does not display any errors - only information about web requests.

Thanks in advance.

- Rob

**Comment by jordan-wright** [comment]
I would recommend trying something with a bit more resources. Windows Server on a t2.micro instance seems to be awfully constrained - even for gophish's low memory footprint.

I would also recommend building from source until we release the new version (coming soon!), since there have been significant changes and feature additions.

Thanks for the report! Let me know if there are any debug logs being printed to the console - that will help us troubleshoot further.

**Comment by jordan-wright** [comment]
Closing this as I haven't heard back in a while. Let me know if the problem persists after using a larger instance.

Thanks for the report!
