### ISSUE TITLE
Live website?

### ISSUE THREAD

**Issue by moeops** [gophish/gophish#347]
What if I am sending the phishing e-mails from a computer outside of the company server? I have a simple login page on a hosting website. How do I link this to gophish? 

GoPhish works fine when I place the URL as my internal IP. But I need to send a company-wide e-mail and my internal IP will not cut it; and so I made a simple login page and got it hosted on a free hosting website and I have the link to that website.

How would I go about doing this? I installed gophish, made some profiles, tested the send e-mail function and it worked, now I just need to know how to setup the external aspect of it.

**Comment by CoreyMcCown13** [comment]
You would have to have to configure the firewall for the company server to allow connections to the GoPhish server from outside. You would likely only need port 80, and 443 if you enabled TLS.

If you wanted to use a website hosting company, you would probably need to get a VPS so that you have terminal/command line access - this likely wouldn't be free.

**Comment by jordan-wright** [comment]
Correct - thanks @CoreyMcCown13!

**Comment by moeops** [comment]
@CoreyMcCown13 Sorry to bother you, but let's say I purchase a VPS. How would I go about using terminal/cmd to fire up GoPhish?

I will inform the hosting company, thank you so much for the tip.

**Comment by jordan-wright** [comment]
You will need ssh access, which is standard for most vps hosting providers.
