### ISSUE TITLE
Feature Request: Multiple SSL/TLS Landing Pages 

### ISSUE THREAD

**Issue by anance25** [gophish/gophish#349]
Currently, as i understand it, to have SSL/TLS on your landing page, you have to point to your cert files in config.json.  Given this, it seems that you can only serve up one SSL protected landing page at a time?

Would it be possible to have be able to serve up multiple ssl-protected landing pages simultaneously, each with different domain names and certs?  Perhaps the certs could be uploaded as a part of the Landing Page creation process?

**Comment by jordan-wright** [comment]
Hey @anance25, thanks for this suggestion! I'm afraid I just can't see us implementing this, as it's a pretty unique use case. 

However, if you implement this and would like to submit a pull request, I would be happy to merge it in! Sorry, I just have *very* little time these days, and I have a huge backlog of features I have to knock out that affect the majority of users.

Thanks again for the idea - keep them coming!

**Comment by Raytri3** [comment]
So if I want to enable a TLS landing page I have to configure a config.json file? For example if I have a campaign running with a Linkedin landing page I would have a Linkedin cert in my config. If however I run another campaign for let's say facebook I would have to change the config.json to include a facebook cert.  - it seems to me that making two available at one time may be difficult but having the ability to switch should be "easier". It would be nice if we can select the cert/keys in the UI when we choose https.

**Comment by jordan-wright** [comment]
I'll consider dynamic SSL certs but it won't be implemented anytime soon, since there are quite a few other high priority items to knock out ATM.

A workaround is to have multiple domains in your subject alternate names in your certificate. That way, one cert is valid for multiple hostnames.

**Comment by Raytri3** [comment]
We appreciate the hard work - you have an excellent product.  The alternate names is a good suggestion to keep the switching of certs down to a minimum.

**Comment by Wh1teHat65** [comment]
Jordan,
As all have stated, excellent product.  We left a competitive product to use yours; it's far superior, flexible, more reliable, and when you interact with your user, you don't treat us like an annoyance.  I'd like to chime in on @anance25 request.  We use a series of domains in our phishing campaigns because 
 you get better results if you don't always phish from one (e.g. acme.co) site.  Eventually even the slow users catch on.  If you could 

> add the ability to tie SSL certs to landing pages

 that would be amazing!  There are more people who would seek this option than are sounding off.

**Comment by magnusstubman** [comment]
I'd just like to +1 this and thank you for your awesome product. We definitely appreciate your hard work. I'd also love to be able to host multiple landing pages with different domains+certs.

**Comment by anance25** [comment]
@jordan-wright im starting to think that this might not be such a unique use-case.  Including myself, 4 people have indicated that they would appreciate and make use of a feature that allowed for multiple ssl landing pages. Some people might want want a long-standing gophish box that is used as part of a phishing service, either for internal use or if they are consultants (my case) and needs to easily support simultaneous ssl campaigns.  

On the other hand, i understand that you probably have a long feature-request list and gophish doesnt put food on your table, so you gotta prioritize.  Thanks for you hard work and a great product.

**Comment by nickvangilder** [comment]
Just to echo everyone else, the ability to run simultaneous SSL campaigns would be huge. I cannot understand how this would be considered a unique case. I need to do this about once a week. Anyone who does SE testing as a consultant for many companies is going to need this capability - otherwise, you have to run one campaign, stop it...and then rinse and repeat. I can be 1000% more efficient by having all the campaigns running simultaneously.

**Comment by jordan-wright** [comment]
Hey everyone,

Thank you all for the feedback. Right now, I'm considering merging this with #854 so that you can have the concept of landing hostname configurations. Each would include a domain and an SSL certificate.

When a new connection is received, Gophish will use the server name to decide what SSL certificate to return - it looks like there's some helpers in Go to make SNI possible so hopefully this won't be too much of a challenge.

In terms of configuration, I'm probably going to keep the config.json file as-is, so as to provide a fallback/default cert and keypair.

I'm still working out the details in my head, so feedback on how you could see the UX flow working is appreciated, but just know that we will move forward with this and track it via #854.

**Comment by st3r30byt3** [comment]
Hey Jordan, great to read your last comment :) Have you had any time to implement that? We also conduct multiple campaigns simultaneously and having SSL capability is a requirement.

Not sure if you received any feedback about the UX flow but I would be happy to contribute with some ideas.

GoPhish is already great but has the potential to become perfect imho.

**Comment by chkconfig** [comment]
Hey Jordan, I'd like to start out by saying amazing tool. I also use multiple domains and would like to be able to have them serve valid certificates.
