### ISSUE TITLE
go 1.7 failures

### ISSUE THREAD

**Issue by miked531** [gophish/gophish#354]
I built from source and the master branch is not working with go 1.7 on linux. i get tracebacks when trying to login. the problem is related to a conflict between the gorilla/context module and go1.7 which includes some of that functionality. go1.6.3 works without errors.

**Comment by jordan-wright** [comment]
Thanks for this- I'll see if I can reproduce the issue and will fix any underlying issues.

**Comment by assimilat** [comment]
ditto

**Comment by jordan-wright** [comment]
I've been able to reproduce this issue. I'm working on a fix and will push it out asap.

Sorry for the inconvenience, everyone!

**Comment by jordan-wright** [comment]
As @miked531 mentions, this problem is related to changes introduced in Go v1.7. [Here are the details](https://github.com/gorilla/context/issues/32).

This will be a tricky fix. Honestly, I don't know the best way to fix this without gophish breaking for all pre1.7 users. However, moving forward I'm migrating to the new `context` package and will remove the reliance on `gorilla/context`. It's my hope that this change will fix the issue.

I'll update as progress is made.

**Comment by jordan-wright** [comment]
I owe it to everyone to provide an update on this- I promise this hasn't been ignore.

Quite the opposite. I've been working on this in all my free time for a few days straight.

Here's a summary of what happened:

Golang 1.7 added a feature that adds a [context package](http://golang.org/pkg/context) to the standard library. This can be used to replace other packages, like the gorilla context package that is currently being used by gophish.

But there's a major problem.

When using the new context package to store a new value, it returns a copy of the original request. This means that if you are using another context package *or any library that uses it's own context package* those won't point to the same request anymore, making that context just not work.

Gophish is using the following packages that had their own context manager:

* gorilla/context
* gorilla/mux
* gorilla/sessions
* justinas/nosurf

Fortunately, the gorilla packages have been quick to update and use the new library if available. This is actually what broke gophish to begin with, since people were using the latest versions of the gorilla packages that use the new context. Remember - *all* packages have to use the same thing or it just doesn't work.

As far as CSRF, there's an open issue for a fix, but I haven't seen it done yet. So I've made the decision to switch to gorilla/csrf which provides the same functionality and lets us be a bit more consistent across the board.

Finally, there's the lingering issue of things like managing sessions. There are cases where we do something like this:

* grab the session for the request ("r1")
* store a new variable in the request context ("r2" = copy of r1)
* save the request (now points to r2, which screws things up)

I'm having to fix those where I can, but it's not easy. I'll keep everyone updated.

Thanks for your patience!

**Comment by jordan-wright** [comment]
Ok, I think this is fixed in 103fd72cc8254b45fd94b4517d9ebcf54875e123. @miked531, @assimilat - can one of y'all confirm?

**Comment by jordan-wright** [comment]
Going ahead and closing this for now. Let me know if y'all run into issues and I can re open.

Thanks!
