### ISSUE TITLE
Simulate Smishing campaigns

### ISSUE THREAD

**Issue by seanthegeek** [gophish/gophish#364]
It would be great to simulate SMS Phishing (Smishing) campaigns using a service like Twilio!

https://www.twilio.com/sms

**Comment by jordan-wright** [comment]
Hi @seanthegeek - thanks for the suggestion!

I don't see us adding the ability to run smishing campaigns, since there would be significant overhead required for the user (setting up a twilio account, configuring everything, etc.).

I might revisit this in the future, but for now I'm going to keep gophish targeted to sending phishing emails.
