### ISSUE TITLE
Campaign stuck 'sending'

### ISSUE THREAD

**Issue by Get-Sleep** [gophish/gophish#368]
I have one particular campaign that will not send, it's stuck 'sending'.
The campaign is identical to working ones, except for a new email template i imported.  I have attached the HTML source for this campaign - nothing sensitive in here. 

[TVLIc-Source.txt](https://github.com/gophish/gophish/files/463649/TVLIc-Source.txt)

**Comment by jordan-wright** [comment]
Chances are, something errored out in the template when trying to send emails.

Can you post the complete output from the terminal when you launch the campaign? That will help us diagnose the root cause.

Thanks!

**Comment by hazevedo89** [comment]
Hello @Get-Sleep @jordan-wright ,

We're experiencing the same issue when launching a campaign. We have a distribution list of 700 email adresses. The first ~300 get to the status "EMAIL SENT". The remaining are stuck in "SENDING". We've tried this multiple times, and the behavior is always similar. When we changed the SMTP to google's, the first ~90 emails got to the status "EMAIL SENT" and we got them in our inbox. After 90, google probably blocked us and we got the status "ERROR" until the ~300 email (which is the behavior we're expecting when the emails are rejected). Then the remaining emails were stuck in "SENDING" as well.

We tried to find additional information on the logs but we weren't able to find any. We've noticed that only sent emails are logged. 

Do you have any idea why the application is stuck after ~300 successful sent emails?

I don't think the problem is related to the email template. We're testing with "Subject" = test and "Body" = test (it cannot get any simpler than that).

Let me know if you need additional information for your "investigation".

Best regards

**Comment by JGoLabs** [comment]
Hi - We are having the same issue - interestingly it is only occurring on a Windows 2012 Server environment.  When we use GoPhish on Mac OS/X (same campaign and parameters) it works.

In our case we only have a single e-mail address we are sending the campaign to - but here is some additional information:

1 - When you view the campaign in the Dashboard it states "queued" as the status.

2 - When you enter the campaign and view the results, the status for targeted user is stuck on "sending"

3 - This installation was done via the Windows 64 binary.

I did let it run over night thinking it might eventually die, timeout or work - but nothing changed.

I am happy to help debug this if there are suggestion on what to try or work through...just let me know.  If there is a solution you want to try - let me know as well.

**Comment by JGoLabs** [comment]
One thing to check is to make sure that your SMTP server doesn't have a limit on "relays" - for example the default SMTP relay per day for GoDaddy is 250.  Once you hit 250 you cannot send more SMTP e-mails without buying more relays.  I believe Google has a similar relay limit - just a thought to consider.

**Comment by kontez** [comment]
same issue here, however, sending the test email works fine.

**Comment by cclements** [comment]
I have a campaign that's gotten stuck 'sending' with only ~10/200 emails sent twice now.  Where can I look for more info on anything that may be erroring out?

**Comment by nzkarit** [comment]
I am seeing the same behaviour had a campaign with a group of 400 emails. Stop after 50ish email.

Did a second run which instead iof having one group of 400 it had 16 groups of 25. This campaign sent all the email.

So it appears there is an issue with large groups rather than total number of email in a campaign.

**Comment by jordan-wright** [comment]
Interesting.. I'll have to investigate this to see what's going on.

Large groups seems somewhat unlikely at first because when we create a campaign we just add all the users in all the groups to the campaign. The idea of groups doesn't exist at that point - it's just a bunch of users.

Regardless - this is super helpful info! I'll see if I can track down what's going on. If anyone has any more logs from the command line, that would be helpful.

Thanks everyone! I apologize for all the trouble.

**Comment by cclements** [comment]
One of the issues I've had troubleshooting this is I can't find any way to get additional debug for you.  If you have any tips on how to get you more info, I'd be glad to see what I can provide.

**Comment by jordan-wright** [comment]
Are you building from source? If so, there is the option to add additional logging.

The place to look would be in [worker.go](https://github.com/gophish/gophish/blob/master/worker/worker.go#L52). This is where the actual campaign is processed. You'll see a loop in there that handles sending the emails. Feel free to add any logging statements you'd like and re-`go build` to build the new binary.

**Comment by hheile** [comment]
Hello Jordan, 
we can go around that when randomizing the sending procedure, means not sending all emails at once and using a time-slot instead (for example sending during 8 hours period or something).
this really helps.... i' doing it manually, splitting up the target-list in two parts, import both two parts as separate adress-lists, doing 2 campaings. 

best regards

**Comment by ryan-es2** [comment]
Can I propose incorporating a Start Sending now button? That way server timezones and such would not be an issue configuring ?

**Comment by SEBreniac** [comment]
See Issue #436 

I posted the reason why this is happening and a fix for the problem.

**Comment by dnkls** [comment]
hello frands , my compain is not start , just cant send mail but test mail send good
http://i.imgur.com/0HpgQCj.png
i weit many time and he dont send(((

**Comment by jordan-wright** [comment]
What is the output of your terminal after you launched the campaign? Do you ever see any output indicating that it's trying to send the email?

**Comment by dnkls** [comment]
No no bro fnz for answer i solve thist issue i understand that problem is different time zone , i see another time in terminal than my brouser 
i set right time and all send good http://i.imgur.com/hhFTy0I.png

**Comment by dnkls** [comment]
fnx for fast answer this is great tool !!!
