### ISSUE TITLE
Where are the results for a landing page stored?

### ISSUE THREAD

**Issue by JGoLabs** [gophish/gophish#373]
Sorry if this is an obvious question, but I am not sure where the results of a form (used in a landing page) are stored?  The documentation states that GoPhish will override the "submit" button and store the results - but how do you see the results?

In the Campaign results I see that the user opened the e-mail - clicked the link - but there is no further timeline for seeing the results of their form input.

Thanks in advance for any help.

**Comment by jordan-wright** [comment]
Unfortunately, the site import process isn't perfect. What do you see in the template as the "action" parameter for the "form" tag in your html?

All results are stored in the database. Specifically, captured credentials are stored in the events table in the json metadata column.

**Comment by JGoLabs** [comment]
The "form" tag didn't change from the imported site - but I will try to take a look inside the database and see if the results are in the database.  Thanks for the response.

**Comment by jordan-wright** [comment]
There are other issues that better describe how the form import function works - I'm on mobile or I would link them. However, a search should find what you need.

It's likely that something in the html isn't playing nice with the import process.

Since the initial issue of answering where results are stored has been resolved, I'm going to go ahead and close this one out.
