### ISSUE TITLE
Template variables after a POST redirect

### ISSUE THREAD

**Issue by javiorcoyen** [gophish/gophish#386]
Hi,

I have created a landing page with a form that captures credentials (check on "Capture Submitted Data"). After credentials are submitted, it redirects the user to a second landing page (URL in "Redirects to"). All works fine, although in the second landing page template variables just appear as: 

"Hi {{.FirstName}}, this was a phishing simulation"

As I would like this second landing page to be personalized, is there a way to show on it the name of the user who clicked on the link and submitted data on the form?

Thanks,

**Comment by jordan-wright** [comment]
Currently, this is not possible since we do a redirect to a URL instead of a page stored in gophish. This means that, when the user is redirected, the user is no longer interacting with gophish.

With #223 being implemented in 0.3, we will allow for multiple landing pages as well as (potentially) full proxy support which should take care of this.
