### ISSUE TITLE
Freeze on high load

### ISSUE THREAD

**Issue by franckyz0r** [gophish/gophish#390]
Hi,

Thank you for your work!

This is a heads up on a possible issue when running the GoPhish with a high number of emails.
Recently I run a test with many, like MANY (1k+) emails in a campaign and I noticed that the web interface freezes under this load.
When you run the campaign there will be a delay of the web untill the campaign will be launched and will appear, but there is more after this. 
After the "In progress" status is changed into "Email Sent" the web ui will work normaly.
If you access the details of the campaign, the web will have a huge delay here, it gets unresponsive - maybe loading all the data makes it so laggy? I waited, it does not get any better than this.

Specs of my VM were pretty good, the server is not the problem.

Have a nice day!

**Comment by jordan-wright** [comment]
Hi @franckyz0r, thanks for reaching out.

This is a known issue that I am hoping to address with a UI refresh as part of 0.3.

In the meantime, my recommendation would be to leverage the API or database access directly to pull results.

Sorry for the trouble! Going ahead and closing this out since we'll be tracking the UI refresh in a separate issue.
