### ISSUE TITLE
record not found issue!

### ISSUE THREAD

**Issue by aprilLast** [gophish/gophish#392]
Hello ! I have a problem.
I occure blow issue. So I want to manually delete campain. 
* same issue : https://github.com/gophish/gophish/issues/197

How can I do that? 
If you have a time, please confirm my question. 
Thank you very much! 
bye.

**Comment by jordan-wright** [comment]
If this is the same issue as #197, please do not open a duplicate.

You'll see in the notes of #197 that this was fixed in the latest source. The fix is not yet in the pre-build binaries. We are releasing new binaries soon, but in the meantime we recommend following the user guide which shows how to build from source.
