### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by vysecurity** [gophish/gophish#407]
Is there any way to configure HTTPS? I could not find any flag or location to specify a certificate.

**Comment by vysecurity** [comment]
For Campaigns that is.

**Comment by Vanhecke** [comment]
Do you want to add HTTPS for the landing pages or admin panel?
Did you check the [documentation](https://getgophish.com/documentation/Gophish%20User%20Guide.pdf) and/or [config.json](https://github.com/gophish/gophish/blob/master/config.json) file?

**Comment by jordan-wright** [comment]
@vysecurity How to do this is, as @Vanhecke mentioned, documented in our user guide. Just do the same steps under "Creating SSL Certificate and Private Keys" for the ```phish_server``` instead of the ```admin_server```.

Then, when creating a new campaign, use "https://[phish_server_entry]", where you specify the correct IP or hostname that your targets can reach. That will serve the campaign over HTTPS.
