### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by ryan-es2** [gophish/gophish#411]
Hello,

So in live testing, I uploaded a CSV of 80 users and triggered spam prevention on send due to the emails sending all at the same time.

A great enhancement would be a way to deliver emails in batches of say 5, or stagger them over time.
At the moment my work around is to Create multiple user groups then creating duplicate campaigns changing the user list for each campaign, unless I am doing this inherently wrong :s 

Cheers, 

Ryan

**Comment by jordan-wright** [comment]
Hey Ryan,

You're right that emails are currently sent all at once. We have [an issue](https://github.com/gophish/gophish/issues/110) and a pull request already open that adds randomized sending, which should take care of the problem you're encountering.

Since we try to track everything through a single issue, I'm going to go ahead and close this one out in favor of #110. 

Keep the good ideas coming!
