### ISSUE TITLE
Language template request

### ISSUE THREAD

**Issue by adarioDeLeon** [gophish/gophish#419]
Hello

Would it be possible to include some sort of language config/xml file in order to be able to use gophish in other languages? I could help with the Spanish translation.

**Comment by jordan-wright** [comment]
Hi @adarioDeLeon,

Thanks for the suggestion!

I'm afraid I don't believe this is possible in gophish's current state. I don't know of a good way to handle things like language translations and I'm afraid it would be pretty low on my list of features to add, since there is quite a bit of other functionality I have on my plate right now.

If you want to try and take this on and submit a PR, I would happily consider merging it in!
