### ISSUE TITLE
Victim interaction only marked as success

### ISSUE THREAD

**Issue by RyanGandrud** [gophish/gophish#422]
First off, I appreciate everything you've been doing with this project. 

I used to use the pre-built binary but have since migrated to the latest pull from here. Whenever a campaign is launched, if the user interacts with the campaign in ANY way, GoPhish marks that user with the status of "Success" instead of the exact details of what the user did. So if they loaded the email tracking email or click the link, the server records it as a "Success" instead of the individual event. The image below is an example of only loading the tracking image.

![image](https://cloud.githubusercontent.com/assets/2633299/20106173/da85b234-a599-11e6-93d9-fae5300dde7c.png)

In addition, if the landing page has a login page, those credentials are never stored anywhere even if the option is marked on the configuration. When I export any results, all I see is the "Success" status regardless of what action the victim took (loaded tracking image, clicked link, entered creds). 

Please let me know if I can provide any additional information to help diagnose this issue.

UPDATE: It appears that the timeline functionality is working. Hovering over the specific dots on the timeline will give the appropriate interaction (data submitted, link clicked, etc), but this is not reflected properly in the email status circle graph, nor is it reflected properly in the csv export.

**Comment by recrudesce** [comment]
The server will record an Email Opened if the user opens the email, and a Success if a user clicks the link.  If the user opens the email but does not click the link, you should see Email Opened against the target in your CSV exports.

**Comment by RyanGandrud** [comment]
Hi recrudesce,

Thanks for the response. I believe I understand how the server is supposed to work and how it's supposed to record actions on the server. However, the install that I currently have is not recording those actions or displaying them correctly. As stated above, when a user loads the tracking image, the GoPhish server records this action as a "Clicked Link". I show this in the image where I hover over the timeline. 

In different Email Status graphs that I have seen both in documentation and other people's installs, this graph is supposed to show "Link Clicked", "Opened email",  and "Data Submitted" based on the user interaction with the site. My graph only shows "Email Sent" and "Success". When I export the CSV results, I still only see "Success" or "Email Sent" as what a user did instead of the individual actions they may have performed. 

I hope I was able to make my issue a little clearer.

**Comment by jordan-wright** [comment]
Do you have an anti spam solution that tries to inspect link contents? These products will typically navigate to each link to inspect the contents of the page for anything malicious. This would show up in gophish as a clicked link.

A good way to tell would be to inspect the user agent of the clicked link event. I would recommend building from source, since you'll definitely see the user agent there. Otherwise you'll just need to watch the terminal to see what UA is hitting the page.

**Comment by S0larflare** [comment]
I have the same issue as the OP, though I think Jordan may have misunderstood? When I export the Results.csv of a campaign, I only ever see the status as "Email Sent" or "Success". Success encompasses anybody who has clicked the link and has stopped there or has submitted data, for example. There is no differentiation within the exported results file. The RawEvents.csv does show the correct output for the campaign and therefore shows if someone clicked a link, submitted data etc and the time that they did so, but it is a less useful format to work with and you occasionally get duplicated (because unfortunately people decide that clicking a phishing link once just isn't enough I suppose...).

Is there any way to get the actual status for each user to be shown in the results export, so we can quickly see how many clicked, how many submitted, how many only opened the email etc.?

**Comment by jordan-wright** [comment]
I understood the question. It's something I'm planning to fix, just haven't had a chance to do so yet. Ideally, I'd like to put in a database migration that cleans up past campaigns as well- getting that right takes some work.

I'll get this fixed, it'll just take some time.

Jordan

**Comment by jordan-wright** [comment]
Good news!

This has been fixed as of https://github.com/gophish/gophish/commit/9982769d0fdfe806a8d971f2a0cd89731efd156a. You can check out #505 for some more information on changes that were made possible because of this.

I appreciate y'all's patience! Let me know if you run into any issues.
