### ISSUE TITLE
No API documentation for setting "redirect_url" etc

### ISSUE THREAD

**Issue by snori74** [gophish/gophish#432]
In latest v0.2.0...
Can't see documentation of the APIs for setting of:
* Capture credentials
* Capture passwords
* Redirect to:

**Comment by jordan-wright** [comment]
Yes, you're right. API documentation is something that I am working to move to a Gitbook to make it easier to collaborate on/update documentation. I opted not to update the existing docs because it would have increased the already too long delay for getting 0.2 out the door.

I'll keep this issue open until we get those docs in place but, if you run into specific questions about leveraging these features via the api, let me know.

**Comment by jordan-wright** [comment]
Just wanted to close the loop on this one. I've since added the documentation for these features to the in progress Gitbook API docs: https://gophish.gitbooks.io/api-documentation/content/landing_pages/

I'm still finalizing the docs, but by the time I'm done it will be a complete reference 😄
