### ISSUE TITLE
Tracking Image not working

### ISSUE THREAD

**Issue by tit0n** [gophish/gophish#433]
When creating an email template, the "Add Tracking Image" button don't seem to be working anymore. 

Even when the box is checked, after saving the email template, the box become unchecked and no tracking image is included in the email being sent. 

Version 0.2alpha

**Comment by jordan-wright** [comment]
Thanks for the report! Can you show us an example email template this is happening on?

**Comment by recrudesce** [comment]
I've seen this before, it adds the tracking image, but the tickbox is unticked when you edit the email (so you have to remember to tick it again else the tracking image is removed).

How to fix (from experience): Compile from source, the issue only seems to happen in the binary release.

**Comment by congriholdplantains** [comment]
I just noticed this on v0.2 GA. If you look at the HTML Source, you should see the "<p>{{.Tracker}}</p>". If you do, you are good to go (already tested it). I noticed this seems to happen with the more lengthy emails.

**Comment by alou1** [comment]
Hello,

I think I know why it's not working (maybe I'm wrong).
I think the problem comes from the URL written inside the mail requesting the tracking image.
This URL uses the landing page's URL (c.URL). 

For example if the gophish base URL is "myserver.com" and the landing page is "myserver.com/something/" the tracking image is requested through an img tag whith an URL like : "src='http://myserver.com/something//track?rid=[target rid]". (https://github.com/gophish/gophish/blob/master/worker/worker.go#L127)

By this way the gophish server takes this like a "clicked link" event because the URL to raise an "email opened" event looks like "http://myserver.com/track?rid=[target rid]".

If I'am not wrong, I think it should be good to fix this.

**Comment by recrudesce** [comment]
I wasn't able to get the tracking image working when using a directory at the end of the URL.  it only worked if it was domain/track?rid= and not domain/directory/track?rid=

**Comment by alou1** [comment]
Ok. Maybe it should be good to allow it. Sometimes I need to use landing page's URL like "domain/directory/". Maybe I am the one.

**Comment by jordan-wright** [comment]
Ok, this should be fixed in the source. If you're building from source, give it a shot with the latest and let me know if you're still having issues!
