### ISSUE TITLE
More detail on error

### ISSUE THREAD

**Issue by AgoraSecurity** [gophish/gophish#456]
I think it would be nice to have more detail (for example a "Show detail" button) when an error sending an email occurs.

It would be easier to know from the framework the reason of failure (bad email, dns error, etc.).

**Comment by jordan-wright** [comment]
Totally - I can get this added.

Thanks for the suggestion!

**Comment by jordan-wright** [comment]
Sorry for the delay - this should be all fixed in the latest source.

It looks like any sending errors have been in the raw events download for a while now, but you're absolutely right that they should be displayed in the web results.

![image](https://cloud.githubusercontent.com/assets/1317288/21487527/ad8879fc-cb90-11e6-809e-a2e5be0a9ba2.png)

Let me know if you run into any issues!
