### ISSUE TITLE
dial tcp i/o timeout

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#459]
Hi,

while creating a  sending profile and trying to send test email then i am facing issue like 

dial tcp 169.45.89.184:25: i/o timeout

why this is coming .. 

when i did this on windows 7 then it was working fine.. 

Now I build on windows server 2012  and facing the above issue

How I can resolve it.

**Comment by S0larflare** [comment]
Is the port open? It could be getting blocked by a firewall, hence the timeout.

**Comment by dalvirsaini** [comment]
Yes port is opened i looked inbound rules and its there.

**Comment by dalvirsaini** [comment]
now I deleted that rule

**Comment by jordan-wright** [comment]
It's still almost certainly some kind of firewall setting, not something with gophish, since you had it working on a different host. You might try running a port scan to see if the service is reachable.

I'm afraid without more diagnosis from your end, there isn't much we can do to help troubleshoot.

Let me know if you've confirmed with a port scan that the service is reachable and we can re open this issue.

**Comment by dalvirsaini** [comment]
yes its fixed by using port 2525 instead of 25
