### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#476]
I found One bug.

1) go to email templates

2) now select an email template or create new one

3) Tick the checkbox "Add Tracking Image"

Make sure not to use that {{.URL}} in ur email template

Now again click on edit icon for the same and you will see that "Add Tracking Image" is unchecked automatic now.

**Comment by S0larflare** [comment]
If you click on the source, is {{.Tracker}} at the bottom of the email? If so, it is being added and it is just a visual bug. I have seen this myself but only intermittantly, and personally I don't tend to use the tracking images so I haven't looked too far into it.

**Comment by dalvirsaini** [comment]
yes {{.Tracker}} is not there . and this issue is coming randomly.

**Comment by jordan-wright** [comment]
I'm guessing you're using a prebuilt binary. This has been fixed in the source version (please see the other issues for this).

To prevent duplicate issues, I highly recommend searching through the existing issues before filing new ones.

If you are building from the latest source and are still seeing this behavior, let me know and we can re open.
