### ISSUE TITLE
Gmail Problem

### ISSUE THREAD

**Issue by karencho777** [gophish/gophish#486]
Hello when using Gmail.com for phishing "From" -address remaining ORIGINAL (when user viewing full message original email address apears)

**Comment by jordan-wright** [comment]
Are you authenticating to Gmail as your gmail address? If so, that is something Google does to prevent spoofing. There is nothing gophish can do to prevent this.

**Comment by karencho777** [comment]
end what smtp service are you suggesting ???can someone help to find SMTP

**Comment by S0larflare** [comment]
I'd suggest setting it up on the server you are using for gophish. Considering you'll likely be wanting this for a small - medium business environment, you could use the mail server of your company for sending it. Provided you're inside of the network, you shouldn't need to do anything special with regards to config.

**Comment by karencho777** [comment]
for example if i using Kali linux can i use my computer to send emails from it?? thanks

**Comment by jordan-wright** [comment]
You will need to setup an open SMTP relay so that you can send emails with Gophish. I'm afraid recommending and supporting SMTP servers is out of scope for what we can provide, since these issues are meant to track bugs in Gophish itself.

There is plenty information on setting up an SMTP relay or using existing SMTP servers online.

Please don't hesitate to file issues if you encounter any bugs with Gophish itself.
