### ISSUE TITLE
Config File Detail

### ISSUE THREAD

**Issue by dragontologist** [gophish/gophish#490]
The config.json file is a little confusing, and the current documentation doesn't have a full explanation of how to configure it. 

- Is the Admin server the server on which you run the EXE, and the Phish server the SQL database, or do I have those reversed? 
- If I choose not to use a key or cert, should I remove the option, or leave it as example? 
- Why is there an SMTP category if those are fields in the Sending profile, and which one takes priority? 
- What's the migrations path option used for?

**Comment by S0larflare** [comment]
1. Admin server is where you are connecting to the console, the Phish server is where your victims will connect to. I believe the default will fit most people here. You probably want the Phish server to be port 80 so you don't need to do any port forwarding or messing with the links to users. The admin server is fine as 127.0.0.1 if you're going to connect to the console from the machine you have gophish running on, you might need to change this if you are connecting remotely (I have it set up as the hostname of the machine, for example, as the machine I have it on lacks a GUI and I use putty to remote on to it, so to get around that I connect from another machine to the url itself for the console).

2. By default, SSL (TLS) will be used for the admin server, so when you are creating campaigns in the console etc. It won't be on by default for the people who click the emails and go to your phishing url - they will be plain http. You can generate an ssl cert if you wish and put the details here or you can leave this as the default and it will autogenerate a self signed certificate when you first run gophish.

3. I think this is from back before you could create sending profiles, you can ignore this. In fact I thought it was removed.

4. Migrations is used for updating the database schema - adding tables, adding columns, things like that. It's not something you'll need to worry about unless you actually make any changes to the code fo gophish and the database itself. The path itself is something so that gophish knows where to look to check if there is anything new that needs changing. Leave this as is so that if there are any database updates in the future your installation won't break.
