### ISSUE TITLE
php code in landing pages

### ISSUE THREAD

**Issue by mcjon3z** [gophish/gophish#491]
I'm in the process of migrating over some of my phishing campaigns over to GoPhish and noticed that the HTML editor for the landing pages is commenting out php code blocks. I'm guessing that it is a security feature in the editor plugin. Any ideas or workarounds to allow use of custom php code in the landing pages?

**Comment by jordan-wright** [comment]
Gophish is written in Go and serves static landing pages. There is no use for PHP in the landing pages because Gophish is not a PHP interpreter. That PHP code, if it would find it's way into the HTML page, would just be dumped out to the user.

I'm afraid there is no way to run PHP code in Gophish at this time or in the future.
