### ISSUE TITLE
Sharing campaign view with other users?

### ISSUE THREAD

**Issue by Antwebb** [gophish/gophish#493]
Hi, I set up and started a campaign. Now my colleague keeps asking me for updates on progress. I set him up with a user account in the hopes he'd be able to see for himself, but it seems campaigns are specific to the user (obviously this is intentional). Would be great to be able to share an active campaign with another user, even better if I could give him view only access..
Thanks
Ant

**Comment by jordan-wright** [comment]
Hi @Antwebb, I'm afraid this isn't currently possible in Gophish. It's possible that I'll RBAC in the future, but it's not on the short list of high priority things I need to fix.

My recommendation in the meantime would be to use a shared account if you need shared access to a campaign. You could probably manually update the SQL to add an entry to give him access to the campaign, but I can't make any guarantees that this would work or be stable 😄 

I'm going to go ahead and close this one out since there is already another issue open for tracking the possible implementation of RBAC.
