### ISSUE TITLE
How to use Logged in user name  in email templates and landing pages?

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#500]
Hi,
How to use Logged in user name  in email templates and landing pages?
Is it possible?

**Comment by S0larflare** [comment]
What do you mean by logged in user name? You'd have to pass this through to gophish somehow. If you're not using the position field for the user, you could put it in there and then reference {{.Position}} in the template

**Comment by dalvirsaini** [comment]
yes I am talking about the logged in user name. 

I need logged in user name in email templates. 

So it it possible to get it ?
Is it easy like {{.FirstName}}??

**Comment by S0larflare** [comment]
I just said how you would be able to do this? Use the position field for each user and instead of putting in their position, put in their username. Then reference it with {{.Position}}.

For example, if their name is "Joe Bloggs", their email address is "jbloggs@example.com" and they are the CEO, rather than entering CEO as their position, you would put "JB_1981", as that is their username.


Now if that isn't what you mean and instead you are after whatever they type in to the login field as their username for a specific site (which you don't currently know) there would be no way of getting this into the email as you wouldn't know the value beforehand.

**Comment by jordan-wright** [comment]
This isn't currently supported directly in Gophish. I recommend doing what S0larflare recommended and using another field like {{.Position}}.
