### ISSUE TITLE
Is it possible to categorized Emails templates and landing pages?

### ISSUE THREAD

**Issue by dalvirsaini** [gophish/gophish#502]
Hi 
Is it possible to categorized Emails templates and landing pages?

Means to add some emails in one category and some in another. so that is can be easy to filter if there are 100 of emails ? 

same for landing pages.
 
Is it supported here?

If its not there then according to me it should be there as a feature.

**Comment by jordan-wright** [comment]
No categorization of emails, landing pages, or any other Gophish object is supported. We do not have plans to add any type of categorization, since the data table allows for searching already.

You can leverage the name field in these objects to do categorization, such as "[TAG] - Name" and then search for the tag in the table.
