### ISSUE TITLE
domain record checks

### ISSUE THREAD

**Issue by nanoymaster** [gophish/gophish#514]
Hi, 

I saw that  FiercePhish has a record checker for domains, wheck a record points to right place, that there is a SPF record etc.
https://github.com/Raikia/FiercePhish/wiki/Feature:-Email-Configuration-Check

I was hoping gophish could implement this also

**Comment by jordan-wright** [comment]
Eh, I'm not sure gophish is the best place to put that feature.

Spam filters are tricky, because they rely on more than just if spf/dkim/dmarc are set. Oftentimes, they rely on things like IP/domain reputation as well.

It looks like FiercePhish only checks SPF, but doesn't check that DKIM signing is taking place, nor does it check for DMARC records. Even then, it would have to parse them for correctness, which isn't the easiest to do.

If you want to check your DNS settings in Gophish, you can setup a Sending Profile and send a test email to the address you get at [mail-tester.com](https://www.mail-tester.com/). This is a free service that is great to check and make sure your SMTP server is properly signing emails via DKIM, that your DNS records are setup properly, and that you aren't on any blacklists.
