### ISSUE TITLE
GoPhish : Email Opened and Clicked Link not appearing under Timeline

### ISSUE THREAD

**Issue by AEThomas** [gophish/gophish#517]
Hi 

I created a campaign by downloading the  version gophish v0.2.0  Windows 64 bit. The Timeline for the Results shows only upto 'Email Sent' . 'Email Opened' and 'Clicked Link' are not shown though the user has performed those actions. 

The Email Template is as given below : 
<html>
<head>
	<title></title>
</head>
<body>
<p>Hello&nbsp;</p>
<p>Someone special has sent you a gift for Valentine&#39;s Day.&nbsp;<br />
For details, click the link <a href="http://www.yahoo.com..sg">GiftsForYou.</a></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
{{.Tracker}}</body>
</html>

Thank you.

**Comment by S0larflare** [comment]
Your link shows up as yahoo.com..sg which is an invalid URL. I'd suspect if you change that to a single . between com and sg that it should work (provided everything is set up on that url to capture it)

**Comment by AEThomas** [comment]
Hi 
It was a typo error. I changed and tried again. Still Timeline shows only until Email Sent; 
Email Opened and Clicked Link are not reflected.

**Comment by S0larflare** [comment]
Well, the URL needs a tracking id appended to it. rather than putting the URL in manually you should put the hyperlink as {{.URL}}. Gophish will do the work from there based upon what you put in to the campaign. I'm not sure if you've done that bit or not, but just judging from the extract you provided it doesn't seem like it.

If you have done that, then the next problem would be that http://www.yahoo.com..sg/ is owned by Yahoo, so Gophish wouldn't be able to capture anything going there (unless you've set up an internal DNS spoof to forward traffic from there to your Gophish server?)

Essentially you need to be sending the phish victims to your gophish server.

**Comment by AEThomas** [comment]
Thank you for the inputs. 
May I know what should be the URL to be given in Campaign Creation page. 
I have used the value http://192.168.1.1 which was already given there.

**Comment by S0larflare** [comment]
The URL in the Campaign Creation page should point to the URL of your Gophish server. 

- If that is its IP address then you can use that. 
- If you have set up a hostname for it, you can use that. 
- If you set up a DNS alias so that it seems like it is say google-play-services.com then you can use that
- If you have set up external hosting/domain name for the server, you can use that.

Basically your users need to be able to reach your gophish server.

**Comment by jordan-wright** [comment]
It looks like this is pretty well resolved from the help provided by @S0lareflare. I'm going to go ahead and close this for now.

@AEThomas, make sure to check out our user guide if you want to see a campaign built from beginning to end.
