### ISSUE TITLE
use trusted certificate on Gophish (what I am doing wrong?)

### ISSUE THREAD

**Issue by mantis-le-sin** [gophish/gophish#523]
Hi guys,
I have requested a trusted certificate for my gophish server.

I have these files:
domain.cer
domain.key
domain.conf
ca.cer
fullchain.cer

now, from the config.json
------------------------------------------------------------------------
{
        "admin_server" : {
                "listen_url" : "172.31.13.125:3333",
                "use_tls" : true,
                "cert_path" : "gophish.cert",
                "key_path" : "gophish.key"
        },
	"phish_server" : {
                "listen_url" : "172.31.13.125:443",
                "use_tls" : true,
                "cert_path" : "gophish.cert",
                "key_path": "gophish.key"
        },
	"db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}
------------------------------------------------------------------------

I already tried to insert domain.cer instead of gophish.cert and domain.key instead of gophish.key
but no luck, the cert is still untrusted.

What I am doing wrong and what should I do with the other files?

There are a lot of HOWTO related on how to install certificates on apache, iis ecc... but I don't think they work for the gophish webserver which looks custom.

thanks!
mantis

**Comment by S0larflare** [comment]
This is something more fundemental to certificates and how Public Key Infrastructure works. The certificate you're using is a self signed certificate. It will still encrypt just like a certificate for google or facebook etc. but it is simply saying "Hi, i'm 'example.com', you should trust this because I am underwritten by 'server532fgg'". A 'proper' certificate would be something more like "Hi, I'm google.com, you should trust this because I am underwritten by the 'Google Internet Authority G2' certificate, which is underwritten by the 'GeoTrust Global CA' certificate, which you trust."

For the admin console, your self-signed certificate is fine, you're the only one who is likely to use that and so you can put an exception in your browser to ignore the error. For users, that wouldn't work. If they suddenly get an error when connecting to example.com, many will think something is wrong (as it is, you're likely spoofing something in your phishing attempt).

So, three ways to get around this, depending on your situation:

1. Go to a Certificate Authority, like Digicert or Symantec or somebody and buy a certificate from them. You would need to pay a fair amount for this and would need to show that you own the domain. 
Pros: Will be trusted by everyone.
Cons: Cost, You won't be able to buy a certificate for a domain you're trying to spoof.

2. Go to somewhere like Let' Encrypt and get a free SSL cert.
Pros: Free, quite easy to do.
Cons: Wouldn't be able to get a cert for a domain you're trying to spoof or dont own

3. If you are doing all this internally, using DNS entries and things to make it looks like your users are actually going out to the internet but are still on your network, you could use an internal PKI.
Pros: Free, Quite easy to get a cert, Possible to get a cert for anything you want
Cons: Needs a PKI set up in your company...

4. Don't use https :D
Pros: Easy, Saves a lot of faffing and potential for things going wrong, Closer to most 'real' phishing campaigns
Cons: The page might look slightly less authentic

**Comment by jordan-wright** [comment]
It looks like @S0larflare did a great job of explaining the different aspects of getting SSL setup. If you have the proper cert and key (setup of these from a trusted CA is outside the scope of the support we can offer), then Gophish should have no problem honoring it.

You could always use a service like [Qualys SSL Labs](https://ssllabs.com) to check your configuration if the server is publicly accessible.

I'm going to go ahead and close this out for now. Let us know if you run into any further issues!

**Comment by mantis-le-sin** [comment]
that was very helpful! Cheers guys!
