### ISSUE TITLE
Exploring option to launch the campaign from a system/ host which is public internet facing

### ISSUE THREAD

**Issue by patilprateek** [gophish/gophish#537]
hello,

the campaign i ran so far, was from a windows 7 64bit system which is on our intranet. The scope of the results were limited to the users who would have their desktops/ laptop connected to the office network where we had the listener service running in the backend tracking all data.

Wanted to check if we have already touched upon/explored an option of hosting the gophish on a host which is internet facing - and doing this would we be able to achieve results when the email gets accessed from a mobile device/ end user system which is outside office network (home pc/ wifi etc)

**Comment by S0larflare** [comment]
Yes, if you put it on an internet facing host then you would be able to use it like this. Essentially if your users can reach it, then it will be logged as a click/submission etc. There are a few points to consider by making it public however.

1. It has a chance of catching people who weren't intended targets (a user might forward the email to their spouse who then clicks it, perhaps more real-world, but a bit more of a grey area ethically as you don't have any recourse to phish them)

2. In order to make it seem more plausable (than sending your users to http://phishserver.mydomain.com) you would have to spin up a domain to match the campaign. This could be a bit more difficult if you are trying to make things more realistic (http://amazon-delivery.com might be available, but it could also have some kind of monitor on it, whereas spoofing it with internal DNS negates that issue).

**Comment by jordan-wright** [comment]
To add to what @S0larflare said, to make Gophish available to the public, you would need to have your host be accessible on the Internet. Doing this is beyond the scope of our support.

Then, you will need to ensure that the `config.json` file has the `phish_server.listen_url` set to bind to all interfaces. [The default value](https://github.com/gophish/gophish/blob/master/config.json#L9), 0.0.0.0, does this for you.

After doing this, Gophish will be accessible from the Internet.

Hope this helps! Let us know if you run into any issues.

**Comment by patilprateek** [comment]
Thanks for the response..

@S0larflare i was looking to play more on the lines of option 1 (we can always reverse lookup the events file report to check which users are actually from the organization. For option 2, i would just be creating a hyper link that would take them to a landing page created using gophish (would the config be different from what i would do when using it internally)

@jordan-wright just to make sure if i got it right, would the modification of file config.json having the default value as 0.0.0.0 as of now be changed to the IP address of that host which i plan to put on the internet? For eg if my ip is **12.8.8.24** then it will be :-1: 
"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "**12.8.8.24**:80"
