### ISSUE TITLE
Windows binaries not working

### ISSUE THREAD

**Issue by ASclund** [gophish/gophish#551]
Every time I try to navigate to the admin console it just downloads a blank file, this is in v0.3. v.02 still works great

**Comment by S0larflare** [comment]
Does it say what the file is? Could be an error with the login page or something similar (only know as I've had similar things happen when I've been fiddling with the campaign page!)

Sent from my iPhone

On 2 Mar 2017, at 20:32, ASclund <notifications@github.com<mailto:notifications@github.com>> wrote:


Every time I try to navigate to the admin console it just downloads a blank file

**Comment by ASclund** [comment]
If you try to go to localhost:3333 it pulls down download. If you do localhost:3333/login it downloads login

**Comment by jordan-wright** [comment]
Check the config.json - does it say it's using `https`? If so, you might try https://localhost:3333/. Since we have automatic SSL cert creation, we moved the default to be https which sometimes shows weird symptoms when accessed over http.

If that doesn't work, could you tell us what browser and architecture (64 or 32 bit) you're using?

**Comment by jordan-wright** [comment]
Hey @ASclund just wanted to check in - any update on this one?

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in a while. @ASclund if you still run into issues, let us know and we'll continue troubleshooting.
