### ISSUE TITLE
Campaign Overview - Improvement request

### ISSUE THREAD

**Issue by mdearlove** [gophish/gophish#552]
Hi please can you consider adding the date that the status "email sent" was achieved as a column on the Campaign overview view?  

I have some campaigns that are in progress but I have to drill down to see when the email was sent out which could vastly different than the "Created Date".

Also for campaigns that are still queued - please add a tool tip to the word 'Queued' to indicate the actual date the campaign will be launched as it is impossible through the current UI to find this out by drilling down to the campaign.

Thanks for your help :-)

**Comment by jordan-wright** [comment]
Good suggestions!

I'll see what I can do UI-wise to address some of these suggestions. I agree that drilling down into campaigns to find some of this information is not ideal.

**Comment by mdearlove** [comment]
Thanks @Jordan-wright.

**Comment by S0larflare** [comment]
I'm currently having a look at this (as having to dive deep into the api to read all the details isn't ideal). So far I've just added a new "tab" in campaign results which has some details in it:

![image](https://cloud.githubusercontent.com/assets/8939757/24105433/c67d4ae0-0d7c-11e7-9b7a-dae9bf061a9f.png)

So you can hop between the tabs, rather than cluttering up the results page. What extra sort of info would people find useful to go there?

**Comment by mdearlove** [comment]
I appreciate the idea but bear in mind you still need to drill down to the campaign to see this info.
What about at the top level campaign level that lists all campaigns, have another button to the left of the "View Results" button which provides a quick summary pop-up window showing:

Scheduled Start Date/time:
Emails Sent:
Emails Opened:
Attachments Opened (if applicable or possible):
Link Clicked/Success:


Then rename the "View Results" button to "Campaign details"?

Just some ideas :-)

**Comment by S0larflare** [comment]
Is this more what you're after?

![image](https://cloud.githubusercontent.com/assets/8939757/24198020/f8d0c1ae-0efb-11e7-9156-92788bc561b2.png)


![image](https://cloud.githubusercontent.com/assets/8939757/24198038/02ffa640-0efc-11e7-8f5a-fe52a9cba02a.png)

**Comment by mdearlove** [comment]
Hi @S0larflare, Yeh thats looking good thanks.  Just means you get the summary info without needing to drilldown.  great work!

**Comment by jordan-wright** [comment]
@S0larflare I *really* dig that. Good call!

**Comment by S0larflare** [comment]
OK, so I have remade this in the current build, but in so doing I have had to drop the "Template name" part of the popup as the summary api call doesn't have that in (and I really don't see the value in either doing a call just for the template name or extending the summary call just for that). I've also moved the tooltip to a right placement so it doesn't obscure other statuses - there's a nice big white space there so might as well use it :)

![image](https://cloud.githubusercontent.com/assets/8939757/24295829/7067d420-1094-11e7-9acf-1c503de9ecda.png)

One thing though, I don't use tracking images in my emails (because of how outlook blocks them by default etc) so none of my campaigns have an "opened" status. I've tried creating a campaign with a tracking image to test this, but I can't get it to work, has something changed with {{.Tracker}} as it used to work fine in an older version?

**Comment by jordan-wright** [comment]
Hey @S0larflare, I'm happy to take a look at this. Want to make a pull request and I can merge it into a branch and finish up any needed dev work before merging into master?

Thanks again for looking into this!

**Comment by S0larflare** [comment]
Yep, will do. I just haven't had a chance to touch it in a while. I'll make the pull request next week!

**Comment by jordan-wright** [comment]
Closing this one since it was merged in #600. Thanks again for the report @mdearlove and all the great work @S0larflare!
