### ISSUE TITLE
GoPhish not able to collect entered data

### ISSUE THREAD

**Issue by saurabhcs0097** [gophish/gophish#574]
Hi ,
I am facing issues in gathering the entered data. I have used LinkedIn login page but entered data is not reflected in campaign report, however the tool updates the "link Clicked" but no progress thereafter.
Also upon entering data link is not getting redirected .
I am using GoPhish for first time so please execuse if my questions sounds novice.
Help Please! 
Thank you!

**Comment by jordan-wright** [comment]
This happens when the landing page you cloned executes Javascript or some other pre-submit process. This is landing page specific so I'm afraid there isn't much we can do on the Gophish side of things to prevent this.

You will need to determine what on your landing page is catching the submit process and edit those processes out.

**Comment by jordan-wright** [comment]
Hi @saurabhcs0097, please see [these similar issues](https://github.com/gophish/gophish/search?q=capturing+credentials&type=Issues&utf8=%E2%9C%93) for more information.
