### ISSUE TITLE
landing page accessible over the internet

### ISSUE THREAD

**Issue by morird74** [gophish/gophish#583]
For phishing external users I know that the landing page needs to be accessible over the internet, but I was wondering what is the best/cost effective way to go about doing that? What are other people using?

**Comment by jordan-wright** [comment]
I've heard of people standing up gophish in a VPS through AWS or DigitalOcean.

You could also just put your gophish server in a DMZ and add the appropriate firewall rules to allow inbound connections only over port 80 (the phishing collector).

**Comment by jordan-wright** [comment]
Going ahead and closing this out since there haven't been any more updated. @morird74, there is a guide from Github user @LarryGrim that goes in detail on how to setup Gophish in AWS - you might find it handy! You can find details [here](https://gophish.gitbooks.io/user-guide/content/additional-references.html)
