### ISSUE TITLE
Adding other html pages in the same landing page

### ISSUE THREAD

**Issue by RatedRR** [gophish/gophish#590]
Hi,

I would like to know if it is possible to add several pages html (files : html, css, jquery...) in the same landing page? (like if it is a landing page template) And so I can do a full scenario as I want.

From what I tested, it is only possible to make a single landing page followed by a redirect to an url.
I want to redirect to one or more pages I also created myself (for a full scenario and ie) so it can be more realistic for a phishing campaign.

Thanks.

**Comment by jordan-wright** [comment]
You can find information about using static assets in your landing pages in the User Guide [here](https://gophish.gitbooks.io/user-guide/content/documentation/landing_pages.html#static-assets).

Otherwise, you are correct that it's currently only possible to have one landing page. You could then chain pages together with your own other static assets or web servers, but these won't be tracked by gophish.

The long term plan is to rebuild how we handle campaigns, as you can see in #223.
