### ISSUE TITLE
Allow controlling the start of a Worker

### ISSUE THREAD

**Issue by advanderveer** [gophish/gophish#610]
Hey!

Great work on this project, it is simple and effective! I would like to run the worker code in a separate process altogether but currently it seems [hardcoded](https://github.com/gophish/gophish/blob/master/controllers/api.go) to be started whenever the controller package is included. 

My take would be to add a configuration option that is evaluated in the main() function and start the worker routine there. If you think that such a solution would work i'm willing to setup a pull request with a proposal.

Cheers,

Ad

**Comment by jordan-wright** [comment]
Hi @advanderveer - sorry for the delay on this one.

What is your goal with running the worker process in a separate process? Typically, an architecture I might see someone pursue is having an admin server and a separate phishing server (they would share a single MySQL db for this to work) but I haven't heard of anyone wanting to break out the worker.

Depending on the use case, I could see a couple of options:
* Add a command line flag to disable the worker (having it on by default since most people use Gophish standalone. Plus, I don't know that this would be used enough to warrant a new config option)
* Create a separate script that invokes the `github.com/gophish/gophish/worker` library. It's all Golang so if you wanted to have a separate worker, you could simply write a script to handle the creation and starting of a [worker.](https://godoc.org/github.com/gophish/gophish/worker).

Let me know what you think in terms of what you're trying to do with the worker and if either of those options appeal to you.

Sorry again for the delay in getting back to you! This one slipped under the radar.

**Comment by jordan-wright** [comment]
Closing this since this functionality appears to have been added in https://github.com/gophish/gophish/commit/1426376aa595c5c7ca83c8a2d2f50a219335f5ae
