### ISSUE TITLE
Tips on keeping emails out of junk/spam folders?

### ISSUE THREAD

**Issue by aj-broadhurst** [gophish/gophish#628]
I was wondering if anyone had some tips on keeping emails from ending up in the junk or spam folders. I've already got SPF/DKIM records established, and the emails I've been using to test all have low SpamAssassin scores (~1.3). I'm having success with multiple email providers, including Gmail and Yahoo, however Microsoft accounts (Outlook, Hotmail) continue to send emails to the junk folder. Not ideal, since the campaign I'm working on is comprised of Office 365 accounts. I'm hoping others may have some suggestions for things I can try. Thanks.

**Comment by jordan-wright** [comment]
Email deliverability is a tricky thing. It's most likely related to IP/domain rep that's getting you flagged, and there isn't really an easy fix besides using different infrastructure. Sendgrid has a [guide on deliverability](https://sendgrid.com/resource/email-deliverability/#introduction) you might find helpful.

That said, the proper use of Gophish is to test accounts you have the proper authorization to test. In this case, you can just whitelist your sending IP in office 365 or, if you're a pentester, ask your customer to whitelist your sending IP. That's the easiest way to get around deliverability issues.

**Comment by aj-broadhurst** [comment]
Thanks for the resource. I'll look it over. We do have authorization from our client, however we're trying to avoid whitelisting in an attempt to simulate an actual outside phish.

**Comment by jordan-wright** [comment]
So there are two parts to this and it depends on what it is you're testing.

Are you testing the security of their email gateways? If so, Gophish may not be the best product since it's somewhat limited in the payloads it can deliver.

Otherwise, if the goal is to test the users' susceptibility to phishing attacks, then whitelisting on the email gateway shouldn't void that test. If anything, it'll make sure you and your customer get the most accurate results possible since it ensures to some extent all the emails will be delivered.

**Comment by jordan-wright** [comment]
Since there hasn't been any updates to this in a couple days, and it seems as though the question was answered, I'm going to go ahead and close this out for now.

@aj-broadhurst I hope the resources above help. If you run into any other issues, don't hesitate to let us know!
