### ISSUE TITLE
How many users can you send to at a time?

### ISSUE THREAD

**Issue by cjhahn13** [gophish/gophish#631]
Is it possible to send to 10,000 users at once? Or would I need to do it in smaller chunks? to avoid crashing it.

**Comment by jordan-wright** [comment]
Sending likely won't be the issue - at least not on Gophish's side.

The issues you might run into currently would be:
* If you have an incorrect email address, you might have issues sending to the rest of the recipients (see #548 )
* Rendering in the UI can be slow due to the polling. If you are using the latest version from source, a checkbox has been introduced to let you shutoff the polling

**Comment by jordan-wright** [comment]
Going ahead and closing this one since the original question _seems_ to have been answered.

@cjhahn13 if the answer above didn't answer your question, let me know and I can re-open this.

Other issues you might want to take a look at include:
* #415 - Unable to import large (~40k) target list
* #282 - Result Page un-responsive for large-scale Campaigns
