### ISSUE TITLE
Only able to access phishing server on 127.0.0.1

### ISSUE THREAD

**Issue by BNWEIN** [gophish/gophish#632]
Hi Guys

I am sure i am missing something simple. I can confirm with 100% certainty this is not a firewall issue.

When i run a campaign, the landing page can be accessed at: http://127.0.0.1/ (with the tracking at the end)

But it cannot be accessed at: http://my.actual.local.ip/ (with the tracking ip at the end)

For example, if my PC's ip is: 192.168.10.10 then i cannot access the landing page on http://192.168.10.10 even from my own computer! 

How ever 127.0.0.1 works fine every time! 

What am i missing!?

**Comment by jordan-wright** [comment]
Can you post your config.json?

**Comment by BNWEIN** [comment]
It's set to listen in 0.0.0.0:80 which I have already checked and assume that's what you wanted to see?

Sent from my iPhone, excuse any typo's


Ben Weinberg
Operations Director
Tel 020 7443 5618
Mob 07515 482 580
Email BWeinberg@prime-networks.co.uk
www.prime-networks.co.uk
Kingsway House, 103 Kingsway, London, WC2B 6QX
The information transmitted in this email is intended only for the person(s) or entity to which it’s addressed and may contain proprietary, confidential and / or privileged material. If you have 
​received this email in error, please contact the sender by replying and delete this email so that it is not recoverable. If you are not the intended recipient(s), any retention, review, disclosure, 
​distribution, copying, printing, dissemination, or other use of, or taking of any action in reliance upon, this information is strictly prohibited and without liability on our part.
On 24 May 2017, at 18:00, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you post your config.json?

**Comment by jordan-wright** [comment]
Yeah, I figured that'd be the most likely culprit.

What do you see in the terminal when you start up Gophish? Do you see any errors about binding to the port? I'm guessing when you request the page and it doesn't work, you also don't see a connection line appear in the terminal output?

The only other thing I could think of since you mentioned it's definitely not a firewall issue would be to look for other processes already listening on port 80.

**Comment by BNWEIN** [comment]
Bear in mind it works on my 127.0.0.1 address so it can't be the port

No errors on startup it's binds to the port fine and correct nothing in the console when I get page cannot be displayed

Sent from my iPhone, excuse any typo's


Ben Weinberg
Operations Director
Tel 020 7443 5618
Mob 07515 482 580
Email BWeinberg@prime-networks.co.uk
www.prime-networks.co.uk
Kingsway House, 103 Kingsway, London, WC2B 6QX
The information transmitted in this email is intended only for the person(s) or entity to which it’s addressed and may contain proprietary, confidential and / or privileged material. If you have 
​received this email in error, please contact the sender by replying and delete this email so that it is not recoverable. If you are not the intended recipient(s), any retention, review, disclosure, 
​distribution, copying, printing, dissemination, or other use of, or taking of any action in reliance upon, this information is strictly prohibited and without liability on our part.
On 24 May 2017, at 18:17, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah, I figured that'd be the most likely culprit.

What do you see in the terminal when you start up Gophish? Do you see any errors about binding to the port? I'm guessing when you request the page and it doesn't work, you also don't see a connection line appear in the terminal output?

The only other thing I could think of since you mentioned it's definitely not a firewall issue would be to look for other processes already listening on port 80.

**Comment by S0larflare** [comment]
Are you trying to access the 192.168.x.x address from another machine?

The 0.0.0.0:80 is the phish server, what have you got set up for the admin server? Is the issue that you can't see the console unless you're using https://127.0.0.1:3333 or that other users can't see the landing pages? I might just be being dense, can't quite work it out!

Sent from my iPhone

On 24 May 2017, at 19:26, BNWEIN <notifications@github.com<mailto:notifications@github.com>> wrote:

Bear in mind it works on my 127.0.0.1 address so it can't be the port

No errors on startup it's binds to the port fine and correct nothing in the console when I get page cannot be displayed

Sent from my iPhone, excuse any typo's


Ben Weinberg
Operations Director
Tel 020 7443 5618
Mob 07515 482 580
Email BWeinberg@prime-networks.co.uk<mailto:BWeinberg@prime-networks.co.uk>
www.prime-networks.co.uk<http://www.prime-networks.co.uk>
Kingsway House, 103 Kingsway, London, WC2B 6QX
The information transmitted in this email is intended only for the person(s) or entity to which it’s addressed and may contain proprietary, confidential and / or privileged material. If you have
​received this email in error, please contact the sender by replying and delete this email so that it is not recoverable. If you are not the intended recipient(s), any retention, review, disclosure,
​distribution, copying, printing, dissemination, or other use of, or taking of any action in reliance upon, this information is strictly prohibited and without liability on our part.
On 24 May 2017, at 18:17, Jordan Wright <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Yeah, I figured that'd be the most likely culprit.

What do you see in the terminal when you start up Gophish? Do you see any errors about binding to the port? I'm guessing when you request the page and it doesn't work, you also don't see a connection line appear in the terminal output?

The only other thing I could think of since you mentioned it's definitely not a firewall issue would be to look for other processes already listening on port 80.

**Comment by BNWEIN** [comment]
No issues on the admin server. This is working a dream

Other users can't access the phish server and neither can I on my local IP (192.168.x.x)

I can access it using 127.0.0.1 but cannot access it on my own machine using 192.168.x.x

There have been random times when it has worked on my IP 192.168.x.x and when I have been able to others have also been able to access it on my IP

But most of the time I can't

No errors in console

It's like the phish server is binding to 127.0.0.1 but not to my actual local ip

Sent from my iPhone, excuse any typo's


Ben Weinberg
Operations Director
Tel 020 7443 5618
Mob 07515 482 580
Email BWeinberg@prime-networks.co.uk
www.prime-networks.co.uk
Kingsway House, 103 Kingsway, London, WC2B 6QX
The information transmitted in this email is intended only for the person(s) or entity to which it’s addressed and may contain proprietary, confidential and / or privileged material. If you have 
​received this email in error, please contact the sender by replying and delete this email so that it is not recoverable. If you are not the intended recipient(s), any retention, review, disclosure, 
​distribution, copying, printing, dissemination, or other use of, or taking of any action in reliance upon, this information is strictly prohibited and without liability on our part.
On 24 May 2017, at 19:35, S0larflare <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you trying to access the 192.168.x.x address from another machine?

The 0.0.0.0:80 is the phish server, what have you got set up for the admin server? Is the issue that you can't see the console unless you're using https://127.0.0.1:3333 or that other users can't see the landing pages? I might just be being dense, can't quite work it out!

Sent from my iPhone

On 24 May 2017, at 19:26, BNWEIN <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Bear in mind it works on my 127.0.0.1 address so it can't be the port

No errors on startup it's binds to the port fine and correct nothing in the console when I get page cannot be displayed

Sent from my iPhone, excuse any typo's


Ben Weinberg
Operations Director
Tel 020 7443 5618
Mob 07515 482 580
Email BWeinberg@prime-networks.co.uk<mailto:BWeinberg@prime-networks.co.uk><mailto:BWeinberg@prime-networks.co.uk>
www.prime-networks.co.uk<http://www.prime-networks.co.uk><http://www.prime-networks.co.uk>
Kingsway House, 103 Kingsway, London, WC2B 6QX
The information transmitted in this email is intended only for the person(s) or entity to which it’s addressed and may contain proprietary, confidential and / or privileged material. If you have
​received this email in error, please contact the sender by replying and delete this email so that it is not recoverable. If you are not the intended recipient(s), any retention, review, disclosure,
​distribution, copying, printing, dissemination, or other use of, or taking of any action in reliance upon, this information is strictly prohibited and without liability on our part.
On 24 May 2017, at 18:17, Jordan Wright <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Yeah, I figured that'd be the most likely culprit.

What do you see in the terminal when you start up Gophish? Do you see any errors about binding to the port? I'm guessing when you request the page and it doesn't work, you also don't see a connection line appear in the terminal output?

The only other thing I could think of since you mentioned it's definitely not a firewall issue would be to look for other processes already listening on port 80.

**Comment by jordan-wright** [comment]
(Updated the comments to remove some personal info - hopefully I didn't change the actual content 😄 ).

Depending on the OS, you might check to see what processes are listening on port 80. Something like `lsof -i tcp:80` or `netstat -tulpn | grep LISTEN` should show you what's going on. That's odd that you're able to hit it on localhost but not from the IP on the same machine. It sounds like there's some other process bound to the non-localhost interface, but my experience with that is limited.

**Comment by BNWEIN** [comment]
Hi Guys

Any further help on this one. To confirm it cannot be port related, because i can access the phishing server on 127.0.0.1 (port 80).  If the port was in use i wouldnt be able to do that.

It makes no sense to me that i can access the server on that address but not on my local ip 192.168.x.x.

Should i change the config.json file? 

{
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

**Comment by S0larflare** [comment]
So if you set up a campaign using 127.0.0.1 as the landing page, send an email and click a link on that machine, it works as intended, but if you set one up as 192.168.x.x you can't get there no matter what machine you come from? That seems like a firewall issue to me, have you checked to see what you have that could be blocking traffic?

**Comment by BNWEIN** [comment]
Nope, the below is not quiet correct. 

1: Windows Firewall fully turned off
2: Setup a campaign and set the landing page to http://192.168.x.x (my local IP)
3: Browse to that address with the /?rid=xxxx from somewhere on my LAN and it does not work
4: Browse to that address from my own computer it does not work
5: Browse to http://127.0.0.1/?rid=xxxxx on my own computer and it DOES work. 

Again, to confirm firewall is fully disabled, and there no firewall sitting between other PC's on my LAN and my own computer.

**Comment by BNWEIN** [comment]
Ok

So i found the issue and owe you all an appology. Skype was bound to port 80 on my local IP. The way i found this was the issue was by changing config.json to my local IP instead of 0.0.0.0:80.  Then when i started it it showed me that it could not bind to 80 on that IP!  Checked and Skype had it in use.

**Comment by jordan-wright** [comment]
No problem at all. We're here to help and I'm glad to hear you got it resolved!

Let us know if you run into any other issues.
