### ISSUE TITLE
Cant get admin to come up on linux

### ISSUE THREAD

**Issue by jbilliau** [gophish/gophish#634]
Threw the code on linux server.  Couldn't run the bash cuz port 80 was already running with apache.  Change ports to 8081.  Put the admin server url on the private IP of that webserver.  I still cant get to the page... what gives?

`{
	"admin_server" : {
		"listen_url" : "10.10.0.75:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:8081",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}
`

**Comment by S0larflare** [comment]
So what happens if you go to https://10.10.0.75:3333 ?

**Comment by jbilliau** [comment]
nothing, just spins.  i cant telnet to 10.10.0.75 either from my windows machine.  I can ping it fine tho

**Comment by S0larflare** [comment]
What does the console show when this is going on?

**Comment by jbilliau** [comment]
`root@icrweb01 [/home/phishing/public_html]# ./gophish
goose: no migrations to run. current version: 20170219122503
 2017/05/24 15:48:59 gophish.go:83: Starting phishing server at http://0.0.0.0:8                                 081
 2017/05/24 15:48:59 worker.go:36: Background Worker Started Successfully - Wait                                 ing for Campaigns
 2017/05/24 15:48:59 gophish.go:66: Starting admin server at https://10.10.0.75:                                 3333
`

**Comment by jbilliau** [comment]
forget linux for a minute, what about IIS.  I have an IIS server exposed to the internet.

How do I get it going on that?  I think I'm getting confused.  I added an IIS website already, and ran the gophish executible.  I dont think the point is to run both the right? Since the exe in itself is the webserver.

My goal is to get the phishing url exposable on the internet, but the admin url can still internal only.

**Comment by jordan-wright** [comment]
IIS is not required. It is a webserver, and Gophish has it's own webserver, so they would conflict unless you're doing some proxying from IIS into Gophish, but my guess is that you're not referring to this.

If you want the phishing server to be exposed externally, the `phish_server` option in the config.json should be set to all interfaces, `0.0.0.0:80`. Likewise, if you want the admin server to only be exposed to localhost (or even internally), just set it to listen on localhost (`127.0.0.1`) or an internal IP address.

Looking at your previous responses, my guess is that you're still running into firewall issues. You say you can't telnet to the IP address after Gophish is started, which indicates a connection issue. Pinging it is a different story (and a different protocol). Just because you can ping the box doesn't mean you don't have a firewall in the way 😄 

My approach would be to see if you can reach the admin server from localhost. If you can do that and you still can't reach it from other boxes on the same subnet, you probably have firewall issues.

**Comment by jordan-wright** [comment]
Closing this out as it's been 3 weeks without an update. @jbilliau if you are still having issues, please respond to the previous comment with any updates and we can re-open.
