### ISSUE TITLE
IMG tag to track opening of mail is visible on mails

### ISSUE THREAD

**Issue by m4mba** [gophish/gophish#647]
the option on email templates were you can add a hidden img tag to check if a user opened the mail is not making the img tag invisible. when this option is chosen and an email is sent and opened in outlook for example, this img tag is visible in the mail. Which part of the code is handling this tag?

**Comment by jordan-wright** [comment]
What does the email source look like? Is there something wrong in the `img` tag? And when you say "this img tag is visible in the mail", do you mean you actually see the tag itself in the content of the email?

**Comment by m4mba** [comment]
Hi, what I mean is that I see a image icon with a red "X" in it. on gmail I don't see this, only on applications like outlook and windows mail. Sendgrid is also using a img tag to check if the user opens the mail, and I noticed that they have added some more html into it to make sure it is invisible.

**Comment by S0larflare** [comment]
That's an Outlook thing rather than a gophish issue. By default, Outlook will block the download of assets unless they are from a trusted source. The red X is the placeholder for an image which hasn't been downloaded or rendered properly. If a user clicks to allow the images, that red x will disappear. Now naturally, from a functional point of view that isn't very good. There is a potential fix however. As far as I am aware, Outlook gets it's trusted list from IE's Trusted sites. So if you wanted your 'victims' to not get the red x, you would have to have the IP of your phish server put in to trusted sites via GPO and that should fix it. I haven't actually done this one my end (I don't use the email tracking) but in my head that should work and was something that was on my to do list...

**Comment by jordan-wright** [comment]
The other possibility is that the image isn't reachable by the user. Have you sent a test campaign to yourself to ensure the image resolves correctly and you can open the landing page? It's possible that there may be networking/firewall issues preventing connections from your users to the Gophish instance.

**Comment by m4mba** [comment]
I actually downloaded the picture in outlook and it didn't work. I am pretty sure that it has to do with the html of the img tag itself. Because I tried sending this through sendgrid which also uses this feature and their img tag does not cause this problem. I have no issues with firewall / network

**Comment by jordan-wright** [comment]
You'll want to disable the image tracking from Sendgrid- it's possible that it might be messing things up.

What HTML in the email do you see? That'll help us figure out if the email is correct or not.

When you say you open the image and it doesn't work, what do you mean? What do you see?

**Comment by m4mba** [comment]
I researched the problem some, and I discovered that something was wrong with the URL. the full in the src of the img tag was not added so the img was rendered with the red X. It now works after adding the correct URL. Wow, It's not usual for me to see this kind of support in a open source product, I really thank you and appreciate your work.

**Comment by m4mba** [comment]
I noticed that when I send the an email with the tracking img tag and with the full URL of the gophish server, the mail gets identified as spam by my company's spam filter which is strange, probably something in the URL of the img tag is identified as malicious. When sending the mail and enabling the tracking img of sendgrid I notice that the mail is successfully received in the inbox without any problems. Could you tell me what part of the gophish code is dealing with the img tag so I can research it? thanks a lot for all the support!

**Comment by jordan-wright** [comment]
Sorry for the delay.

The checkbox you see to add tracking adds the `{{.Tracker}}` template tag to the email. This is done via Javascript here: https://github.com/gophish/gophish/blob/master/static/js/src/app/templates.js#L30

Then, the actual template is parsed in the worker here: https://github.com/gophish/gophish/blob/master/worker/worker.go#L127

Hope this helps! Closing this one out since the original issue appears to be resolved. 😄
