### ISSUE TITLE
The credentials received is not been displayed. 

### ISSUE THREAD

**Issue by manny-queen** [gophish/gophish#659]
After launch of campaign, email is been opened, read and redirected but the credentials does not display on the dashboard. By the way, I am using the windows version.

**Comment by jordan-wright** [comment]
What does your HTML form look like? To capture credentials that are stored, you will need to make sure that every form `input` element has a `name` attribute. 

There are multiple other issues on this subject that may provide [more information.](https://github.com/gophish/gophish/search?utf8=%E2%9C%93&q=capture+credentials&type=Issues)

Let me know if you're still running into issues after looking through those questions- happy to help any way we can.

**Comment by manny-queen** [comment]
Wow.... that worked. Stepping a bit further, can gophish be hosted? Saying over the internet (WAN)

**Comment by jordan-wright** [comment]
Yes, as long as your targets can reach the phishing server everything will work fine over the wan. You just need to set your phishing server address in the config.json to 0.0.0.0 so that it binds to the external interface. Then, in the URL of your campaign configuration, you'll want to make sure to put in the external IP/domain name of the phishing server.

**Comment by jordan-wright** [comment]
Going ahead and closing this one out since the original issue appears to have been resolved. Let us know if you continue to run into any issues!
