### ISSUE TITLE
Need fully-qualified hostname

### ISSUE THREAD

**Issue by Svanekongen** [gophish/gophish#669]
Hello,

i'v tried to resolve this problem for too long now, and now i need your guys help.
When i try to send a test mail to my mailserver it says "Need fully-qualified hostname"
![fqdn](https://user-images.githubusercontent.com/29792723/27725463-c5132964-5d76-11e7-835a-df522e953dbf.png)

my DNS works fine i can ping and lookup names, my fqdn is configured on all my clients.

my mailserver works, i have tested it to see if it was the mailserver who was the issue here.

i'm on a internal network from Virtualbox and i don't know if that is the problem??

i have attached some picture of my configuration so you can take a look at it 
![dns](https://user-images.githubusercontent.com/29792723/27725569-3fe79b98-5d77-11e7-844d-2d4cc47241d9.png)

![gophish dns](https://user-images.githubusercontent.com/29792723/27725575-437f13bc-5d77-11e7-89ca-cf6c6927c613.png)

![hosts dns](https://user-images.githubusercontent.com/29792723/27725580-47c5c894-5d77-11e7-98fc-3d53b9ee2461.png)

![mailserver hosts](https://user-images.githubusercontent.com/29792723/27725583-4b6cd7ee-5d77-11e7-81ef-f820573e644e.png)

**Comment by S0larflare** [comment]
Instead of 192.168.0.20 try putting in the hostname (mailserver.fred3riksberg.dk<http://mailserver.fred3riksberg.dk>)

Sent from my iPhone

On 30 Jun 2017, at 08:37, Svanekongen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

i'v tried to resolve this problem for too long now, and now i need your guys help.
When i try to send a test mail to my mailserver it says "Need fully-qualified hostname"
[fqdn]<https://user-images.githubusercontent.com/29792723/27725463-c5132964-5d76-11e7-835a-df522e953dbf.png>

my DNS works fine i can ping and lookup names, my fqdn is configured on all my clients.

my mailserver works, i have tested it to see if it was the mailserver who was the issue here.

i'm on a internal network from Virtualbox and i don't know if that is the problem??

i have attached some picture of my configuration so you can take a look at it
[dns]<https://user-images.githubusercontent.com/29792723/27725569-3fe79b98-5d77-11e7-844d-2d4cc47241d9.png>

[gophish dns]<https://user-images.githubusercontent.com/29792723/27725575-437f13bc-5d77-11e7-89ca-cf6c6927c613.png>

[hosts dns]<https://user-images.githubusercontent.com/29792723/27725580-47c5c894-5d77-11e7-98fc-3d53b9ee2461.png>

[mailserver hosts]<https://user-images.githubusercontent.com/29792723/27725583-4b6cd7ee-5d77-11e7-81ef-f820573e644e.png>

**Comment by Svanekongen** [comment]
in dns hosts file? :)

**Comment by S0larflare** [comment]
In the gophish sending profile. You've put an IP, the error suggests it wants an FQDN

Sent from my iPhone

On 30 Jun 2017, at 08:54, Svanekongen <notifications@github.com<mailto:notifications@github.com>> wrote:


in dns hosts file? :)

**Comment by Svanekongen** [comment]
i got it to work now! thanks

now i get this error "Policy rejection not logged in" i'm using iRedmail server if it can help?
