### ISSUE TITLE
Does Gopish run on 2008r2 ?

### ISSUE THREAD

**Issue by OVMorat** [gophish/gophish#670]
It's just that I had it running fine on my w10 laptop when messing about but I've tried two different 08 VMs and no joy. The app just crashes out and the web pages aren't served. It's too fast to see what errors are showing in the window :(

**Comment by S0larflare** [comment]
Try running it as something like "cmd /k gophish.exe"

That should leave the cmd window open after the process ends and show any output that shows the cause of the crash

Sent from my iPhone

On 30 Jun 2017, at 09:28, OVMorat <notifications@github.com<mailto:notifications@github.com>> wrote:


It's just that I had it running fine on my laptop when messing about but I've tried to different 08 VMs and no joy. The app just crashes out and the web pages aren't served. It's too fast to see what errors are showing in the window :(

**Comment by OVMorat** [comment]
Hah, thank you :)

2017/06/30 10:02:54 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was
ade to access a socket in a way forbidden by its access permissions.

**Comment by S0larflare** [comment]
Sounds like gophish doesn't have permissions to use port 80. This could be that the port is already in use or that it needs to be run as admin in order to bind the port

Sent from my iPhone

On 30 Jun 2017, at 10:04, OVMorat <notifications@github.com<mailto:notifications@github.com>> wrote:


Hah, thank you :)

2017/06/30 10:02:54 gophish.go:84: listen tcp 0.0.0.0:80: bind: An attempt was
ade to access a socket in a way forbidden by its access permissions.

**Comment by OVMorat** [comment]
I'm going to run this on a virgin server which doesn't have lots of other apps getting in the way. Thanks for the help, it got me to the right decision :)
