### ISSUE TITLE
Windows intallation

### ISSUE THREAD

**Issue by taharmk** [gophish/gophish#674]
Hello everyone,
i have TLS certificat issue, chrome is not validating my certificate, is there any solution.
thanks

**Comment by jordan-wright** [comment]
Hey there.

What site are you trying? You should be able to reach the server by trying https://localhost:3333. You will need to accept the SSL certificate warning since Gophish by default uses a self signed certificate.

**Comment by taharmk** [comment]
Hi,
i get warning, i accept it and then i got login form and connected.
but still HTTPS is in red (because it is self signed).
1- how to get a good SSL certificated to avoid the warning and how to replace it by the existing one.
thanks a lot

**Comment by jordan-wright** [comment]
The SSL certificates used by Gophish do not have anything to do with the SMTP provider you choose to use.

Getting a CA-signed cert is outside of the support we offer. There are tons of tutorials available online that you can use. You may choose to get a certificate from your domain name registrar or using something like Let's Encrypt.

Once you have the cert/key pair, you can find instructions on how to use them in our documentation: https://gophish.gitbooks.io/user-guide/content/installation.html

I recommend searching through other issues for people who have had similar questions in the past.

Since Gophish appears to be working properly and you can login, I'm going to close out this issue.
