### ISSUE TITLE
Adding bcc emails in header

### ISSUE THREAD

**Issue by veki91** [gophish/gophish#685]
Was wondering if there is anyway to add bcc email addresses in the header when creating a campaign. I am trying to use this in an upcoming campaign.

**Comment by Mlb66** [comment]
Hello,
I do not think this is possible with the current version, without touching
the code.
As an addition to this post, one feature I thought of when running a test
is to have the target email in the BCC field and having the to field empty,
to simulate a mail manually sent at once to a lot of people. I do not know
if it would be ok to add on the roadmap of this app.

Le 11 juil. 2017 8:23 PM, "Veki Nikolic" <notifications@github.com> a
écrit :

Was wondering if there is anyway to add bcc email addresses when creating a
campaign.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gophish/gophish/issues/685>, or mute the thread

**Comment by jordan-wright** [comment]
I'm afraid I believe the only way to add information in the Bcc field is to add custom headers when setting up the sending profile, though I can almost promise you that it won't do what you're looking for, since the "To" field will stay the same.

I don't have plans at this time to add support for Bcc campaigns unless there is significant requests from the community, as this would add quite a bit of complexity to the UI and backend, and my goal is to keep Gophish as simple and easy to use as possible while hitting the majority of major use cases.

Thanks for the suggestion, though!
