### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by riot1502** [gophish/gophish#689]
My dashboard does not update when emails are opened or if links are clicked.  Not sure if this has something to do with my config file.

Campaigns are being ran internally.

Here is my config...

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:8084",
                "use_tls" : false,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}

Thanks for all the help!

**Comment by S0larflare** [comment]
Do you mean the campaign doesn't show clicks etc? It might be to do with the port of 3333 for the phishing server. With that you would have you manually state that port in the campaign (so instead of http://fakegoogle.com you'd need to do http://fakegoogle.com:3333 as the campaign url)

Sent from my iPhone

On 12 Jul 2017, at 15:02, riot1502 <notifications@github.com<mailto:notifications@github.com>> wrote:


My dashboard does not update when emails are opened or if links are clicked. Not sure if this has something to do with my config file.

Campaigns are being ran internally.

Here is my config...

{
"admin_server" : {
"listen_url" : "0.0.0.0:8084",
"use_tls" : false,
"cert_path" : "gophish_admin.crt",
"key_path" : "gophish_admin.key"
},
"phish_server" : {
"listen_url" : "0.0.0.0:3333",
"use_tls" : false,
"cert_path" : "example.crt",
"key_path": "example.key"
},
"db_name" : "sqlite3",
"db_path" : "gophish.db",
"migrations_prefix" : "db/db_"
}

Thanks for all the help!

**Comment by riot1502** [comment]
Still no change to the dashboard after creating a new campaign with the port number appended to the URL.

**Comment by jordan-wright** [comment]
If you include yourself on the campaign, what do you see when you open the email, click the link, etc.?

And when I say "what do you see" I mean in your browser, in the Gophish terminal, etc.

**Comment by riot1502** [comment]
I see the landing page that I tailored when clicking the link within the email I also customized.  Everything looks like its running correctly.  The console shows myself as a recipient of the email and that the message has been successfully sent.

Within the GoPhish Terminal, the following output is displayed.

2017/07/18 07:37:22 campaign.go:340: Found 1 Campaigns to run
 2017/07/18 07:37:22 worker.go:53: Worker received: Support Test
 2017/07/18 07:37:22 worker.go:170: Creating email using template
 2017/07/18 07:37:22 worker.go:210: Sending Email to myemail@mydomain.com
 2017/07/18 07:37:22 main.go:724: sql/go/src/github.com/gophish/gophish/models/campaign.go:144158.231µsINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[11 myemail@mydomain.com 2017-07-18 07:37:22.290974665 -0500 CDT Email Sent ]

Followed by what looks like a successful network connection from the victim machine (my computer)

'my internal private IP address' - - [18/Jul/2017:07:37:26 -0500] "GET /api/campaigns/11/results?api_key=9870214e51f849c7e5f92bd0f18549c72c48002f54355ed7cbef5a3cac763e3d&{} HTTP/1.1" 200 310 "http://THEserversDNSname:8084/campaigns/11" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

This is repeated numerous times in the terminal and then this line of code appears...

 2017/07/18 07:38:22 campaign.go:340: Found 0 Campaigns to run

**Comment by riot1502** [comment]
It just occurred to me that the log information could also result from my PC being connected to the dashboard and not necessarily from opening the email and clicking the link.

**Comment by jordan-wright** [comment]
Correct, the second log you showed was hitting the `/campaigns/11/results` endpoint, which is just the dashboard polling for new results. We would need to see a log that points to the phishing server to indicate that the user hit Gophish successfully.

**Comment by riot1502** [comment]
What should I see from and end user machine if I navigate to the internal IP address with port 3333 appended at the end?  Right now I get a connection refused page.  Is that the likely cause?

**Comment by BBsttx** [comment]
riot1502 - Did you resolve you issue of Dashboard not updating?  I seem to have the exact same problem.

**Comment by riot1502** [comment]
Negative.  Have not resolved the issue.  

Thank you,

John Keese
Jkeese1502@gmail.com
262-422-1509

**Comment by jordan-wright** [comment]
@riot1502 sorry for the delay in getting back to you.

It looks like the issue is that you're phishing server is listening on port `3333`. If you didn't specify `x.x.x.x:3333` in your campaign URL value, it's likely that the wrong link was sent in emails.

In addition to this:

> What should I see from and end user machine if I navigate to the internal IP address with port 3333 appended at the end? Right now I get a connection refused page. Is that the likely cause?

is indicative that there is network connectivity problems between your end user machine and Gophish. If you are able to reach the server, you should see a very boring "404 page not found" error page.

I personally recommend keeping the phishing server on port 80 if possible and working to diagnose any possible firewall rules which may be preventing connectivity to Gophish.

Let us know if that helps any!

**Comment by riot1502** [comment]
After switching the admin port to 8080 and the phishing server port to 8084, creating another campaign, then typing the following into the URL field "http://serverIPaddress:8084" I am able to get a result IF AND ONLY IF the recipient of them email performs the "Click here to download pictures.  To help protect your privacy, Outlook prevented automatic download of some pictures in this message."

Is the latter normal functionality?  Do images NEED to be downloaded for the tracking to work?

**Comment by jordan-wright** [comment]
Hey there! Sorry for the delay on this.

That's normal functionality. Gophish adds a tracking pixel which is the way email tracking in general works. Email clients know this and can block these by default to protect privacy. Unfortunately, there is very little we can do about this.

Glad to here you got it working by changing the port!
