### ISSUE TITLE
Open email not displayed

### ISSUE THREAD

**Issue by jresende** [gophish/gophish#692]
Hello,

I'm testing your framework and the message Email Openned is not displayed.
To test this I'm sending an email from gmail to a gmail client (in this case the same account) and other images are displayed.
I'm using the pré compiled version for linux 64 bits on ubuntu.

Can you help me on this?

best
João

**Comment by jordan-wright** [comment]
Hey there!

When you say other images are displayed, do you mean other images in the email? Gmail is kinda funny in that it proxies external image requests for users, so you may see mixed results when sending emails to Gmail addresses.

That being said, do you see any logs in the terminal when you open the email? If not, make sure that the Gophish phishing server is accessible from the Internet, so that the request for the external image can be received.

**Comment by jresende** [comment]
Hello,

Thanks for the support.

I has assuming that the request from gmail has performed locally on the browser. But yes I set the machine to receive request and the flag of open has displayed

best
João
