### ISSUE TITLE
Sqlite3 to Mysql help

### ISSUE THREAD

**Issue by InternSta** [gophish/gophish#701]
Currently gophish is running on the admin server and i am able to login with the default credentials/change them etc. Its not working on the phishing server . Gophish is currently using sqlite3 in the config file, how do i move it over to mysql?

**Comment by jordan-wright** [comment]
> Its not working on the phishing server

What do you mean by this? We'd need to know what you're trying to do, what you tried, and what you're seeing when it's not working.

> how do i move it over to mysql?

If you're hoping that moving it to MySQL would fix this issue, it's unlikely. But, if you want to move it to MySQL and you are ok with losing your data (since we don't have scripts to migrate everything over) you can follow the docs to setup the config here: https://gophish.gitbooks.io/user-guide/content/installation.html#using-mysql

**Comment by InternSta** [comment]
When I try to go to the phishing server address it will give me a 404 error, and when I check this Is the message that occurs in the shell;

[21/Jul/2017:09:28:18 +0100] "GET / HTTP/1.1" 404 43 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

I'm fine with losing data, I just need to be able to get both servers working, and be able to use a MySQL database. Currently I'm just using sqlite3 however I have tried to follow the docs to setup the config before with not much success which Is why I've redone everything to start clean.

**Comment by jordan-wright** [comment]
It looks like you're trying to navigate to the address directly, which would return a 404. That's expected.

When Gophish sends out links in emails, it puts a parameter on the URL such as `rid=123456` where the ID is a unique ID for every recipient. Then, when this URL is requested, Gophish dynamically loads the correct landing page and returns it to the client.

**Comment by jordan-wright** [comment]
So my recommendation would be to launch a campaign against your own email address and see if Gophish returns the page you expected.

**Comment by InternSta** [comment]
Thanks for the help, I have been able to get gophish up and running as well as using the MySQL database.
