### ISSUE TITLE
Send mails CCO

### ISSUE THREAD

**Issue by knowtheunknown** [gophish/gophish#711]
Hi everyone!

I wish that an adressee doesn't be able to read the others adressees. ¿How can I get the following message header on my campaigns?

**_Sender: sender@domain.com
To: sender@domain.com
CC: 
CCO: target1@domain2.com ; target2@domain2.com ; target3@domain2.com_**

Thank's!

**Comment by S0larflare** [comment]
Everyone gets their own separate email. They are the only recipient so they are unable to see others in the campaign

Sent from my iPhone

On 28 Jul 2017, at 13:05, knowtheunknown <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi everyone!

I wish that an adressee doesn't be able to read the others adressees. ¿How can I get the following message header on my campaigns?

Sender: sender@domain.com<mailto:sender@domain.com>
To: sender@domain.com<mailto:sender@domain.com>
CC:
CCO: target1@domain2.com<mailto:target1@domain2.com> ; target2@domain2.com<mailto:target2@domain2.com> ; target3@domain2.com<mailto:target3@domain2.com>

Thank's!

**Comment by jordan-wright** [comment]
@S0larflare is absolutely correct. We don't support any sort of BCC system right now since everyone receives a separate email.

It sounds like this solves the issue you're asking about so I'm going to close this out. If you're seeing odd behavior with the emails sent by Gophish, let us know and we can continue troubleshooting.
