### ISSUE TITLE
Feature Request: Sending profile interface using EWS

### ISSUE THREAD

**Issue by stusmall** [gophish/gophish#714]
Sometimes SMTP isn't exposed on the target.  Being able to send over EWS would be nice

**Comment by stusmall** [comment]
For anyone who runs into a similar problem in the future, I got around this by using a davmail gateway between gophish and the EWS endpoint.  Native support would be nice but this work around exists.

**Comment by jordan-wright** [comment]
Hey there! Thanks for the suggestion!

Can you explain the use case a bit more? I can't imagine a scenario where the target can't accept email over SMTP but I could be missing something. Generally, people will just setup a local SMTP relay and point Gophish to that, so that the relay will find the correct MX records and send mail to the target org.

That said, there are other difficulties with implementing EWS. It's a very specific protocol that would only apply in limited set of scenarios. That makes me leery to dedicate the dev time to implement it since it would only be used by a few people. It also introduces significant UX work to make things seamless in configuration/etc. Unless there's a clear use case I'm missing, I likely won't be able to add EWS support any time soon if at all.

**Comment by stusmall** [comment]
I'll be honest, it is a pretty edge case.  You aren't missing the clear use case :)  It was the peculiarities of the situation that I was facing that required it.  The mail server I wanted to use didn't expose SMTP to the internet but did expose EWS.  It would make sense if you passed on the feature, especially since there is a work around available, even if it was kind of hacky.

**Comment by jordan-wright** [comment]
I think you're right. For now, we'll close this one out since there is a work around available. I appreciate you updating the issue with the workaround!
