### ISSUE TITLE
Having trouble starting GoPhish

### ISSUE THREAD

**Issue by MrStrixJoker** [gophish/gophish#717]
Hello, I have been trying to set it up but localhost will not connect, I tried changing ports, IP Addresses etc. Nothing Yet

Here is the message I get

![image](https://user-images.githubusercontent.com/25812275/29090520-6d1c9982-7c45-11e7-8f6a-d76af8c736f1.png)

**Comment by S0larflare** [comment]
Looks like a permissions issue. Try running cmd as admin (right click the start button for a quick shortcut) and try again

Sent from my iPhone

On 8 Aug 2017, at 20:25, MrStrixJoker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, I have been trying to set it up but localhost will not connect, I tried changing ports, IP Addresses etc. Nothing Yet

Here is the message I get

[image]<https://user-images.githubusercontent.com/25812275/29090520-6d1c9982-7c45-11e7-8f6a-d76af8c736f1.png>

**Comment by MrStrixJoker** [comment]
I did run it via admin, Ill try again

**Comment by jordan-wright** [comment]
Most of the time, this means that the port already has another service listening on it. You can try to [use this](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows) to find out what's using the port and stop that service.

Otherwise, [similar issues](https://github.com/gophish/gophish/search?q=an+attempt+was+made&type=Issues&utf8=%E2%9C%93) are usually resolved by changing the port of the phishing server.

Hope this helps!

**Comment by MrStrixJoker** [comment]
is port 83 ok to use? I got it working on that

**Comment by jordan-wright** [comment]
You can use port 83, but you'll need to remember to use port 83 on the "URL" setting when you launch a campaign.

**Comment by jordan-wright** [comment]
Closing this out since there hasn't been any updates in a couple of weeks.
