### ISSUE TITLE
Stop Future Emails from Being Sent When Campaigns Are Deleted or Cancelled

### ISSUE THREAD

**Issue by Raytri3** [gophish/gophish#719]
I had to put an emergency stop on one of my campaigns tonight (I hit the delete campaign button wasn't sure how to best kill it in the UI). When I did so I noticed that some of the emails went through while others were still in the queue. Obviously there isn't a way to do anything with the messages that were delivered outside working with the client; however as we were doing so, messages in the queue started getting delivered (after I told them I hit delete).  I had to go in and issue a postsuper -d ALL to kill messages in the queue. I would love a "kill" button in the UI that does this - stops the mailer (so nothing more can be sent), flushes the queue and the restarts the mailer.

**Comment by jordan-wright** [comment]
Ah, I hadn't even thought about this scenario.

Killing all outgoing mail should be possible when I finish refactoring the mall queue. Until then, I think you're right that completing or deleting a campaign should cancel any outgoing emails that haven't been sent. I'll see if I can put in that functionality.

**Comment by mfberry** [comment]
Has this been changed? I'm on the 7.1 release using a campaign with end time, and ran into this issue today. I've since just blocked outbound SMTP but would rather not lose my database of information.

I have completed and deleted the campaign and still see emails getting sent to postfix.

**Comment by Gradle999** [comment]
Just to add to this, is there a way of viewing the queued/scheduled emails in the GUI or a log somewhere? I'm thinking that once the emails are 'scheduled' for sending, it then continues to send these out even though the campaign is deleted. 

I've also encountered this issue, as I had to delete a campaign yesterday which was scheduled to run over a week, replaced it with the new campaign, and some users are receiving two emails still today, despite the campaign being deleted yesterday. Would be good if there was a log somewhere that I can look at to check if there are duplicate emails in the queue.

**Comment by jordan-wright** [comment]
Hey everyone,

I've made a change in 53b3a98 that deletes outstanding emails to be sent when a campaign is complete.

Unfortunately, this isn't perfect. As I mentioned in a similar issue (#1318), what this does is delete emails that haven't been picked up to be sent yet. So if a campaign is set to launch immediately, this won't help since the background worker already picked up all the emails to send. However, if a campaign is scheduled in the future, the emails should be prevented from being sent.

**Comment by ImperatorRuscal** [comment]
Is this issue supposed to be fixed in release 0.7.1 ?

I came here to see if I could offer a code update (or, at least a new issue) regarding messages still being queued in maillog after a campaign is deleted.  I got to models/campaign and see a note on the last commit that the problem was fixed as a resolution to this issue.

But I am using release 0.7.1 (windows) and ran a campaign this week where this exact thing happened.  I'd scheduled a send, an hour later (still well before send was scheduled) I got a message from management wanting to change some wording in the email and alter the target list, so I deleted the existing campaign.  I had the console window open and it "felt wrong" (I guess I was expecting to see a console message about clearing the log since it scrolled through pages of how it populated it).  So I close down, open up the db to take a browse, and see all of the messages from the deleted campaign still sitting there in the log, waiting to send on schedule.

I manually cleared them out, restarted gophish, and scheduled my new campaign.  So I'm not hurting.  But that could have been rather bad.

**Comment by nin-ack** [comment]
Also checking in here to see if this issue is fixed as of `0.7.1`. All emails appeared to remain "scheduled" in the UI after the campaign was manually completed so I have killed the gophish instance until I can be certain. 

![image](https://user-images.githubusercontent.com/16235213/80132467-53a70c80-8561-11ea-9365-0dc663c9e2f7.png)
