### ISSUE TITLE
Trusted Certificate

### ISSUE THREAD

**Issue by RoNinja** [gophish/gophish#721]
Hi 
I had been installed gophish system on my server and I want to use https protocol and also that the clients will be able to see the landing page as trust site.
so I purchased certificate from godaddy and I'm not sure what's the next steps.
Godaddy need CSR and I don't know how to create it so I used DigiCertUtil.exe based on country and domain name and I saved it to txt file.
next thing I copied that string into godaddy box and request for certificate.
when I download it I got two files *.cert.
which one should I use? 
where can I find *.key?

**Comment by jordan-wright** [comment]
There are quite a few tutorials online that go over the process for getting the .crt and .key files. [This](https://helpdesk.ssls.com/hc/en-us/articles/203427642-How-to-install-a-SSL-certificate-on-a-NGINX-server) is one of them, but instead of using the files in nginx, you would use it in Gophish.

I'm afraid generating the CSR and getting the cert/key from that is out of the scope of our support. I recommend contacting GoDaddy support if you are having trouble getting those files.

**Comment by jordan-wright** [comment]
Going ahead and closing this one out since generating the certificate and private key are outside of the support we can offer.

After you generate the files, let me know if you're having trouble using them we Gophish and we can work together to troubleshoot.

**Comment by KrishanKanagarajah** [comment]
Hi Jordan,

I got the files and I do not know where to put them or install in gophish.

Note: Gophish 7.2 is running on Windows 2016 server in AWS instances.

Please let me know if you need more information.

Krishan
