### ISSUE TITLE
OpenSuse Download Issue

### ISSUE THREAD

**Issue by Jackbquick212** [gophish/gophish#736]
I downloaded Gophish into an OpenSuse VM, extracted the files, and each time I try to run the binary I get a "gophish: gophish: cannot execute binary file" error message.  I chmod'd executable permissions on the binary, and I'm running as root, and still nothing. 

Anyone know what might be causing the hiccup?

**Comment by jordan-wright** [comment]
I'm afraid I haven't tested with OpenSuse. It may be the case that the binary isn't compatible with the OS.

If this is a VM dedicated for use with Gophish, you may have better luck with something like Debian.

I'll keep this issue open for a bit so that maybe we can get someone with more OpenSuse experience than I have to chime in :)

**Comment by Jackbquick212** [comment]
Huh, interesting.  I'll try it on a Debian build and see how it goes.

Thanks!

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in a couple of weeks. @Jackbquick212 let us know if trying a Debian build still yields the same results.

Thanks again for getting in touch!
