### ISSUE TITLE
External URL

### ISSUE THREAD

**Issue by DownloadError** [gophish/gophish#743]
I'm attempting to make the URL available externally outside of the local network but to no avail.

From what I can gather the link would link back to http://serverip:80.

Any help would be greatly appreciated.

**Comment by jordan-wright** [comment]
Hey there!

You'll need to set your config.json phish server address to 0.0.0.0:80 and then use your servers external IP address when setting up the campaign (it goes the in "URL" field).

You can find more information here: https://gophish.gitbooks.io/user-guide/content/installation.html

If that still doesn't work, just try hitting your servers IP address manually. If you see a boring 404 page then you should be fine on connectivity. Otherwise, check for any firewall rules that may be causing connectivity issues.

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in a while. @DownloadError let us know if the information above doesn't help resolve the issue and we can re-open to continue troubleshooting.
