### ISSUE TITLE
suggestion for functions

### ISSUE THREAD

**Issue by ITsenhong** [gophish/gophish#748]
I am new to gophish and very interesting with it!
I have 2 suggested functions for it:
1. I know gophish have tracking "rid" in link when sent email to targets. It is very helpful for Email phishing but it limit gophish's ability within only Email phishing tool (think of myself). I knew target can submit multiple credential with one "rid", but it still depend on email for setup. With a hope gophish will become Social Phishing Tool, I suggest that gophish shall have fixed "rid", independent about email or just default domain we fill in setup campaign for capture credential's page
2. I setup gophish on aws ec2 and public admin's page on internet for convenient. but  someone know about it (imagine it), he register one account (even more) and he use my hard setup service free. I don't know about it until I have accessed to gophish.db via sqlite3 because it not show in admin control panel. I suggest the function: admin can control user direct in control panel.
I am sorry I am not helpful for my suggestion because I am not a programmer. I don't know Am I very idiot for my suggestion?, I am not also think the functions is accepted, but i think it useful for gophish and I said.
Lastly, sorry for my poor english!
Thanks!

**Comment by jordan-wright** [comment]
Thanks for reaching out!

1. I'm afraid this won't be possible. The `rid` is not just for a result, but rather for a result/campaign pair. It identifies a target in the context of a campaign. There aren't any plans to add an accessible persistent ID to each target, and there also aren't any plans to add social phishing aspects to Gophish, since this is outside the scope of what we aim to accomplish.

2. This is something that I'll need to consider a bit more. I can see the issue, since exposing the admin panel opens the host up to abuse. Ideally, it should still be firewalled off as much as possible, but leaving it wide open for registration probably isn't the best. I'll consider how to best handle this, but we'll handle it through #693.
.

**Comment by ITsenhong** [comment]
1. Thanks! I understand the aim of gophish.
2. Hope you will fix soon!
