### ISSUE TITLE
Import Landing Page Failure: Office 365

### ISSUE THREAD

**Issue by reubadoob** [gophish/gophish#753]
Anytime I attempt to import a Microsoft login page I get a blue screen on the import screen. I checked with google and no issues. The import worked flawlessly. Just wondering if this is a problem with M$ login page or gophish. Thanks for all the help! 

1. [Current M$ Login Page](https://login.microsoftonline.com/common/reprocess?ctx=rQIIAXWRO2_TUACFsfNABakgJNSVgQWkJNfPxJEqUdI87MR2Hk5Te4n8TOzk2ql9Wyd3QKj8gHaApRILQkLqyAJir5A6deYHIMTIxIj7A1iOvuEMR995nqPKVP0py7CcWbWEkmDyTIkVKFAyWZovMRzDMzSgHA4w8aN7D9-ffTfkq9Pemyv1_ouzZx8viZ05QqukXqmkaVqOPM-33bIdwcpXgrghiF8EcUEW3LA0Hl2SCc_wLAVoBtRqHOBonq-WdSxBfdLcKMEeUrUlNEYA6LQEe9rSV7CIjMAGCnYWMlb8jFNjonM6FtdyICMlEFm1AUDGm95EpORJE8n0mFKwjuV2k9LxDP8gH6h7x2hO30YU-9j9Q255UQynqyhBF7lPhLpyQ9FpRGHo2qh8W3ND5Nsm8qOwH0crN0a-m-wy04FANWR-2jWT7rAFWzCsarbQORk2LU3bpLpldFq8UJ22tZOhdtAX5kOFGzZq1SPFwwec0Q_2N6k8gCtNCCYiNrmZmtlt01pLtdWxRPWgxUoD7FKKBWcvk67nHVjzcWfRlPx4hHH3c66YaYVReJ3bzkaFvvNkFUeev3Rv8sTvPAm2_-aJD4Xsoy_vXu2c_nzce7sevb7rkHeuC5UEJpqE0kPYA9JRA46sNl7EnCIZwaFFr_dTd8QvRNF1js10t1anzovEebH4bet_3_4D0)
2. [New M$ Login Page](https://login.microsoftonline.com/common/reprocess?ctx=rQIIAXWRu27TUACG69xQGQpCQqwMSEgIJz4-viQRFYqSOLUTO4kvcuKlcnxJ7OBL7eM68c7CgLqwdIwQSGVjQAjeoFNnXoCqIxMj7QOwfNM_fPq_F2VQB-1nFKRok1208JbJQJxqAQI3KZLBIQ0ZSBLApgmYPLr_8OaI3318L4gffvvfnr_bJRfYkxVCcdpuNPI8r0eu61lO3YqCxncMu8Kwaww7L1WdENeUi1LKQIYCBGg1WRKQgCGaZH1erIHU43zD55FEatDwCELUpfVIF1YiOUWGztOiynlS0Kel3pqc63wu9uaUWGhILOakpBCE4WvUSOcCMZijsWqsjJ6Wz30RSoUGf5UejDsZWpF3iBKvcP6U9t0oCY7jKEXn5c_YOHZC3u5GYehYqH43c0LkWSbyonCSRLGTIM9JD0_jsZzZfbrQh1spZzl6yroscDWoUlQRicZRZ-BvpgsUUJkcgyKVrWAitzi1WA2VLDY5ZHY5JKasDZsKdDsCKTY5YbbdqrTLmoDqZMxWsORUXyZCJMeScnpsoP5yyeC8fKINjdnXcu321iAKL8sHt1KhZz-Nk8j13jhXFeymUiIO_lawXfW20b3H-eTTz83gy9tXr19e7-1dVhtpkKoCymfBiBBOuoGyGBTrhJYEw58tyE0vdxRmzfOOnZn5IdsGZzXsrFb7sf-_tv8A0)

![landingpage](https://user-images.githubusercontent.com/31323201/30457738-c8524008-9965-11e7-81c4-64b48ec966e8.png)

**Comment by jordan-wright** [comment]
Unfortunately, there are some pages that are so heavily tied into Javascript that when you preview them in CKEditor (our HTML editor) they won't show up right because it prevents the execution of scripts for security reasons.

With that being the case, it's possible that saving the page might make it look ok when it comes time to run a campaign, but I can't make that guarantee.

I wish there were more we could do about this, but you may just have to clone the website locally, make any changes and then manually add in the HTML to your landing page.
