### ISSUE TITLE
Feature Request: Retargeting 

### ISSUE THREAD

**Issue by hevnsnt** [gophish/gophish#755]
I would like a feature to retarget specific users:

- Resend to people who opened
- Resend to people who clicked
- Resend to people who didn't take action

**Comment by jordan-wright** [comment]
In it's current form, this is probably best handled via the API since it would introduce quite a bit of complexity to the UI.

However, that said, the new campaign builder in #223 will allow you to send multiple emails in a campaign. That would take care of the middle one since people who clicked the links in the email could receive a second email.

I hope this helps! Sorry we won't be implementing this in the current form. If you start implementing this via the API and run into issues, don't hesitate to open new issues here and we'll be happy to troubleshoot.
