### ISSUE TITLE
Issue with my phishing page and Gophish listener on different servers

### ISSUE THREAD

**Issue by Clunkline** [gophish/gophish#757]
Hi all,

I need some help with setting up my Phishing campains.

**Context:** First I installed Gophish locally. I succeeded in setting it up correctly and it was possible to perform phishing attack campains succesfully. Then I wanted to set it up on the internet.

**Problem:** Now I have my phishing page hosted by company A on the internet where I can just host multiple webpages, but it is shared and I cannot install stuff. Then I configured Gophish on a seperate dedicated Ubuntu server at company B. Now when I setup my Campain I need to fill in the Gophish listener in the URL parameter. When I fill in the Gophish IP from company B, users will be redirected to this IP when clicking the link in the phish mail and no phish page is hosted there. When I fill in the phish page URL, the users will land on my phishing page, but it Gophish does not seem to record clicks etc. probably because the gophish listener is on another IP. 

**Question:** I've been thinking about it and I've read the manual a couple of times, but I seem not to be able to figure it out. It should be possible to have your page and listener on different servers/IPs right? Can someone please help me out and tell me how to set this up correctly?

Thanks!

**Comment by jordan-wright** [comment]
Hey there!

You're absolutely right that this should be possible. The trick is that Gophish is _heavily_ tied to the database. All email templates, campaign information, landing pages, etc. are hosted in the db.

So, if you want a distributed architecture the Gophish instances need to share a database. This is easiest if you're using MySQL. Just point each instance to the same mysql instance and they should share the same data.

Then, when you setup the campaign, just point the URL to the external gophish listener and when links in the email are clicked, users will be taken to the external listener and things should be recorded properly.

Hope this helps! I'll go ahead and close this out since it seems like the scenario is answered, but don't hesitate to let me know if you have any other questions.

**Comment by Clunkline** [comment]
Hi Jordan,

Thank you for your quick answer! It is much appreciated! One more follow-up question; Basically it comes down to this: How do I share this DB ?? What is the best way to do this? I mean, when GoPhish  is installed it creates a local DB? I need to create a database and need to point eacht instance to it? Each instance is the system running GoPhish and the system running the phishing page then right ? Is there any way you could provide me some more "step-by-step guide" ? I mean, I'm not sure how to make this thing work corrrectly.. How do I "point" the system with the landing pages to the DB?? Do I only need to create a DB and change the config file ?

Hope you can help me out a little bit here!

Jasper

**Comment by jim-droid** [comment]
my gophish is not listening on everything.
does not show if the link is clicked, email opened it just sends emails only no connection at all

**Comment by jim-droid** [comment]
How am i supposed to configure it
help pliz
