### ISSUE TITLE
Windows Installation and Google Chrome Phishing

### ISSUE THREAD

**Issue by raycmitchell** [gophish/gophish#780]
Hi people,

I had setup GoPhish successfully on a Microsoft Windows Azure platform several months ago without any issues.  Recently I have noticed all of my click through campaigns that go to a landing page are resulting in a Google security page warning users of the phishing exercise.  I have tried to authenticate the web server against the GoPhish landing page but I am unable to authenticate as the root landing page is not accessible in windows.  Please advise how I may resolve this issue.

Best regards

Ray

**Comment by jordan-wright** [comment]
> I have tried to authenticate the web server against the GoPhish landing page but I am unable to authenticate as the root landing page is not accessible in windows

I'm not sure what you mean by this.

Google is actively searching for phishing sites that attempt to trick users into giving up credentials. This is a great thing!

There is nothing we can do on Gophish's end to prevent this from happening if Google correctly identifies a phishing page (even if it's just for an internal org) and blocks the page using SafeBrowsing. You'll have to recreate the campaign on a different host knowing that Google could come along again and blacklist it.

If this is a test for an internal organization, you could consider hosting Gophish internally knowing that mobile employees outside the LAN may not reach the Gophish server. But, that would prevent Google from being able to blacklist the site.

**Comment by teddielong** [comment]
Just thinking out loud here, but as Google is only picking up the landing page as phishing, would a workaround be to;

1) permanent set up of GoPhish on fixed domain
2) ability for landing pages to be hosted on alternative domains (so that these could be spun up quickly for new campaigns without the need to set up a brand new instance of GoPhish each time?)

Out of curiosity how do Wombat, PhishMe etc get around the issue of their landing pages? What's the difference between how they operate and GoPhish?
