### ISSUE TITLE
Setting email headers

### ISSUE THREAD

**Issue by teddielong** [gophish/gophish#783]
I'm a bit confused by the email headers. Should I be aiming to customise these per campaign or would I be better creating the same header that I use across all campaigns? I'm mainly thinking for a whitelisting perspective?

**Comment by CoreyMcCown13** [comment]
That would entirely depend on your use case. You don't HAVE to customize the headers at all (in fact, I do not). Whitelisting is a good example of why you may want a custom header. All of the headers that are needed to send the email are applied automatically, so if you do not need anything special, there is no need to customize them.

**Comment by teddielong** [comment]
Thanks for your message in response. Presumably having a custom header could assist the whitelist and therefore deliverability? I’m just thinking if it’s easy to edit, then is there any reason I wouldn’t use a custom header - if it helps ensure delivery etc?

**Comment by jordan-wright** [comment]
As @CoreyMcCown13 indicated, the custom headers are to help with deliverability since you can often whitelist headers in your spam appliance.

So, you could theoretically make something like `X-Gophish-Campaign: <some value>` and then whitelist emails with an `X-Gophish-Campaign`. If you're concerned about attackers also using this header (exceedingly low probability) you can make the header whatever you.
