### ISSUE TITLE
Group campaigns into deployment groups

### ISSUE THREAD

**Issue by hpscrappy** [gophish/gophish#784]
Would it be possible to add a deployment group function, Essentially group multiple campaigns into deployment groups. For example if i run 10 campaigns in September and want those campaigns under a group called September. This would allow me to select that group and view the total metrics for that month/quarter. Let me know what you think.

**Comment by jordan-wright** [comment]
This is something that would be best done with the API. In fact, doing this kind of stuff is 100% why the API was built since this would be really difficult to achieve while preserving a simple UX. 😄 

You might check out community driven tools like [GoReport](https://github.com/chrismaddalena/GoReport) which can help aggregate campaign statistics.

In the future, I might consider adding basic tagging for campaigns, but I'm afraid I can't guarantee anything at this point.
