### ISSUE TITLE
Import Site of Instagram

### ISSUE THREAD

**Issue by Zafrilla227** [gophish/gophish#795]
When i use the  option "Import Site" in a Landing Page, and type: https://www.instagram.com/accounts/login/ 

It doesn't do anything, I heard it's because of the form action, but it should be changed at the time of cloning, isn't it? Help pls

**Comment by S0larflare** [comment]
What does the console say? Any errors?

Sent from my iPhone

On 9 Oct 2017, at 16:36, Zafrilla227 <notifications@github.com<mailto:notifications@github.com>> wrote:


When i use the option "Import Site" in a Landing Page, and type: https://www.instagram.com/accounts/login/

It doesn't do anything, I heard it's because of the form action, but it should be changed at the time of cloning, isn't it? Help pls

**Comment by Zafrilla227** [comment]
No, try to do it, and you'll see what i mean. You can't clone https://www.instagram.com/accounts/login/

**Comment by S0larflare** [comment]
It will grab something, but the page isn't usable (tried it, ended up with a blank page that kep showing as click after click, not the best :D). I'm afraid it is due to Instagram itself, they use a lot of scripts which makes it hard to easily clone (that's likely the point). You might be best doing it manually, copy the source yourself and remove scripts which seem to stop things loading if it isn't from instagram itself. I have managed to do that with other pages in the past with similar problems.

**Comment by jordan-wright** [comment]
@S0larflare is correct. We can't guarantee that we're able to import every site 100% perfectly. A good rule of thumb is that if the auto import doesn't work, you need to manually clone the site and dump the HTML into the landing page.

**Comment by Tunchii69** [comment]
can i get a landing page for instagram
