### ISSUE TITLE
Scheduler Uses Unknown Timezone

### ISSUE THREAD

**Issue by haloux** [gophish/gophish#798]
Good (PST) morning folks,
When using GoPhish 0.3 (looking at the source, it doesn't appear that anything was done to address this yet), the timezone that GoPhish identifies as 'Local' isn't sync'd up with the timezone that the Campaign Scheduler uses.

ex: Scheduling a campaign for 09:30 AM, PST in the _Create A New Campaign - Scheduler UI_, while the current time is 08:45 AM, PST, causes the campaign to be launched immediately. 

This bug is reproducible across two installations and multiple attempts. This definitely seems like a useful feature, but for some reason it doesn't appear to be working. Suggestions? Where could I look in the source for hints on fixing this?

**Comment by jordan-wright** [comment]
Hi @haloux - thanks for reaching out.

Have you tried using version 0.4? For a bit of background, the scheduler used to have issues where we were storing dates in the server's local time zone.

This was changed in 0.4 so that all dates are stored and processed in UTC. You can see this when we save campaigns here: https://github.com/gophish/gophish/blob/master/models/campaign.go#L364

These campaigns are picked up by the worker [here](https://github.com/gophish/gophish/blob/master/models/campaign.go#L364) which gets queued campaigns from [here](https://github.com/gophish/gophish/blob/master/models/campaign.go#L339).

So I recommend giving 0.4 a shot and letting us know if you still encounter issues. Hope this helps!

**Comment by jordan-wright** [comment]
Hi @haloux ,

Just checking in, did moving to 0.4 help address the issue?

**Comment by haloux** [comment]
Hello. Apologies for the radio silence. Unfortunately I’m not able to update the program just yet. I’m in the middle of a long campaign right now and I fear that updating would complicate my response statistics. After this upcoming campaign I will update and report back with results. Thank you for your suggestion.

**Comment by haloux** [comment]
If it is well with you, you can close this issue. Should I encounter the problem again, I'll respond with more detailed information (after upgrading to 0.4 of course). Thank you for your quick response @jordan-wright !

**Comment by jordan-wright** [comment]
Sounds good! If you give 0.4 a shot and continue to run into issues, please don't hesitate to let us know.
