### ISSUE TITLE
Tracker and URL tag issue?

### ISSUE THREAD

**Issue by wdy43di** [gophish/gophish#800]
Good Morning,

I will start with the tl;dr version.  I have spun up a gophish for the first time and my tags for URL and tracking does not work.

Alright now for details.  I am currently running 0.4 installed on a Ubuntu command line server.  When I attempt to send a phishing campaign, I am inserting tags for Tracking and URL. They are visible in the email.

I have tried sending from a gmail account, as well as my internal account.  Same symptoms.  I have tried sending to my gmail account, and multiple internal accounts with my admin address and password.  Same symptoms.

First attachment is the email its self

email body = 

John Schreckendgust
test

John Schreckendgust

<img alt='' style='display:

none' src='/track?rid=oxQnk3E'/>  (broken up so its visible on this forum)

?rid=oxQnk3E

Email Template =

{{.FirstName}}{{.LastName}}
test

{{.From}}

{{.Tracker}}

{{.URL}}

Here is the config.json

{
        "admin_server" : {
                "listen_url" : "0.0.0.0:3333",
                "use_tls" : false,
                "cert_path" : "gophish_admin.crt",
                "key_path" : "gophish_admin.key"
        },
        "phish_server" : {
                "listen_url" : "0.0.0.0:80",
                "use_tls" : false,
                "cert_path" : "example.crt",
                "key_path": "example.key"
        },
        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"
}

**Comment by S0larflare** [comment]
Could you give the very not tl;dr version, I’m not sure what the problem is?

Sent from my iPhone

On 18 Oct 2017, at 20:30, wdy43di <notifications@github.com<mailto:notifications@github.com>> wrote:


Good Morning,

I will start with the tl;dr version. I have spun up a gophish for the first time and my tags for URL and tracking does not work.

Alright now for details. I am currently running 0.4 installed on a Ubuntu command line server. When I attempt to send a phishing campaign, I am inserting tags for Tracking and URL. They are visible in the email.

First attachment is the email its self

email body =

John Schreckendgust
test

John Schreckendgust

[X]</track?rid=oxQnk3E>

?rid=oxQnk3E

Email Template =

{{.FirstName}}{{.LastName}}
test

{{.From}}

{{.Tracker}}

{{.URL}}

Here is the config.json

{
"admin_server" : {
"listen_url" : "0.0.0.0:3333",
"use_tls" : false,
"cert_path" : "gophish_admin.crt",
"key_path" : "gophish_admin.key"
},
"phish_server" : {
"listen_url" : "0.0.0.0:80",
"use_tls" : false,
"cert_path" : "example.crt",
"key_path": "example.key"
},
"db_name" : "sqlite3",
"db_path" : "gophish.db",
"migrations_prefix" : "db/db_"
}

**Comment by wdy43di** [comment]
Just the first line of tl;dr was the tl;dr

In my email template, I have {{.Tracker}} and {{.URL}}.  

in the actual email, it comes up with the following.

<img alt='' style='display:

none' src='/track?rid=oxQnk3E'/> (broken up so its visible on this forum)

?rid=oxQnk3E

![gophish](https://user-images.githubusercontent.com/10539362/31742236-2a52b79c-b414-11e7-8cde-0b81baa73427.JPG)

**Comment by wdy43di** [comment]
I just tried setting it up on a whole new system.  Used my laptop. Windows 64 bit.  Same result in the email.  
So we know it's not os based issue.  I am going to try again at home to eliminate the corporate network/filters.

**Comment by S0larflare** [comment]
Oh in an email there isn’t anything before ?rid ? I thought you’d removed the domain from what you’d posted

Are you setting it in the campaign? Seems odd!

Sent from my iPhone

On 18 Oct 2017, at 22:30, wdy43di <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tried setting it up on a whole new system. Used my laptop. Windows 64 bit. Same result in the email.
So we know it's not os based issue. I am going to try again at home to eliminate the corporate network/filters.

**Comment by jordan-wright** [comment]
Make sure you’re putting the full url to your Gophish server in the URL field when setting up the campaign.

**Comment by wdy43di** [comment]
Awesome, we are making progress.  I thought that is the url where you got the landing page from.  Hopefully my last question is are we suppose to see the img alt?

BTW thank you all for developing this app.  We tried a third party phishing application and we had a 41 percent click.  So my IT director has sent me to educate my users.  Attached is the updated information.
![gophish](https://user-images.githubusercontent.com/10539362/31744730-38eca534-b41d-11e7-865d-b168fc680ccc.JPG)

**Comment by jordan-wright** [comment]
Check the source of the email to see the actual HTML. Everything looks correct, but you shouldn't see the image tag (it should be a hidden tracking pixel).

If the HTML looks correct, then there's likely something client side preventing the image from rendering and it's out of our hands.

**Comment by jordan-wright** [comment]
Hi @wdy43di - just checking in, did the previous comment help you resolve the issue?

**Comment by wdy43di** [comment]
Yes sir it did... thank you.
