### ISSUE TITLE
Settings gone after VM reboot

### ISSUE THREAD

**Issue by cam-gab** [gophish/gophish#805]
Hi,

I have gophish perfectly running in a VM however after a VM reboot and restarting the service, my saved settings were gone in the admin portal. I have checked the gophish.db SQLite file and the settings are saved there but I can't see them in the portal (using the same browser and credentials), am I missing something? Thank you.

**Comment by jordan-wright** [comment]
What settings specifically were reset?

**Comment by cam-gab** [comment]
Thank you for the quick response. It's the landing pages and email templates.

**Comment by jordan-wright** [comment]
Can you be more specific? I’m not sure what the issue is.

The initial issue says that your settings weren’t saved. Are you saying that the actual problem is that your landing pages and email templates aren’t saved?

And you verified that you see the landing pages and templates in the database?

What messages do you see in the terminal when you try to start Gophish or load the templates or landing page tabs?

Do you see any messages in the devtools in the browser that might indicate some JavaScript weirdness?

Any extra info around what you expect to see and what you’re seeing will help us troubleshoot this.

**Comment by cam-gab** [comment]
Sorry. Yes, to be precise the settings I am referring to are the landing pages, email templates and users.
Yes, they are all still in the SQLite database.

Kindly see attached screenshots for additional info. Thanks!
[missing saved - gophish.docx](https://github.com/gophish/gophish/files/1409474/missing.saved.-.gophish.docx)

**Comment by jordan-wright** [comment]
Can you please upload the images to a service such as [imgur.com](https://imgur.com)? I make it a policy to avoid downloading files from Github issues.

Thanks!

**Comment by cam-gab** [comment]
Got it. Thanks.
https://imgur.com/a/4CY9c

**Comment by jordan-wright** [comment]
It's odd that the values are under the user_id 2. Are you using the admin user or did you create another user? If you created another user, are you sure you're logging into the correct account?

**Comment by cam-gab** [comment]
Oh shoot. Sorry for that noob mistake. So I guess the admin wouldn't be able to see the campaigns of other users? Thank you for your help and sorry for the trouble.

**Comment by jordan-wright** [comment]
That's correct - each user is unique. There was a plan a while back to implement full RBAC, but this would be pretty difficult with the current setup. I'd rather focus efforts on making the campaigns themselves as powerful and intuitive as possible.

Glad we were able to get it figured out! Have a good one.
