### ISSUE TITLE
Database column addition - migration needed?

### ISSUE THREAD

**Issue by ekleintop** [gophish/gophish#813]
I have added a new column to the results table.  It is updating fine with additional code changes.  However when the results are extracted the column data is missing. I can see the data in the database.  I’m pretty sure I have traced the code back to the db.Table call and can see the data is missing in the result. I know this is unsupported but is there something additional I have to do to get gorm I see the new column?  

Thanks,

Eric

**Comment by jordan-wright** [comment]
Hi Eric,

Yes, you'll need to setup a database migration to support your new column. You'll need `gorm` to be able to do this.

Here's some details on how the migrations work: https://getgophish.com/blog/post/database-migrations-in-go/

Though, the exact command line for creating a new migration has changed when we added MySQL support. You can find an example of the new syntax here: https://github.com/gophish/gophish/pull/336

Hope this helps!

**Comment by ekleintop** [comment]
Thanks for the rapid response Jordan!  I suspected there was something more to do!  I’ll review the blog post ad figure it out.  

Thanks again!

Eric

**Comment by jordan-wright** [comment]
Since I had to add a new migration myself today, here's the command I used. You'll need to also do the mysql one if you're using mysql:

`goose -env production -path "db/db_sqlite3" create 0.4.1_maillogs sql`

The `0.4.1_maillogs` is the migration filename - it can be anything, but I typically do [version]_[description]. This creates the SQL file and you add your SQL commands to that file.

**Comment by ekleintop** [comment]
Excellent!  Many thanks Jordan!! 

Eric
