### ISSUE TITLE
Gophish - DigitalOcean Ubuntu error  

### ISSUE THREAD

**Issue by Jenderz** [gophish/gophish#828]
**I really need your help, I want to install Gophish in Digitalocean Ubuntu Server 16.04 x64, following these steps does not work. I do not know what is happening**

```
# wget https://github.com/gophish/gophish/releases/download/v0.4.0/gophish-v0.4-linux-64bit.zip
# apt install unzip
# unzip gophish-v0.4-linux-64bit.zip -d /opt
# ln -s /opt/gophish-v0.4-linux-64bit/ /opt/gophish
# chmod +x /opt/gophish/gophish
# sed -i 's!127.0.0.1!0.0.0.0!g' /opt/gophish/config.json
# cd / opt / gophish 
# ./gophish
```
Placing server ip:3333 does not work, and error 404

Will it be necessary to install other initial packages? When starting the vps

**Comment by jordan-wright** [comment]
What do you see after the ./gophish command?

**Comment by Jenderz** [comment]
@jordan-wright :/opt/gophish# ./gophish

goose: migrating db environment 'production', current version: 0, target: 20170827141312
 2017/11/05 16:43:07 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
OK    20170219122503_0.2.1_email_headers.sql
OK    20170827141312_0.4_utc_dates.sql
 2017/11/05 16:43:07 gophish.go:104: Starting phishing server at http://0.0.0.0:80
 2017/11/05 16:43:07 util.go:124: Creating new self-signed certificates for administration interface...
 2017/11/05 16:43:07 util.go:177: TLS Certificate Generation complete
 2017/11/05 16:43:07 gophish.go:87: Starting admin server at https://0.0.0.0:3333
2017/11/05 16:44:04 http: TLS handshake error from 186.94.28.242:20028: tls: first record does not look like a TLS handshake
2017/11/05 16:44:06 http: TLS handshake error from 186.94.28.242:20030: tls: first record does not look like a TLS handshake
2017/11/05 16:44:06 http: TLS handshake error from 186.94.28.242:20031: tls: first record does not look like a TLS handshake
 2017/11/05 16:44:07 campaign.go:348: Found 0 Campaigns to run
2017/11/05 16:44:36 http: TLS handshake error from 186.94.28.242:20003: tls: first record does not look like a TLS handshake

![image](https://user-images.githubusercontent.com/33388647/32416916-8f03b21a-c227-11e7-962b-ddfe6601955a.png)
![image](https://user-images.githubusercontent.com/33388647/32416919-9c27d494-c227-11e7-9a27-45af19fc3996.png)

**Comment by jordan-wright** [comment]
Try https://127.0.0.1:3333 :)

**Comment by S0larflare** [comment]
You’re trying to connect using http rather than https, go to https://165.227.181.3:3333 instead

Sent from my iPhone

On 5 Nov 2017, at 16:50, Jenderz <notifications@github.com<mailto:notifications@github.com>> wrote:


@jordan-wright<https://github.com/jordan-wright> :/opt/gophish# ./gophish

goose: migrating db environment 'production', current version: 0, target: 20170827141312
2017/11/05 16:43:07 worker.go:37: Background Worker Started Successfully - Waiting for Campaigns
OK 20160118194630_init.sql
OK 20160131153104_0.1.2_add_event_details.sql
OK 20160211211220_0.1.2_add_ignore_cert_errors.sql
OK 20160217211342_0.1.2_create_from_col_results.sql
OK 20160225173824_0.1.2_capture_credentials.sql
OK 20160227180335_0.1.2_store-smtp-settings.sql
OK 20160317214457_0.2_redirect_url.sql
OK 20160605210903_0.2_campaign_scheduling.sql
OK 20170104220731_0.2_result_statuses.sql
OK 20170219122503_0.2.1_email_headers.sql
OK 20170827141312_0.4_utc_dates.sql
2017/11/05 16:43:07 gophish.go:104: Starting phishing server at http://0.0.0.0:80
2017/11/05 16:43:07 util.go:124: Creating new self-signed certificates for administration interface...
2017/11/05 16:43:07 util.go:177: TLS Certificate Generation complete
2017/11/05 16:43:07 gophish.go:87: Starting admin server at https://0.0.0.0:3333
2017/11/05 16:44:04 http: TLS handshake error from 186.94.28.242:20028: tls: first record does not look like a TLS handshake
2017/11/05 16:44:06 http: TLS handshake error from 186.94.28.242:20030: tls: first record does not look like a TLS handshake
2017/11/05 16:44:06 http: TLS handshake error from 186.94.28.242:20031: tls: first record does not look like a TLS handshake
2017/11/05 16:44:07 campaign.go:348: Found 0 Campaigns to run
2017/11/05 16:44:36 http: TLS handshake error from 186.94.28.242:20003: tls: first record does not look like a TLS handshake

[image]<https://user-images.githubusercontent.com/33388647/32416916-8f03b21a-c227-11e7-962b-ddfe6601955a.png>
[image]<https://user-images.githubusercontent.com/33388647/32416919-9c27d494-c227-11e7-9a27-45af19fc3996.png>

**Comment by Jenderz** [comment]
### Thanks very mucho @jordan-wright @S0larflare Great, excuse my ignorance. I would like to keep it running 24/7, how could I do it? I have read about creating a virtual terminal using screen. Would it be nice to keep it online that way? Does not consume many resources on the server? . I am new at this

**Comment by jordan-wright** [comment]
Screen is a possible way to keep the service running. Alternatively, you could consider running Gophish as a service. You can refer to the "Running Gophish as a Service" section of our documentation for information on how to do this: https://gophish.gitbooks.io/user-guide/content/installation.html
