### ISSUE TITLE
Campaign Results Not Loading

### ISSUE THREAD

**Issue by RCPMAD** [gophish/gophish#841]
What version of Gophish are you using?
0.4

Brief description of the issue: 
I am unable to export results from a campaign sent to over 8k users, the campaign results page freezes.

What are you expecting to see happen?
Load campaign results page and export results.

What are you seeing happen?
Page loads but freezes, unable to click on any links or export results.

I am at a loss, how do I get my results now?

**Comment by RCPMAD** [comment]
I am having no luck, I am unable to access my results. This is a shame really as we just managed to approve the use of the platform for a campaign against our users and now we cannot access the results.

**Comment by S0larflare** [comment]
Hi,

Can you just confirm that this is an issue with the page itself not loading? Or is this that when you get to the page and click to export the results then it hangs? Depending on the stage at which this happens, I can suggest different ways to get the results.

**Comment by RCPMAD** [comment]
Hi @S0larflare,

Whenever I click on View Results the web page freezes. I cannot even clock on Export CSV because the page is frozen. Same behavior in Chrome, Firefox and IE.

**Comment by S0larflare** [comment]
OK, so you have a couple of options.

1. Use the api: That's usually best when it comes to large result sets due to issues like this.

2. If you're not comfortable with the api you're probably best increasing the refresh period for the results page. I take it you are using the release version of gophish rather than compiling from source? There has been a recent change to disable the map by default as that is pretty resource hungry and doesn't add much to most people. If you still have that 'switched on' then that is likely what is doing most of the slow down. I would suggest increasing the refresh period and seeing if that fixes it. There are two places this should be changed:
- Edit <gophish_directory> /static/js/src/app/campaign_results.js . Change line 768.
 "setRefresh = setTimeout(refresh, 60000)" The value there is for 60 seconds, I'd change this to say 5 minutes or something.
- Edit <gophish_directory> /static/js/dist/app/campaign_results.min.js go to the end and change the value to match
"setRefresh=setTimeout(refresh,6e4)" this is in SI notation, so 5 minutes would be 3e5 for example.

After that, try the campaign again and let it load for a couple of minutes. I have got results from a campaign with about 5,500 users through the browser without a big issue doing it this way.

**Comment by RCPMAD** [comment]
Hello @S0larflare,

Just tried this and it has worked!

Thank You

**Comment by S0larflare** [comment]
I take it you haven't yet completed the campaign? Once you do that it won't try to auto refresh any more. If you're finished with the campaign I'd recommend you complete it

**Comment by RCPMAD** [comment]
I know what you are saying, it's just that once it loads the auto refresh kicks in again and I do not have time to complete the campaign on time. Tried to match that a few times.

**Comment by stracire** [comment]
You could try to edit the status of the campaign with a SQL query. Last time I tried it didn't finish the campaign, but did stop the refreshing.

You could also try to get the data using the API.

**Comment by jordan-wright** [comment]
It sounds like you don't want the auto refresh on at all. I'm planning on making that an optional setting in the UI settings pretty soon, but in the meantime @S0larflare's last suggestions about changing the `setRefresh` timeouts would be the best bet.

Otherwise, you can use our awesome Python API client (https://github.com/gophish/api-client-python) to get the results you're looking for, which should be really snappy. 😄 

Sorry for the hassle! There's still some optimization I have left to do on the results page. It's a WIP for large campaigns, but I promise it'll continue to get better over time.

**Comment by jordan-wright** [comment]
Closing this since @S0larflare provided some of the best recommendations available at this time. Optimizing for a large user base is an ongoing effort which would best be captured in a full project and not tied to one issue.

I hope the comments in this issue help @RCPMAD - thanks for giving Gophish a shot and rest assured we'll keep working to make performance as good as we can!
