### ISSUE TITLE
Database limitations for High user volume.

### ISSUE THREAD

**Issue by turnerdb** [gophish/gophish#845]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4.0
Brief description of the issue: 
Not and issue as much as a general question.  We use sqllite in our GoPhish instance.  We are looking to do a campaign with 10K plus users and we would like to know if there is a limitation to using the sqlite instead of using mysql?
What are you expecting to see happen? :
n/a
What are you seeing happen?
n/a
If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by turnerdb** [comment]
Also is there a limit to the number of users I can phish in a campaign all at once.  I work for the Department of the Interior and obviously the federal gov is very large.  Just looking to know what type of growth we have using GoPhish.

**Comment by jordan-wright** [comment]
Hi @turnerdb! Thanks for reaching out.

>We use sqllite in our GoPhish instance. We are looking to do a campaign with 10K plus users and we would like to know if there is a limitation to using the sqlite instead of using mysql?

SQLite almost certainly wouldn't be the bottleneck. Right now, I can see two possible issues:

* **Invalid email addresses cause issues during mailing** - Right now, the way we send email is pretty naive. We run through each email address and try to send the email. If something goes wrong, we just error everything out. Fortunately, this is the number one in-progress item that should be finished mayyyybe next week. It was a big undertaking but it's almost fixed so the mail sending should be much more reliable.

* **Results UI** - If you're planning on using the results page in the UI, just know that it can still be sluggish with 10k users. There are some things you can do to alleviate this a bit (@S0larflare sums these up really nicely here: https://github.com/gophish/gophish/issues/841#issuecomment-344585927). You can either do the things mentioned in that comment or you can use the API, which should be really snappy.

Hope this helps! Long story short, it's almost certainly going to be Gophish specific limitations, not SQLite vs. MySQL limitations. And that's good, because the Gophish limitations can and are being addresses slowly but surely 😄

**Comment by jordan-wright** [comment]
Going ahead and closing this out since it seems as though the original question has been answered above.
