### ISSUE TITLE
Difficulty Pointing gophish to website

### ISSUE THREAD

**Issue by jammeystuggy** [gophish/gophish#849]
I want to set up Gophish Externally i.e I want to point it to website. I have gotten a domain of my choice, I tried to set an A record to the external ip on my kali linux on vmware but its not working. Is it because its a virtual host? Please how do i successfully set up an A record to my gophish server in my virtual machine. Thanks in advance

**Comment by jordan-wright** [comment]
I'm afraid there's not too much we can do to help here, since this is really outside the realm of Gophish itself.

I recommend making sure that the virtual host has the correct IP address assigned to the interface. Otherwise, just make sure that the right networking is setup to forward traffic from that external IP to the internal interface.

In addition to this, make sure the Gophish phishing server address in `config.json` is set to `0.0.0.0:80` so that the landing pages are available on all interfaces.

I'm sorry there isn't more we can do to help, but I'm afraid I don't have much vmware experience and this question is really outside the support we can provide.
