### ISSUE TITLE
No go phish binary - "go build" installation error 

### ISSUE THREAD

**Issue by sragona** [gophish/gophish#852]
GoPhish version 0.3-dev

I am attempting to install GoPhish from the source on Ubuntu 16.0.4 however I have run into an error when running "go build".  I get the following:

```
root@GoPhish-Ubuntu:~/work/src/github.com/gophish/gophish# go build
# github.com/go-sql-driver/mysql
../../go-sql-driver/mysql/utils.go:81: undefined: cloneTLSConfig
```

I had trouble installing "go1.9.2.linux-amd64.tar.gz" as I received the following error:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

 I was able to successfully install "go1.8.linux-amd64.tar.gz" and set my Go path.

I then installed GCC per the following instructions: [https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91](url)

Thanks in advance.

**Comment by jordan-wright** [comment]
Make sure you're running `go get ./...` to get all the dependencies. Other than that, I'm afraid I can't really help with installing Go itself, since that's a bit out of scope of our support.

Let me know if installing those dependencies helps resolve the issue. Gophish should work just fine with go v1.8.

**Comment by jordan-wright** [comment]
Closing this since there hasn't been any updates in a while. @sragona if you're still running into issues, let us know and we can continue troubleshooting.
