### ISSUE TITLE
Duplicate recipients should be skipped in sending emails.

### ISSUE THREAD

**Issue by jas-deep** [gophish/gophish#855]
Duplicate recipients should be skipped in sending emails.
Suppose I have two groups (A and B) and a user is present in both the groups (A and B). Email will be sent twice two the user.

PS: I am working on fixing it.
Please let me know if you have any comments.

**Comment by S0larflare** [comment]
I’d prefer if this was kept or made optional. I’ve used this for testing in the past with a few things :)

Sent from my iPhone

On 23 Nov 2017, at 21:58, Jasdeep Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


Duplicate recipients should be skipped in sending emails.
Suppose I have two groups (A and B) and a user is present in both the groups (A and B). Email will be sent twice two the user.

PS: I am working on fixing it.
Please let me know if you have any comments.

**Comment by jordan-wright** [comment]
Thanks for reaching out! I'll keep this as-is for now. There's a balance with the design of Gophish to limit how opinionated it is while still keeping the UI simple.

I can see it being useful where people would expect recipients, if specified in more than one group, would receive more than one email. This means that, as @S0larflare mentions, I would have to make this optional which would mean a setting when building campaigns. I'm really picky about what new checkboxes or options we put in building a campaign, since space is already limited. This seems like a really specific change in behavior to warrant a full option when building a campaign, so it just doesn't cross that threshold for me at this time.

After finishing up the mail refactor I'm working on now, I plan to fix up a couple of minor outstanding issues, then start work on the new campaign builder (see #223). It's possible that when I break actions out into their own pane that I could consider action-specific settings like this. But for now, I'm going to leave the behavior as-is.

Thanks again for getting in touch!

**Comment by jas-deep** [comment]
I can't think of a scenario where same campaign sending the **same email** multiple times to a user makes much sense.

**Comment by jordan-wright** [comment]
Maybe I closed this one too soon. Let's get some more feedback, and then I'll decide if this should be changed or not. I can see your point, but I want to make sure we aren't breaking existing workflows.

@S0larflare can you let us know a bit more about the workflow that would be affected by this?

**Comment by S0larflare** [comment]
Mine specifically was when I was making my homebrewed sending delay + randomised order. I made multiple users which all had my email and used those in a single campaign to confirm behaviour

In truth outside of this I cant think of a reason to need this in ‘real scenario’. So it’s probably a fair point that it could be removed. Alternatively make it a dialog box to make people aware that there are multiples in the campaign and to confirm you want to go ahead? Depends on whether you think it would clutter things

Sent from my iPhone

On 24 Nov 2017, at 19:25, Jordan Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe I closed this one too soon. Let's get some more feedback, and then I'll decide if this should be changed or not. I can see your point, but I want to make sure we aren't breaking existing workflows.

@S0larflare<https://github.com/s0larflare> can you let us know a bit more about the workflow that would be affected by this?

**Comment by jordan-wright** [comment]
I guess the more I think about it, the more this makes sense to change. Especially if the use case wasn’t a standard scenario but testing a different feature (thanks for the quick response @S0larflare!)

At this point I’m leaning towards just removing duplicates and calling it a day. I can’t see a good place to put a UI option for this, and even then I’d have to make an API option for it, too, which would really clutter things up. :/

It’ll be a bit before I can get around to fixing this, but I’ll keep y’all updated.

**Comment by jordan-wright** [comment]
This has been fixed. Let me know if you run into any issues!
