### ISSUE TITLE
Sending automatic emails in parallel 

### ISSUE THREAD

**Issue by imal987** [gophish/gophish#863]
What version of Gophish are you using?: 0.4

Brief description of the issue: 
 I'd like to ask if there is a way to send automatic emails to the targets after they clicked the link to the landing page, it means when the targets receive the Template email and they click the link it will leads to the landing page and also (in parallel) an automatic email will be sent to the targets explaning to them phishing awareness.
Is that second feature of sending automatic emails possible?

Thanks!!

**Comment by jordan-wright** [comment]
Hey @imal987, thanks for reaching out!

Right now, this isn't possible. But, this falls under what will be possible with the new campaign creator in #223. We don't have a timeline for that yet, but since this falls under that project, I'm going to close this out as a duplicate.

Thanks again for getting in touch!
