### ISSUE TITLE
Deleted Request !!!

### ISSUE THREAD

**Issue by imal987** [gophish/gophish#865]
I don't see why my request have been deleted whithout any answer, I'm working on gophish and I expected that this is a place to discuss about it. 
It's not professional at all to do that kind of action, I'm really disapointed of the way that you reacted!!! 
The minimum that you can do is to answer me even if it's a "NO I can't help" answer!!

**Comment by jordan-wright** [comment]
They've just been closed since they were answered. I answered the issue and you can find the response here https://github.com/gophish/gophish/issues/863. You should have received the response via email.

Also, the second issue you filed was an exact copy of the first issue you filed so I closed it as such. Please only file one issue per request.

**Comment by imal987** [comment]
really sorry, I didn't open my email !!!

2017-11-30 16:18 GMT+01:00 Jordan Wright <notifications@github.com>:
