### ISSUE TITLE
Assistance required for setting up GoPhish with existing web server.

### ISSUE THREAD

**Issue by cHa0sAngeL** [gophish/gophish#866]
Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
v0.4

Brief description of the issue: 
Require assistance to have new setup of GoPhish to sit in an existing server hosting web app with IIS. Existing web app is public facing.

What are you expecting to see happen? :
1. GoPhish to reside in an existing server with web application (sub.domain.com) listening on 443
2. URL of landing page to be of sub.domain.com/mail

What are you seeing happen?
For 1): Need advice on how and where to place GoPhish folders etc.
For 2): Need advice on how to have GoPhish in IIS proper.

Appreciate all help rendered. Apologies for the seemingly low level questions. Quite a challenge for a non web/developer/system guy.

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Gophish launches with its own webserver. It doesn’t requires IIS to run. Simply launch Gophish without IIS and it will work.

If you are required to try and use it with IIS, then you will still need to launch Gophish on a nonstandard port and proxy requests to it. I’m afraid this particular setup is outside the scope of the support we can provide, since I don’t have any IIS experience.

**Comment by cHa0sAngeL** [comment]
Hi Jordan,

Thanks for helping. Fully understand that the IIS portion is out of the scope.

How about the requirement for getting sub.domain.com/mail for the landing page? I remember seeing this in the documentation. Does it mean that GoPhish files need to sit behind a /mail somewhere in the server?

-cA

**Comment by jordan-wright** [comment]
If I recall correctly, Gophish supports putting any path you want in the “URL” field when building a campaign. You can launch a test campaign to verify.

Just make sure the domain and port in the url points to Gophish and you should be good to go.

**Comment by S0larflare** [comment]
I think the only thing to avoid with the URL is **/track.**

So www.example.com is fine
subdomain.example.com is fine
subdomain.example.com.au/folderstructure is fine
but www.example.com/track isn't ok

The reason for this is that /track is used for the tracking pixel, so rather than an 'email clicked' and the page being rendered, GoPhish will see this as the tracking pixel being requested and assume that the email has been opened.

**Comment by jordan-wright** [comment]
Going ahead and closing this since the original question was answered. Hope this help @cHa0sAngeL!
