### ISSUE TITLE
Time line not loading too much data

### ISSUE THREAD

**Issue by wanoo** [gophish/gophish#881]
Hello first of all, thank you for this tool, i launch my first campaign this week end for my company and i got lot of fish!

What version of Gophish are you using?:  Linux V4.0 with mysql DB

Brief description of the issue: On a campaign of 1962 email the timeline didn't show up.

What are you expecting to see happen? : See the timeline ;)

What are you seeing happen? The Js console return this fowllowing error --> [Error #12 Hightchart](https://www.highcharts.com/errors/12). I understand for performance issue the setting are really low, but if you can order the data table by event time it will be nice workaround

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a big campaign of 1962 email
 * Step 2 - Generate lots of event (Around 6000 in th DB)

**Comment by jordan-wright** [comment]
The fix for this was committed on September 26 (see https://github.com/gophish/gophish/issues/765) in commit https://github.com/gophish/gophish/commit/e785af5c0aff104318628b01b9fcf4a15bdc7d44#diff-851cc3a2890b735d948e7137cfb8e07eR391.

I haven't bundled that fix into an official release since there are still things I'm finishing up first. The best recommendation is to either fix this file yourself using the patch from that commit, or build Gophish from source - either of those should fix the issue.

Hope this helps! Sorry for the inconvenience.
