### ISSUE TITLE
Check email adresses

### ISSUE THREAD

**Issue by jerempan** [gophish/gophish#886]
Hi , 

I would like to know if gopish can test users's email addresses before launching the campaign.... Indeed, this will avoid making mistakes when launching the campaign.

Thanks you :)

**Comment by jordan-wright** [comment]
Hey @jerempan - thanks for reaching out! Right now, Gophish doesn't support checking recipients via the `VRFY` command and I don't plan on adding that functionality in the immediate future since not many SMTP servers have it enabled as best-practice now, and that number is (should) only be decreasing, making the feature less useful over time.

The latest mailer refactoring that was just recently completed handles errors when sending emails much, much better. So, if you have an invalid email address it won't crater the entire campaign sending. 😄 

Hope this helps!
