### ISSUE TITLE
Data Capture, Dashboard meter

### ISSUE THREAD

**Issue by shirshendud** [gophish/gophish#903]
Sir
2 Issues

1. When we are viewing the results after sending the mails then in the circles only Email sent is showing results but Email clicked, E mail opened  and Submitted data figures are not getting captured and showing zero. 
2. What is this submitted data for?

**Comment by jordan-wright** [comment]
I highly recommend reading through our excellent [documentation](https://getgophish.com/documentation) since it likely provides the answers to both of these questions.

If after reading the documentation you still have issues, please create a new Github issue, closely following our issue template. It's there to help guide you to providing the information we need to troubleshoot issues.

Thanks!
