### ISSUE TITLE
Per-campaign-configrable tracking parameter name

### ISSUE THREAD

**Issue by atropineal** [gophish/gophish#911]
This is an enhancement request.

At the moment the tracking code parameter is (AFAICT) hardwired to be 'rid'.  This might turn into an easy way to fingerprint gophish.  Certainly if you google 'rid parameter phish' (which suspicious blue teamers may do) then you get gophish results.  And different phishes to the same target(s) may be link-able via this parameter upon casual inspection.

Consequently, as a professional whitehat I'd like to have the ability to change 'rid' to be something else, on a per-campaign basis.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for getting in touch, and thanks for filing this suggestion.

This has been asked before, and for now I don't plan to make the `rid` parameter changeable, especially per-campaign since this would almost certainly cause a confusing UI as well as making processing incoming requests slower since I would have to do a lookup for the parameter (for each parameter given) and _then_ a lookup for the value.

The best way to move forward at this point would be to compile Gophish from source, changing the `rid` parameter to whatever you would like it to be. To make this easier, one thing I will do is move it to a constant so that it's easy to find and change.

Hope this helps! Thanks again for getting in touch!

**Comment by jordan-wright** [comment]
(Re-opening until I get the `rid` parameter moved to a constant)

**Comment by atropineal** [comment]
Great, thanks a lot for the assistance and direction!
