### ISSUE TITLE
No tracking of Email opend - Linked clicked - submit Info

### ISSUE THREAD

**Issue by Piratebayy** [gophish/gophish#913]
Hello everyone,

Today I setted up a GoPhish GitHub Server, but unfortunately it doesn't really function for me.
When I test it by myself with Gmail and Outlook and I open the emails and click and login it doesn't show it in my Campaign.

It only shows when it is sent which isn't really the reason why I setted up the server ;)

I also tried it with tracking images and uploading the images from the mail but this also didn't fix the issue.

I already had a PHP code of the Phish website, so I filled it in the page section so I didn't loaded a website.
I also already had a email template so I didn't loaded that one either, maybe that would be the reason.
If someone could help me out with this would be great!

Kind regards!

**Comment by jordan-wright** [comment]
I recommend reading through our [excellent documentation](https://getgophish.com/documentation) that discusses in detail how to setup Gophish landing pages and email templates.

> I already had a PHP code of the Phish website, so I filled it in the page section so I didn't loaded a website.

This won't work. Gophish doesn't support PHP and requires all landing pages to be created and hosted by Gophish.

> I also already had a email template so I didn't loaded that one either, maybe that would be the reason.

This won't work either. Gophish requires all email templates to be hosted by Gophish.

I recommend following the documentation closely since it describes what Gophish supports and how to properly set up campaigns.

If you continue to run into issues, please file a new issue following our issue template format.

Hope this helps!

**Comment by Piratebayy** [comment]
I have some issues with installing GoPhish on my VPS, I have followed all the installation instructions but I still get some errors:

root@199335:~/go/src/github.com/gophish/gophish# go build
gophish.go:30:2: cannot find package "context" in any of:
        /usr/lib/go/src/pkg/context (from $GOROOT)
        /.go/src/context (from $GOPATH)
/.go/src/github.com/jordan-wright/email/email.go:18:2: cannot find package "mime      /quotedprintable" in any of:
        /usr/lib/go/src/pkg/mime/quotedprintable (from $GOROOT)
        /.go/src/mime/quotedprintable (from $GOPATH)


I have already set a $GOPATH with the export command.

If someone could help me out with teamviewer or something Iw ill give him some BTC :)
