### ISSUE TITLE
Issue #913 Not fixed

### ISSUE THREAD

**Issue by Piratebayy** [gophish/gophish#914]
Hello everyone, 

A few hours ago I have been submitting a issue, but unfortunately it didn't helped me out.

I would like to get some support I will even pay some $ so someone can help me out over screenshare.

Kind regards!

**Comment by jordan-wright** [comment]
Hi there,

I would ask that you please stop filing new issues, and instead comment on the existing issues. If the response in #913 didn't help, please leave a comment **on that issue** with how it didn't help, exactly what you tried, etc. so that we can continue troubleshooting.

The main reason that the issues you have been submitting are closed is due to not enough information being provided for us to troubleshoot. It takes significant time and effort to try and collect this information for every issue, which is why we created the issue template (it's the block of text you're deleting when you're filling out these issues). You'll notice when creating a new issue that the template contains this section:

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

It's my goal to help fix any issues you're encountering, but I can only work with the information I'm given.

For now, I will close out this issue since it is not a new issue, but simply references #913. Please add updated information as a comment on that issue and we can always re-open it as necessary.
