### ISSUE TITLE
I cant install $GOPATH

### ISSUE THREAD

**Issue by ygoncalves1999** [gophish/gophish#923]
i'm executing this command for install gophish: 
go get github.com/gophish/gophish

the system return this messege:
cannot download, $GOPATH not set. For more details see: go help gopath

how can i fix it?

**Comment by S0larflare** [comment]
I take it that you have fixed your Go installation or have used a prebuilt binary now as you have posted a further question related to templates?

**Comment by ygoncalves1999** [comment]
this problem is about version 0.4, the other doubt is about version 0.3 :D

**Comment by S0larflare** [comment]
This link should help:

https://stackoverflow.com/questions/20628918/cannot-download-gopath-not-set

You need to export $GOPATH into your bash profile or similar.

**Comment by jordan-wright** [comment]
Yep! @S0larflare is completely correct, this is a symptom indicating that your installation of Go isn't setup correctly. You can find information both at that stackoverflow link as well as the official Golang [installation docs](https://golang.org/doc/install).

Since this isn't Gophish related, I'm going to go ahead and close this one out. I hope the links help. Let us know if you continue to run into issues and we can always re-open the issue.
