### ISSUE TITLE
Import Email Issue

### ISSUE THREAD

**Issue by securityhawk** [gophish/gophish#932]
Hi Guys

Just wondering if you would be happy to help out with the issue below.

Thanks

Phil

What version of Gophish are you using?: 

Latest

Brief description of the issue: 

Import Email function does not import email

What are you expecting to see happen? :

The email to preview in the html pane when an email source is imported.

What are you seeing happen?

Nothing Imported.

I have tried this with Windows and Ubuntu.

**Comment by jordan-wright** [comment]
Hi @securityhawk,

Can you provide an example of an email that isn't importing correctly?

**Comment by securityhawk** [comment]
Thanks for the replies, @jordan-wright I am 'viewing source' in Outlook and then pasting into the 'Import Email' option, nothing is imported.  I can however paste the source directly into the HTML editor and this fine, although the links are original and not replaced by GP as the replace link function is in the import email function.

The source is standard HTML from Outlook 'view source'.  I have tried various emails.

Any help is appreciated.

Thanks

Phil

**Comment by jordan-wright** [comment]
Unfortunately, you need to import the email with the complete MIME headers. I know that the "View Source" feature in Outlook doesn't do this by default, so I'm afraid a workaround will need to be found. You can find other issues referencing [importing emails from Outlook](https://github.com/gophish/gophish/search?q=import+outlook&type=Issues&utf8=%E2%9C%93) that might help.

It's possible that saving the message as a .msg as indicated [here](https://www.lifewire.com/view-complete-message-source-outlook-1173713) might help (the "Received:" headers aren't important to Gophish) so that might be worth a shot. Though, it looks like that's a weird binary format so conversion to text would be required before importing.

Otherwise, you might be able to save the headers and body separately as indicated [here](https://community.f-secure.com/t5/Business/Exporting-Internet-headers-and/ta-p/21006) and concat them together before importing.

If none of that works, I'm afraid the only option is to input the HTML manually. There's not much Gophish can do to help when Outlook doesn't really give the data we need 🙁

**Comment by securityhawk** [comment]
That makes sense @jordan-wright thank you for helping a newbie - may need to use Thunderbird as I've heard we can get good results with that.

Thank you for taking the time to reply.

Cheers

Phil
