### ISSUE TITLE
Add Command Line Flag to Enable/Disable Mail Sending

### ISSUE THREAD

**Issue by GregCFTS** [gophish/gophish#935]
Version: 0.4

Setting up a sending server and landing server. 

I want to be able to have one server sending the emails that isn't accessible externally, as it will contain user details, and another server for the landing page after the user has clicked the link.

Currently, I have a domain that points to the gophish server that is sending the emails, this works fine as it's being sent from the same server, but when I point the domain to another server and send an email, the link in the emails don't work properly. Do I need to redirect anything else? I couldn't find much documentation on it.

Additionally, is it possible to hide the headers in the email, or partially mask them?

Cheers.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. This is a trickier problem than it might seem, for a couple of reasons.

Architecturally, this should just require setting up Gophish to use a MySQL instance, and pointing both instances (the mailer and the landing page hoster) to the same MySQL database.

To be a bit more clear, this is what it should look like:

```
domain ---> landing_page_host --->
                                    MySQL
                      mailer  ---->
```

**However** Gophish won't know which server should send the emails and which shouldn't. Both servers will have a worker process looking for new emails to send.

I see this use case pretty frequently, so I'll likely add in a command line flag to determine if the server should send emails or not so that you can have a dedicated worker with other servers just serving the landing page.

**Comment by GregCFTS** [comment]
Hi Jordan,

Thanks for this. I assume in the mean time, this isn't possible to do and there's no workaround? 

Cheers.

**Comment by jordan-wright** [comment]
Correct - without modifying the code yourself, I'm afraid this isn't possible to do in the meantime.

**Comment by GregCFTS** [comment]
Hi Jordan,

Thanks, for free software it's really good!

Cheers.
