### ISSUE TITLE
Outlook phising filter

### ISSUE THREAD

**Issue by bofhzen** [gophish/gophish#936]
Hi everyone,
I´m making a phishing campaign inside my company copying the email template from an Amazon mail.
The mail is sent by novedades@amazon.es
the problem is outlook says is phishing  and deactivate the links.
How can I evade this without manually access outlook clients and uncheck  the phishing option?
Thank you
Regards

**Comment by jordan-wright** [comment]
It might be possible to whitelist emails from a specific IP address (the Gophish sender) or with a specific header (which you can add in the sending profile).

Other than that, Outlook is doing what it's designed to do, which is block phishing emails 😄 I'm afraid there isn't much in Gophish we can do to get around that, which is a good thing because it means there isn't much bad actors can do to get around it 😉 

Hope this helps!

**Comment by jordan-wright** [comment]
A quick Google search turned this up in case it helps https://support.knowbe4.com/hc/en-us/articles/218134997-Whitelisting-by-IP-Address-in-Exchange-2013-2016-or-Office-365

**Comment by bofhzen** [comment]
Thank you so!
I'm going to talk with  IT to whitelist my IP and create a rule.
I was thinking about whitelisting but I thought this only affects normal spam.
I will tell you the results
Thanks!

**Comment by jordan-wright** [comment]
Sounds good! I'm going to go ahead and close this one out for now since there isn't anything in Gophish we can change to fix this. However, let me know if you continue to run into issues and we can always re-open to continue troubleshooting.

Thanks!

**Comment by abdelakp** [comment]
Hi guys,
I have a problem when I use outlook to send test mail , I have this message  //550 5.7.60 SMTP; Client does not have permissions to send as this sender, How can I fix the problem?
Thank you
