### ISSUE TITLE
How to use the built in mailer for go phish? I am currently getting ready for a phishing campaign for my company. I have everything setup except how to send the email. I need to be able to send the email without authentication so it matches the domain i have purchased. Is there something I need to install on GoPhish?

### ISSUE THREAD

**Issue by jakara8** [gophish/gophish#937]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 

Brief description of the issue: 

What are you expecting to see happen? :

What are you seeing happen?

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
Insert output here
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - 
 * Step 2 -

**Comment by jordan-wright** [comment]
Hi @jakara8, thanks for reaching out!

If you could, please provide details about the issue by filling out the fields provided in the issue template. That will help is troubleshoot and resolve the issue.

Thanks!

**Comment by jordan-wright** [comment]
Gophish does not provide a built-in SMTP server. It is assumed you already have one set up, which is outside the scope of our support. Since you said you're doing a test for your company, it's almost certain your company already has an SMTP server set up that you can point to so send email.

Otherwise, there are many options available, and the [ansible playbook](https://github.com/gophish/gophish/blob/master/ansible-playbook/roles/gophish/tasks/main.yml#L21) that comes with Gophish includes a task to setup `postfix` so that it can be used, which might provide some guidance.

**Comment by jakara8** [comment]
What version of Gophish are you using?: 4

Brief description of the issue: I need to be able to send my emails without authentication to match the domain I have purchased. How do you use the built in SMTP to achieve this?

What are you expecting to see happen? : Emails are sent matching the domain purchased.

What are you seeing happen? I have been using Google but require something else to achieve this.

**Comment by jordan-wright** [comment]
@jakara8 please see my comment above and let me know if you have any other questions.

**Comment by jakara8** [comment]
I am really new to GoPhish and it’s amazing and I can’t wait to use it. So I guess the first thing I need to do is setup an SMTP sever? How do you use postfix with gophish?

**Comment by jordan-wright** [comment]
Yes, Gophish requires an SMTP server to be set up. You create a "Sending Profile" in Gophish and point it to the SMTP server.

You said you're getting ready to perform a phishing campaign for your company. It's almost certain that your company has an SMTP server already set up that you should use. You can contact whoever is in IT at your company to get the details from them.

**Comment by rfdevere** [comment]
@jakara8 could you get by using postfix? 

Install postfix in the server you are using.

In the host field on sending profiles input “localhost:25” 

If you’re whitelisting it will probably be ok like this, if not consider ‘Mail-in-a-box’ which you can set up with your domains and this will give you a DIY mail server, void of them pesky restrictions that Gmail place on phishers.

**Comment by jordan-wright** [comment]
Going ahead and closing this since there hasn't been any updates in a week and the original question seems to have been answered. The details on how to install and configure postfix is outside the scope of our support, but once the SMTP server is set up, you simply need to point Gophish to it when creating the sending profile.

Hope this helps! Thanks @rfdevere for providing the additional info. Always appreciated 😄
