### ISSUE TITLE
Please help me understand the listener URL

### ISSUE THREAD

**Issue by ocdomo** [gophish/gophish#952]
We've configured Gophish but when users click onto the target URL contained in the email they get a 404.

I suspect this is because we're running Gophish off a server which resides in a VM on my laptop - so not publicly accessible.

What am I supposed to enter for the listener URL?

**Comment by jordan-wright** [comment]
Thanks for reaching out!

The listener URL should point to the IP address of the Gophish phishing server that is reachable by the targets.

What does the 404 page look like?

What are you using as your email template?

As a future note, if you could please use the issue template provided, it would be appreciated, since it helps guide what information we need to effectively troubleshoot.

**Comment by jordan-wright** [comment]
Hi @ocdomo just checking in - are you still running into issues? If so, if you could please provide the information requested from the previous comment, we can continue troubleshooting.
