### ISSUE TITLE
CSS proper directory

### ISSUE THREAD

**Issue by bycior** [gophish/gophish#954]
What version of Gophish are you using?: 

GoPhish v0.4

Brief description of the issue: 

When You put your CSS file into static folder ('static/endpoint') you can not really see if it's working through preview window in the "New Landing Page" window.
On the other hand, when you put your CSS into 'static/css/dist' folder it runs okay in preview window but does not work when you run campaign.

What are you expecting to see happen? :
Allow to use static/css/dist folder for CSS when you run campaign or repair preview with CSS placed in static folder.

And extra (for another issue maybe?): Preview window should be able to stretch more, or go fullscreen so it is not pain in the *** when you try to edit your landing page or email template.

I don't see the need of providing the code - I think it's not really related.

**Comment by jordan-wright** [comment]
Hi @bycior thanks for reaching out! Unfortunately, this won't be a simple change, and I'm not quite sure it's possible at all.

The issue is that there are two static folders - the static folder used by the admin panel and the static folder used by the phishing server (that's the /static/endpoint/ folder). It would be really tricky to make it such that both the admin and the phishing server are smart enough to use the /static/endpoint folder without breaking the existing static assets for the admin server.

One thing you could do is to reference the full ip:port of the phishing server when referencing the static assets. So, `<link href=/css/foo.css>` would be something like `<link href="http://x.x.x.x:80/css/foo.css>`. This forces the connection to go through the phishing server, where it should work just fine.

Hope this helps!

**Comment by bycior** [comment]
Hi Jordan,
thank you for the reply. I was aware of that solution but I thought of this as a bug not a feature :-)

What about resising the preview window? Is it the topic for another issue or you can answer me here?

**Comment by bycior** [comment]
Oh yea, I havent noticed that little thingy before... It is fine that way. Thank you for the reply!
