### ISSUE TITLE
Port and Certificate

### ISSUE THREAD

**Issue by GregCFTS** [gophish/gophish#956]
GoPhish version 4

Do you know what port GoPhish uses, and if not, how do you find out?

Also, I'm having a bit of an issue setting up a certificate. I have purchased a certificate from an authority. Do I need to setup the certificate through IIS?

Cheers

**Comment by S0larflare** [comment]
Standard (admin console) port is 3333, you can change this in your config.json if you wish. Is this so you have a trusted cert for the admin console or are you after https for a phishing page? You don't have to set up IIS, it is all done through Gophish. If you want to use your own cert, generate a CSR through openssl, get the certificate and convert it, you will need the .key and the .crt/cer file. Edit your config.json to mirror the name of the certificate

**Comment by GregCFTS** [comment]
Hi S0larflare, it's for the admin portal

I've got the .crt, how do I get the .key?

**Comment by S0larflare** [comment]
The admin portal will generate it's own self-signed certificate upon first run. Considering you should be the only person to see it (or your team should be the only people to see it) this should be sufficient, buying a certificate for it is a bit OTT in my opinion.

You won't be able to extract the .key from the .crt, you will get the .key when you generate the CSR.

The admin portal is where you set up all the campaigns and view the results. It will coordinate the sending of the emails but doesn't send them itself, instead it uses a mailserver which you are assumed to have access to in order to send the emails.

**Comment by GregCFTS** [comment]
Hi S0larflare,

The organisation I work for provided the certificate for free. 

If my organisation has an exchange server, it will use this to send the emails? So whatever port we use for that, it will use as well?

Cheers

**Comment by GregCFTS** [comment]
@S0larflare 

FYI, I have now updated to GoPhish 5 if this makes a difference?

**Comment by jordan-wright** [comment]
Hey @GregCFTS,

Using version 0.5.0 won't make a difference here. It sounds like you might be getting the certificates confused. If your organization has an exchange server, it likely has a certificate to support sending emails over TLS. This won't really matter to Gophish, but you'll likely want to set that exchange server up as your sending profile later on.

It sounds like what you're referring to is setting up a certificate for the admin panel so that you aren't using the self-signed ones generated by Gophish. For that, you will need both a private key and a certificate. If you don't have both, it won't work.

Once you have both of these (they need to be provided by your organization or a CA), you just need to update the config to point to these files. I'm afraid actually getting the cert and key is outside the scope of our support.

I hope this helps!

**Comment by GregCFTS** [comment]
Hi  @jordan-wright 

Thanks for this, really useful information there.

Do you know what port the emails are sending from? Is it just the standard whatever our exchange server is using?

Cheers

**Comment by jordan-wright** [comment]
> Do you know what port the emails are sending from? Is it just the standard whatever our exchange server is using?

I'm not quite sure what you mean by this. The destination port (the port Gophish connects to) will likely be the standard SMTP ports (either 25 or 587), but you'll want to confirm with the administrator who runs the Exchange server. The source port the emails are coming from will be dynamic and not always predictable, but my guess is that you were likely referring to the destination port here 😄

**Comment by GregCFTS** [comment]
@jordan-wright 

Hi Jordan, I'll clarify a little.

In order to lock-down the firewall, we block all the ports on the server and open only the necessary ones. So when the emails are being sent from GoPhish, what port are they using?

Cheers

**Comment by jordan-wright** [comment]
Gophish will be making connections to the SMTP server using whatever port you specify in the sending profile. This is likely going to be a standard SMTP port (TCP port 25 or 587), but you'll want to confirm the port with the exchange server administrator.

**Comment by GregCFTS** [comment]
@jordan-wright 

Hi Jordan,

Thanks for the help!

Cheers :)

**Comment by jordan-wright** [comment]
You bet! Glad we were able to help. Thanks again for reaching out.
