### ISSUE TITLE
Get groups from campaign

### ISSUE THREAD

**Issue by AuditeMarlow** [gophish/gophish#957]
Using the API, I can get results from a campaign, which describe the targets with some additional info. However, I lack the ability to directly link these back to the group these results belong to. This is crucial to me, as I'd like to report per group as well as per target.

I can't rely on looking for a target in a group, as a single target can belong to multiple groups. There's currently just no way to reliably tell what groups were specified for a campaign using the API.

Is there any hope for me that groups will be related to the campaign's results later on?

**Comment by jordan-wright** [comment]
Hi there! Thanks for reaching out.

It's _possible_ that we could add this in the future, but I think it's important to mention why things are the way they are.

I choose to associate (copies of) targets with a campaign as opposed to groups simply because groups could be changed after a campaign has started. If I did everything by referencing the data off groups, this would lead to inconsistencies.

So I guess I _could_ add the group name to the copy of the target I use in the campaign, but this could cause confusion later if you're looking at the results of a campaign, see that a target is associated with a specific group, and realize that the target actually isn't in that group anymore.

It's a tricky thing, so I'll have to think about it a bit more. Happy to consider any suggestions!

**Comment by AuditeMarlow** [comment]
Hmm, this _does_ prove to be a tricky thing... I guess as a temporary solution, we could shit the copies of targets with, for example, the group name as a parameter in the object. But yeah, like you said, this would lead to inconsistencies too.

Then again, storing copies of targets in the campaign seems fairly inconsistent, too, as targets may be removed or updated at any time. While I understand you basically start a campaign to get results from the targets, it may be nice to get results from the groups the targets are a part of, too.

I don't know, I'm sort of thinking out loud right now, but sometimes it may be undesirable to view the results from the targets directly. Maybe I'm more worried about censoring who did what and need to find another solution.
