### ISSUE TITLE
Hosting gophish in a domain

### ISSUE THREAD

**Issue by velu120029** [gophish/gophish#958]
Can anyone guide me how to host gophish in a domain? I recently tried gophish and I need to try this for one of my customers. I tried through internal servers and worked fine. How to setup gophish with public IP? Kindly support.

**Comment by velu120029** [comment]
I have a domain purchased from GoDaddy.

**Comment by jordan-wright** [comment]
What have you tried that's not working? If the domain resolves to the external IP address, then everything should work fine if you put the domain as the URL when building a campaign.

I recommend following the issue template we provide, since it guides you towards providing the information we need to troubleshoot effectively.

**Comment by velu120029** [comment]
HI Jordan,

Thanks for your quick response.

I bought the domain from Godaddy.

I wanted to host gophish on this domain. I am not sure how to do that. I am
new for hosting and not sure of hosting procedures for gophish. Can you
help with some steps for hosting gophish in godaddy domain?
I have to complete phishing activity for one of my customer.
Your support is much appreciated.

Thanks and Regards

Vadivelan

**Comment by stracire** [comment]
The most easy way is to rent a [VPS](https://nl.wikipedia.org/wiki/Virtual_private_server) and setup your [dns](https://nl.wikipedia.org/wiki/Domain_Name_System). You can also set the A-record to your own IP but then you have to allow these ports on your modem as wel.

**Comment by jordan-wright** [comment]
@stracire is absolutely correct. You need to be able to create an external server (such as a DigitalOcean droplet) where you're running Gophish, and point the domain to the IP address of that server.

Then, when you create a campaign, you can put the domain as the URL, since it resolves to the Gophish server.

**Comment by jordan-wright** [comment]
Going ahead and closing this out since it's been a while since there were any updates and it appears the original question has been answered.

@velu120029 if you're still running into issues, let us know and we can always re-open. Thanks for reaching out!

**Comment by habsfan50** [comment]
@jordan-wright @stracire Hi, I am very new to all of this and please tell me if I understand this correctly. I rent a VPS, log into my VPS using something like SSH, and install gophish. Then I purchase a domain and inside the dns management page of my domain, point the domain to the IP address of the server. Does this mean that when I connect to my domain address I will be directed to the server?

Can the VPS have a domain so I can skip buying a domain? 

Thanks in advance.

**Comment by payvandpg** [comment]
> Can anyone guide me how to host gophish in a domain? I recently tried gophish and I need to try this for one of my customers. I tried through internal servers and worked fine. How to setup gophish with public IP? Kindly support.

Its pretty easy, You just need to go to AWS and enable your port. It could be HTTPS or HTTP
