### ISSUE TITLE
Per email customisation of attachments 

### ISSUE THREAD

**Issue by truekonrads** [gophish/gophish#964]
Hello,

I’d like to have a method which would customise each attachment in the email. I would imagine that GoPhish would invoke a program, feed it the template attachment and take the transformed output and use that as the actual attachment. 

This is if we want to customise each attachment for user. 

I’m happy to give it a go, but would need some design guidance

**Comment by rfdevere** [comment]
This sounds interesting but massively outside of what GoPhish is, one for Jordan and Co.

Whats the use case and is there a better way? Rather than sending 50 different versions of an attachment is there an attachment you could send that maybe identifies a user that opens it? If you're wanting to test and simulate who runs an .exe it could maybe be a benign .exe that grabs the machines user/hostname and posts that info to a server etc...

**Comment by truekonrads** [comment]
Hello @rfdevere,

There are a few reasons why bother:
1) Include personalized content that makes the user more likely to click, for example, it could say: "This document is solely meant for Konrads
2) Be more efficient in evading sandboxes by customization detection per user, e.g. if 
(StrComp(Env("USERNAME") , "konrads", vbTextCompare) = 0) then run, else crash.

Again, I'm asking for some design guidance only rather than asking people for their free time to help my cause. I was thinking of modifying:
 ```golang 
func (m *MailLog) Generate(msg *gomail.Message) error {}
```
In there, I wanted to pass all the data model values such as username,password,email, etc in environment variables much like CGI interface does.  The question then remains if we should pipe the binary attachment to STDIN and read from STDOUT or use a file system exchange mechanism

**Comment by jordan-wright** [comment]
@rfdevere is correct that this won't be something we implement natively in Gophish, since there's simply too much overhead, and it would undoubtedly create more support tickets than we can handle.

If you're looking to implement this for your own Gophish instance, you're on the right track. The `Generate` function populates the `gomail.Message`, so that's where you can generate and add your attachments. For information on the fields/functions available to a `Message`, you can refer to [this documentation.](https://godoc.org/github.com/gophish/gomail)

Hope this helps! Thanks for getting in touch.
