### ISSUE TITLE
Two-Factor Phishing

### ISSUE THREAD

**Issue by giomke** [gophish/gophish#971]
I think it will be great to implement Two-Factor Phishing, similar like 
https://github.com/fireeye/ReelPhish
https://github.com/kgretzky/evilginx
https://github.com/ustayready/CredSniper
tools

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. This has been considered in the past and is being tracked best by #223, which will let users make extremely flexible campaigns.

In addition to this, I've done a PoC of what I would call the generic "proxy" feature in the past which would mitm any credentials sent - similar to ReelPhish. However, it's much trickier than it sounds. There are cases where things just break because the references to static assets aren't correct anymore, or credentials are submitted via Javascript, not via a form, etc. etc. Basically, there are so many edge cases, that it's difficult to get correct.

For now, since we do have #223 open, I'm going to close this out in favor of that issue where we'll track the development of that new campaign editor 😄 

Thanks again for sending this over!
