### ISSUE TITLE
Safelink false positives

### ISSUE THREAD

**Issue by apatedolos** [gophish/gophish#973]
Microsoft Safelinks are causing false positives in campaigns.

When a users mail is delivered, there are two GET requests performed on the link by safelinks which indicates in the UI that the user has opened and clicked which is not the case.

The only difference between the requests is a /track is added before the rid and a %27 is added after the rid which throws a 404 error, almost feels like a SQLI test! this produces a 404.

The second request is correct which gives a 200 error as expected.

See below what happens from the log, times and actual get requests have been modified.

40.107.218.12 - - [12/Feb/2018:08:02:36] "GET /location/file.extension/track?rid=RandoMID%27/ HTTP/2.0" 404 19 "" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
40.107.218.12 - - [12/Feb/2018:8:02:36] "GET /location/file.extension?rid=RandoMID HTTP/2.0" 200 20791 "" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

The following site lists the known Microsoft online protection IP's

https://technet.microsoft.com/en-us/library/dn163583(v=exchg.150).aspx

It would be good if the system has a method to either detect this sort of event and not report it on campaigns.

One possible solution could cross reference these source IP's and not output them in the UI to remove false positives, this may not always be reliable as it should be noted that the IP the made the GET requests is just outside the ranges listed at that URL.

Another solution may be the ability to manually add IP's to blacklist that could be redirected to a dummy copy of the campaign.

**Comment by jordan-wright** [comment]
Thanks for reaching out!

I completely understand that it's frustrating seeing these false positives coming from the anti-spam systems. However, I'm not too keen on identifying/blocking those by default in Gophish itself, for multiple reasons:

* It would be a cat/mouse game - we would be locked into maintaining these IP lists and updating them anytime the IP ranges change. And it would only be the beginning, since Microsoft is one of countless anti-spam appliances that have link checking.

* Blocking or otherwise modifying the response based on the IP ranges would be a bad-faith effort on our part - The best way to run phishing campaigns is to be transparent about the infrastructure around it. If someone is going out of their way to figure out if this is an approved phishing campaign, we shouldn't be hiding from it. Even as pentesters, we should encourage that behavior.

In terms of reporting, it's not inaccurate to say the links were clicked since, technically, they were clicked - just not by the user. This information from a defender's perspective is valuable since you know the systems in place are working, and from a red-team's perspective is valuable since you can better fingerprint the organization's infrastructure.

My best recommendation at this point would be to filter those out using the API. By exporting the results or writing a quick script using our [`python-client`](https://github.com/gophish/api-client-python/), you can quickly filter out any results you don't want to show including these IP ranges.

I hope this helps! I appreciate you taking the time to send this over, and hope this explains the reasoning behind the decision not to implement this.

**Comment by ironc0in** [comment]
A cool feature in the GUI could be to identify the spam filter IPs using a custom spam list filed somewhere in the account settings.
The stats page could check against that customer user list and mark those as email filters and not count them as user clicks.

I know this is a side project, just brainstorming on possible solutions.
At this point most of my campaign results are basically skewed because of this and I have to manually figure out how many clicked from the cvs output. Would be an extremely neat feature to have.
