### ISSUE TITLE
Feature request: More advanced campaign scheduling

### ISSUE THREAD

**Issue by andrew-vu** [gophish/gophish#985]
It would be great to have a couple of options when configuring a campaign which alter when the emails are sent.

First, a start and end date/time, during which, emails would be sent individually with an equal gap between each one.

Second, the option to send those emails within specified business hours.

When performing a campaign against an office, it's all too easy for people to talk and realise they've all been subjected to the same email at the same time. Once that happens, the success rate will be greatly reduced and the realism of the simulation is tarnished as it's more likely an individual will be targeted in a real-world scenario, rather than the whole company.

If the emails are spread out over the course of a given period, the chances word spreading is bound to be reduced. 

I think if emails are spread out evenly over a schedule, it's also a good idea to add the business hours control to ensure lots of emails aren't being sent in the middle of the night. 

I've seen requests posted here for adding a delay between each email, while that idea is preferable to nothing at all, I think it is useful to have some control over how long a campaign will last.

**Comment by jordan-wright** [comment]
Hi @andrew-vu - thanks for reaching out!

There have been [quite a few](https://github.com/gophish/gophish/search?p=2&q=random&type=Issues&utf8=%E2%9C%93) discussions on implementing randomized email sending.

The good news is that, thanks to the email refactor we finished recently, this is now possible to implement and is a high priority item. My plan is to basically do what you're suggesting- allow users to specify an optional end time and emails will be spaced out throughout that interval.

It's _possible_ that we could implement the "business hours" idea, and I think it's a good idea, it just won't be in the first iteration since it's trickier to implement since we're already having to calculate the delays between each email.

Since there are so many open issues about this, I'm going to close this out as a duplicate for now. I encourage you to keep an eye on the other issues for any updates as to the implementation and progress 😄 

Thanks again for getting in touch!

**Comment by GregCFTS** [comment]
@jordan-wright 

Hi Jordan,

Sorry if you've already answered this. Do you have an estimated time frame for implementing this feature? E.g. 2 weeks, 1 month? If not, it's not a problem 👍 

Cheers.

**Comment by jordan-wright** [comment]
It's going to be one of the next things I work on. Right now, I'm spending any time I have reviewing PR's to get email reporting and custom envelope senders integrated. After that, I'll add the delayed sending. So no timeline atm, but it shouldn't be too far off 😄

**Comment by GregCFTS** [comment]
@jordan-wright 

Sounds great, good luck with all the PR stuff :)
