### ISSUE TITLE
Tracking which links are clicked

### ISSUE THREAD

**Issue by bm1391** [gophish/gophish#987]
I have a question regarding the ability to track whether users select certain links in the phish email. For example, given a email template that has 2 links, are we able to track whether user clicked the first link or the second one?

I am aware you can redirect users to certain links/pages/domains, but this would be more for tracking purposes. My first guess is no, because each email sent out is assigned a id that is used to track them when they load the gophish page on 3333. Any help would be greatly appreciated!

Thanks in advance!

**Comment by jordan-wright** [comment]
I'm afraid Gophish doesn't support multiple forms of tracking in the same email and, since this would be a feature that would have a really narrow use case mixed with significant development time, I don't foresee us adding this in the future. At this time, we only support generic binary tracking - either they clicked the link or they didn't.

Thanks so much for taking the time to reach out!
