### ISSUE TITLE
Feature Request: Lowercase-only tracking links

### ISSUE THREAD

**Issue by mtvprueba** [gophish/gophish#991]
Hey!

We're running on the newest version of GoPhish in my company, and it seems that the newest update adds uppercase letters to the tracking links, thus making them case-sensitive.

This turned out to be a problem, as some spamfilters that we've encountered replaces all links in the e-mail with a special link formatted by the spamfilters, and afterwards links to the original tracking link. However, these new tracking links have been made all lowercase thus breaking the tracking links.

What I am looking for is an option to enable lowercase-only tracking links.

Thanks

**Comment by jordan-wright** [comment]
Hi @mtvprueba - thanks for reaching out! Since this is an awfully specific request, I don't plan to implement this in Gophish itself at this time.

However, this is a really simple thing to change in the code and then you can just build Gophish from source. You'll find the function here https://github.com/gophish/gophish/blob/master/models/result.go#L72, simply remove the capital letters and you're good to go!

Hope this helps! Thanks for reaching out.
