### ISSUE TITLE
Permanent change in .zip folder structure?

### ISSUE THREAD

**Issue by derpadoo** [gophish/gophish#993]
If so, I'll update the Ansible playbook since it expects a certain structure.  Your latest build does not have the same base `gophish-v0.4-linux-64bit` version folder.

v 0.4.0 looked like this:

```bash
unzip -t gophish2.zip 
Archive:  gophish2.zip
    testing: gophish-v0.4-linux-64bit/   OK
    testing: gophish-v0.4-linux-64bit/doc/   OK
    testing: gophish-v0.4-linux-64bit/doc/individual_contributor_license_agreement.md   OK
    testing: gophish-v0.4-linux-64bit/doc/corporate_contributor_license_agreement.md   OK
    testing: gophish-v0.4-linux-64bit/README.md   OK
```

and version 0.5.0 looks like this:

```bash
unzip -t gophish.zip
Archive:  gophish.zip
    testing: static/js/dist/app/      OK
    testing: static/js/dist/vendor.min.js   OK
    testing: static/js/dist/app/users.min.js   OK
    testing: static/js/dist/app/settings.min.js   OK
    testing: static/js/dist/app/sending_profiles.min.js   OK
    testing: static/js/dist/app/landing_pages.min.js   OK

```

**Comment by jordan-wright** [comment]
Hey @derpadoo! Sorry about the change. Yeah, this will be the structure moving forward since I've automated the way releases are compiled and built. You can find details on the process [here](https://jordan-wright.com/blog/post/2018-02-04-automating-gophish-releases/) if you're interested. 😄 

Sorry for the inconvenience - good catch!
