### ISSUE TITLE
Email errors

### ISSUE THREAD

**Issue by mdavis332** [gophish/gophish#997]
What version of Gophish are you using? 0.5.0

Brief description of the issue: 
Email sending errors during the campaign after about 250-300 emails are successfully sent.

What are you expecting to see happen? 
All emails going through without erroring out (as in previous versions).

What are you seeing happen?
I opened a new campaign yesterday to 879 users in our org. I've done this same type of campaign quarterly since Sept 2016. Each time we've used an on-prem Exchange 2010 server to email. This is the first time we've used GoPhish v0.5.0 and we're seeing errors trying to send many of the emails. The campaign sent 312 emails and then reported errors on the rest. The error is reported in GoPhish under each user as follows:

Error write tcp <GoPhishIp>:55163-><MailServerIp>:25: wsasend: An established connection was aborted by the software in your host machine.

I pulled a report of all the ones that failed (567 out of the 879) and used that to generate a new campaign with just the users that failed sending for the first campaign. The 2nd campaign managed to successfully send to 265 users but failed on 301 of them.

I pulled one final report of the 301 failures and launched a 3rd campaign to send to those. All of those went through successfully.

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Create a new campaign with at least 400 recipients
 * Step 2 - Launch

**Comment by mcvic1rj** [comment]
Do you have access to the exchange server protocol logs? Or do you have logs from GoPhish?

**Comment by S0larflare** [comment]
How long did it take for the 312 to send? I’m wondering if it’s a timeout with GoMail. Also, do you know what email 313 was? That could have had an error that caused this

Sent from my iPhone

On 8 Mar 2018, at 15:38, Ryan McVicar <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have access to the exchange server protocol logs? Or do you have logs from GoPhish?

**Comment by jordan-wright** [comment]
This is interesting - I haven't heard of this occurring, especially not with the latest version.

Are there any other logs you can provide @mdavis332? I'd be curious to know where in the mailing process this occurred.

Also, did you see any indications of retries happening? The new mailer we implemented with v0.5.0 should be smart enough to properly backoff and retry sending failed emails a total of 10 times to prevent exactly this from happening 🤔

**Comment by mdavis332** [comment]
I worked with our email admin this morning to try to get some logs from our on-prem Exchange server. From some test campaigns I ran that morning against just my email address, there are mail trace logs from our SMTP server where the GoPhish server hit our smtp server on port 25 and successfully resolved/routed the email to me. 

However, a few hours later when I launched the org-wide campaign that included my email again, the trace from that time period doesn't show the exchange server ever even tried to send to my email address. That kinda makes me think GoPhish gave up sending at that point and didn't even try anymore from the server where GoPhish is running. 
![mailfail](https://user-images.githubusercontent.com/1747636/37222096-946b84c8-2391-11e8-9e7a-580bb82641e4.jpg)

Continuing to investigate, our email admin looked at our raw SMTP logs and I reconciled those with the raw events export of the campaign from GoPhish. Here's what looks like happened:

2018-03-06 18:02:51 UTC - Campaign Created
2018-03-06 18:03:19 UTC - First email goes out
Lots of emails successfully sent and some opened until....
2018-03-06 18:13:17 UTC - First error in the raw events csv ("error":"421 4.4.1 Connection timed out") on user JohnWhite@host.com
The SMTP logs from that time showed that GoPhish's smtp session timed out at that same time
2018-03-06 18:13:18 UTC - EHLO from gophish on SMTP server
2018-03-06 18:13:18 UTC - RCPT TO JohnWhite@host.com on the SMTP server
2018-03-06 18:13:19 UTC - raw events csv shows Email Sent to JohnWhite@host.com
2018-03-06 18:13:20 UTC - SMTP server gets QUIT from GoPhish IP
2018-03-06 18:13:20 UTC - SMTP logs show 221 2.0.0 Service closing transmission channel
2018-03-06 18:13:20 UTC - GoPhish raw events csv shows Error Sending email for everyone after this time

Our SMTP server session timeout is 10 mins. It seems like GoPhish hit the session timeout limit, disconnected, reconnected, resent one failed email (the JohnWhite@host.com), then closed the connection and never tried to send any more.

![mailfail2](https://user-images.githubusercontent.com/1747636/37223233-81399918-2395-11e8-8e7d-11ca76a7b64d.jpg)

Sorry for all the redaction. Trying to sanitize our logs so my network guys don't shoot me :)

**Comment by mcvic1rj** [comment]
It would be more work but it should probably be a setting under the mail profile. 

I wonder if this happens when the smtpserver has a connection time max of 2 min or 5 ect

**Comment by jordan-wright** [comment]
> Perhaps having GoPhish use a new dialer every 10 minutes would fix this?

What's odd to me is that the logic we put in place with the new mailer _should_ fix this. Like, if things go wrong anywhere in the chain, Gophish should be backing off and trying again later with a fresh connection.

And that's the way I'd like to fix it. Instead of having a setting for the timeout on the receiving end (which would probably cause a ton of support requests), I'd rather Gophish just be resilient enough to handle errors like this gracefully. This fact that this is occurring on the latest 0.5.0 release is just odd to me.

You can see the logic in place [here](https://github.com/gophish/gophish/blob/master/mailer/mailer.go#L125) (the code should be reasonably readable). Basically:

* We try to open a connection to the host (try 10 times until it works or we throw an error)
* Once the connection is open, we try to send each email.
* If we get a temporary 4xx error, we "backoff" and log the email to re-send after an exponential amount of time. Then, we "reset" the sender (which means it'll start the email process again with the `EHLO` command.
* If we get a permanent 5xx error, we completely error out that email - it won't be retried. Then, we reset the sender.
* Any other errors just error out the email and reset the sender. This is the "uhh... wtf" case. 😉 

Off the top of my head, I could see a possible case where perhaps the underlying connection is being closed (the timeout) and Gophish doesn't know it. Then, resetting the sender won't really fix that issue because it's the underlying TCP connection that's closed, not just the SMTP connection. Right now, the behavior is just to error out the email and reset the sender, which won't help us for future emails since it's not SMTP's problem.

Come to think of it - that's probably what's happening here.

Now, how to fix this is a different story. I'll have to think about how I can tell if the connection itself was broken, try to reset it, and go back to where we were. I'll be thinking on this and will get back to y'all.

@mdavis332 Thanks so much for grabbing those logs. That helps tell the story and gives a good picture of what's going on. I know you had to take time out of your day to gather all that for us, so please know it's much appreciated!

**Comment by mdavis332** [comment]
>  I could see a possible case where perhaps the underlying connection is being closed (the timeout) and Gophish doesn't know it.

What's odd about that is that the SMTP logs seems to show the server received a QUIT transmission from GoPhish, which makes me think it's not just losing the TCP socket. I know next to nothing about Golang, but the only thing I can find that sends a quit is the Close() function from github.com/gophish/gomail/smtp.go (which I guess calls Quit() from net/smtp). Perhaps GoPhish is re-establishing a connection, sending to that one email, then quitting again? I'm out of my depth, so I'll stop the speculation there :) I can confirm we didn't see this behavior in prior versions (including 0.4.0). 

@jordan-wright no thanks necessary, very happy to help if we can. Like most IT teams, we're constantly challenged to do more with less. GoPhish being FOSS has really helped increase our user-level security posture. We've gone from about a 15% submit rate across 870 employees in Sept 2016 down to 2% this month (running campaigns quarterly). If we can help you make GoPhish better, everybody wins. On that note, let me know if we can provide further info.

**Comment by rfdevere** [comment]
Just thought I’d chime in. I’ve ran many campaigns overs 50,000 users and this (to me) looks like your internal mail host doing what it’s supposed to do, recognising automated crap mail and binning it. 
Different mail providers have different daily limits like gmail was 250, Outlook 100 etc then anything after that is canned. In the Wild spam groups try tricks like ‘knocking twice’ where an SMTP connection is tried twice, and only on the second will it be accepted... 

If you’re of low tech ability then schedule shortened groups of 50/100 to go out daily for a while - done. This should avoid the error, if you’re feeling adventurous then spin up mail-in-a-box and use that free of restriction. 

NB - I’m seeing more spammers use Mail-In-A-Box just because it works and nearly every host these days is wise to GoPhish and automated = spam mentality.

**Comment by jordan-wright** [comment]
Hmmm..... that's not good. Thanks for the heads up @S0larflare. I'll raise the priority on this and see if I can get it fixed ASAP. It's looking like I'll need to be quicker and more robust in choosing to shut down the connection complete and rebuilding it.

**Comment by jordan-wright** [comment]
Hey everyone, sorry for the delay on this. Any change I make to the mailing section of Gophish I try to make with care since sending emails correctly is pretty important 😝 

I'm nearly 100% confident that the (or at least "a") problem we're seeing is happening [here](https://github.com/gophish/gophish/blob/3a7a62e9d6aaa2ce42c65e52df93758ef427c9ea/mailer/mailer.go#L189). In this case, as mentioned above, if the underlying TCP connection breaks then Gophish won't be able to gracefully handle this and will instead cause all the remaining emails to fail.

This isn't what should happen. We can do better 😄 

Instead, I'm changing that `else` block to attempt to re-create the connection. Most of the time, this should work fine, in which case we'll _backoff_ the email instead of erroring it out.

If we can't reestablish the connection (still trying 10 times as usual) then we have a problem, since this means Gophish just can't reach the mail server. This likely means that something went wrong with the remote host and it wouldn't be a good idea to backoff the emails since we would wind up causing a huge delay of backed up emails for a problem that's not guaranteed to go away. So, if this were to happen, I'll go ahead and error out the remaining emails.

The last part of this will have to happen in a separate section. Let's say the remote host goes down, we can't reconnect, and we error out the remaining emails but now we want to actually send those emails (e.g. we fixed the problem on the mail server). I believe we should make it easy to re-send emails in a campaign from the campaign view directly. The plumbing is there with this new redesign, we just have to implement the code. Something like a Resend button at the top, and you can choose to resend all or resend the errored emails. Additionally, it'd be nice to resend individual emails from within the campaign results dropdown.

I know this is a lot of info, but I want to be transparent about the changes I'm planning. I should have something up in the next day or so, but please don't hesitate to let me know if you have any questions in the meantime! Thanks again for reporting this @mdavis332!

**Comment by jordan-wright** [comment]
Ok, I've pushed up the proposed fix for this. I'll create a new release sometime early next week if not sooner. If y'all could give this a shot and let me know if it helps fix the problem, it'd be much appreciated!

Thanks again for all the help tracking this one down!
