### ISSUE TITLE
URL/Listening Server/Landing Page help

### ISSUE THREAD

**Issue by NicolasCarson** [gophish/gophish#998]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: current version: 20171208201932

Brief description of the issue: I am having issues getting the landing page to load, I believe is is because I am misunderstanding how to setup the listening server and the URL.  

What are you expecting to see happen? : I am expecting the URL link in the email template to send the user to my specified landing page. 

What are you seeing happen? When I click the link in the email template it eventually times out with the message "This site took too long to reach" in chrome, ERR_CONNECTION_TIME_OUT

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Email HTML
```html
<html>
<head>
	<title></title>
</head>
<body>
<p>Dear {{.FirstName}}, We received a request to reset the password associated with this email address. Please follow the instructions below to reset your password. If you did not make this request, please use the link below to report this quickly and easily to the security team.</p>

<p><a href="{{.URL}}">File Report</a></p>

<p>Thanks for using Amazon</p>
{{.Tracker}}</body>
</html>

Landing Page HTML:
<html><head></head><body><header><title>This is title</title></header>

Hello world

</body></html>

```

Please provide any terminal output that may be relevant below:

 2018/03/08 13:05:24 worker.go:26: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20171208201932
 2018/03/08 13:05:24 gophish.go:115: Starting phishing server at http://0.0.0.0:80
 2018/03/08 13:05:24 gophish.go:98: Starting admin server at https://127.0.0.1:3333

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Run GoPhish with config {
	"admin_server" : {
		"listen_url" : "127.0.0.1:3333",
		"use_tls" : true,
		"cert_path" : "gophish_admin.crt",
		"key_path" : "gophish_admin.key"
	},
	"phish_server" : {
		"listen_url" : "0.0.0.0:80",
		"use_tls" : false,
		"cert_path" : "example.crt",
		"key_path": "example.key"
	},
	"db_name" : "sqlite3",
	"db_path" : "gophish.db",
	"migrations_prefix" : "db/db_"
}

 * Step 2 - Run campaign with various URLs, I have tried using my public ip address which shows up on Whats my ip, I have tried using http://0.0.0.0 at the URL, and I have tried using my local IP address as it shows up on my wireless adapter under ipv4, I have also tried using these three addresses with the port specified as port 80 like http://0.0.0.0:80

So with this default config file how can i make the listener server public so that it can be accessed over the internet, so that a target that clicks the link it brought to the landing page. 

Also when the link is clicked It redirects me to: 0.0.0.0/?rid=5kaP2A2 or whatever Ip I specified in URL with "/?rid=5kaP2A2" following behind it. None of the ip's I have specified for the URL have worked, so my main question is what am I doing wrong with the URL? With default config how do I make the URL publicly reachable?

**Comment by S0larflare** [comment]
0.0.0.0 isn’t a routable address, it basically just means anything/default. It’s useful for listening, but putting it in a browser won’t get you anywhere. Your config looks fine, you just need to get to your box, where is gophish being run? Are you clicking the link on the machine gophish is hosted on? If so, using http://127.0.0.1 is probably the way to go. If not, use the public IP or internal network IP to reach it.

All that said, getting a timeout like that implies to me that you might have a firewall blocking you

Sent from my iPhone

On 8 Mar 2018, at 20:24, NicolasCarson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reaching out! We're happy to help resolve issues as quickly as possible.

Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our documentation<https://getgophish.com/documentation/>, which covers how to use Gophish.

What version of Gophish are you using?: current version: 20171208201932

Brief description of the issue: I am having issues getting the landing page to load, I believe is is because I am misunderstanding how to setup the listening server and the URL.

What are you expecting to see happen? : I am expecting the URL link in the email template to send the user to my specified landing page.

What are you seeing happen? When I click the link in the email template it eventually times out with the message "This site took too long to reach" in chrome, ERR_CONNECTION_TIME_OUT

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

Email HTML

<html>
<head>
        <title></title>
</head>
<body>
<p>Dear {{.FirstName}}, We received a request to reset the password associated with this email address. Please follow the instructions below to reset your password. If you did not make this request, please use the link below to report this quickly and easily to the security team.</p>

<p><a href="{{.URL}}">File Report</a></p>

<p>Thanks for using Amazon</p>
{{.Tracker}}</body>
</html>

Landing Page HTML:
<html><head></head><body><header><title>This is title</title></header>

Hello world

</body></html>


Please provide any terminal output that may be relevant below:

2018/03/08 13:05:24 worker.go:26: Background Worker Started Successfully - Waiting for Campaigns
goose: no migrations to run. current version: 20171208201932
2018/03/08 13:05:24 gophish.go:115: Starting phishing server at http://0.0.0.0:80
2018/03/08 13:05:24 gophish.go:98: Starting admin server at https://127.0.0.1:3333

Please provide as many steps as you can to reproduce the problem:

  *   Step 1 - Run GoPhish with config {
"admin_server" : {
"listen_url" : "127.0.0.1:3333",
"use_tls" : true,
"cert_path" : "gophish_admin.crt",
"key_path" : "gophish_admin.key"
},
"phish_server" : {
"listen_url" : "0.0.0.0:80",
"use_tls" : false,
"cert_path" : "example.crt",
"key_path": "example.key"
},
"db_name" : "sqlite3",
"db_path" : "gophish.db",
"migrations_prefix" : "db/db_"
}

  *   Step 2 - Run campaign with various URLs, I have tried using my public ip address which shows up on Whats my ip, I have tried using http://0.0.0.0 at the URL, and I have tried using my local IP address as it shows up on my wireless adapter under ipv4, I have also tried using these three addresses with the port specified as port 80 like http://0.0.0.0:80

So with this default config file how can i make the listener server public so that it can be accessed over the internet, so that a target that clicks the link it brought to the landing page.

Also when the link is clicked It redirects me to: 0.0.0.0/?rid=5kaP2A2 or whatever Ip I specified in URL with "/?rid=5kaP2A2" following behind it. None of the ip's I have specified for the URL have worked, so my main question is what doing wrong with the URL? With default config how do I make the URL publicly reachable?

**Comment by NicolasCarson** [comment]
I am running go phish from a laptop, and then clicking links from my mobile phone. So your saying if i click the links from the laptop then i should set the URL to be http://127.0.0.1 ? Because I have tried using my laptops public ip and private ip, listed next to ipv4, in separate campaigns, as the URL but using either one didnt allow my phone to load the landing page. Thanks Ill try clicking links from the same laptop im running gophish on and see what happens.

**Comment by jordan-wright** [comment]
It seems that the problem is a misunderstanding about how networking works.

In simplest terms, when you click the link on your phone, the URL needs to point to an IP address that points to your Gophish server. You can find information on what it means for 0.0.0.0 to be non-routable [here](https://en.wikipedia.org/wiki/0.0.0.0).

Instead, you need to use a routable IP address that points to your laptop. If you're on the same network as your phone, this can be as simple as setting it to your laptops IP address on the network (if you're on Windows, this can be found with `ipconfig` but if you're on a "standard" home lan it's likely your address will look something like `192.168.x.x`.)

If you're _not_ on the same network, as in your phone is on the cellular network and your laptop is on your home network, things are more tricky. You mentioned you tried your external IP address. That would be what you'd do here, but you'd need to make sure your router knew how to forward traffic internally to your laptop. This is referred to as "port forwarding". You would set up a rule on your router that basically said "forward all traffic to the external interface on port 80 to my laptops internal ip address". You'd also need to make sure there weren't any firewalls in the way blocking the connections from being set up.

Hope this helps! I'm afraid there isn't much basic networking advice we can offer aside from what's above since networking concepts are outside of our support scope with Gophish.

**Comment by jordan-wright** [comment]
Going ahead and closing this one out since it appears the original question has been answered and is almost certainly a networking issue outside of Gophish.

@NicolasCarson if you continue to run into issues, please don't hesitate to let us know. Thanks again for getting in touch!

**Comment by LidiaNg** [comment]
hi, i would like to know, how to mi ip address in the url (how to hide my url of listener)
